---
permalink: online-help-96-97/concept_nodes.html 
sidebar: sidebar 
keywords: node, system, manager, view, detail, cluster, online, help 
summary: System Manager を使用して、クラスタ内のノードの詳細を表示できます。 
---
= System Manager - ONTAP 9.7 以前を使用してノードを管理します
:allow-uri-read: 


[role="lead"]
ONTAP System Manager クラシック（ ONTAP 9.7 以前で使用可能）を使用して、クラスタ内のノードの詳細を表示できます。



== ComplianceClock 時間を初期化します

System Manager を使用して、 ComplianceClock 時間を現在のクラスタ時間に初期化できます。SnapLock アグリゲートを作成するには、 ComplianceClock 時間を初期化しておく必要があります。

.作業を開始する前に
SnapLock ライセンスがインストールされている必要があります。

.このタスクについて
初期化した ComplianceClock 時間は、変更または停止することはできません。

.手順
. [ * ストレージ * > * ノード * ] をクリックします。
. ノードを選択し、 * Initialize ComplianceClock * をクリックします。
. Initialize ComplianceClock * （ ComplianceClock の初期化）ダイアログボックスで * Yes （はい） * をクリックし、 ComplianceClock 時間を現在のクラスタ時間に初期化します。




== ノードウィンドウ

ノードウィンドウを使用して、クラスタ内のノードの詳細を表示できます。



=== コマンドボタン

* * ComplianceClock を初期化 *
+
選択したノードの ComplianceClock をシステムクロックの現在の値に初期化します。

* * 更新 *
+
ウィンドウ内の情報を更新します。





=== ノードリスト

* * 名前 *
+
ノードの名前が表示されます。

* * 状態 *
+
ノードの状態（稼働しているかどうか）が表示されます。

* * アップタイム *
+
ノードの稼働期間が表示されます。

* * ONTAP バージョン *
+
ノードにインストールされている ONTAP のバージョンが表示されます。

* * モデル *
+
ノードのプラットフォームモデル番号が表示されます。

* * システム ID *
+
ノードの ID が表示されます。

* * シリアル番号 *
+
ノードのシリアル番号が表示されます。





=== 詳細領域

選択したノードに関する詳細情報を表示します。

* * 詳細タブ *
+
選択したノードに関する情報が表示されます。これには、ノードの名前、ノードの状態、ノードの稼働期間などの情報が含まれます。

* * パフォーマンスタブ *
+
選択したノードのスループット、 IOPS 、レイテンシが表示されます。

+
クライアントのタイムゾーンやクラスタのタイムゾーンを変更すると、パフォーマンス指標のグラフも変わります。最新のグラフを表示するには、ブラウザの表示を更新してください。


