---
permalink: online-help-96-97/concept_events.html 
sidebar: sidebar 
keywords: event, log, notification, system, manager, online, help, view 
summary: System Manager を使用して、イベントログやイベント通知を表示できます。 
---
= System Manager - ONTAP 9.7 以前を使用してイベントを管理します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP System Manager クラシック（ ONTAP 9.7 以前で使用可能）を使用して、イベントログとイベント通知を表示できます。



== イベントウィンドウ

イベントウィンドウを使用して、イベントログとイベント通知を表示できます。



=== コマンドボタン

* * 更新 *
+
ウィンドウ内の情報を更新します。





=== イベントのリスト

* * 時間 *
+
イベントが発生した時刻が表示されます。

* * ノード *
+
イベントが発生したノードとクラスタを表示します。

* * 重大度 *
+
イベントの重大度が表示されます。指定可能な重大度レベルは次のとおりです。

+
** 緊急
+
イベントソースが予期せず停止し、回復不能なデータ損失がシステムで発生したことを示します。長時間のダウンタイムを回避するために、すぐに対処する必要があります。

** アラート
+
イベントソースにアラートが発生し、ダウンタイムを回避するために対処が必要であることを示します。

** 重要
+
イベントソースがクリティカルな状態であり、すぐに対処しないとサービスが停止する可能性があることを示します。

** エラー
+
イベントソースが実行中ではあるものの、サービスの停止を回避するために対処が必要であることを示します。

** 警告
+
イベントソースに注意が必要なアラートが発生したことを示します。この重大度のイベントでは原因サービスは停止しない可能性がありますが、対処が必要な場合があります。

** 注意
+
イベントソースは正常ですが、重大度は重要な状態にあり、注意が必要であることを示します。

** 情報
+
イベントソースに注意が必要であることを示します。対処は不要です。

** デバッグ
+
イベントソースにデバッグメッセージが含まれるように指定します。



+
デフォルトでは、アラートの重大度タイプ、緊急の重大度タイプ、およびエラーの重大度タイプが表示されます。

* * 出典 *
+
イベントのソースを表示します。

* * イベント *
+
イベントの概要を表示します。





=== 詳細領域

イベント概要、メッセージ名、シーケンス番号、メッセージ概要、および選択したイベントの対処方法など、イベントの詳細を表示します。
