---
permalink: online-help-96-97/concept_array_luns.html 
sidebar: sidebar 
keywords: system, manager, array, lun, aggregate, assign, online, help, classic 
summary: System Manager を使用して、既存のアグリゲートにアレイ LUN を割り当てたり、アレイ LUN を管理したりできます。 
---
= System Manager - ONTAP 9.7 以前を使用してアレイ LUN を管理します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP System Manager クラシック（ ONTAP 9.7 以前で使用可能）を使用して、既存のアグリゲートにアレイ LUN を割り当て、アレイ LUN を管理できます。



== アレイ LUN を割り当て

System Manager を使用して既存のアグリゲートに未割り当てのアレイ LUN を割り当てることで、アグリゲートのサイズを拡張することができます。

.このタスクについて
* アレイ LUN の割り当ては、次の条件に当てはまる場合に実行できます。
+
** 選択したアレイ LUN のコンテナタイプは「 unassigned 」である必要があります。
** ディスクが HA ペア内のノードに接続されている。
** ディスクがノードで認識されている必要があります。


* MetroCluster 構成の場合、 System Manager でアレイ LUN をスペアとして割り当てることはできません。
+
代わりにコマンドラインインターフェイスを使用してください。



.手順
. [* ストレージ * > * アグリゲートとディスク * > * アレイ LUN * ] をクリックします。
. アレイ LUN を選択し、 * assign * をクリックします。
. [* アレイ LUN の割り当て * ] ダイアログ・ボックスで ' アレイ LUN を割り当てるノードを選択します
. [*Assign*] をクリックします。




== スペアアレイ LUN をノードに再割り当て

System Manager を使用してスペアアレイ LUN を別のノードに再割り当てすることで、アグリゲートの容量を拡張することができます。

.このタスクについて
* アレイ LUN の再割り当ては、次の条件に当てはまる場合に実行できます。
+
** 選択したアレイ LUN のコンテナタイプは「 'srep' 」でなければなりません。
** ディスクが HA ペア内のノードに接続されている。
** ディスクがノードで認識されている必要があります。


* MetroCluster 構成の場合、 System Manager でアレイ LUN をスペアとして再割り当てすることはできません。
+
代わりにコマンドラインインターフェイスを使用してください。



.手順
. [* ストレージ * > * アグリゲートとディスク * > * アレイ LUN * ] をクリックします。
. 再割り当てするスペアアレイ LUN を選択し、 * assign * をクリックします。
. 警告 * （ * Warning * ）ダイアログボックスで、 * 続行 * （ * Continue * ）をクリックします。
. [* アレイ LUN の割り当て * ] ダイアログ・ボックスで ' スペア・アレイ LUN を再割り当てするノードを選択します
. [*Assign*] をクリックします。




== スペアアレイ LUN の初期化

System Manager を使用して、スペアアレイ LUN に 0 を書き込むことで、アレイ LUN のすべてのデータを消去してフォーマットすることができます。これらのアレイ LUN は新しいアグリゲートで使用できます。

.このタスクについて
スペアアレイ LUN を初期化すると、スペアディスクも含め、クラスタ内のすべてのスペアが初期化されます。特定のノードまたはクラスタ全体について、スペアアレイ LUN を初期化することができます。

.手順
. [* ストレージ * > * アグリゲートとディスク * > * アレイ LUN * ] をクリックします。
. [* Zero Spares] をクリックします。
. [*Zero Spares*] ダイアログ・ボックスで ' アレイ LUN をゼロにするノードまたはすべてのノードを選択します
. ゼロ化処理を確定するには、「ゼロ化されていないスペアをすべて初期化」チェックボックスを選択します。
. [* Zero Spares] をクリックします。




== ディスクおよびアレイ LUN について

ディスクは、 ONTAP ソフトウェアを使用してネイティブなディスクシェルフにアクセスする、ストレージシステムの基本的なストレージユニットです。アレイ LUN は、サードパーティのストレージアレイが ONTAP ソフトウェアを実行するストレージシステムに提供する、基本的なストレージユニットです。

ONTAP ソフトウェアでは、ディスクおよびアレイ LUN に所有権を割り当てて、それらをアグリゲートに追加できます。ONTAP ソフトウェアには、ディスクの削除、交換、消去など、ディスクを管理するさまざまな方法も用意されています。アレイ LUN はサードパーティのストレージアレイによって提供されるため、アレイ LUN に関する他のすべての管理タスクにはサードパーティのストレージアレイを使用します。

アグリゲートはディスクまたはアレイ LUN のどちらかを使用して作成できます。作成したアグリゲートは、ディスクまたはアレイ LUN のどちらから作成したかにかかわらず、 ONTAP ソフトウェアを使用してまったく同じ方法で管理できます。



== アレイ LUN ウィンドウ

アレイ LUN ウィンドウでは、アレイ LUN に所有権を割り当ててアグリゲートに追加できます。

左側のナビゲーションペインの Array LUNs リンクは、スペアアレイ LUN がある場合、または V_StorageAttach ライセンスがインストールされている場合にのみ表示されます。



=== コマンドボタン

* * 割り当て *
+
アレイ LUN の所有権をノードに割り当てまたは再割り当てできます。

* * ゼロスペア *
+
スペアアレイ LUN およびスペアディスクのすべてのデータを消去してフォーマットします。

* * 更新 *
+
ウィンドウ内の情報を更新します。





=== アレイ LUN リスト

各アレイ LUN の名前、状態、およびベンダーなどの情報が表示されます。

* * 名前 *
+
アレイ LUN の名前です。

* * 状態 *
+
アレイ LUN の状態です。

* * ベンダー *
+
ベンダーの名前です。

* * 使用済みスペース *
+
アレイ LUN で使用されているスペースです。

* * 合計サイズ *
+
アレイ LUN のサイズです。

* * コンテナ *
+
このアレイ LUN が属するアグリゲートです。

* * ノード名 *
+
このアレイ LUN が属するノードの名前です。

* * 家の所有者 *
+
アレイ LUN が割り当てられているホームノードの名前が表示されます。

* * 現在の所有者 *
+
アレイ LUN を現在所有しているノードの名前が表示されます。

* * アレイ名 *
+
アレイの名前です。

* * プール *
+
選択したアレイ LUN が割り当てられているプールの名前が表示されます。





=== 詳細領域

アレイ LUN リストの下の領域には、選択したアレイ LUN に関する詳細情報が表示されます。

* 関連情報 *

https://docs.netapp.com/ontap-9/topic/com.netapp.doc.vs-irrg/home.html["FlexArray 仮想化のインストール要件およびリファレンス"]
