---
permalink: online-help-96-97/concept_storage_pools.html 
sidebar: sidebar 
keywords: system, manager, storage, pools, ssd, flash, pool, aggregates, online, help, create, 
summary: System Manager を使用してストレージプールを作成すると、 SSD を複数の Flash Pool アグリゲートで共有できるようになります。 
---
= System Manager - ONTAP 9.7 以前を使用してストレージプールを管理します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP System Manager クラシック（ ONTAP 9.7 以前で使用可能）を使用してストレージプールを作成し、 SSD を複数の Flash Pool アグリゲートで共有できるようにすることができます。



== ストレージプールを作成します

ストレージプールは SSD （キャッシュディスク）の集まりです。System Manager を使用して複数の SSD を組み合わせてストレージプールを作成すると、 HA ペア間で SSD と SSD スペアを共有し、 2 つ以上の Flash Pool アグリゲートに同時に割り当てることができます。

.作業を開始する前に
* ストレージプール経由で SSD と SSD スペアを割り当てるためには、 HA ペアの両方のノードが稼働している必要があります。
* ストレージプールには少なくとも 3 本の SSD が必要です。
* ストレージプール内のすべての SSD は、同じ HA ペアによって所有されている必要があります。


.このタスクについて
ストレージプールへのディスクの追加に SSD を使用する際、 System Manager は、 SSD RAID グループにホットスペアルールを適用します。たとえば、SSD RAIDグループにSSDが10本あり、オプションが `raid.min_spare_count` がに設定されます `1` System Managerはノードレベルでは、1本のSSDをホットスペアとして残し、残りの9本をSSD関連の処理に使用します。

System Manager を使用してストレージプールを作成する場合、パーティショニングされた SSD を使用することはできません。

.手順
. [ * ストレージ * > * アグリゲートとディスク * > * ストレージプール * ] をクリックします。
. [ * ストレージプール * ] ウィンドウで、 [ * 作成 ] をクリックします。
. Create Storage Pool * （ストレージプールの作成 * ）ダイアログボックスで、ストレージプールの名前、ディスクサイズ、ディスク数を指定します。
. [ 作成（ Create ） ] をクリックします。




== ストレージプールにディスクを追加します

System Manager を使用して、既存のストレージプールに SSD を追加してキャッシュサイズを拡張できます。

.作業を開始する前に
ストレージプール経由で SSD と SSD スペアを割り当てるためには、 HA ペアの両方のノードが稼働している必要があります。

.このタスクについて
* ストレージプールに追加した SSD は、ストレージプールキャッシュを使用する各アグリゲートと、ストレージプールの空きスペースに、均等に配分されます。
* ストレージプールへのディスクの追加に SSD を使用する際、 System Manager は、 SSD RAID グループにホットスペアルールを適用します。
+
たとえば、SSD RAIDグループにSSDが10本あり、オプションが `raid.min_spare_count` がに設定されます `1` System Managerはノードレベルでは、1本のSSDをホットスペアとして残し、残りの9本をSSD関連の処理に使用します。

* System Manager を使用してディスクをストレージプールに追加する場合、パーティショニングされた SSD は使用できません。


.手順
. [ * ストレージ * > * アグリゲートとディスク * > * ストレージプール * ] をクリックします。
. [ * ストレージプール * ] ウィンドウで、ストレージプールを選択し、 [ * ディスクの追加 * ] をクリックします。
. [ * ディスクの追加 * ] ダイアログボックスで、追加するディスクの数を指定します。
. 「 * 次へ * 」をクリックします。
. サマリー * ダイアログボックスで、各アグリゲートとストレージプールの空きスペースにどのようにキャッシュが分散されているかを確認します。
. [ 追加（ Add ） ] をクリックします。




== ストレージプールを削除する

ストレージプールのキャッシュが最適でない場合や、アグリゲートまたは Flash Pool アグリゲートでストレージプールが使用されなくなった場合などに、ストレージプールを削除することができます。System Manager のストレージプールの削除ダイアログボックスを使用して、ストレージプールを削除できます。

.作業を開始する前に
ストレージプールを使用しているアグリゲートがないことを確認してください。

.手順
. [ * ストレージ * > * アグリゲートとディスク * > * ストレージプール * ] をクリックします。
. [ * ストレージ・プール * ] ウィンドウで、削除するストレージ・プールを選択し、 [ * 削除 * ] をクリックします。
. ［ * ストレージプールの削除 * ］ ダイアログボックスで、 ［ * 削除 * ］ をクリックします。




== SSD ストレージプールを使用する

SSD を複数の Flash Pool アグリゲートで共有できるようにするには、 SSD を a_storage pool_ に追加します。ストレージプールに追加した SSD は、スタンドアロンのエンティティとしては管理できなくなります。その SSD からストレージを割り当てるには、ストレージプールを使用する必要があります。

特定のハイアベイラビリティ（ HA ）ペア用にストレージプールを作成できます。作成したら、そのストレージプールから、同じ HA ペアが所有する 1 つ以上の Flash Pool アグリゲートに割り当て単位を追加できます。アグリゲートに割り当てるディスクがアグリゲートを所有するノードに所有されている必要があるのと同様に、ストレージプールは、そのストレージプールが所属するいずれかのノードに所有されている Flash Pool アグリゲートにのみストレージを提供できます。

システムの Flash Pool キャッシュの量を拡張するには、ストレージプールに SSD を追加します。 SSD は、そのストレージプールを使用する Flash Pool キャッシュの RAID タイプの最大 RAID グループサイズまで追加できます。既存のストレージプールに SSD を追加すると、 Flash Pool アグリゲートに割り当て済みの割り当て単位も含めて、ストレージプールの割り当て単位が拡張されます。

ストレージプールに使用できるスペア SSD は 1 本のみです。スペア SSD を用意しておけば、ストレージプール内の SSD に障害が発生した場合に、正常に機能しない SSD のパーティションを ONTAP で再構築できます。割り当て単位をスペア容量として確保する必要はありません。 ONTAP は、ストレージプール内のパーティショニングされていない完全な SSD のみを SSD のスペアとして使用できます。

アグリゲートからディスクを削除できないのと同様に、いったんストレージプールに追加した SSD は削除できません。ストレージプール内の SSD を単独のドライブとして再度使用するには、ストレージプールの割り当て単位が割り当てられている Flash Pool アグリゲートをすべて破棄してから、ストレージプールを破棄する必要があります。



== SSD ストレージプールを使用する際の要件およびベストプラクティス

一部のテクノロジは、 SSD ストレージプールを使用する Flash Pool アグリゲートと組み合わせることができません。

次のテクノロジは、 SSD ストレージプールをキャッシュストレージに使用する Flash Pool アグリゲートでは使用できません。

* MetroCluster
* SyncMirror 機能
+
ミラーされたアグリゲートとストレージプールを使用する Flash Pool アグリゲートは一緒に使用できますが、 Flash Pool アグリゲートはミラーできません。

* 物理 SSD
+
Flash Pool アグリゲートでは、 SSD ストレージプールまたは物理 SSD のどちらか一方を使用できますが、両方は使用できません。



SSD ストレージプールは次のルールに従う必要があります。

* SSD ストレージプールには SSD のみを含めることができます。 HDD は SSD ストレージプールに追加できません。
* SSD ストレージプール内のすべての SSD は、同じハイアベイラビリティ（ HA ）ペアに所有されている必要があります。
* ストレージプール内でルートデータのパーティショニング用にパーティショニングされた SSD は使用できません。


単一のストレージプールから RAID タイプが異なる 2 つのキャッシュにストレージを提供し、ストレージプールのサイズを RAID 4 の最大 RAID グループサイズよりも大きく拡張した場合、 RAID 4 割り当て単位内の余分なパーティションは使用されません。このため、ストレージプール内のキャッシュ RAID タイプは統一することを推奨します。

ストレージプールから割り当てられているキャッシュ RAID グループの RAID タイプは変更できません。最初の割り当て単位を追加する前にキャッシュの RAID タイプを設定すると、あとから変更できません。

ストレージプールを作成したり、 SSD を既存のストレージプールに追加したりするときは、同じサイズの SSD を使用する必要があります。障害発生時に適切なサイズのスペア SSD がない場合、 ONTAP では、より大容量の SSD を使用して障害の発生した SSD を交換できます。ただし、交換後の SSD はストレージプール内の他の SSD と同じサイズに調整されるため、 SSD の容量が失われることになります。

ストレージプールに使用できるスペア SSD は 1 本のみです。HA ペアの両方のノードが所有する Flash Pool アグリゲートにストレージプールが割り当て単位を提供する場合は、どちらのノードでもスペア SSD を所有できます。ただし、 HA ペアの一方のノードが所有する Flash Pool アグリゲートにのみストレージプールが割り当て単位を提供する場合は、その同じノードがスペア SSD を所有する必要があります。



== SSD ストレージプールを使用するケースに関する考慮事項

SSD ストレージプールにはさまざまな利点がありますが、 SSD ストレージプールと専用 SSD のどちらを使用するかを決定する際には、考慮すべき制限事項がいくつかあります。

SSD ストレージプールは、 2 つ以上の Flash Pool アグリゲートにキャッシュを提供する場合にのみ効果を発揮します。SSD ストレージプールには次のようなメリットがあります。

* Flash Pool アグリゲートで使用される SSD のストレージ利用率の向上
+
SSD ストレージプールは、複数の Flash Pool アグリゲートでパリティ SSD を共有できるため、パリティに必要な SSD の全体的な割合が下がります。

* HA パートナー間でのスペアの共有
+
ストレージプールは HA ペアによって所有されるため、 HA パートナーのいずれかに所有される 1 つのスペアが、必要に応じて SSD ストレージプール全体のスペアとして機能します。

* SSD パフォーマンスの利用率が向上します
+
SSD が提供するハイパフォーマンスによって、 HA ペアの両方のコントローラからのアクセスがサポートされます。



SSD ストレージプールを使用する際のこのような利点について、以下の欠点も含めて、その利用コストと比較する必要があります。

* 障害の切り分けが困難
+
1 本の SSD の損失が、そのパーティションに含まれるすべての RAID グループに影響します。この場合、影響を受ける SSD を含む SSD ストレージプールからキャッシュが割り当てられているすべての Flash Pool アグリゲートで、 1 つ以上の RAID グループが再構築されます。

* パフォーマンスの分離が困難
+
Flash Pool キャッシュのサイズを適切に設定しないと、共有している Flash Pool アグリゲート間のキャッシュで競合が発生する可能性があります。このリスクは、適切なキャッシュのサイジングと QoS 管理によって軽減されます。

* 管理の柔軟性の低下
+
ストレージをストレージプールに追加すると、そのストレージプールから 1 つ以上の割り当て単位を含むすべての Flash Pool キャッシュのサイズが拡張されます。追加の容量の配分方法は指定できません。





== SSD を既存のストレージプールに追加する場合と新規作成する場合の考慮事項

SSD キャッシュのサイズは、既存の SSD ストレージプールに SSD を追加する方法と、新しい SSD ストレージプールを作成する方法の 2 つで拡張できます。最適な方法は、ストレージの構成と計画によって異なります。

ストレージプールを新規作成するか既存のストレージプールにストレージ容量を追加するかを選択するは、 RAID グループを新規作成するか既存にストレージを追加するかどうかを決定することに似ています。

* 多数の SSD を追加する場合、ストレージプールを新規作成すると新しいストレージプールを既存とは別の方法で割り当てることができるため、柔軟性が増します。
* 追加する SSD が少数であり、既存の Flash Pool キャッシュのサイズ増加が問題ではない場合は、 SSD を既存のストレージプールに追加することで、スペアとパリティのコストを抑制し、新しいストレージを自動的に割り当てます。


ストレージプールが、キャッシュの RAID タイプが異なる Flash Pool アグリゲートに割り当て単位を提供している場合に、ストレージプールのサイズを最大 RAID 4 RAID グループサイズを超えると、 RAID 4 割り当て単位で新たに追加されたパーティションは使用されません。



== ストレージプールにディスクを追加する理由

既存のストレージプールに SSD を追加してキャッシュサイズを拡張できます。割り当て単位が Flash Pool アグリゲートにすでに割り当てられているストレージプールに SSD を追加すると、これらのアグリゲートそれぞれのキャッシュサイズと、ストレージプールの合計キャッシュサイズが増加します。

割り当て単位がまだ割り当てられていないストレージプールに SSD を追加しても、 SSD のキャッシュサイズには影響しません。

既存のストレージプールに SSD を追加する場合は、ストレージプール内の既存の SSD を所有するノードと同じ HA ペアのどちらかのノードが所有する SSD を追加する必要があります。HA ペアのどちらのノードが所有する SSD でもかまいません。



== ストレージプールの仕組み

a_storage pool_ は SSD の集合です。複数の SSD からストレージプールを作成すると、複数の Flash Pool アグリゲート間で SSD と SSD スペアを同時に共有できます。

ストレージプールは複数の割り当て単位で構成されます。割り当て単位を使用して、 SSD および SSD スペアをアグリゲートに提供したり、既存の SSD サイズを拡張したりできます。

ストレージプールに追加した SSD は、個別のディスクとして使用することはできません。その SSD からストレージを割り当てるには、ストレージプールを使用する必要があります。



== ストレージプールウィンドウ

Storage Pools （ストレージプール）ウィンドウを使用して、 SSD の専用キャッシュ（ _ ストレージプール _ ）を作成、表示、管理できます。ストレージプールはルート以外のアグリゲートに関連付けて SSD キャッシュを提供したり、 Flash Pool アグリゲートに関連付けてサイズを拡張したりできます。

このページは、オールフラッシュで最適化されたノードを含むクラスタでは使用できません。



=== コマンドボタン

* * 作成 * 。
+
ストレージプールの作成ダイアログボックスを開きます。このダイアログボックスで、ストレージプールを作成できます。

* * ディスクの追加 *
+
Add Disks （ディスクの追加）ダイアログボックスを開きます。このダイアログボックスでは、ストレージプールにキャッシュディスクを追加できます。

* * 削除 *
+
選択したストレージプールを削除します。

* * 更新 *
+
ウィンドウ内の情報を更新します。





=== ストレージプールのリスト

* * 名前 *
+
ストレージプールの名前が表示されます。

* * 合計キャッシュ *
+
ストレージプールの合計キャッシュサイズが表示されます。

* * スペアキャッシュ *
+
ストレージプールの利用可能なスペアキャッシュサイズが表示されます。

* * 使用キャッシュ（ % ） *
+
ストレージプールの使用済みキャッシュサイズの割合が表示されます。

* * 割り当て単位 *
+
ストレージプールのサイズ拡張に使用できる合計キャッシュサイズの最小割り当て単位が表示されます。

* * 所有者 *
+
ストレージプールが関連付けられている HA ペアまたはノードの名前が表示されます。

* * 状態 *
+
ストレージプールの状態が表示されます。正常、デグレード、作成、削除、再割り当て、 成長する。

* * は正常です *
+
ストレージプールが正常であるかどうかが表示されます。





=== [ 詳細 ] タブ

選択したストレージプールに関する詳細情報が表示されます。これには、名前、健常性、ストレージタイプ、ディスク数、合計キャッシュ、 スペアキャッシュ、使用済みキャッシュサイズ（割合）、および割り当て単位。このタブには、ストレージプールによってプロビジョニングされるアグリゲートの名前も表示されます。



=== Disks （ディスク）タブ

選択したストレージプール内のディスクに関する詳細情報が表示されます。これには、名前、ディスクタイプ、使用可能なサイズ、合計サイズなどの情報が含まれます。

* 関連情報 *

xref:task_provisioning_storage_by_creating_flash_pool_aggregate_manually.adoc[Flash Pool アグリゲートを手動で作成してストレージをプロビジョニングする]

xref:task_provisioning_cache_by_adding_disks.adoc[SSD の追加によるキャッシュのプロビジョニング]

https://docs.netapp.com/us-en/ontap/disks-aggregates/index.html["ディスクおよびアグリゲートの管理"]
