---
permalink: online-help-96-97/concept_namespace.html 
sidebar: sidebar 
keywords: junction, path, window, system, manager, mount, unmount, flexvol, volume, svm, namespace, online, help, policies, export 
summary: System Manager のジャンクションパスウィンドウを使用して、 FlexVol ボリュームを SVM ネームスペースのジャンクションにマウントまたはアンマウントできます。 
---
= System Manager のジャンクションパスウィンドウ - ONTAP 9.7 以前
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP System Manager クラシック（ ONTAP 9.7 以前で利用可能）のジャンクションパスウィンドウを使用して、 FlexVol ボリュームを SVM ネームスペースのジャンクションにマウントまたはアンマウントできます。



== ボリュームをマウント

System Manager を使用して、 Storage Virtual Machine （ SVM ）のネームスペースのジャンクションにボリュームをマウントできます。

.このタスクについて
* ジャンクションパスにボリュームをマウントする際に、言語設定がそのパスの直接の親ボリュームと異なっていると、一部の文字が正しくデコードされないために NFSv3 クライアントから一部のファイルにアクセスできないことがあります。
+
直接の親ディレクトリがルートボリュームの場合、この問題は発生しません。

* SnapLock ボリュームは SVM のルートにしかマウントできません。
* 通常のボリュームを SnapLock ボリュームにマウントすることはできません。


.手順
. Storage * > * Junction Path * をクリックします。
. SVM * フィールドのドロップダウンメニューから、ボリュームをマウントする SVM を選択します。
. [ マウント ] をクリックし、マウントするボリュームを選択します。
. *オプション：*デフォルトのジャンクション名を変更する場合は、新しい名前を指定します。
. 「 * Browse * 」をクリックし、ボリュームをマウントするジャンクションパスを選択します。
. [OK] をクリックし、 [ マウント *] をクリックします。
. 新しいジャンクションパスを「 * Details * 」タブで確認します。




== FlexVol ボリュームをアンマウント

System Manager の Storage ペインで Junction Path オプションを使用すると、 Storage Virtual Machine （ SVM ）ネームスペースのジャンクションから FlexVol ボリュームをアンマウントできます。

.手順
. Storage * > * Junction Path * をクリックします。
. SVM * フィールドのドロップダウンメニューで、ボリュームをアンマウントする SVM を選択します。
. アンマウントする必要があるボリュームを選択し、 * Unmount * をクリックします。
. 確認のチェックボックスをオンにし、 * Unmount * をクリックします。




== エクスポートポリシーを変更します

ボリュームの作成時には、 Storage Virtual Machine （ SVM ）のルートボリュームのデフォルトのエクスポートポリシーが自動的に継承されます。System Manager を使用して、ボリュームに関連付けられているデフォルトのエクスポートポリシーを変更して、データにアクセスするクライアントを再定義できます。

.手順
. Storage * > * Junction Path * をクリックします。
. SVM * フィールドのドロップダウンメニューから、変更するボリュームが配置されている SVM を選択します。
. ボリュームを選択し、 * エクスポートポリシーの変更 * をクリックします。
. エクスポートポリシーを選択し、 * Change * をクリックします。
. ジャンクションパス * ウィンドウの * エクスポートポリシー * 列に、ボリュームに適用したエクスポートポリシーが表示されていることを確認します。


.結果
デフォルトのエクスポートポリシーが選択したエクスポートポリシーに置き換えられます。



== ジャンクションパスウィンドウ

Junction Path メニューを使用して、 Storage Virtual Machine （ SVM ）の NAS ネームスペースを管理できます。



=== コマンドボタン

* * マウント *
+
ボリュームのマウントダイアログボックスを開きます。このダイアログボックスで、 SVM ネームスペースのジャンクションにボリュームをマウントできます。

* * Unmount *
+
ボリュームのアンマウントダイアログボックスを開きます。このダイアログボックスで、ボリュームを親ボリュームからアンマウントできます。

* * エクスポートポリシーの変更 *
+
エクスポートポリシーの変更ダイアログボックスを開きます。このダイアログボックスで、ボリュームに関連付けられている既存のエクスポートポリシーを変更できます。

* * 更新 *
+
ウィンドウ内の情報を更新します。





=== ジャンクションパスのリスト

* * パス *
+
マウントされたボリュームのジャンクションパスを指定します。ジャンクションパスをクリックすると、関連するボリュームと qtree を表示できます。

* * ストレージオブジェクト *
+
ジャンクションパスにマウントされたボリュームの名前を指定します。ボリュームに含まれる qtree を表示することもできます。

* * エクスポートポリシー *
+
マウントされたボリュームのエクスポートポリシーを指定します。

* * セキュリティ形式 *
+
ボリュームのセキュリティ形式を指定します。指定できる値は、 UNIX （ UNIX モードビット）、 NTFS （ CIFS ACL ）、 Mixed （ NFS 権限と CIFS 権限の混合）です。





=== [ 詳細 ] タブ

選択したボリュームまたは qtree に関する、名前、ストレージオブジェクトのタイプ、マウントオブジェクトのジャンクションパス、エクスポートポリシーなどの基本的な情報が表示されます。選択したオブジェクトが qtree の場合、スペースのハードリミット、ソフトリミット、および使用状況が表示されます。
