---
permalink: online-help-96-97/concept_quotas.html 
sidebar: sidebar 
keywords: system, manager, quota, online, help, view, activate, deactivate, information, types, targets, default, limits, space, files, manage, tree, group 
summary: System Manager を使用して、クォータを作成、編集、削除できます。 
---
= System Manager - ONTAP 9.7 以前を使用してクォータを管理します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP System Manager クラシック（ ONTAP 9.7 以前で使用可能）を使用して、クォータを作成、編集、および削除できます。



== クォータを作成する

クォータを使用すると、ユーザ、グループ、または qtree によって使用されるディスクスペースやファイル数を制限したり、追跡したりできます。System Manager のクォータの追加ウィザードを使用して、クォータを作成し、そのクォータを特定のボリュームまたは qtree に適用できます。

.このタスクについて
System Manager を使用する場合、クォータで所有できるファイル数のハードリミットとソフトリミットに指定できる最小値は 1000 です。1000 未満の値を指定する場合は、 CLI を使用してください。

.手順
. [* ストレージ *>* クォータ ] をクリックします。
. SVM * フィールドのドロップダウンメニューから、クォータを作成する Storage Virtual Machine （ SVM ）を選択します。
. ユーザー定義のクォータ * （ User Defined Quotas * ）タブで、 * 作成 * （ Create * ）をクリックします。
+
クォータの作成ウィザードが表示されます。

. ウィザードの指示に従って、情報を入力または選択します。
. 詳細を確認し、 [* 終了 ] をクリックしてウィザードを完了します。




=== 次に何をするか

ローカルのユーザ名または RID を使用してユーザクォータを作成できます。ユーザ名またはグループ名を使用してユーザクォータまたはグループクォータを作成する場合は、 ``/etc/passwd``ファイルと``/etc/group``ファイルはそれぞれ更新する必要があります。



== クォータを削除します

ユーザやユーザのストレージ要件および制限が変更になった場合は、 System Manager を使用して 1 つ以上のクォータを削除できます。

.手順
. [* ストレージ *>* クォータ ] をクリックします。
. SVM * フィールドのドロップダウンメニューから、削除するクォータが配置されている Storage Virtual Machine （ SVM ）を選択します。
. 削除するクォータを 1 つ以上選択し、 * 削除 * をクリックします。
. 確認のチェックボックスをオンにし、 * 削除 * をクリックします。




== クォータ制限を編集します

System Manager を使用して、ディスクスペースのしきい値、クォータターゲットで使用できるディスクスペースの容量のハードリミットとソフトリミット、およびクォータターゲットで所有できるファイル数のハードリミットとソフトリミットを編集できます。

.手順
. [* ストレージ *>* クォータ ] をクリックします。
. SVM * フィールドのドロップダウンメニューから、編集するクォータが含まれている Storage Virtual Machine （ SVM ）を選択します。
. 編集するクォータを選択し、 * 制限の編集 * をクリックします。
. [ 制限の編集 *] ダイアログボックスで、必要に応じてクォータの設定を編集します。
+
クォータで所有できるファイル数のハードリミットとソフトリミットに指定できる最小値は 100 です。100未満の値を指定する場合は、コマンドラインインターフェイス（CLI）を使用してください。

. [ 保存して閉じる ] をクリックします。
. [ ユーザー定義クォータ ] タブで、選択したクォータに加えた変更を確認します。




== クォータをアクティブ化または非アクティブ化します

System Manager を使用して、ストレージシステム上の選択した 1 つ以上のボリュームでクォータをアクティブ化または非アクティブ化できます。ユーザやユーザのストレージ要件および制限が変更になった場合に、クォータをアクティブ化または非アクティブ化できます。

.手順
. [* ストレージ *>* クォータ ] をクリックします。
. SVM フィールドのドロップダウンメニューから、アクティブ化または非アクティブ化するクォータが配置されている Storage Virtual Machine （ SVM ）を選択します。
. [* Quota Status on Volumes] タブで、クォータをアクティブ化または非アクティブ化する 1 つ以上のボリュームを選択します。
. 必要に応じて、 [ 活動化（ Activate ） ] または [ * 非活動化（ * Deactivate ） ] をクリック
. クォータを非アクティブ化する場合は、確認のチェックボックスをオンにし、 * OK * をクリックします。
. ボリュームのクォータステータスを * Status * 列で確認します。




== クォータのサイズを変更

System Manager のクォータのサイズ変更ダイアログボックスを使用して、指定したボリューム内のアクティブなクォータを調整し、クォータに対する変更を反映させることができます。

.作業を開始する前に
クォータのサイズを変更するボリュームで、クォータが有効になっている必要があります。

.手順
. [* ストレージ *>* クォータ ] をクリックします。
. [* Quotas* （クォータ） ] ウィンドウの [* Quota Status on Volumes] （ボリュームのクォータステータス）タブで、クォータのサイズを変更する 1 つ以上のボリュームを選択します。
. [ * サイズ変更 * ] をクリックします。




== クォータ情報を表示します

System Manager のクォータウィンドウを使用して、クォータが適用されているボリュームと qtree 、クォータのタイプ、クォータが適用されているユーザまたはグループ、スペースおよびファイルの使用量など、クォータの詳細を表示できます。

.手順
. [* ストレージ *>* クォータ ] をクリックします。
. SVM * フィールドのドロップダウンメニューから、情報を表示するクォータが存在する Storage Virtual Machine （ SVM ）を選択します。
. 適切な操作を実行します。
+
[cols="1a,1a"]
|===
| 状況 | 作業 


 a| 
作成したすべてのクォータの詳細を表示する
 a| 
ユーザー定義クォータ * タブをクリックします。



 a| 
現在アクティブなクォータの詳細を表示する
 a| 
[* クォータレポート *] タブをクリックします。

|===
. 表示されているクォータのリストから、情報を表示するクォータを選択します。
. クォータの詳細を確認します。




== クォータのタイプ

クォータは、適用先のターゲットに基づいて分類できます。

適用先のターゲットに基づくクォータのタイプを次に示します。

* * ユーザークォータ *
+
ターゲットはユーザです。

+
ユーザは、 UNIX ユーザ名、 UNIX UID 、 Windows SID 、 UID がユーザに一致するファイルまたはディレクトリ、 Windows 2000 より前の形式の Windows ユーザ名、およびユーザの SID 所有の ACL が設定されたファイルまたはディレクトリによって表すことができます。このクォータはボリュームまたは qtree に適用できます。

* * グループクォータ *
+
ターゲットはグループです。

+
グループは、 UNIX グループ名、 GID 、または GID がグループに一致するファイルまたはディレクトリで表されます。ONTAP では、 Windows ID に基づいてグループクォータを適用しません。クォータはボリュームまたは qtree に適用できます。

* * qtree クォータ *
+
ターゲットは qtree であり、 qtree へのパス名によって指定されます。

+
ターゲット qtree のサイズを決定できます。

* * デフォルトクォータ *
+
ターゲットごとに個別のクォータを作成することなく、大量のクォータターゲットにクォータ制限を自動的に適用します。

+
デフォルトクォータは、 3 種類のクォータターゲット（ユーザ、グループ、および qtree ）のすべてに適用できます。クォータのタイプは type フィールドの値によって決まります





== クォータ制限

クォータタイプごとにディスクスペース制限を適用するか、ファイル数を制限できます。クォータの制限を指定しない場合、何も適用されません。

クォータには、ソフトクォータとハードクォータがあります。ソフトクォータ原因 Data ONTAP では、指定された制限を超過すると通知が送信されますが、ハードクォータでは、指定された制限を超過すると書き込み処理が失敗します。

ハードクォータを設定すると、システムリソースにハードリミットが適用されます。実行することで制限値を超えてしまう処理は、すべて失敗します。以下の設定でハードクォータを作成します。

* ディスク制限パラメータ
* ファイル制限パラメータ


ソフトクォータを設定すると、リソース使用量が特定のレベルに達したときに警告メッセージが送信されますが、データアクセス処理には影響しません。そのため、クォータを超過する前に適切な処理を実行できます。ソフトクォータは以下の設定で構成されます。

* ディスク制限しきい値パラメータ
* ディスクのソフトリミットパラメータ
* ファイルのソフトリミットパラメータ


しきい値クォータとソフトディスククォータを使用すると、管理者はクォータについての通知を複数受け取ることができます。通常、書き込みが失敗し始める前にしきい値によって「最終警告」が通知されるようにするため、管理者はディスク制限のしきい値をディスク制限よりもわずかに小さい値に設定します。

* * ディスク容量のハードリミット *
+
ハードクォータに適用されるディスクスペース制限。

* * ディスク容量のソフトリミット *
+
ソフトクォータに適用されるディスクスペース制限。

* * しきい値制限 *
+
しきい値クォータに適用されるディスクスペース制限。

* * ファイルのハードリミット *
+
ハードクォータの最大ファイル数。

* * ファイルソフトリミット *
+
ソフトクォータの最大ファイル数。





== クォータ管理

System Manager には、クォータを作成、編集、または削除するいくつかの機能が用意されています。ユーザクォータ、グループクォータ、またはツリークォータを作成し、ディスクレベルおよびファイルレベルでクォータ制限を指定できます。すべてのクォータは、ボリューム単位で設定されます。

クォータの作成後、次のタスクを実行できます。

* クォータを有効または無効にします
* クォータのサイズを変更




== クォータウィンドウ

クォータウィンドウを使用して、クォータに関する情報を作成、表示、および管理できます。



=== タブ

* * ユーザー定義クォータ *
+
ユーザー定義クォータ * タブを使用して、作成したクォータの詳細を表示したり、クォータを作成、編集、または削除することができます。

* * クォータレポート *
+
クォータレポートタブを使用して、スペースとファイルの使用状況を表示したり、アクティブなクォータのスペースとファイルの制限を編集したりできます。

* * ボリュームのクォータステータス *
+
ボリュームのクォータステータスタブを使用して、クォータのステータスを表示したり、クォータのオン / オフを切り替えたり、クォータのサイズを変更したりできます。





=== コマンドボタン

* * 作成 * 。
+
クォータの作成ウィザードを開きます。このウィザードで、クォータを作成できます。

* * 制限の編集 *
+
制限の編集ダイアログボックスを開きます。このダイアログボックスで、選択したクォータの設定を編集できます。

* * 削除 *
+
選択したクォータをクォータのリストから削除します。

* * 更新 *
+
ウィンドウ内の情報を更新します。





=== ユーザ定義のクォータのリスト

クォータのリストには、各クォータの名前とストレージの情報が表示されます。

* * 音量 *
+
クォータが適用されるボリュームを示します。

* * qtree *
+
クォータに関連付けられている qtree を示します。「すべての qtree 」は、クォータがすべての qtree に関連付けられていることを示します。

* * タイプ *
+
クォータのタイプがユーザ、グループ、またはツリーのいずれであるかを示します。

* * ユーザー / グループ *
+
クォータに関連付けられているユーザまたはグループを示します。「 all users 」は、クォータがすべてのユーザに関連付けられていることを示します。「すべてのグループ」は、そのクォータがすべてのグループに関連付けられていることを示します。

* * クォータターゲット *
+
クォータの割り当て先のターゲットのタイプを示します。qtree 、ユーザ、またはグループです。

* * スペースのハードリミット *
+
ハードクォータに適用されるディスクスペース制限を示します。

+
このフィールドはデフォルトでは非表示になっています。

* * スペースソフトリミット *
+
ソフトクォータに適用されるディスクスペース制限を示します。

+
このフィールドはデフォルトでは非表示になっています。

* * しきい値 *
+
しきい値クォータに適用されるディスクスペース制限を示します。

+
このフィールドはデフォルトでは非表示になっています。

* * ファイルハードリミット *
+
ハードクォータの最大ファイル数を示します。

+
このフィールドはデフォルトでは非表示になっています。

* * ファイルソフトリミット *
+
ソフトクォータの最大ファイル数を指定します。

+
このフィールドはデフォルトでは非表示になっています。





=== 詳細領域

クォータのリストの下の領域には、クォータの詳細が表示されます。これには、クォータエラー、スペースの使用量と制限、ファイルの使用量と制限などの情報が含まれます。

* 関連情報 *

https://docs.netapp.com/us-en/ontap/volumes/index.html["論理ストレージ管理"^]
