---
permalink: online-help-96-97/concept_svm_user_accounts.html 
sidebar: sidebar 
keywords: system, manager, create, manage, online, help, storage, virtual, machine, svm, user, account, password, change, lock, unlock , command, button 
summary: System Manager を使用して、 Storage Virtual Machine （ SVM ）ユーザアカウントを作成および管理できます。 
---
= System Manager - ONTAP 9.7以前を使用して、SVMユーザアカウントを作成および管理します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP System Manager クラシック（ ONTAP 9.7 以前で使用可能）を使用して、 Storage Virtual Machine （ SVM ）ユーザアカウントを作成および管理できます。



== SVM ユーザアカウントを追加

System Manager を使用して、 Storage Virtual Machine （ SVM ）ユーザアカウントを追加して、ストレージシステムにアクセスするためのユーザのログイン方法を指定できます。

.手順
. [ * ストレージ * > * SVMs * ] をクリックします。
. SVM を選択し、 * SVM 設定 * をクリックします。
. [* SVM User Details] ペインで、 [* Users] をクリックします。
. [ 追加（ Add ） ] をクリックします。
. ストレージシステムへの接続に使用するユーザ名およびパスワードを指定し、確認のためにパスワードをもう一度入力します。
. 1 つまたは複数のユーザーログイン方法を追加し、 * 追加 * をクリックします。
+
新しい vsadmin アカウント用に、 HTTP をアプリケーションとして使用して証明書で認証するログイン方法が自動的に組み込まれます。





== SVM ユーザアカウントのパスワードを変更します

System Manager を使用して、 Storage Virtual Machine （ SVM ）ユーザアカウントのパスワードをリセットできます。

.手順
. [ * ストレージ * > * SVMs * ] をクリックします。
. SVM を選択し、 * SVM 設定 * をクリックします。
. [* SVM User Details] ペインで、 [* Users] をクリックします。
. パスワードを変更するユーザーアカウントを選択し、 * パスワードのリセット * をクリックします。
. [ パスワードのリセット *] ダイアログボックスで、新しいパスワードを入力し、確認のために新しいパスワードを入力して、 [ *Change* ] をクリックします。




== SVM ユーザアカウントを編集します

System Manager を使用して、 Storage Virtual Machine （ SVM ）ユーザアカウントを編集し、ストレージシステムにアクセスするためのユーザのログイン方法を変更できます。

.手順
. [ * ストレージ * > * SVMs * ] をクリックします。
. SVM を選択し、 * SVM 設定 * をクリックします。
. [* SVM User Details] ペインで、 [* Users] をクリックします。
. 編集するユーザーアカウントを選択し、 * 編集 * をクリックします。
. 1 つ以上のユーザーログイン方法を変更し、 * 変更 * をクリックします。




== SVM ユーザアカウントをロックまたはロック解除します

System Manager を使用して、 Storage Virtual Machine （ SVM ）ユーザアカウントをロックしたりロックを解除したりできます。

.手順
. [ * ストレージ * > * SVMs * ] をクリックします。
. SVM を選択し、 * SVM 設定 * をクリックします。
. [* SVM User Details] ペインで、 [* Users] をクリックします。
. [ * ユーザー * ] ウィンドウで、アカウントステータスを変更するユーザーアカウントを選択し、必要に応じて [ * ロック * ] または [ * ロック解除 * ] をクリックします。




== ユーザーウィンドウ

ユーザウィンドウを使用して、ユーザアカウントの管理、ユーザのパスワードのリセット、およびすべてのユーザアカウントに関する情報の表示を行うことができます。



=== コマンドボタン

* * 追加 * 。
+
ユーザーの追加ダイアログボックスを開きます。このダイアログボックスで、ユーザーアカウントを追加できます。

* * 編集 * 。
+
Modify User ダイアログボックスが開き、ユーザのログイン方法を変更できます。

+
[NOTE]
====
ユーザアカウントのすべてのアクセス方法と認証方法で 1 つのロールを使用することがベストプラクティスです。

====
* * 削除 *
+
選択したユーザアカウントを削除できます。

* * パスワードの変更 *
+
[ パスワードの変更 ] ダイアログボックスが開き、選択したユーザーのパスワードをリセットできます。

* * ロック *
+
ユーザアカウントをロックします。

* * 更新 *
+
ウィンドウ内の情報を更新します。





=== ユーザリスト

ユーザリストの下の領域には、選択したユーザに関する詳細情報が表示されます。

* * ユーザー *
+
ユーザアカウントの名前が表示されます。

* * アカウントがロックされています *
+
ユーザアカウントがロックされているかどうかが表示されます。





=== User Login Methods 領域

* * アプリケーション *
+
ユーザがストレージシステムにアクセスするために使用できるアクセス方法を表示します。サポートされるアクセス方法は次のとおりです。

+
** システムコンソール（ console ）
** HTTP （ S ）（ http ）
** ONTAP API （ ONTAPI ）
** サービスプロセッサ（ service-processor ）
** SSH （ ssh ）


* * 認証 *
+
デフォルトでサポートされている認証方式（「 password 」）を表示します。

* * 役割 *
+
選択したユーザのロールが表示されます。


