---
permalink: online-help-96-97/concept_cluster_peers.html 
sidebar: sidebar 
keywords: cluster, peer, data, replication, snapmirror, snapvault, flexcache, syncmirror, configuration, system, manager, modify, passphrase, lif, configure, remote, change, encryption, status, online, help 
summary: SnapMirror テクノロジと SnapVault テクノロジを使用したデータレプリケーションや、 MetroCluster 構成で FlexCache ボリュームと SyncMirror テクノロジを使用したデータレプリケーションを行うには、クラスタ間にピア関係を設定することが必要になります。System Manager を使用して、 2 つのクラスタ間にピア関係を設定できます。 2 つのクラスタを連携させて、クラスタ間でリソースを共有できるようになります。 
---
= System Manager とクラスタピア - ONTAP 9.7 以前
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP System Manager クラシック（ ONTAP 9.7 以前で使用可能）を使用して、 2 つのクラスタをピアリングし、ピアクラスタ間でリソースを調整および共有できるようにすることができます。SnapMirror テクノロジと SnapVault テクノロジを使用したデータレプリケーションや、 MetroCluster 構成で FlexCache ボリュームと SyncMirror テクノロジを使用したデータレプリケーションを行うには、クラスタ間にピア関係を設定することが必要になります。



== ピアリングパスフレーズを生成

System Manager 9.6 以降では、ローカルクラスタの IPspace のパスフレーズを生成し、リモートクラスタでピア関係を作成するときに同じパスフレーズを使用できます。

.手順
. [ * Configuration * ] > [* Cluster Peers* ] をクリックします。
. [Generate Peering Passphrase]( ピアリングパスフレーズの生成 ) を
+
[Generate Peering Passphrase] ダイアログウィンドウが表示されます。

. 次のフィールドを設定します。
+
** * IPspace * ：プルダウンメニューから IPspace を選択します。
** * パスフレーズの有効期限 * ：パスフレーズを有効にする期間をドロップダウンメニューから選択します。
** * SVM 権限 * ：次のいずれかを選択します。
+
*** * すべての SVM * ：クラスタへのアクセスをすべての SVM に許可します。
*** * 選択した SVM * 。クラスタへのアクセスを許可する SVM を指定します。指定するフィールドで SVM 名を選択します。




. *オプション：リモートクラスタの有効なクラスタバージョンがONTAP 9.6より前の場合はチェックボックスを選択します。選択しないとクラスタピアリングが生成されません。
. [*Generate] をクリックしてパスフレーズを生成します。
+
生成が完了すると、パスフレーズが記載されたメッセージが表示されます。

. パスフレーズを E メールで送信するかコピーする場合は、次のいずれかを実行します。
+
** [ * 電子メールパスフレーズの詳細を送信する * ] をクリック
** [* パスフレーズのコピー * ] をクリックします。






== クラスタピアパスフレーズを変更します

クラスタピアの作成時に作成されたパスフレーズを変更できます。

.手順
. [[step1]]*[設定]*>*[クラスタピア]*をクリックします。
. ピアクラスタを選択し、 * Edit * をクリックします
+
ドロップダウンメニューが表示されます。

. [ ローカルクラスタのパスフレーズ ] をクリックします。
+
Edit Local Cluster Passphrase （ローカルクラスタのパスフレーズの編集）ダイアログウィンドウが表示

. [[step4]]*[パスフレーズの入力]*フィールドに新しいパスフレーズを入力し、*[適用]*をクリックします。
+
[NOTE]
====
パスフレーズは 8 文字以上で指定する必要があります。

====
+
パスフレーズはすぐに変更されます。ただし、正しい認証ステータスが表示されるまでに時間がかかることがあります。

. リモートクラスタにログインし、手順を実行します link:#step1["1."] から link:#step4["4."] リモートクラスタでパスフレーズを変更してください。
+
ローカルクラスタの認証ステータスはと表示されます。 `ok_and_offer` ただし、リモートクラスタでパスフレーズを変更する必要はありません。





== リモートクラスタ用に設定されている LIF を変更します

System Manager を使用して、リモートクラスタ用に設定されている IPspace およびクラスタ間論理インターフェイス（ LIF ）を変更できます。クラスタ間 IP アドレスの新規追加や既存の IP アドレスの削除が可能です。

.作業を開始する前に
クラスタピア関係を作成するためには、クラスタ間 IP アドレスが少なくとも 1 つ必要です。

.手順
. [ * Configuration * ] > [* Cluster*] > [* Configuration Updates* ] をクリックします。
. ピアクラスタを選択し、 * Edit * をクリックします
+
ドロップダウンメニューが表示されます。

. [* Peer Cluster Network Parameters* （ピアクラスタネットワークパラメータ * ） ] をクリック
+
[Edit Peer Network Parameters] ダイアログボックスが表示されます。

. 必要に応じて、次のフィールドを変更します。
+
** * IPspace * ：プルダウンメニューから IPspace を選択します。
** * インタークラスタ LIF * ：クラスタ間 IP アドレスを追加または削除します。複数の IP アドレスを追加する場合は、カンマで区切ります。


. * 変更 * をクリックします。
. [*Cluster Peers* （クラスタピア * ） ] ウィンドウで行った変更を確認します。




== ピアリングの暗号化ステータスを変更します

System Manager を使用して、選択したクラスタのピアリングの暗号化ステータスを変更できます。

.このタスクについて
暗号化ステータスは有効または無効にできます。[ 有効 ] から [ 無効 ] または [ 無効 ] から [ 有効 ] にステータスを変更するには、 [ * 暗号化の変更 * ] を選択します。

.手順
. [ * Configuration * ] > [* Cluster Peers* ] をクリックします。
. ピアクラスタを選択し、 * Edit * をクリックします
+
ドロップダウンメニューが表示されます。

. ［ * 暗号化の変更 * ］ をクリックします。
+
暗号化ステータスが「 N/A 」の場合、このアクションは使用できません。

+
[ 暗号化の変更 ] ダイアログボックスが表示されます。現在の暗号化ステータスがボタンに表示されます。

. ボタンをスライドしてピアリングの暗号化ステータスを変更し、次に進みます。
+
** 現在の暗号化ステータスが「 none 」の場合は、トグルボタンをスライドしてステータスを「 tls_psk 」に変更することで暗号化を有効にできます。
** 現在の暗号化ステータスが「 TLS_PSK 」の場合は、トグルボタンをスライドしてステータスを「 none 」に変更することで暗号化を無効にできます。


. ピアリングの暗号化を有効または無効にしたら、新しいパスフレーズを生成してピアクラスタで指定するか、ピアクラスタで生成済みの既存のパスフレーズを適用することができます。
+
[NOTE]
====
ローカルサイトで使用しているパスフレーズがリモートサイトで使用しているパスフレーズと一致しないと、クラスタピア関係は正しく機能しません。

====
+
次のいずれかを選択します。

+
** *パスフレーズの生成*：に進みます。 link:#step6["ステップ6"]。
** *すでにパスフレーズを使用しています*：に進みます。 link:#step9["ステップ9"]。


. [[step6]]*[パスフレーズの生成]*を選択した場合は、必要なフィールドに入力します。
+
** * IPspace * ：ドロップダウンメニューから IPspace を選択します。
** * パスフレーズの有効期限 * ：パスフレーズを有効にする期間をドロップダウンメニューから選択します。
** * SVM 権限 * ：次のいずれかを選択します。
+
*** * すべての SVM * 。すべての SVM にクラスタへのアクセスを許可します。
*** * 選択した SVM * 。クラスタへのアクセスを許可する SVM を指定します。指定するフィールドで SVM 名を選択します。




. *オプション：リモートクラスタの有効なクラスタバージョンがONTAP 9.6より前の場合はチェックボックスを選択します。選択しないとパスフレーズの生成が失敗します。
. [ 適用（ Apply ） ] をクリックします。
+
関係のパスフレーズが生成されて表示されます。パスフレーズはコピーするか E メールで送信することができます。

+
ローカルクラスタの認証ステータスはと表示されます。 `ok_and_offer` 選択したパスフレーズの有効期間（リモートクラスタでパスフレーズを指定するまで）。

. [[step9]]リモートクラスタで新しいパスフレーズをすでに生成している場合は、次の手順を実行します。
+
.. [ * 既存のパスフレーズを使用する * ] をクリックします。
.. 「 * Passphrase * 」フィールドに、リモートクラスタで生成されたパスフレーズと同じパスフレーズを入力します。
.. [ 適用（ Apply ） ] をクリックします。






== クラスタピア関係を削除します

System Manager を使用して、不要になったクラスタピア関係を削除できます。クラスタピア関係は、ピア関係にある各クラスタから削除する必要があります。

.手順
. [[step1]]*[設定]*>*[クラスタピア]*をクリックします。
. 関係を削除するクラスタピアを選択し、 * Delete * をクリックします。
. [[step3]]確認のチェックボックスを選択し、*[削除]*をクリックします。
. リモートクラスタにログインし、手順を実行します link:#step1["1."] から link:#step3["3."] ローカルクラスタとリモートクラスタ間のピア関係を削除します。
+
ローカルクラスタとリモートクラスタの両方から関係が削除されるまで、ピア関係のステータスは「 unhealthy 」と表示されます。





== クラスタピアウィンドウ

クラスタピアウィンドウを使用してピアクラスタ関係を管理し、クラスタ間でデータを移動できます。



=== コマンドボタン

* * 作成 * 。
+
クラスタピアリングの作成ダイアログボックスを開きます。このダイアログボックスで、リモートクラスタとの関係を作成できます。

* * 編集 * 。
+
ドロップダウンメニューに次のオプションが表示されます。

+
** * ローカルクラスタのパスフレーズ *
+
Edit Local Cluster Passphrase （ローカルクラスタのパスフレーズの編集）ダイアログボックスを開きます。このダイアログボックスで、ローカルクラスタを検証する新しいパスフレーズを入力できます。

** * ピアクラスタのネットワークパラメータ *
+
Edit Peer Cluster Network Parameters ダイアログボックスを開きます。このダイアログボックスで、 IPspace を変更したり、クラスタ間 LIF の IP アドレスを追加または削除したりできます。

+
複数の IP アドレスを追加する場合は、カンマで区切ります。

** * 暗号化の変更 *
+
選択したピアクラスタの Change Encryption ダイアログボックスを開きます。ピア関係の暗号化を変更した場合、新しいパスフレーズを生成してピアクラスタで指定するか、ピアクラスタで生成済みの既存のパスフレーズを指定することができます。

+
暗号化ステータスが「 N/A 」の場合、このアクションは使用できません。



* * 削除 *
+
クラスタピア関係の削除ダイアログボックスを開きます。このダイアログボックスで、選択したピアクラスタ関係を削除できます。

* * 更新 *
+
ウィンドウ内の情報を更新します。

* * SVM の権限の管理 *
+
SVM で SVM ピア要求を自動的に承認できます。

* * ピアリングパスフレーズの生成 *
+
IPspace 、パスフレーズの有効期限、および権限を付与する SVM を指定して、ローカルクラスタの IPspace のパスフレーズを生成できます。

+
リモートクラスタでも同じピアリングパスフレーズを使用します。





=== ピアクラスタリスト

* * ピアクラスタ *
+
関係内のピアクラスタの名前を示します。

* * 利用可能性 *
+
ピアクラスタを通信に使用できるかどうかを示します。

* * 認証ステータス *
+
ピアクラスタが認証済みかどうかを示します。

* * ローカルクラスタ IPspace *
+
ローカルクラスタピア関係に関連付けられている IPspace が表示されます。

* * ピアクラスタのクラスタ間 IP アドレス *
+
クラスタ間ピア関係に関連付けられている IP アドレスが表示されます。

* * 最終更新日時 *
+
ピアクラスタが最後に変更された日時が表示されます。

* * 暗号化 *
+
ピア関係の暗号化ステータスが表示されます。

+
[NOTE]
====
System Manager 9.6 以降では、 2 つのクラスタ間にピア関係を確立する際、デフォルトでピア関係が暗号化されます

====
+
** * N/A * ：暗号化は関係に適用されません。
** * none * ：ピア関係は暗号化されません。
** * tls_psk * ：ピア関係は暗号化されています。



