---
permalink: online-help-96-97/concept_name_mapping.html 
sidebar: sidebar 
keywords: name, mapping, system, manager, specify, user, platform, online, help, command, button, rules 
summary: System Manager を使用して、ネームマッピングエントリを指定し、異なるプラットフォームのユーザをマッピングできます。 
---
= System Manager を使用したネームマッピング - ONTAP 9.7 以前
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP System Manager クラシック（ ONTAP 9.7 以前で使用可能）を使用して、ネームマッピングエントリを指定し、異なるプラットフォームのユーザをマッピングできます。



== ネームマッピングの変換ルール

ONTAP システムには、 SVM ごとに一連の変換ルールが保存されています。各ルールは、 a_pattern_ と a_replacement _ の 2 つの要素で構成されます。変換は該当するリストの先頭から開始され、最初に一致したルールに基づいて実行されます。パターンは UNIX 形式の正規表現です。リプレースメントは、UNIXのように、パターンのサブ式を表すエスケープシーケンスを含む文字列です `sed` プログラム。



== ネームマッピングウィンドウ

ネームマッピングウィンドウを使用して、ネームマッピングエントリを指定し、異なるプラットフォームのユーザをマッピングできます。



=== ネームマッピング

ネームマッピングを作成して使用することにより、 UNIX ユーザから Windows ユーザ、 Windows ユーザから UNIX ユーザ、 Kerberos ユーザから UNIX ユーザへのマッピングが可能です。



=== コマンドボタン

* * 追加 * 。
+
ネームマッピングエントリの追加ダイアログボックスを開きます。このダイアログボックスで、 Storage Virtual Machine （ SVM ）上にネームマッピングを作成できます。

* * 編集 * 。
+
ネームマッピングエントリの編集ダイアログボックスを開きます。このダイアログボックスで、 SVM のネームマッピングを編集できます。

* * 削除 *
+
ネームマッピングエントリの削除ダイアログボックスを開きます。このダイアログボックスで、ネームマッピングエントリを削除できます。

* * スワップ *
+
ネームマッピングエントリのスワップ（ Swap Name Mapping Entries ）ダイアログボックスを開きます。このダイアログボックスでは、選択した 2 つのネームマッピングエントリの位置を切り替えることができます。

* * 更新 *
+
ウィンドウ内の情報を更新します。





=== ネームマッピングのリスト

* * 位置 *
+
優先順位リスト内でのネームマッピングの位置を示します。ネームマッピングは、優先順位リストの順序に従って適用されます。

* * パターン *
+
照合するユーザ名のパターンを示します。

* * 交換 *
+
変換後のユーザ名のパターンを示します。

* * 方向 *
+
ネームマッピングの方向を示します。Kerberos から UNIX へのネームマッピングの場合は krb_unix 、 Windows から UNIX へのネームマッピングの場合は win_unix 、 UNIX から Windows へのネームマッピングの場合は unix_win になります。





=== コマンドボタン

* * 追加 * 。
+
Add Group Mapping Entry ダイアログボックスを開きます。このダイアログボックスで、 SVM に対するグループマッピングを作成できます。

* * 編集 * 。
+
Edit Group Mapping Entry ダイアログボックスを開きます。このダイアログボックスで、 SVM のグループマッピングを編集できます。

* * 削除 *
+
Delete Group Mapping Entries ダイアログボックスを開きます。このダイアログボックスで、グループマッピングエントリを削除できます。

* * スワップ *
+
Swap Group Mapping Entries ダイアログボックスを開きます。このダイアログボックスで、選択した 2 つのグループマッピングエントリの位置を切り替えることができます。

* * 更新 *
+
ウィンドウ内の情報を更新します。





=== グループマッピングのリスト

* * 位置 *
+
優先順位リスト内でのグループマッピングの位置を示します。グループマッピングは、優先順位リストの順序に従って適用されます。

* * パターン *
+
照合するユーザ名のパターンを示します。

* * 交換 *
+
変換後のユーザ名のパターンを示します。

* * 方向 *
+
グループマッピングの方向を示します。指定できる値はです `krb_unix` KerberosからUNIXへのグループマッピングの場合は、 `win_unix` WindowsからUNIXへのグループマッピングの場合 `unix_win` UNIXからWindowsへのグループマッピングの場合。



* 関連情報 *

https://docs.netapp.com/us-en/ontap/smb-admin/index.html["SMB / CIFS の管理"]
