---
permalink: online-help-96-97/concept_what_compatible_spare_disks_are.html 
sidebar: sidebar 
keywords: system, manager, compatible, spare, disk, hdd, compacity, raid, online, help 
summary: System Manager では、互換性のあるスペアディスクとは、アグリゲート内の他のディスクとプロパティが一致するディスクです。HDD （データディスク）を追加して既存のアグリゲートのサイズを拡張する場合、またはアグリゲートの RAID タイプを RAID4 から RAID-DP に変更する場合は、十分な数の互換性のあるスペアディスクがアグリゲートに含まれている必要があります。 
---
= System Manager - ONTAP 9.7 以前の互換性のあるスペアディスク
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP System Manager クラシック（ ONTAP 9.7 以前で使用可能）では、互換性のあるスペアディスクとは、アグリゲート内の他のディスクとプロパティが一致するディスクです。HDD （データディスク）を追加して既存のアグリゲートのサイズを拡張する場合、またはアグリゲートの RAID タイプを RAID4 から RAID-DP に変更する場合は、十分な数の互換性のあるスペアディスクがアグリゲートに含まれている必要があります。

一致する必要のあるディスクプロパティは、ディスクタイプ、ディスクサイズ（同じディスクサイズを使用できない場合は、より大きなサイズ）、ディスクの rpm 、チェックサム、ノードの所有者、プール、 共有ディスクのプロパティを定義できます。大きいサイズのディスクを使用する場合、ディスクがダウンサイズされ、すべてのディスクのサイズが最もサイズの小さいディスクに合わせて縮小されることに注意してください。既存の共有ディスクはそれよりもサイズの大きい非共有ディスクに合わせられ、非共有ディスクが共有ディスクに変換されてスペアとして追加されます。

ディスクタイプの混在やディスク rpm の混在など、 RAID の混在オプションが RAID グループに対して有効になっている場合は、 アグリゲートの既存のディスクのディスクタイプとディスク rpm は、互換性があるスペアを取得するために使用されるスペアディスクの有効なディスクタイプと有効なディスク rpm と一致します。

* 関連情報 *

xref:task_adding_capacity_disks.adoc[データディスクを追加しています]

xref:task_editing_aggregates.adoc[アグリゲートの編集]
