---
permalink: online-help-96-97/concept_iscsi_protocol.html 
sidebar: sidebar 
keywords: iscsi, protocol, system, manager, configure, block, data, host, tcp, ip, online, help, initiate, disable, enable, dialog, box, security, authentication, default 
summary: System Manager を使用して iSCSI プロトコルを設定できます。これにより、 TCP / IP で SCSI プロトコルを使用してブロックデータをホストに転送できます。 
---
= System Manager - ONTAP 9.7 以前で iSCSI プロトコルを設定します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP System Manager クラシック（ ONTAP 9.7 以前で使用可能）を使用して iSCSI プロトコルを設定できます。これにより、 TCP / IP で SCSI プロトコルを使用してブロックデータをホストに転送できます。



== iSCSI エイリアスを作成します

iSCSI エイリアスは、ユーザインターフェイスで iSCSI ターゲットデバイス（この場合はストレージシステム）を識別しやすくするために、そのターゲットデバイスに割り当てるわかりやすい識別子です。System Manager を使用して、 iSCSI エイリアスを作成できます。

.このタスクについて
iSCSI エイリアスは、 1~128 の印刷可能文字で構成される文字列です。 iSCSI エイリアスにはスペースを使用できません。

.手順
. [ * ストレージ * > * SVMs * ] をクリックします。
. SVM を選択し、 * SVM 設定 * をクリックします。
. [*Protocols* ] ペインで、 [*iSCSI*] をクリックします。
. [* iSCSI * ] ウィンドウの [ サービス * ] タブで、 [ * 編集 ] をクリックします。
. Edit iSCSI Service Configuration * （ iSCSI サービス構成の編集）ダイアログボックスの * Target Alias （ターゲットエイリアス） * フィールドに iSCSI エイリアスを入力し、 * OK * をクリックします。




== ストレージシステムインターフェイスで iSCSI サービスを有効または無効にします

System Manager を使用してネットワークインターフェイスを有効または無効にすることで、 iSCSI 通信に使用するネットワークインターフェイスを制御できます。iSCSI サービスが有効な場合、 iSCSI の接続と要求は、 iSCSI に対して有効になっているネットワークインターフェイス上で許可されますが、無効になっているインターフェイス上では許可されません。

.作業を開始する前に
インターフェイスを現在使用している iSCSI 接続および iSCSI セッションをすべて終了しておく必要があります。デフォルトでは、 iSCSI ライセンスを有効にすると、すべてのイーサネットインターフェイスで iSCSI サービスが有効になります。

.手順
. [ * ストレージ * > * SVMs * ] をクリックします。
. SVM を選択し、 * SVM 設定 * をクリックします。
. [*Protocols* ] ペインで、 [*iSCSI*] をクリックします。
. iSCSI Interfaces * 領域で、 iSCSI サービスを有効または無効にするインターフェイスを選択します。
. 必要に応じて、 *Enable* または *Disable* をクリックします。




== iSCSI イニシエータのセキュリティ方式を追加します

System Manager を使用して、イニシエータを追加し、イニシエータの認証に使用されるセキュリティ方式を指定できます。

.手順
. [ * ストレージ * > * SVMs * ] をクリックします。
. SVM を選択し、 * SVM 設定 * をクリックします。
. [*Protocols* ] ペインで、 [*iSCSI*] をクリックします。
. [* iSCSI * ] ウィンドウで、 [ * イニシエータ・セキュリティ * ] タブをクリックします。
. [* Initiator Security* （イニシエータセキュリティ * ） ] 領域で [* Add] をクリックします。
. イニシエータを認証するためのイニシエータ名とセキュリティ方式を指定します。
+
CHAP 認証の場合、インバウンド設定に対するユーザ名とパスワードを入力し、確認用にパスワードを再度入力する必要があります。アウトバウンド設定の場合、このログイン情報はオプションです。

. [OK] をクリックします。




== デフォルトのセキュリティ設定を編集します

System Manager の Edit Default Security ダイアログボックスを使用して、ストレージシステムに接続されている iSCSI イニシエータのデフォルトのセキュリティ設定を編集できます。

.手順
. [ * ストレージ * > * SVMs * ] をクリックします。
. SVM を選択し、 * SVM 設定 * をクリックします。
. [*Protocols* ] ペインで、 [*iSCSI*] をクリックします。
. [ イニシエータセキュリティ *] タブの [ デフォルトセキュリティ *] 領域で、 [ 編集 *] をクリックします。
. [ デフォルトセキュリティの編集 *] ダイアログボックスで、セキュリティタイプを変更します。
+
CHAP 認証の場合、インバウンド設定に対するユーザ名とパスワードを入力し、確認用にパスワードを再度入力する必要があります。アウトバウンド設定の場合、このログイン情報はオプションです。

. [OK] をクリックします。




== デフォルトの iSCSI イニシエータ認証方法を変更します

System Manager を使用して、特定の認証方式が設定されていないイニシエータに対して使用されるデフォルトの iSCSI 認証方式を変更できます。

.手順
. [ * ストレージ * > * SVMs * ] をクリックします。
. SVM を選択し、 * SVM 設定 * をクリックします。
. [*Protocols* ] ペインで、 [*iSCSI*] をクリックします。
. [ * イニシエータ・セキュリティ * ] タブの [ * デフォルト・セキュリティ * ] 領域で、 [ * 編集 * ] をクリックします。
. セキュリティタイプを変更します。
+
CHAP 認証の場合、インバウンド設定に対するユーザ名とパスワードを入力し、確認用にパスワードを再度入力する必要があります。アウトバウンド設定の場合、このログイン情報はオプションです。

. [OK] をクリックします。




== iSCSI イニシエータのデフォルトセキュリティを設定します

System Manager を使用して、イニシエータの認証設定を削除し、イニシエータの認証にデフォルトのセキュリティ方法を使用できます。

.手順
. [ * ストレージ * > * SVMs * ] をクリックします。
. SVM を選択し、 * SVM 設定 * をクリックします。
. [*Protocols* ] ペインで、 [*iSCSI*] をクリックします。
. [* Initiator Security* （イニシエータセキュリティ * ） ] タブで、セキュリティ設定を変更するイニシエータを選択します。
. [* Initiator Security* （イニシエータセキュリティ * ） ] 領域で [* Set Default* （デフォルトの設定 * ） ] をクリックし、確認ダイアログボックスで [* Set Default* （デフォルトの設定 * ） ] をクリックします。




== iSCSI サービスを開始または停止します

System Manager を使用して、ストレージシステムで iSCSI サービスを開始または停止できます。

.手順
. [ * ストレージ * > * SVMs * ] をクリックします。
. SVM を選択し、 * SVM 設定 * をクリックします。
. [*Protocols* ] ペインで、 [*iSCSI*] をクリックします。
. 必要に応じて、 [ スタート * ] または [ * 停止 * ] をクリックします。




== イニシエータセキュリティ情報を表示します

System Manager を使用して、デフォルトの認証情報、およびイニシエータ固有のすべての認証情報を表示できます。

.手順
. [ * ストレージ * > * SVMs * ] をクリックします。
. SVM を選択し、 * SVM 設定 * をクリックします。
. [*Protocols* ] ペインで、 [*iSCSI*] をクリックします。
. [* iSCSI * ] ウィンドウの [ * イニシエータ・セキュリティ * ] タブで、詳細を確認します。




== iSCSI ウィンドウ

iSCSI ウィンドウでは、 iSCSI サービスの開始または停止、ストレージシステムの iSCSI ノード名の変更、ストレージシステムの iSCSI エイリアスの作成または変更を行うことができます。また、ストレージシステムに接続されている iSCSI イニシエータのイニシエータセキュリティ設定の追加や変更も可能です。



=== タブ

* * サービス *
+
サービス * タブを使用して、 iSCSI サービスの開始または停止、ストレージ・システムの iSCSI ノード名の変更、ストレージ・システムの iSCSI エイリアスの作成または変更を行うことができます。

* * イニシエータセキュリティ *
+
[ * イニシエータ・セキュリティ * ] タブを使用して、ストレージ・システムに接続されている iSCSI イニシエータのイニシエータ・セキュリティ設定を追加または変更できます。





=== コマンドボタン

* * 編集 * 。
+
Edit iSCSI Service Configurations （ iSCSI サービス設定の編集）ダイアログボックスが開きます。このダイアログボックスで、ストレージシステムの iSCSI ノード名と iSCSI エイリアスを変更できます。

* * 開始 *
+
iSCSI サービスを開始します。

* * 停止 *
+
iSCSI サービスを停止します。

* * 更新 *
+
ウィンドウ内の情報を更新します。





=== 詳細領域

詳細領域には、 iSCSI サービスのステータス、 iSCSI ターゲットノード名、および iSCSI ターゲットエイリアスに関する情報が表示されます。この領域で、ネットワークインターフェイスに対して iSCSI サービスを有効または無効にできます。

* 関連情報 *

https://docs.netapp.com/us-en/ontap/san-admin/index.html["SAN 管理"^]
