---
permalink: online-help-96-97/concept_high_availability.html 
sidebar: sidebar 
keywords: high, availability, system, manager, hardware, redundancy, nondisruptive, operations, fault, tolerance 
summary: System Manager を使用して、ノンストップオペレーションやフォールトトレランスに不可欠なハードウェアの冗長性を確保するためのハイアベイラビリティ（ HA ）ペアを作成できます。 
---
= System Manager - ONTAP 9.7 以前を使用してハイアベイラビリティペアを作成します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP System Managerクラシック（ONTAP 9.7以前で使用可能）を使用して、ノンストップオペレーションやフォールトトレランスに必要なハードウェアの冗長性を確保するハイアベイラビリティ（HA）ペアを作成できます。



== [ ハイアベイラビリティ（ High Availability ） ] ウィンドウ

ハイアベイラビリティウィンドウには、 ONTAP のすべての HA ペアのハイアベイラビリティ（ HA ）の状態、インターコネクトのステータス、テイクオーバーまたはギブバックのステータスが図で表示されます。ハイアベイラビリティウィンドウを使用して、テイクオーバー処理やギブバック処理を手動で開始することもできます。

HA ペアの図をクリックすると、テイクオーバー / ギブバックのステータスやインターコネクトのステータスなどの詳細を確認できます。

HA ペアのステータスは色で示されます。

* グリーン： HA ペアとインターコネクトが最適に構成されており、テイクオーバーやギブバックが可能であることを示します。
+
テイクオーバーを実行中、ギブバックを実行中、およびギブバックを待機中の状態のときもグリーンになります。

* 赤：テイクオーバーエラーなどのダウングレード状態が発生していることを示します。
* イエロー：インターコネクトのステータスが停止中であることを示します。


クラスタの複数の HA ペアで同時にストレージフェイルオーバー処理を実行中の場合、表示されるクラスタのステータスは HA ペアのステータスと重大度に基づいて決まります。クラスタのステータス表示の優先順位は、テイクオーバー実行中、ギブバック実行中、ギブバック待機中の順となります。



=== アクション

HA ペアのノードのステータスに基づいて、テイクオーバーやギブバックなどの作業を実行できます。

* テイクオーバー `node_name`
+
パートナーノードで保守を行う必要があるときにテイクオーバー処理を実行できます。

* ギブバック `node_name`
+
テイクオーバーされたパートナーノードがギブバック待機状態または部分的なギブバック状態になったときにギブバック処理を実行できます。

* 自動ギブバックを有効または無効にします
+
自動ギブバック処理を有効または無効にします。

+
[NOTE]
====
自動ギブバックはデフォルトでは有効になっています。

====




=== コマンドボタン

* * 更新 *
+
ウィンドウ内の情報を更新します。

+
[NOTE]
====
ハイアベイラビリティウィンドウに表示される情報は、 60 秒ごとに自動的に更新されます。

====


* 関連情報 *

xref:task_monitoring_ha_pairs.adoc[HA ペアの監視]
