---
permalink: online-help-96-97/concept_hardware_cache.html 
sidebar: sidebar 
keywords: hardware, cache, system, manager, manage, online, help, flash, 
summary: System Manager を使用して、ハードウェアキャッシュモジュールを管理できます。 
---
= System Manager - ONTAP 9.7 以前を使用してハードウェアキャッシュを管理します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP System Manager クラシック（ ONTAP 9.7 以前で使用可能）を使用して、ハードウェアキャッシュモジュールを管理できます。

[NOTE]
====
System Manager では、 Flash Cache をハードウェアキャッシュと呼びます。

====


== Flash Cache モジュールを有効または無効にします

System Manager を使用して、 Flash Cache モジュールがインストールされているストレージシステムに対して、外部キャッシュ機能を有効または無効にできます。Flash Cache モジュールは、ストレージシステムのワークロード要件に基づいて有効にすることができます。

.手順
. [ * 構成 *>* ハードウェアキャッシュ *] をクリックします
. モジュールを変更する場合は、スライダボタンを動かして各モジュールを必要に応じて有効または無効にします。




== Flash Cache モジュールの仕組み

Flash Cache モジュールを使用すると、ストレージシステムのパフォーマンスが向上します。Flash Cache モジュールの使用による影響は、 Hardware Cache ウィンドウに表示されます。

Flash Cache モジュールとディスクは、ストレージシステムのワークロード要件に基づいて設定することができます。Flash Cache モジュールとディスクで処理する読み取りワークロード（読み取り操作の数）を特定することで、ストレージシステムのパフォーマンスを分析できます。

ストレージシステムのブート時や、テイクオーバー後にストレージシステムに制御が戻った時点では、 Flash Cache モジュールにはデータが格納されていません。そのため、ストレージシステムのその時点のデータ読み取り要求はすべてディスクで処理されます。

Flash Cache モジュールには、データ読み取り要求が処理されるに従って少しずつデータが取り込まれます。データ読み取り要求の処理は、 Flash Cache モジュールの方がディスクよりも高速であるため、 Flash Cache モジュールを利用するとストレージシステムのパフォーマンスが向上します。

Flash Cache モジュールで処理されるデータ読み取り要求は、ディスクで処理されるデータ読み取り要求に代わるものであるため、ストレージシステムのパフォーマンスがどの程度向上するかは、代わりに処理されるディスク読み取りによって決まります。ストレージシステムのパフォーマンスに対する Flash Cache モジュールの影響を判断するには、 Flash Cache モジュールにデータが含まれている場合に、 Hardware Cache ウィンドウに読み取りワークロードのグラフを表示する必要があります。



== Hardware Cache （ハードウェアキャッシュ）ウィンドウ

Hardware Cache ウィンドウを使用して、 Flash Cache モジュールがインストールされているストレージシステムに対して Flash Cache モジュールを有効または無効にすることができます。また、読み取りワークロードの統計情報も確認できます。



=== モジュール情報

* * ストレージシステム名 *
+
Flash Cache モジュールがインストールされているストレージシステムの名前が、図の下に表示されます。

* * 切り替えボタンを有効 / 無効にします *
+
トグルボタンを動かしてモジュールを有効または無効にします。

* * サイズ *
+
モジュールのサイズ（ギガバイト）。Flash Cache モジュールカードが複数ある場合は、すべてのカードのキャッシュサイズの合計が表示されます。

+
[NOTE]
====
表示されるFlash Cacheモジュールのサイズは、次の理由により実際のサイズと異なります。
    - System Managerでは、ONTAPから提供される使用可能容量のみが報告されます。
    -合計容量の一部はメタデータを格納するために予約されています。

====
* * モデル名 *
+
モジュールのモデル名。

* * システムの読み取り遅延 *
+
平均読み取りレイテンシがミリ秒単位で表示されます。





=== キャッシュの読み取りワークロード

ディスクと Flash Cache モジュールで処理される読み取りワークロードの割合をグラフに示して、ストレージシステムのパフォーマンスを示します。
