---
permalink: online-help-96-97/concept_aggregates.html 
sidebar: sidebar 
keywords: aggregates, system, manager, security, backup, performance, data, sharing, classic, online, help, window 
summary: System Manager を使用して、セキュリティ、バックアップ、パフォーマンス、およびデータ共有に関するさまざまな要件をサポートするアグリゲートを作成できます。 
---
= System Manager - ONTAP 9.7 以前を使用してアグリゲートを管理します
:allow-uri-read: 


ONTAP System Manager クラシック（ ONTAP 9.7 以前で使用可能）を使用して、セキュリティ、バックアップ、パフォーマンス、およびデータ共有に関するさまざまな要件をサポートするアグリゲートを作成できます。



== アグリゲートウィンドウに戻ります

アグリゲートウィンドウを使用して、アグリゲートに関する情報を作成、表示、および管理できます。



=== コマンドボタン

* * 作成 * 。
+
アグリゲートの作成ダイアログボックスを開きます。このダイアログボックスで、アグリゲートを作成できます。

* * 編集 * 。
+
アグリゲートの編集ダイアログボックスを開きます。このダイアログボックスで、アグリゲートの名前またはアグリゲートに提供する RAID 保護のレベルを変更できます。

* * 削除 *
+
選択したアグリゲートを削除します。

+
[NOTE]
====
このボタンは、ルートアグリゲートに対しては無効になります。

====
* * その他のアクション *
+
次のオプションが用意されています。

* * ステータスを * に変更します
+
選択したアグリゲートのステータスを次のいずれかに変更します。

+
** オンライン
+
このアグリゲートに含まれるボリュームへの読み取りおよび書き込みアクセスが許可されます。

** オフラインです
+
読み取りおよび書き込みアクセスが許可されていません。

** 制限
+
パリティの再構築などの一部の処理は許可されますが、データアクセスは許可されません。



* * 容量を追加 *
+
既存のアグリゲートに容量（ HDD または SSD ）を追加できます。

* * キャッシュを追加 *
+
既存の HDD アグリゲートまたは Flash Pool アグリゲートにキャッシュディスク（ SSD ）を追加できます。

+
このボタンは、オールフラッシュで最適化されたノードを含むクラスタでは使用できません。

* * ミラー *
+
アグリゲートをミラーリングできます。

* * ボリューム移動 *
+
FlexVol ボリュームを移動できます。

* * クラウド階層を接続 *
+
アグリゲートにクラウド階層を接続できます。

* * 更新 *
+
ウィンドウ内の情報を更新します。





=== アグリゲートリスト

各アグリゲートの名前とスペース使用量情報が表示されます。

* * ステータス *
+
アグリゲートのステータスが表示されます。

* * 名前 *
+
アグリゲートの名前が表示されます。

* * ノード *
+
アグリゲートのディスクが割り当てられているノードの名前が表示されます。

+
このフィールドは、クラスタレベルでのみ使用できます。

* * タイプ *
+
アグリゲートのタイプが表示されます。

+
このフィールドは、オールフラッシュで最適化されたノードを含むクラスタに対しては表示されません。

* * 使用（ % ） *
+
アグリゲートで使用されているスペースの割合が表示されます。

* * 利用可能なスペース *
+
アグリゲートの使用可能なスペースが表示されます。

* * 使用済みスペース *
+
アグリゲートでデータに使用されているスペースの量が表示されます。

* * 合計容量 *
+
アグリゲートの合計スペースが表示されます。

* * FabricPool *
+
選択したアグリゲートがクラウド階層に接続されているかどうかが表示されます。

* * クラウド階層 *
+
選択したアグリゲートがクラウド階層に接続されている場合は、クラウド階層の名前が表示されます。

* * ボリューム数 *
+
アグリゲートに関連付けられているボリュームの数が表示されます。

* * ディスク数 *
+
アグリゲートの作成に使用されているディスクの数が表示されます。

* * Flash Pool *
+
Flash Pool アグリゲートの合計キャッシュサイズが表示されます。「 NA 」という値は、アグリゲートが Flash Pool アグリゲートではないことを示します。

+
このフィールドは、オールフラッシュで最適化されたノードを含むクラスタに対しては表示されません。

* * Mirrored * （ミラーリング）
+
アグリゲートがミラーされているかどうかが表示されます

* * SnapLock タイプ *
+
アグリゲートの SnapLock タイプが表示されます。





=== 詳細領域

アグリゲートを選択すると、選択したアグリゲートに関する情報が表示されます。Show More Details をクリックすると、選択したアグリゲートに関する詳細情報を表示できます。

* * 概要タブ *
+
選択したアグリゲートに関する詳細な情報が表示されます。これには、アグリゲートのスペース割り当て、アグリゲートのスペース削減、アグリゲートのパフォーマンス（ IOPS および合計データ転送数）などの情報が含まれます。

* * ディスク情報タブ *
+
ディスクの名前、ディスクタイプ、物理サイズ、使用可能なサイズ、ディスクの位置などのディスクのレイアウト情報が表示されます。 ディスクのステータス、プレックス名、プレックスのステータス、 RAID グループ、 RAID タイプ、 選択したアグリゲートのストレージプール（存在する場合）を指定します。ディスクのプライマリパスに関連付けられたディスクポート、およびマルチパス設定の場合はディスクのセカンダリパスに関連付けられたディスク名も表示されます。

* * Volumes （ボリューム）タブ *
+
アグリゲート上の合計ボリューム数、合計アグリゲートスペース、およびアグリゲートにコミット済みのスペースについての詳細が表示されます。

* * パフォーマンスタブ *
+
スループットや IOPS など、アグリゲートのパフォーマンス指標のグラフが表示されます。スループットや IOPS についての読み取り、書き込み、および合計転送回数のパフォーマンス指標データが、 SSD と HDD で別々に表示されます。

+
クライアントのタイムゾーンやクラスタのタイムゾーンを変更すると、パフォーマンス指標のグラフも変わります。最新のグラフを表示するには、ブラウザの表示を更新してください。



* 関連情報 *

xref:task_provisioning_storage_through_aggregates.adoc[アグリゲートを使用したストレージのプロビジョニング]

xref:task_deleting_aggregates.adoc[アグリゲートを削除中]

xref:task_editing_aggregates.adoc[アグリゲートの編集]
