---
permalink: online-help-96-97/concept_schedules.html 
sidebar: sidebar 
keywords: online, help, system, manager, manage, schedule, storage 
summary: System Manager を使用して、ストレージシステムのスケジュールを作成および管理できます。 
---
= System Manager - ONTAP 9.7以前を使用してスケジュールを管理します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP System Managerクラシック（ONTAP 9.7以前で使用可能）を使用して、ストレージシステムのスケジュールを作成および管理できます。



== スケジュールを作成

System Manager を使用して、特定の時間または定期的にジョブを実行するようにスケジュールを作成できます。

.このタスクについて
MetroCluster 構成でスケジュールを作成するときは、セカンダリサイト内のクラスタにも同等のスケジュールを作成することを推奨します。

.手順
. [* 保護 *>* スケジュール *] をクリックします。
. [ 作成（ Create ） ] をクリックします。
. [ スケジュールの作成 *] ダイアログボックスで、スケジュール名を指定します。
. 要件に応じたスケジュールを作成します。
+
|===
| 作成する項目 | 手順 


 a| 
日単位または特定の日単位の特定のスケジュール
 a| 
[*Basic*] を選択し、スケジュールと繰り返しの詳細を指定します（時間と分）。



 a| 
特定の間隔で実行するスケジュール
 a| 
[*Interval] を選択し、スケジュールと繰り返しの詳細（日数、時間、分）を指定します。



 a| 
特定の期間に実行されるスケジュール
 a| 
[ 詳細設定 *] を選択し、スケジュールと繰り返しの詳細 ( 月、日、曜日、時間、および分 ) を指定します。

|===
. [ 作成（ Create ） ] をクリックします。




== スケジュールを編集します

以前に作成した cron スケジュールや実行間隔が要件に合わない場合は、 System Manager を使用してスケジュールを変更できます。曜日、時間、間隔のオプション、および詳細な cron オプションなど、スケジュールの詳細を変更できます。

.このタスクについて
MetroCluster 構成でスケジュールを編集するときは、セカンダリサイトのクラスタでも同等のスケジュールを編集することを推奨します。

.手順
. [* 保護 *>* スケジュール *] をクリックします。
. 変更するスケジュールを選択し、 * Edit * をクリックします。
. [ スケジュールの編集 *] ダイアログボックスで、適切なアクションを実行してスケジュールを変更します。
+
|===
| 選択するスケジュールオプション | 手順 


 a| 
基本
 a| 
曜日およびスケジュールの詳細を指定します。



 a| 
間隔：
 a| 
間隔のオプションを日数、時間、および分で指定します。



 a| 
詳細設定
 a| 
詳細な cron オプションを、月、日、曜日（該当する場合）、時間、および分で指定します。

|===
. [OK] をクリックします。




== スケジュールを削除します

[role="lead"]
System Manager を使用して、特定のストレージ管理タスクを実行するスケジュールを削除できます。

.手順
. [* 保護 *>* スケジュール *] をクリックします。
. 削除するスケジュールを選択し、 * Delete * をクリックします。
. 確認のチェックボックスをオンにし、 * 削除 * をクリックします。




== スケジュールを管理します

多くのタスク（ボリュームの Snapshot コピーやミラーレプリケーションなど）を、指定したスケジュールで実行されるように設定できます。指定したスケジュールで実行されるスケジュールは、UNIXと類似しているため、_cron_schedulesと呼ばれます。 `cron` スケジュール：一定間隔で実行されるスケジュールは、 _interval_schedules と呼ばれます。

スケジュールは、次の方法で管理できます。

* cron スケジュールまたはインターバルスケジュールを作成する
* すべてのスケジュールに関する情報を表示する
* cron スケジュールまたはインターバルスケジュールを変更する
* cron スケジュールまたはインターバルスケジュールを削除する
+
実行中のジョブで現在使用されているスケジュールを削除することはできません。



クラスタ管理者は、すべてのスケジュール管理タスクを実行できます。



== スケジュールウィンドウ

スケジュールウィンドウを使用して、スケジュールの作成、情報の表示、変更、削除など、スケジュールされたタスクを管理できます。



=== コマンドボタン

* * 作成 * 。
+
スケジュールの作成ダイアログボックスを開きます。このダイアログボックスで、時間ベースおよび間隔スケジュールを作成できます。

* * 編集 * 。
+
スケジュールの編集ダイアログボックスが開き、選択したスケジュールを編集できます。

* * 削除 *
+
スケジュールの削除ダイアログボックスを開きます。このダイアログボックスで、選択したスケジュールを削除できます。

* * 更新 *
+
ウィンドウ内の情報を更新します。





=== スケジュールのリスト

* * 名前 *
+
スケジュールの名前を示します。

* * タイプ *
+
schedule-time-based または interval] ベースのタイプを指定します。





=== 詳細領域

詳細領域には、選択したスケジュールが実行されるタイミングに関する情報が表示されます。
