---
permalink: online-help-96-97/concept_setting_up_network.html 
sidebar: sidebar 
keywords: online, help, set, up, network, ipspace, broadcast, domain, subnet, system, manager, cluster, range 
summary: ネットワークのセットアップでは、 IPspace 、ブロードキャストドメイン、およびサブネットを作成します。 
---
= System Manager - ONTAP 9.7 以前を使用してネットワークをセットアップします
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP System Manager クラシック（ ONTAP 9.7 以前で使用可能）を使用してネットワークをセットアップできます。ネットワークのセットアップでは、 IPspace 、ブロードキャストドメイン、およびサブネットを作成します。



== IPspaces を作成します

System Manager を使用して IPspace を作成すると、管理上分離された複数のネットワークドメインのクライアントアクセス用に 1 つの ONTAP クラスタを設定できます。クライアントが同じ IP アドレス範囲を使用している場合でも同様です。これにより、クライアントトラフィックを分離してプライバシーとセキュリティを確保できます。

.このタスクについて
IPspace の名前はすべてクラスタ内で一意である必要があり、「 local 」や「 localhost 」など、システムによって予約されている名前ではない必要があります。

.手順
. [ * ネットワーク * ] タブをクリックします。
. [*IPspaces *] タブで、 [*Create] をクリックします。
. Create IPspaces * ダイアログボックスで、作成する IPspace の名前を指定します。
. [ 作成（ Create ） ] をクリックします。




== ブロードキャストドメインを作成する

System Manager を使用してブロードキャストドメインを作成すると、コンピュータネットワークを論理的に分割することができます。あるブロードキャストドメインに関連付けられたノードには、すべてデータリンク層のブロードキャストを介してアクセスすることができます

.手順
. [ * ネットワーク * ] タブをクリックします。
. [ ブロードキャストドメイン *] タブで、 [ 作成 *] をクリックします。
. ブロードキャストドメインの作成 * ダイアログボックスで、作成するブロードキャストドメインの名前、 MTU サイズ、 IPspace 、ポートを指定します。
. [ 作成（ Create ） ] をクリックします。




== サブネットを作成する

System Manager を使用してサブネットを作成し、 IP アドレスを事前に割り当てるための IP ネットワークを論理的に分割できます。サブネットでは、 IP アドレスやネットワークマスク値を指定する代わりにサブネット名を指定して、インターフェイスを簡単に作成できます。

.作業を開始する前に
サブネットを使用するブロードキャストドメインを作成しておく必要があります。

.このタスクについて
サブネットを作成するときにゲートウェイを指定した場合は、そのサブネットを使用して LIF を作成するときに、ゲートウェイへのデフォルトルートが SVM に自動的に追加されます。

.手順
. [ * ネットワーク * ] タブをクリックします。
. [* Subnets] タブで、 [* Create] をクリックします。
. [ サブネットの作成 *] ダイアログボックスで、名前、サブネット IP アドレスまたはサブネットマスク、 IP アドレスの範囲、ゲートウェイアドレス、ブロードキャストドメインなどのサブネットの詳細を指定します。
+
IP アドレスは、範囲で指定することも、複数のアドレスをカンマで区切って指定することも、両方を組み合わせて指定することもできます。

. [ 作成（ Create ） ] をクリックします。


* 関連情報 *

xref:reference_network_window.adoc[[ ネットワーク ] ウィンドウ]
