---
permalink: online-help-96-97/concept_efficiency_policies.html 
sidebar: sidebar 
keywords: efficiency, policy, system, manager, create, edit, delete, online, help, flexvol, window 
summary: System Manager を使用して、効率化ポリシーを作成、編集、削除できます。 
---
= System Manager - ONTAP 9.7 以前を使用して効率化ポリシーを管理します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP System Manager クラシック（ ONTAP 9.7 以前で使用可能）を使用して、効率化ポリシーを作成、編集、削除できます。



== 効率化ポリシーを追加します

System Manager を使用して効率化ポリシーを追加し、指定したスケジュールやボリュームデータの変更率が指定したしきい値に達したときに、ボリュームに対する重複排除処理を実行することができます。

.手順
. [ * ストレージ * > * SVMs * ] をクリックします。
. SVM を選択し、 * SVM 設定 * をクリックします。
. [* Policies] ペインで、 [* 効率化ポリシー * ] をクリックします。
. [ * 追加 ] をクリックし、ポリシー名を指定します。
. ストレージ効率化ポリシーの実行方法を指定します。
+
** [ スケジュール ] を選択し、スケジュール名とスケジュールの詳細を指定します。
+
必要に応じて、効率化ポリシーの最大実行時間を指定できます。

** 「 * ChangeLog Threshold * 」を選択し、ボリュームデータの変更についてのしきい値を指定します。


. *オプション：*クライアント処理へのパフォーマンスの影響を軽減するには、* QoSポリシーをバックグラウンドに設定*チェックボックスを選択します。
. [ 追加（ Add ） ] をクリックします。




== 効率化ポリシーを編集します

System Manager を使用して、ポリシー名、スケジュール名、最大実行時間などの効率化ポリシーの属性を変更できます。

.手順
. [ * ストレージ * > * SVMs * ] をクリックします。
. SVM を選択し、 * SVM 設定 * をクリックします。
. [* Policies] ペインで、 [* 効率化ポリシー * ] をクリックします。
. [ * 効率化ポリシー * ] ウィンドウで、編集するポリシーを選択し、 [ * 編集 ] をクリックします。
. 効率化ポリシーの編集 * ダイアログボックスで、必要な変更を行います。
. [ 保存（ Save ） ] をクリックします。




== 効率化ポリシーを削除します

System Manager を使用すると、不要になった効率化ポリシーを削除できます。

.作業を開始する前に
効率化ポリシーは無効にする必要があります。

.手順
. [ * ストレージ * > * SVMs * ] をクリックします。
. SVM を選択し、 * SVM 設定 * をクリックします。
. [* Policies] ペインで、 [* 効率化ポリシー * ] をクリックします。
. 削除する効率化ポリシーを選択し、 * Delete * をクリックします。
. 確認のチェックボックスをオンにし、 * 削除 * をクリックします。




== 効率化ポリシーを有効または無効にします

System Manager を使用して効率化ポリシーを有効または無効にできます。

.手順
. [ * ストレージ * > * SVMs * ] をクリックします。
. SVM を選択し、 * SVM 設定 * をクリックします。
. [* Policies] ペインで、 [* 効率化ポリシー * ] をクリックします。
. 有効または無効にする効率化ポリシーを 1 つ以上選択します。
. 必要に応じて、 * Status * > * Enable * または * Status * > * Disable * をクリックします。
. 効率化ポリシーを無効にする場合は、確認のチェックボックスをオンにし、 * OK * をクリックします。




== 効率化ポリシーとは

効率化ポリシーは、 FlexVol に対する重複排除処理のジョブスケジュールです。

FlexVol ボリュームに対して重複排除を実行するには、特定の時間に処理を開始するようにスケジュールを設定するか、しきい値を超えたときに処理がトリガーされるように指定します。重複排除処理のスケジュールを設定するときは、ジョブスケジュールを作成して効率化ポリシーに含めます。ボリューム効率化ポリシーは、タイプが cron のジョブスケジュールのみをサポートします。または、しきい値の割合を指定することもできます。新規データが指定した割合を超えると、重複排除処理が開始されます。



== 事前定義された効率化ポリシーの概要

効率化ポリシーをボリュームに設定して、より多くのスペースを削減できます。ボリュームでインライン圧縮を実行するように設定でき、スケジュール設定または手動開始によるバックグラウンドの効率化処理を設定する必要はありません。

SVM を作成すると、次の効率化ポリシーが自動的に作成されます。これらのポリシーは削除できません。

* デフォルト
+
スケジュール設定した重複排除処理をボリュームで実行するには、効率化ポリシーをボリュームに設定します。

* インラインのみ
+
スケジュール設定または手動開始によるバックグラウンドの効率化処理を実行せずにボリュームのインライン圧縮を実行するには、インラインのみの効率化ポリシーをボリュームに設定し、インライン圧縮を有効にします。



インラインのみおよびデフォルトの効率化ポリシーの詳細については、マニュアルページを参照してください。



== [ 効率化ポリシー ] ウィンドウ

効率化ポリシーウィンドウを使用して、効率化ポリシーに関する情報を作成、表示、管理できます。



=== コマンドボタン

* * 追加 * 。
+
効率化ポリシーの追加ダイアログボックスを開きます。このダイアログボックスで、指定した期間（スケジュールベース）、またはボリュームデータの変更率が指定したしきい値（しきい値ベース）に達したときに、ボリュームに対して重複排除処理を実行できます。

* * 編集 * 。
+
効率化ポリシーの編集ダイアログボックスを開きます。このダイアログボックスで、重複排除処理のスケジュール、しきい値、 QoS タイプ、および最大実行時間を変更できます。

* * 削除 *
+
効率化ポリシーの削除ダイアログボックスを開きます。このダイアログボックスで、選択した効率化ポリシーを削除できます。

* * ステータス *
+
ドロップダウンメニューを開きます。選択した効率化ポリシーを有効または無効にするオプションがあります。

* * 更新 *
+
ウィンドウ内の情報を更新します。





=== 効率化ポリシーのリスト

* * 自動 *
+
重複排除がバックグラウンドで継続的に実行されるように指定します。このポリシーは、新規に作成するすべてのボリューム、およびアップグレードしたボリュームのうち、バックグラウンド重複排除が手動で設定されていないボリュームに対して設定されます。ポリシーをデフォルトまたはその他のポリシーに変更すると' autoポリシーは無効になります

+
ボリュームがAFF以外のシステムからAFF システムに移動した場合、デスティネーションノードで「auto」ポリシーがデフォルトで有効になります。ボリュームがAFF ノードからAFF以外のノードに移動すると、デフォルトでデスティネーションノードの「auto」ポリシーが「inline-only」ポリシーに置き換えられます。

* * ポリシー *
+
効率化ポリシーの名前を指定します。

* * ステータス *
+
効率化ポリシーのステータスを指定します。ステータスは、次のいずれかになります。

+
** 有効
+
効率化ポリシーを重複排除処理に割り当てることができるように指定します。

** 無効
+
効率化ポリシーが無効であることを示します。ポリシーを有効にするには、 status ドロップダウンメニューを使用してポリシーを有効にし、あとで重複排除処理に割り当てることができます。



* * 実行者 *
+
ストレージ効率化ポリシーをスケジュールとしきい値（変更ログのしきい値）のどちらに基づいて実行するかを指定します。

* * QoS ポリシー *
+
ストレージ効率化ポリシーの QoS タイプを指定します。QoS タイプは、次のいずれかになります。

+
** 背景（ Background ）
+
QoS ポリシーをバックグラウンドで実行するように指定します。このタイプを使用すると、クライアント処理へのパフォーマンスの影響を軽減できます。

** ベストエフォート
+
QoS ポリシーをベストエフォートベースで実行するように指定します。これにより、システムリソースの利用率を最大限に高めることができます。



* * 最大実行時間 *
+
効率化ポリシーの最大実行時間を指定します。この値を指定しない場合は、処理が完了するまで効率化ポリシーが実行されます。





=== 詳細領域

効率化ポリシーのリストの下の領域には、選択した効率化ポリシーに関する追加情報が表示されます。スケジュールベースのポリシーのスケジュール名と詳細、およびしきい値ベースのポリシーのしきい値などが含まれます。
