---
permalink: online-help-96-97/concept_how_to_determine_when_safe_to_remove_multi_disk_carrier.html 
sidebar: sidebar 
keywords: remove, multidisk, carrier, system, manager, storage, disruption, raid 
summary: マルチディスクキャリアを安全に取り外す準備ができる前に取り外すと、 RAID グループがデグレード状態になったり、ストレージが停止してしまうこともあります。System Manager を使用すると、マルチディスクキャリアを安全に取り外せるかどうかを確認することができます。 
---
= System Manager - ONTAP 9.7 以前のバージョンで、マルチディスクキャリアを安全に取り外すタイミングを確認します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
マルチディスクキャリアを安全に取り外す準備ができる前に取り外すと、 RAID グループがデグレード状態になったり、ストレージが停止してしまうこともあります。ONTAP System Manager クラシック（ ONTAP 9.7 以前で使用可能）を使用すると、マルチディスクキャリアを安全に取り外せるかどうかを確認することができます。

マルチディスクキャリアの交換が必要なときは、キャリアを取り外す前に、次のことを確認する必要があります。

* キャリアを取り外す準備ができたことを示す AutoSupport メッセージが記録されている。
* キャリアを取り外す準備ができたことを示す EMS メッセージが記録されている。
* キャリア内の両方のディスクの状態がと表示されている必要があります。 `broken` [ディスク]ウィンドウで、
+
障害が発生したディスクのキャリアメイトを退避してからでないと、ディスクを取り外すことはできません。詳細をクリックすると ' ディスクウィンドウのプロパティタブにディスクの退避ステータスが表示されます

* キャリアの障害 LED （アンバー）が点灯している（取り外す準備ができたことを示す）。
* アクティビティ LED （緑）が消灯している（ディスクアクティビティがないことを示す）。
* シェルフのデジタルディスプレイにシェルフの ID 番号だけが表示されている。


[NOTE]
====
障害が発生したディスクのキャリアメイトを再利用することはできません。障害が発生したディスクを含むマルチキャリアシェルフを取り外した場合は、新しいキャリアに交換する必要があります。

====