---
permalink: online-help-96-97/concept_cluster_expansion.html 
sidebar: sidebar 
keywords: cluster, expanision, system, manager, storage, size, capabilities, add, node, configure, network, online, help 
summary: System Manager を使用して、互換性のあるノードをクラスタに追加し、ノードのネットワークの詳細を設定することで、ストレージのサイズと容量を拡張できます。ノードの概要を確認することもできます。 
---
= System Manager を使用したクラスタの拡張 - ONTAP 9.7 以前
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP System Managerクラシック（ONTAP 9.7以前で使用可能）を使用して、互換性のあるノードをクラスタに追加し、ノードのネットワークの詳細を設定することで、ストレージのサイズと容量を拡張できます。ノードの概要を確認することもできます。

System Manager にログインしたときに、互換性があるノードでクラスタにまだ追加されていない接続済みのノードがあると、 System Manager で自動的に検出され、そのノードを追加するように通知されます。互換性があるノードは、 System Manager で検出されたときに追加することも、あとから手動で追加することもできます。



== クラスタにノードを追加

System Manager を使用して、既存のクラスタにノードを追加し、ストレージシステムのサイズと容量を拡張できます。

.作業を開始する前に
* 互換性がある新しいノードをクラスタに接続しておく必要があります。
+
Default ブロードキャストドメイン内のポートだけが Network ウィンドウに表示されます。

* クラスタのすべてのノードが動作している必要があります。
* すべてのノードのバージョンが同じである必要があります。


.手順
. 互換性がある新しいノードをクラスタに追加します。
+
|===
| 実行する作業 | 手順 


 a| 
System Manager にログインしていません
 a| 
.. System Manager にログインします。
+
[NOTE]
====
System Manager にログインすると、互換性がある新しいノードが自動的に検出されます。互換性がある新しいノードをクラスタに追加するように System Manager から通知されます。

====
.. [ クラスタへのノードの追加 ] をクリックします。
.. ノードの名前を変更します。
.. ノードライセンスを指定します。
.. Submit and Proceed* をクリックします。




 a| 
System Manager にログインしています
 a| 
.. [ * Configuration * > * Cluster * > * Expansion * ] をクリックします。
+
System Manager によって、新しく追加したノードが検索されます。警告が表示された場合は、処理を続行する前に修正する必要があります。互換性がある新しいノードが検出された場合は、次の手順に進みます。

.. ノードの名前を変更します。
.. ノードライセンスを指定します。
.. Submit and Proceed* をクリックします。


|===




== ノードのネットワークの詳細を設定

System Manager を使用して、新しく追加したノードのノード管理 LIF およびサービスプロセッサを設定できます。

.作業を開始する前に
* デフォルトの IPspace に、 LIF の作成に使用する十分な数のポートが必要です。
* すべてのポートが動作している必要があります。


.手順
. ノード管理を設定します。
+
.. [IP アドレス *] フィールドに IP アドレスを入力します。
.. ノード管理用のポートを * Port * フィールドで選択します。
.. ネットマスクとゲートウェイの詳細を入力します。


. サービスプロセッサを設定します。
+
.. デフォルト値を上書きするには、 * デフォルト値を上書き * （ Override defaults * ）チェックボックスを選択します。
.. IP アドレス、ネットマスク、およびゲートウェイの詳細を入力します。


. Submit and Proceed * をクリックして、ノードのネットワーク設定を完了します。
. ノードの詳細を * Summary * ページで確認します。




=== 次に何をするか

* クラスタが保護されている場合は、ピア関係や保護状態に問題が生じないように、新しく追加したノードに必要な数のクラスタ間 LIF を作成します。
* クラスタで SAN データプロトコルが有効になっている場合は、データ処理用の SAN データ LIF を必要な数だけ作成します。


* 関連情報 *

xref:task_creating_network_interfaces.adoc[ネットワークインターフェイスを作成しています]
