---
permalink: online-help-96-97/concept_using_space_reservation_for_luns.html 
sidebar: sidebar 
keywords: understand, space, reservation, lun, volume, guarantee, online, help 
summary: スペースリザベーション設定（ボリュームギャランティとの組み合わせ）と LUN のスペース予約の関係を知っておくと、スペースリザベーションを無効にした場合の影響や、 LUN 設定とボリューム設定の特定の組み合わせが有用でない理由を理解することができます。 
---
= System Manager - ONTAP 9.7 以前での LUN のスペースリザベーションについて理解している必要があります
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP System Manager クラシック（ ONTAP 9.7 以前で使用可能）のスペースリザベーション設定（ボリュームギャランティとの組み合わせ）と LUN のスペース予約の関係を知っておくと、スペースリザベーションを無効にした場合の影響を理解することができます。また、 LUN とボリューム設定の特定の組み合わせが有用でない理由について理解することもできます。

スペースリザベーションを有効にして LUN （スペースリザーブ LUN ）を格納するボリュームギャランティを設定している場合、作成時にボリュームの空きスペースが LUN 用に確保されます。このリザーブスペースのサイズは LUN のサイズで決まります。ボリュームの他のストレージオブジェクト（他の LUN 、ファイル、 Snapshot コピーなど）はこのスペースを使用できません。

スペースリザベーションを無効にして LUN （スペースリザーブなしの LUN ）を作成すると、その LUN 用のスペースは確保されません。LUN への書き込み処理に必要なストレージは、十分な空きスペースがある場合にかぎり、必要なときにボリュームから割り当てられます。

ギャランティが none のボリュームにスペースリザーブ LUN を作成する場合の処理は、スペースリザーブなしの LUN と同じです。ギャランティが none のボリュームは、ボリューム自体、書き込み時に初めてスペースが割り当てられるため、 LUN に割り当てられるスペースはありません。このため、ギャランティが none のボリュームにスペースリザーブ LUN を作成することは推奨されません。この組み合わせは、書き込みが保証されているような誤解を与えますが、実際には保証されていません。

スペースリザベーションが「デフォルト」に設定されている場合、 ONTAP のスペースリザベーション設定が LUN に適用されます。新しいボリュームを作成する場合、コンテナボリュームにも ONTAP のスペースリザベーション設定が適用されます。
