---
permalink: online-help-96-97/concept_broadcast_domains.html 
sidebar: sidebar 
keywords: system, manager, create, manage, broadcast, domain, online, help, edit, settings, port, delete 
summary: System Manager を使用して、ブロードキャストドメインを作成および管理できます。 
---
= System Manager - ONTAP 9.7 以前を使用してブロードキャストドメインを管理します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP System Manager クラシック（ ONTAP 9.7 以前で使用可能）を使用して、ブロードキャストドメインを作成および管理できます。



== ブロードキャストドメインの設定を編集します

System Manager を使用して、名前、 MTU サイズ、ブロードキャストドメインに関連付けられているポートなどのブロードキャストドメインの属性を変更できます。

.このタスクについて
* 管理ポート e0M が割り当てられているブロードキャストドメインの MTU サイズは変更しないでください。
* System Manager を使用して、クラスタ IPspace 内のブロードキャストドメインを編集することはできません。
+
代わりにコマンドラインインターフェイス（ CLI ）を使用してください。



.手順
. [ ネットワーク *>] 、 [ ブロードキャストドメイン *] の順にクリックします。
. 変更するブロードキャストドメインを選択し、 * 編集 * をクリックします。
. ブロードキャストドメインの編集 * ダイアログボックスで、ブロードキャストドメインの属性を必要に応じて変更します。
. [ 保存して閉じる ] をクリックします。




== ブロードキャストドメインを削除する

不要になったブロードキャストドメインは、 System Manager を使用して削除できます。

.作業を開始する前に
削除するブロードキャストドメインに関連付けられているサブネットがないようにします。

.このタスクについて
* ブロードキャストドメインを削除すると、ブロードキャストドメインに関連付けられているポートにはデフォルト IPspace が割り当てられ、ポートの MTU 設定は変更されません。
* System Manager を使用して、クラスタ IPspace 内のブロードキャストドメインを削除することはできません。
+
代わりにコマンドラインインターフェイス（ CLI ）を使用してください。



.手順
. [ ネットワーク *>] 、 [ ブロードキャストドメイン *] の順にクリックします。
. 削除するブロードキャストドメインを選択し、「 * 削除 * 」をクリックします。
. 確認のチェックボックスをオンにし、 * 削除 * をクリックします。


* 関連情報 *

xref:reference_network_window.adoc[[ ネットワーク ] ウィンドウ]

https://docs.netapp.com/us-en/ontap/networking/index.html["Network Management の略"]
