---
permalink: online-help-96-97/concept_export_policies.html 
sidebar: sidebar 
keywords: system, manager, create, edit, manage, export, policy, online, help, volume, rules, svm, qtree, rename 
summary: System Manager を使用して、エクスポートポリシーを作成、編集、管理できます。 
---
= System Manager - ONTAP 9.7 以前を使用してエクスポートポリシーを管理します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP System Managerクラシック（ONTAP 9.7以前で使用可能）を使用して、エクスポートポリシーを作成、編集、管理できます。



== エクスポートポリシーを作成する

System Manager を使用して、クライアントが特定のボリュームにアクセスできるように、エクスポートポリシーを作成できます。

.手順
. [ * ストレージ * > * SVMs * ] をクリックします。
. SVM を選択し、 * SVM 設定 * をクリックします。
. [* Policies * （ポリシー * ） ] ペインで、 [* Export Policies （エクスポートポリシー * ） ] をクリックします。
. [ 作成（ Create ） ] をクリックします。
. Create Export Policy * ダイアログボックスで、エクスポートポリシーの名前を指定します。
. 既存のエクスポートポリシーのルールをコピーしてエクスポートポリシーを作成する場合は、 * Copy Rules From * チェックボックスを選択し、 Storage Virtual Machine （ SVM ）とエクスポートポリシーを選択します。
+
エクスポートポリシーを作成する場合には、ディザスタリカバリのデスティネーション SVM は選択しないでください。

. ** エクスポートルール ** 領域で、 *Add* をクリックしてエクスポートポリシーにルールを追加します。
. [ 作成（ Create ） ] をクリックします。
. 作成したエクスポートポリシーが ［ * エクスポートポリシー * ］ ウィンドウに表示されていることを確認します。




== エクスポートポリシーの名前を変更します

システム管理を使用すると、既存のエクスポートポリシーの名前を変更できます。

.手順
. [ * ストレージ * > * SVMs * ] をクリックします。
. SVM を選択し、 * SVM 設定 * をクリックします。
. [* Policies * （ポリシー * ） ] ペインで、 [* Export Policies （エクスポートポリシー * ） ] をクリックします。
. 名前を変更するエクスポートポリシーを選択し、 * ポリシー名の変更 * をクリックします。
. [ ポリシー名の変更 *] ダイアログボックスで、新しいポリシー名を指定し、 [*Modify*] をクリックします。
. [* エクスポートポリシー * （ * Export Policies * ） ] ウィンドウで行った変更を確認します。




== エクスポートポリシーを削除する

System Manager を使用して、不要になったエクスポートポリシーを削除できます。

.手順
. [ * ストレージ * > * SVMs * ] をクリックします。
. SVM を選択し、 * SVM 設定 * をクリックします。
. [* Policies * （ポリシー * ） ] ペインで、 [* Export Policies （エクスポートポリシー * ） ] をクリックします。
. 削除するエクスポートポリシーを選択し、 * ポリシーの削除 * をクリックします。
. 確認のチェックボックスをオンにし、 * 削除 * をクリックします。




== エクスポートポリシーにルールを追加します

System Manager を使用してエクスポートポリシーにルールを追加して、データへのクライアントアクセスを定義できます。

.作業を開始する前に
エクスポートルールを追加するエクスポートポリシーを作成しておく必要があります。

.手順
. [ * ストレージ * > * SVMs * ] をクリックします。
. SVM を選択し、 * SVM 設定 * をクリックします。
. [* Policies * （ポリシー * ） ] ペインで、 [* Export Policies （エクスポートポリシー * ） ] をクリックします。
. ルールを追加するエクスポートポリシーを選択し、 * エクスポートルール * タブで * 追加 * をクリックします。
. [ エクスポートルールの作成 * （ Create Export Rule * ） ] ダイアログボックスで、次の手順を実行します。
+
.. データへのアクセスを必要とするクライアントを指定します。
+
複数のクライアントをカンマで区切って指定できます。

+
クライアントは次のいずれかの形式で指定できます。

+
*** ホスト名として、例： host1
*** IPv4 アドレス。たとえば、 10.1.12.24 のように指定します
*** たとえば、 10.1.16.0/255.255.255.0 のように、ネットワークマスクを持つ IPv4 アドレスとして指定します
*** IPv6 アドレスとして。たとえば、 FE80::0202:B3FF:FE1E:8329 のように指定します
*** たとえば、 2001:db8::/32 のように、 IPv6 アドレスをネットワークマスクで指定します
*** ネットグループ。ネットグループ名の前にアットマーク（ @ ）が付いているネットグループ。例： @netgroup
*** 先頭にピリオド（ . ）が付いたドメイン名として使用できます。たとえば、 .example.com などです


+
[NOTE]
====
10.1.12.10-10.1.12.70 のように、 IP アドレスの範囲を入力することはできません。この形式のエントリはテキスト文字列と解釈され、ホスト名として扱われます。

====
+
IPv4アドレスを入力できます。 `0.0.0.0/0` すべてのホストへのアクセスを提供します。

.. ルールインデックス番号を変更する場合は、適切なルールインデックス番号を選択します。
.. 1 つ以上のアクセスプロトコルを選択します。
+
アクセスプロトコルを選択しなかった場合、デフォルト値の「 any 」がエクスポートルールに割り当てられます。

.. 1 つ以上のセキュリティタイプとアクセスルールを選択します。


. [OK] をクリックします。
. 選択したエクスポートポリシーの * エクスポートルール * タブで、追加したエクスポートルールが表示されていることを確認します。




== エクスポートポリシールールの変更

System Manager を使用して、指定したクライアントのアクセスプロトコル、およびエクスポートポリシールールのアクセス権限を変更できます。

.手順
. [ * ストレージ * > * SVMs * ] をクリックします。
. SVM を選択し、 * SVM 設定 * をクリックします。
. [* Policies * （ポリシー * ） ] ペインで、 [* Export Policies （エクスポートポリシー * ） ] をクリックします。
. [ * エクスポートポリシー * ] ウィンドウで、エクスポートルールを編集するエクスポートポリシーを選択し、 [ * エクスポートルール * ] タブで編集するルールを選択して、 [ * 編集 ] をクリックします。
. 必要に応じて次のパラメータを変更します。
+
** クライアント仕様
** アクセスプロトコル
** 詳細を確認


. [OK] をクリックします。
. エクスポートルールの更新された変更が * エクスポートルール * タブに表示されていることを確認します。




== エクスポートポリシールールを削除する

System Manager を使用して、不要になったエクスポートポリシールールを削除できます。

.手順
. [ * ストレージ * > * SVMs * ] をクリックします。
. SVM を選択し、 * SVM 設定 * をクリックします。
. [* Policies * （ポリシー * ） ] ペインで、 [* Export Policies （エクスポートポリシー * ） ] をクリックします。
. エクスポートルールを削除するエクスポートポリシーを選択します。
. [* エクスポートルール * （ * Export Rules * ） ] タブで、削除するエクスポートルールを選択し、 [ * 削除 * （ * Delete * ） ] をクリックします。
. 確認ボックスで、 * 削除 * をクリックします。




== エクスポートポリシーがボリュームまたは qtree へのクライアントアクセスを制御する仕組み

エクスポートポリシーには、各クライアントアクセス要求を処理する 1 つ以上の _ エクスポートルール _ が含まれています。このプロセスの結果、クライアントアクセスを許可するかどうか、およびアクセスのレベルが決まります。クライアントがデータにアクセスするためには、エクスポートルールを含むエクスポートポリシーが Storage Virtual Machine （ SVM ）上に存在する必要があります。

ボリュームまたは qtree へのクライアントアクセスを設定するには、各ボリュームまたは qtree にポリシーを 1 つ関連付けます。SVM には複数のエクスポートポリシーを含めることができます。これにより、複数のボリュームまたは qtree を含む SVM に対して次の操作を実行できます。

* SVM のボリュームまたは qtree ごとに異なるエクスポートポリシーを割り当て、 SVM の各ボリュームまたは qtree へのクライアントアクセスを個別に制御する。
* SVM の複数のボリュームまたは qtree に同じエクスポートポリシーを割り当て、同一のクライアントアクセス制御を実行する。ボリュームまたは qtree ごとに新しいエクスポートポリシーを作成する必要はありません。


クライアントが適用可能なエクスポートポリシーで許可されていないアクセス要求を行うと、権限拒否のメッセージが表示され、その要求は失敗します。クライアントがエクスポートポリシーのどのルールにも一致しない場合、アクセスは拒否されます。エクスポートポリシーが空の場合は、すべてのアクセスが暗黙的に拒否されます。

エクスポートポリシーは、 ONTAP を実行しているシステム上で動的に変更できます。



== [ エクスポートポリシー ] ウィンドウ

Export Policies ウィンドウを使用して、エクスポートポリシーおよび関連するエクスポートルールに関する情報を作成、表示、および管理できます。



=== エクスポートポリシー

Export Policies ウィンドウを使用して、 Storage Virtual Machine （ SVM ）に対して作成されたエクスポートポリシーを表示および管理できます。

* * コマンドボタン *
+
** 作成
+
Create Export Policy ダイアログボックスを開きます。このダイアログボックスで、エクスポートポリシーを作成し、エクスポートルールを追加できます。また、既存の SVM からエクスポートルールをコピーすることもできます。

** 名前を変更する
+
ポリシーの名前変更ダイアログボックスが開き、選択したエクスポートポリシーの名前を変更できます。

** 削除
+
Delete Export Policy ダイアログボックスを開きます。このダイアログボックスで、選択したエクスポートポリシーを削除できます。

** 更新
+
ウィンドウ内の情報を更新します。







=== [ エクスポートルール ] タブ

Export Rules タブでは、特定のエクスポートポリシーに対して作成されたエクスポートルールに関する情報を表示できます。ルールを追加、編集、削除することもできます。

* * コマンドボタン *
+
** 追加（ Add ）
+
Create Export Rule ダイアログボックスを開きます。このダイアログボックスで、選択したエクスポートポリシーにエクスポートルールを追加できます。

** 編集
+
Modify Export Rule ダイアログボックスが開き、選択したエクスポートルールの属性を変更できます。

** 削除
+
Delete Export Rule ダイアログボックスを開きます。このダイアログボックスで、選択したエクスポートルールを削除できます。

** 上に移動します
+
選択したエクスポートルールのルールインデックスを上に移動します。

** 下に移動します
+
選択したエクスポートルールのルールインデックスを下に移動します。

** 更新
+
ウィンドウ内の情報を更新します。



* * エクスポートルールリスト *
+
** ルールインデックス
+
エクスポートルールを処理する優先度を指定します。[ 上へ移動 ] ボタンと [ 下へ移動 ] ボタンを使用して、優先度を選択できます。

** クライアント
+
ルールを適用するクライアントを指定します。

** アクセスプロトコル
+
エクスポートルールに対して指定されているアクセスプロトコルが表示されます。

+
アクセスプロトコルを指定しなかった場合、デフォルト値の「 any 」が考慮されます。

** 読み取り専用ルール
+
読み取り専用アクセスのセキュリティタイプを 1 つ以上指定します。

** 読み取り / 書き込みルール
+
読み取り / 書き込みアクセスのセキュリティタイプを 1 つ以上指定します。

** スーパーユーザアクセス
+
スーパーユーザアクセスのセキュリティタイプを 1 つ以上指定します。







=== [ 割り当て済みオブジェクト ] タブ

割り当て済みオブジェクトタブでは、選択したエクスポートポリシーに割り当てられているボリュームと qtree を表示できます。ボリュームが暗号化されているかどうかも確認できます。

* 関連情報 *

xref:task_setting_up_cifs.adoc[CIFSノセツトアツフ]
