---
permalink: online-help-96-97/concept_how_volume_guarantees_work_for_flexvol_volumes.html 
sidebar: sidebar 
keywords: volume, guarantee, work, flexvol, volume, space, preallocated, aggregate, online, help 
summary: ボリュームギャランティ（スペースギャランティとも呼ばれます）の設定により、ボリュームのスペースを包含アグリゲートから割り当てる方法が決まります。ボリュームに対してスペースを事前に割り当てるか、または事前割り当てを行わないオプションがあります。 
---
= System Manager - ONTAP 9.7 以前のバージョンでの FlexVol のボリュームギャランティについて
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
System Manager クラシック（ ONTAP 9.7 以前で使用可能）を使用して、 FlexVol ボリュームのボリュームギャランティを設定できます。ボリュームギャランティ（ _ スペースギャランティ _ とも呼ばれます）の設定により、ボリュームのスペースを包含アグリゲートから割り当てる方法が決まります。ボリュームに対してスペースを事前に割り当てるか、または事前割り当てを行わないオプションがあります。

ギャランティ設定はボリュームの属性です。

ギャランティは、新しいボリュームを作成するときに設定します。また、新しいギャランティ用の十分な空きスペースがある場合、既存のボリュームのギャランティを変更することもできます。

ボリュームギャランティのタイプは次のとおりです。 `volume` （デフォルトのタイプ）または `none`。

* 保証タイプ： `volume` アグリゲート内のスペースをボリュームの作成時にボリューム全体に割り当てます。そのスペースがまだデータに使用されているかどうかは関係ありません。
+
割り当てられたスペースは、アグリゲート内の他のボリュームには割り当てることはできません。

* 保証 `none` ボリュームで必要になったときにのみ、アグリゲートからスペースを割り当てます。
+
このギャランティタイプのボリュームで使用されるスペースの量は、ボリュームの初期サイズで決まるのではなく、データが追加されるに従って増えていきます。ボリュームのデータが初期サイズに達しないかぎり、スペースは未使用のままになります。ギャランティがに設定されたボリュームの最大サイズ `none` は、アグリゲート内の空きスペースの量に制限されません。アグリゲートに関連付けられたすべてのボリュームの合計サイズがアグリゲートの空きスペースの量を超えることがありますが、実際に使用できるスペースの量はアグリゲートのサイズによって制限されます。

+
書き込みに対応できる十分なスペースが包含アグリゲートにない場合、そのボリュームに格納された LUN またはファイル（スペースがリザーブされた LUN およびファイルを含む）への書き込みが失敗することがあります。



アグリゲートのスペースが `volume` 既存のボリュームに対して、ボリュームがまだスペースを使用していない場合でも、そのスペースはアグリゲート内で空きスペースとみなされなくなります。アグリゲート Snapshot コピーの作成や包含アグリゲートでの新しいボリュームの作成など、アグリゲートの空きスペースを消費する操作は、そのアグリゲートに十分な空きスペースがある場合にのみ行うことができます。これらの操作では、すでに別のボリュームに割り当てられているスペースを使用できません。

アグリゲートの空きスペースを使い果たした場合、成功が保証されるのは、そのアグリゲート内のスペースが事前に割り当てられているボリュームまたはファイルへの書き込みだけです。

ギャランティはオンラインボリュームについてのみ適用されます。ボリュームをオフラインにした場合、そのボリュームに対して割り当てられた未使用のスペースは、そのアグリゲート内の他のボリュームで使用可能になります。ボリュームを再びオンラインにするときに、そのギャランティに対応できるだけの十分なスペースがアグリゲートにないと、ボリュームはオフラインのままになります。ボリュームを強制的にオンラインにする必要があります。その時点でボリュームのギャランティは無効になります。

* 関連情報 *

http://www.netapp.com/us/media/tr-3965.pdf["ネットアップテクニカルレポート 3965 ：『 NetApp Thin Provisioning Deployment and Implementation Data ONTAP 8.1 （ 7-Mode ） 』"^]
