---
permalink: online-help-96-97/concept_network_interfaces.html 
sidebar: sidebar 
keywords: system, manager, network, interface, create, manage, online, help, create, lif, intercluster, svm, migrate, data 
summary: System Manager を使用して、ネットワークインターフェイスを作成および管理できます。 
---
= System Manager - ONTAP 9.7 以前を使用してネットワークインターフェイスを管理します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP System Manager クラシック（ ONTAP 9.7 以前で使用可能）を使用して、ネットワークインターフェイスを作成および管理できます。



== ネットワークインターフェイスを作成

System Manager を使用して、 Storage Virtual Machine （ SVM ）からのデータアクセス、 SVM の管理、クラスタ間接続を行うためのネットワークインターフェイスまたは LIF を作成できます。

.作業を開始する前に
サブネットに関連付けたブロードキャストドメインにポートを割り当てておきます。

.このタスクについて
* LIF の作成時には、 Dynamic DNS （ DDNS ；動的 DNS ）がデフォルトで有効になります。
+
ただし、 iSCSI 、 NVMe 、 FC / FCoE のいずれかのプロトコルを使用するクラスタ間通信用の LIF 、または管理アクセス専用の LIF を設定する場合は、 DDNS が無効になります。

* IP アドレスは、サブネットを使用しても使用しなくても指定できます。
* ポートがデグレード状態の場合、 System Manager でネットワークインターフェイスを作成することはできません。
+
このような場合は、コマンドラインインターフェイス（ CLI ）を使用してネットワークインターフェイスを作成してください。

* NVMeoF データ LIF を作成するには、 SVM がセットアップ済みで、 SVM に NVMe サービスがあり、 NVMeoF 対応アダプタが使用可能である必要があります。
* NVMe プロトコルは、選択した SVM に NVMe サービスが設定されている場合にのみ有効になります。


.手順
. [ * ネットワーク * ] > [* ネットワーク・インターフェイス * ] をクリックします。
. [ 作成（ Create ） ] をクリックします。
. Create Network Interface * ダイアログボックスで、インターフェイス名を指定します。
. インターフェイスロールを指定します。
+
|===
| 状況 | 作業 


 a| 
ネットワークインターフェイスをデータ LIF に関連付けます
 a| 
.. [*Serves Data*] を選択します。
.. ネットワークインターフェイスの SVM を選択してください。




 a| 
ネットワークインターフェイスをクラスタ間 LIF に関連付けます
 a| 
.. 「 * クラスタ間接続 * 」を選択します。
.. ネットワークインターフェイスの IPspace を選択します。


|===
. 適切なプロトコルを選択します。
+
インターフェイスは、このプロトコルを使用して、 SVM からデータにアクセスします。

+
[NOTE]
====
NVMe プロトコルを選択すると、残りのプロトコルは無効になります。NAS （ CIFS および NFS ）プロトコルがサポートされている場合、それらのプロトコルは引き続き使用できます。NVMe プロトコルを選択すると NVMe 転送フィールドが表示され、 FC-NVMe プロトコルが転送プロトコルとして表示されます。

====
. データ LIF で管理アクセスを有効にする場合は、 * 管理アクセスの有効化 * チェックボックスを選択します。
+
クラスタ間 LIF 、または FC / FCoE プロトコルや NVMe プロトコルを使用する LIF では、管理アクセスを有効にすることはできません。

. IP アドレスを割り当てます。
+
|===
| 状況 | 作業 


 a| 
サブネットを使用して IP アドレスを指定します
 a| 
.. サブネットを使用する * を選択します。
.. Add Details ダイアログボックスで、 IP アドレスを割り当てるサブネットを選択します。
+
クラスタ間 LIF の場合、選択した IPspace に関連付けられているサブネットだけが表示されます。

.. インターフェイスに特定の IP アドレスを割り当てる場合は、 * 特定の IP アドレスを使用する * を選択して、 IP アドレスを入力します。
+
指定した IP アドレスがサブネット内にない場合、追加されます。

.. [OK] をクリックします。




 a| 
サブネットを使用せずに手動で IP アドレスを指定します
 a| 
.. サブネットなし * を選択します。
.. [ 詳細の追加 ] ダイアログボックスで、次の手順を実行します。
+
... IP アドレスとネットワークマスクまたはプレフィックスを指定します。
... オプション：ゲートウェイを指定します。
... Destination フィールドにデフォルト値を使用しない場合は、新しい宛先値を指定します。
+
送信先の値を指定しない場合は、 IP アドレスのファミリーに基づいて、 Destination フィールドにデフォルト値が設定されます。



+
ルートが存在しない場合は、ゲートウェイとデスティネーションに基づいて新しいルートが自動的に作成されます。

.. [OK] をクリックします。


|===
. ポート * の詳細領域から必要なポートを選択します。
+
** データ LIF の場合、ポートの詳細領域には、 SVM の IPspace に関連付けられたブロードキャストドメインにあるすべてのポートが表示されます。
** クラスタ間 LIF の場合、ポートの詳細領域には、要求された IPspace に関連付けられたブロードキャストドメインにあるすべてのポートが表示されます。
** NVMe プロトコルが選択されている場合、ポートの詳細領域には NVMe 対応アダプタのみが表示されます。


. *オプション：* Dynamic DNS（DDNS）*チェックボックスを選択して、DDNSを有効にします。
. [ 作成（ Create ） ] をクリックします。




== ネットワークインターフェイスの設定を編集します

System Manager を使用してネットワークインターフェイスを変更することで、データ LIF の管理アクセスを有効にすることができます。

.このタスクについて
* System Manager を使用して、クラスタ LIF 、クラスタ管理 LIF 、またはノード管理 LIF を変更することはできません。
* クラスタ間 LIF の管理アクセスは有効にできません。


.手順
. [ * ネットワーク * ] > [* ネットワーク・インターフェイス * ] をクリックします。
. 変更するインターフェイスを選択し、 * Edit * をクリックします。
. Edit Network Interface * ダイアログボックスで、必要に応じてネットワーク・インターフェイスの設定を変更します。
. [ 保存して閉じる ] をクリックします。




== ネットワークインターフェイスを削除

System Manager を使用してネットワークインターフェイスを削除し、そのインターフェイスの IP アドレスを解放して、別の用途に使用できます。

.作業を開始する前に
ネットワークインターフェイスのステータスを無効にする必要があります。

.手順
. [ * ネットワーク * ] > [* ネットワーク・インターフェイス * ] をクリックします。
. 削除するインターフェイスを選択し、 * Delete * をクリックします。
. 確認のチェックボックスをオンにし、 * 削除 * をクリックします。




== LIF を移行

ソースポートで障害が発生した場合やメンテナンスが必要な場合は、 System Manager を使用して、データ LIF またはクラスタ管理 LIF を同じノードの別のポートやクラスタ内の別のノードに移行できます。

.作業を開始する前に
デスティネーションのノードおよびポートが動作していて、ソースポートと同じネットワークにアクセスできる必要があります。

.このタスクについて
* ノードから NIC を削除する場合は、 NIC に属しているポートでホストされている LIF をクラスタ内の他のポートに移行する必要があります。
* iSCSI または FC の LIF は移行できません。


.手順
. [ * ネットワーク * ] > [* ネットワーク・インターフェイス * ] をクリックします。
. 移行するインターフェイスを選択し、 * Migrate * をクリックします。
. * Migrate Interface * ダイアログボックスで、 LIF を移行するデスティネーションポートを選択します。
. *オプション：デスティネーションポートをLIFの新しいホームポートに設定する場合は、* Migrate permanently-*チェックボックスを選択します。
. [* Migrate （移行） ] をクリックします


* 関連情報 *

xref:reference_network_window.adoc[[ ネットワーク ] ウィンドウ]

xref:task_configuring_iscsi_protocol_on_svms.adoc[SVM で iSCSI プロトコルを設定します]

https://docs.netapp.com/us-en/ontap/concepts/index.html["ONTAP の概念"]

https://docs.netapp.com/us-en/ontap/networking/index.html["Network Management の略"]
