---
permalink: online-help-96-97/concept_qtrees.html 
sidebar: sidebar 
keywords: system, manager, create, edit, delete, qtree, partition, data, policies, svm 
summary: System Manager を使用して、 qtree を作成、編集、削除できます。 
---
= System Manager - ONTAP 9.7 以前を使用して qtree を管理します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP System Manager クラシック（ ONTAP 9.7 以前で使用可能）を使用して、 qtree を作成、編集、および削除できます。



== qtree を作成する

qtree を使用すると、ボリューム内のデータを管理およびパーティショニングできます。System Manager の qtree の作成ダイアログボックスを使用して、ストレージシステム上のボリュームに新しい qtree を追加できます。

.手順
. Storage * > * Qtrees * をクリックします。
. SVM * フィールドのドロップダウンメニューから、 qtree を作成する Storage Virtual Machine （ SVM ）を選択します。
. [ 作成（ Create ） ] をクリックします。
. Create Qtree * ダイアログボックスの * Details * タブに、 qtree の名前を入力します。
. qtree を追加するボリュームを選択します。
+
ボリューム参照リストには、オンラインになっているボリュームのみが表示されます。

. qtree の便宜的ロック（ oplock ）を無効にするには、この qtree * のファイルとディレクトリで oplock を有効にするチェックボックスをオフにします。
+
デフォルトでは、 oplock は各 qtree で有効になっています。

. デフォルトで継承されるセキュリティ形式を変更する場合は、新しいセキュリティ形式を選択します。
+
qtree のデフォルトのセキュリティ形式は、 qtree が含まれるボリュームのセキュリティ形式です。

. デフォルトで継承されるエクスポートポリシーを変更する場合は、既存のエクスポートポリシーを選択するか、エクスポートポリシーを作成します。
+
qtree のデフォルトのエクスポートポリシーは、 qtree が含まれるボリュームに割り当てられているエクスポートポリシーです。

. ディスクスペースの使用を制限する場合は、 [Quotas] タブをクリックします。
+
.. qtree にクォータを適用する場合は、 * qtree quota * をクリックし、ディスクスペース制限を指定します。
.. qtree 上のすべてのユーザにクォータを適用する場合は、 * User quota * をクリックし、ディスクスペースリミットを指定します。


. [ 作成（ Create ） ] をクリックします。
. Qtrees * ウィンドウで、作成した qtree が qtree のリストに含まれていることを確認します。




== qtree を削除します

System Manager で qtree を削除し、ボリューム内で qtree が使用しているディスクスペースを再利用することができます。qtree を削除すると、その qtree に適用されているすべてのクォータが ONTAP によって適用されなくなります。

.作業を開始する前に
* qtree のステータスは正常である必要があります。
* LUN を含む qtree に対しては実行できません。


.手順
. Storage * > * Qtrees * をクリックします。
. Qtrees * ウィンドウで、削除する qtree を 1 つ以上選択し、 * Delete * をクリックします。
. 確認のチェックボックスをオンにし、 * 削除 * をクリックします。
. Qtrees * ウィンドウで、削除した qtree が qtree のリストに含まれていないことを確認します。




== qtree を編集します

System Manager を使用して、セキュリティ形式、便宜的ロック（ oplock ）の有効化と無効化、新規または既存のエクスポートポリシーの割り当てなど、 qtree のプロパティを変更できます。

.手順
. Storage * > * Qtrees * をクリックします。
. 編集する qtree を選択し、 * Edit * をクリックします。
. Edit Qtree * ダイアログボックスで、必要に応じて次のプロパティを編集します。
+
** oplock
** セキュリティ形式
** エクスポートポリシー


. [ 保存（ Save ） ] をクリックします。
. Qtrees * ウィンドウで、選択した qtree に加えた変更を確認します。




== qtree へのエクスポートポリシーの割り当て

ボリューム全体をエクスポートする代わりに、ボリュームの特定の qtree をエクスポートしてクライアントから直接アクセスできるようにすることができます。System Manager を使用すると、 qtree にエクスポートポリシーを割り当てて qtree をエクスポートできます。Qtrees window では、 1 つ以上の qtree にエクスポートポリシーを割り当てることができます。

.手順
. Storage * > * Qtrees * をクリックします。
. SVM フィールドのドロップダウンメニューから、エクスポートする qtree を配置する Storage Virtual Machine （ SVM ）を選択します。
. エクスポートポリシーを割り当てる qtree を 1 つ以上選択し、 * エクスポートポリシーの変更 * をクリックします。
. エクスポートポリシー * ダイアログボックスで、エクスポートポリシーを作成するか、既存のエクスポートポリシーを選択します。
+
link:task_creating_export_policy.html["エクスポートポリシーを作成しています"]

. [ 保存（ Save ） ] をクリックします。
. qtree に割り当てたエクスポートポリシーとそれに関連するエクスポートルールが、該当する qtree の「 * Details * 」タブに表示されていることを確認します。




== qtree 情報を表示します

System Manager の qtree ウィンドウを使用して、 qtree を含むボリューム、 qtree 名、セキュリティ形式、および qtree のステータス、および oplock のステータスを表示できます。

.手順
. Storage * > * Qtrees * をクリックします。
. SVM * フィールドのドロップダウンメニューから、情報を表示する qtree が含まれている Storage Virtual Machine （ SVM ）を選択します。
. 表示された qtree のリストから qtree を選択します。
. Qtrees * ウィンドウで qtree の詳細を確認します。




== qtree のオプション

qtree とは、論理的に定義されたファイルシステムで、 FlexVol ボリューム内のルートディレクトリに特別なサブディレクトリとして作成できます。qtree は、ボリューム内のデータの管理やパーティショニングに使用できます。

ボリュームを含む FlexVol に qtree を作成した場合、 qtree はディレクトリとして表示されます。そのため、ボリュームを削除する際に誤って qtree を削除しないように注意する必要があります。

qtree の作成時に指定できるオプションは次のとおりです。

* qtree の名前
* qtree を配置するボリューム
* oplock
+
デフォルトでは、 qtree の oplock は有効になっています。ストレージシステム全体の oplock を無効にすると、個々の qtree で oplock を有効にしても、 oplock は設定されません。

* セキュリティ形式
+
セキュリティ形式には、 UNIX 、 NTFS 、 Mixed （ UNIX および NTFS ）のいずれかを指定できます。デフォルトでは、 qtree のセキュリティ形式は、選択したボリュームのセキュリティ形式と同じになります。

* エクスポートポリシー
+
新しいエクスポートポリシーを作成するか、既存のポリシーを選択できます。デフォルトでは、 qtree のエクスポートポリシーは、選択したボリュームのものと同じになります。

* qtree とユーザクォータのスペース使用制限




== Qtrees window

Qtrees window では、 qtree に関する情報を作成、表示、および管理できます。



=== コマンドボタン

* * 作成 * 。
+
qtree の作成ダイアログボックスを開きます。このダイアログボックスで、新しい qtree を作成できます。

* * 編集 * 。
+
qtree の編集ダイアログボックスを開きます。このダイアログボックスで、セキュリティ形式を変更したり、 qtree 上の oplock （便宜的ロック）を有効または無効にしたりできます。

* * エクスポートポリシーの変更 *
+
エクスポートポリシーダイアログボックスを開きます。このダイアログボックスで、新規または既存のエクスポートポリシーに 1 つ以上の qtree を割り当てることができます。

* * 削除 *
+
選択した qtree を削除します。

+
このボタンは、選択した qtree のステータスが正常な場合にのみ有効になります。

* * 更新 *
+
ウィンドウ内の情報を更新します。





=== qtree のリスト

qtree のリストには、 qtree が属するボリュームと qtree の名前が表示されます。

* * 名前 *
+
qtree の名前が表示されます。

* * 音量 *
+
qtree が属するボリュームの名前が表示されます。

* * セキュリティ形式 *
+
qtree のセキュリティ形式を示します。

* * ステータス *
+
qtree の現在のステータスを示します。

* * oplocks *
+
qtree に対して oplock の設定が有効になっているか無効になっているかを示します。

* * エクスポートポリシー *
+
qtree が割り当てられているエクスポートポリシーの名前が表示されます。





=== 詳細領域

* * 詳細タブ *
+
選択した qtree に関する詳細情報が表示されます。これには、 qtree が含まれているボリュームのマウントパス、エクスポートポリシーの詳細、エクスポートポリシールールなどの情報が含まれます。



* 関連情報 *

https://docs.netapp.com/us-en/ontap/concepts/index.html["ONTAP の概念"^]

https://docs.netapp.com/us-en/ontap/volumes/index.html["論理ストレージ管理"^]

https://docs.netapp.com/us-en/ontap/nfs-admin/index.html["NFS の管理"^]

https://docs.netapp.com/us-en/ontap/smb-admin/index.html["SMB / CIFS の管理"^]
