---
permalink: online-help-96-97/concept_service_processors.html 
sidebar: sidebar 
keywords: service, processors, monitor, manage, storage, system, manager, temperature, voltage, current, fan, speed, online, help, isolate, management, network, traffic, sp, bmc, e0m, interface, subnet, performance, routing, ip, address, edit 
summary: System Manager でサービスプロセッサを使用して、ストレージシステムの温度、電圧、電流、ファン速度などのパラメータを監視および管理できます。 
---
= System Manager - ONTAP 9.7 以前のバージョンでサービスプロセッサを使用します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP System Manager クラシック（ ONTAP 9.7 以前で使用可能）のサービスプロセッサを使用して、ストレージシステムの温度、電圧、電流、ファン速度などのパラメータを監視および管理できます。



== 管理ネットワークトラフィックを分離します

SP / BMC と e0M 管理インターフェイスは、管理トラフィック専用のサブネット上に設定することを推奨します。管理ネットワーク上でデータトラフィックを実行すると、原因のパフォーマンスの低下やルーティングの問題が発生する可能性があります。

ほとんどのストレージコントローラの管理イーサネットポート（シャーシ背面にあるレンチマークの付いたポート）は、内部イーサネットスイッチに接続されます。内部スイッチは、 SP / BMC および e0M 管理インターフェイスへの接続を提供します。これらを使用して、 Telnet 、 SSH 、 SNMP などの TCP/IP プロトコル経由でストレージシステムにアクセスできます。

リモート管理デバイスと e0M の両方を使用する場合は、同じ IP サブネット上に設定する必要があります。これらは低帯域幅のインターフェイスであるため、 SP / BMC と e0M は管理トラフィック専用のサブネット上に設定することを推奨します。

管理トラフィックを分離できない場合や、専用の管理ネットワークの規模が非常に大きい場合は、ネットワークトラフィックをできるだけ少なく抑える必要があります。イングレスブロードキャストまたはマルチキャストトラフィックが大量になると、 SP / BMC のパフォーマンスが低下する可能性があります。

[NOTE]
====
AFF A800 などの一部のストレージコントローラには、外部ポートが 2 つあります。 1 つは BMC 用、もう 1 つは e0M 用です。これらのコントローラの場合、 BMC と e0M を同じ IP サブネット上に設定する必要はありません。

====


== サービスプロセッサへの IP アドレスの割り当て

System Manager を使用して IP アドレスをすべてのサービスプロセッサに同時に割り当て、これらのサービスプロセッサを使用して、ストレージシステムのさまざまなシステムパラメータを監視および管理することができます。

.手順
. [ * Configuration * ] > [* Cluster*] > [* Configuration Updates* ] をクリックします。
. [Service Processor* （サービスプロセッサ * ） ] ウィンドウで、 [* グローバル設定 * （ Global Settings * ） ] をクリックします。
. [* グローバル設定 * （ Global Settings * ） ] ダイアログボックスで、 IP アドレスを割り当てるソースを選択します。
+
|===
| 状況 | 作業 


 a| 
IP アドレスを DHCP サーバから自動的に割り当てます
 a| 
[DHCP]*を選択します。



 a| 
IP アドレスをサブネットから割り当てます
 a| 
[* Subnet] を選択します。



 a| 
IP アドレスを手動で割り当てる
 a| 
[* 手動割り当て * ] を選択します。

|===
. [ 保存（ Save ） ] をクリックします。




== サービスプロセッサ設定を編集します

IP アドレス、ネットワークマスクまたはプレフィックス長、ゲートウェイアドレスなどのサービスプロセッサ属性は、 System Manager を使用して変更できます。IP アドレスが割り当てられていないサービスプロセッサに IP アドレスを割り当てることもできます。

.このタスクについて
* IP アドレスが手動で割り当てられているサービスプロセッサの設定を編集できます。
* DHCP サーバまたはサブネットから IP アドレスが割り当てられているサービスプロセッサの設定は編集できません。


.手順
. [ * Configuration * > * Cluster * > * Service Processor * ] をクリックします。
. [ サービスプロセッサ * ] ウィンドウで、変更するサービスプロセッサを選択し、 [ * 編集 ] をクリックします。
. [ サービスプロセッサの編集 *] ダイアログボックスで、必要な変更を行い、 [ 保存して閉じる *] をクリックします。




== サービスプロセッサを確認

サービスプロセッサは、ストレージシステム上のシステムに依存しないリソースであり、温度、電圧、電流、ファン速度などのストレージシステムパラメータを監視および管理できます。

サービスプロセッサがいずれかのストレージシステムパラメータで異常な状態を検出すると、サービスプロセッサはイベントをログに記録し、問題について ONTAP に通知します。また、 E メールまたは SNMP トラップを使用して AutoSupport メッセージを生成します。

サービスプロセッサは、 watchdog メカニズムを介して ONTAP を監視し、パートナーノードへの即座のフェイルオーバーを可能にします。サービスプロセッサは多数のシステムイベントも追跡し、ログファイルに保存します。イベントには、ブートの進行状況、 Field Replaceable Unit （ FRU ；フィールド交換可能ユニット）の交換、 ONTAP が生成するイベント、ユーザトランザクション履歴が含まれます。

サービスプロセッサを使用すると、ストレージシステムの状態に関係なくリモートからログインして、システムの診断、シャットダウン、電源の再投入、リブートを実行できます。また、サービスプロセッサにはリモート診断機能もあります。

監視機能と管理機能が統合されているサービスプロセッサを使用すると、問題発生時にストレージシステムを評価して、効果的な保守操作を即座に実行できます。



== サービスプロセッサウィンドウ

サービスプロセッサウィンドウを使用して、 IP アドレス、ネットワークマスク（ IPv4 ）、プレフィックス長（ IPv6 ）、ゲートウェイなどのサービスプロセッサ属性を表示および変更したり、サービスプロセッサの IP ソースを設定したりできます。



=== コマンドボタン

* * 編集 * 。
+
サービスプロセッサの編集ダイアログボックスを開きます。このダイアログボックスで、サービスプロセッサの IP アドレス、ネットワークマスク（ IPv4 ）またはプレフィックス長（ IPv6 ）、およびゲートウェイの情報を変更できます。

* * グローバル設定 *
+
Global Settings ダイアログボックスを開きます。このダイアログボックスでは、すべてのサービスプロセッサの IP アドレスのソースを、 DHCP 、サブネット、または手動のいずれかとして設定できます。

* * 更新 *
+
ウィンドウ内の情報を更新します。





=== サービスプロセッサのリスト

* * ノード *
+
サービスプロセッサが配置されているノードを指定します。

* * IP アドレス *
+
サービスプロセッサの IP アドレスを指定します。

* * ステータス *
+
サービスプロセッサのステータスを示します。オンライン、オフライン、デーモンオフライン、ノードオフライン、デグレード、 リブートされたか、不明です。

* * MACアドレス*
+
サービスプロセッサの MAC アドレスを指定します。





=== 詳細領域

サービスプロセッサリストの下の領域には、 IP アドレス、ネットワークマスク（ IPv4 ）、プレフィックス長（ IPv6 ）、ゲートウェイ、 IP ソース、 MAC アドレス、ファームウェアバージョン、ファームウェアの自動更新が有効かどうかなどの一般的な詳細情報。

* 関連情報 *

xref:task_setting_up_network_when_ip_address_range_is_disabled.adoc[IP アドレス範囲を無効にした状態でのネットワークの設定]
