---
permalink: online-help-96-97/concept_what_nvme_subsystem_is.html 
sidebar: sidebar 
keywords: nvme, subsystem, fc, rdma, transport, port, vserver, online, help, controller, cluster, table, settings, manage 
summary: NVMe サブシステムには、 1 つ以上のコントローラ、 1 つ以上のネームスペース、 1 つ以上の不揮発性メモリ（ NVM ）サブシステムポート（ FC-NVMe または RDMA トランスポートポート）、 NVM ストレージメディア、およびコントローラと NVM ストレージメディア間のインターフェイスが含まれます。コントローラのマッピングと管理のために、 NVM サブシステムは ONTAP の SVM にマッピングされます。 
---
= ONTAP 9.7 以前の System Manager で NVMe サブシステムを管理します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP システムマネージャクラシック（ ONTAP 9.7 以前で使用可能）を使用して、 NVMe サブシステムを作成および管理できます。SVM 内の異なるホストやネームスペースに NVMe サブシステムを関連付けることができます。また、 SVM ごとに複数の NVMe サブシステムをサポートできます。ただし、 NVMe サブシステムを複数の SVM で使用するように設定することはできません。



== NVMe サブシステムを作成する

System Manager を使用して、 NVMe サブシステムを作成できます。

.手順
. [* NVMe subsystems] ウィンドウで [* Create] をクリックします。
. NVMe サブシステムにエントリを入力します。 Create * window for the following fields ：
+
** * SVM *
+
ドロップダウンメニューから、サブシステムを作成する SVM を選択します。

** * 名前 *
+
サブシステムの名前を入力します。SVM にすでに存在するサブシステム名は使用できません。名前では大文字と小文字が区別され、最大文字数は 96 文字です。特殊文字を使用できます。

** *ホストOS *
+
ドロップダウンメニューから、サブシステムのホスト OS のタイプを選択します。

** *ホストNQN *
+
コントローラに接続されたホストの NQN を入力します。ホスト NQN は、カンマで区切って複数入力できます。



. [ 保存（ Save ） ] をクリックします。
+
NVMe サブシステムが作成され、 NVMe サブシステムのウィンドウが表示されます。





== NVMe サブシステムの詳細を編集します

System Manager を使用して、 NVMe サブシステムの詳細を編集できます。

.手順
. 編集する NVMe サブシステムを「 * NVMe サブシステム * 」ウィンドウで検索します。
. 編集するサブシステムの名前の左にあるチェックボックスをオンにします。
. [ 編集（ Edit ） ] をクリックします。
+
NVMe サブシステムの現在の詳細が、 NVMe サブシステムの Editwindow に表示されます。

. 変更できるのはホスト NQN * フィールド内の情報のみです。
+
** *ホストNQN *
+
コントローラに接続されたホストの NQN を変更します。ホスト NQN は、カンマで区切って複数入力できます。



+
関連付けられた * NVMe ネームスペース * テーブルは、ホスト NQN フィールドの下に表示されます。各ネームスペースについて、ネームスペースパスとネームスペース ID が表示されます。

. [ 保存（ Save ） ] をクリックします。
+
NVMe サブシステムの詳細が更新され、 NVMe サブシステムのウィンドウが表示されます。





== NVMe サブシステムを削除する

System Manager を使用して、クラスタから NVMe サブシステムを削除できます。

.このタスクについて
NVMe サブシステムを削除すると、次の処理が実行されます。

* NVMe サブシステムにホストが設定されている場合、マッピングされているホストは削除されます。
* NVMe サブシステムにネームスペースがマッピングされている場合、マッピングは解除されます。


.手順
. [* NVMe Subsystem* ] ウィンドウで、削除する NVMe サブシステムを検索します。
. 削除するサブシステムの名前の左にあるチェックボックスをオンにします。
. [ 削除（ Delete ） ] をクリックします。
+
警告メッセージが表示されます。

. 削除を確認する * Delete the NVMe Subsystem * （ NVMe サブシステムの削除）チェックボックスをクリックし、 * Yes * をクリックします。
+
NVMe サブシステムがクラスタから削除され、 NVMe サブシステムウィンドウが表示されます。





== NVMe サフシステムウイントウ

NVMe サブシステムウィンドウには、クラスタ内の NVMe サブシステムのインベントリリストがデフォルトで表示されます。リストをフィルタして、ある SVM に固有のサブシステムのみを表示することができます。また、 NVMe サブシステムを作成、編集、削除することもできます。このウィンドウにアクセスするには、 * Storage * > * NVMe * > * subsystems * を選択します。

* <<NVMe サブシステムテーブル>>
* <<ツールバー>>




=== NVMe サブシステムテーブル

NVMe サブシステムテーブルには、クラスタ内の NVMe サブシステムのインベントリが表示されます。このリストを絞り込むには、「 * SVM * 」フィールドのドロップダウンメニューを使用して、その SVM に関連付けられている NVMe サブシステムのみを表示する SVM を選択します。[*Search] フィールドと [*Filtering*] ドロップダウンメニューを使用して、リストをさらにカスタマイズできます。

NVMe サブシステムテーブルには次の列があります。

* * （チェックボックス） *
+
処理を実行するサブシステムを指定できます。

+
チェックボックスをクリックしてサブシステムを選択し、実行する処理をツールバーでクリックします。

* * 名前 *
+
サブシステムの名前が表示されます。

+
検索 * フィールドにサブシステム名を入力すると、そのサブシステムを検索できます。

* *ホストOS *
+
サブシステムに関連付けられているホスト OS の名前が表示されます。

* *ホストNQN *
+
コントローラに接続された NQN が表示されます。NQN が複数ある場合はカンマで区切って表示されます。

* * 関連付けられている NVMe ネームスペース *
+
サブシステムに関連付けられている NVM ネームスペースの数が表示されます。数字にカーソルを合わせると、関連付けられているネームスペースのパスが表示されます。パスをクリックすると、 [ 名前空間の詳細 ] ウィンドウが表示されます。





=== ツールバー

ツールバーは列ヘッダーの上にあります。ツールバーのフィールドとボタンを使用して、さまざまな操作を実行できます。

* * 検索 *
+
[ * 名前 * ] 列にある値を検索できます。

* * フィルタリング *
+
リストをフィルタするさまざまな方法をドロップダウンメニューから選択できます。

* * 作成 * 。
+
NVMe サブシステムの作成ダイアログボックスを開きます。このダイアログボックスで、 NVMe サブシステムを作成できます。

* * 編集 * 。
+
NVMe サブシステムの編集ダイアログボックスを開きます。このダイアログボックスで、既存の NVMe サブシステムを編集できます。

* * 削除 *
+
NVMe サブシステムの削除の確認ダイアログボックスを開きます。このダイアログボックスで、既存の NVMe サブシステムを削除できます。


