---
permalink: online-help-96-97/concept_system_alerts.html 
sidebar: sidebar 
keywords: system, manager, monitor, cluster, health, alerts, delete, 
summary: System Manager を使用して、クラスタのさまざまな要素を監視できます。 
---
= System Manager - ONTAP 9.7 以前を使用してシステムアラートを管理します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP System Manager クラシック（ ONTAP 9.7 以前で使用可能）を使用して、クラスタのさまざまな要素を監視できます。



== システムヘルスアラートを確認します

System Manager を使用して、サブシステムのシステムヘルスアラートについて承認して対応することができます。表示される情報に基づいて、推奨される対処方法を実行し、アラートによって報告された問題を修正できます。

.手順
. [* Events & Jobs*>* System Alerts*] をクリックします。
. [ * システム・アラート * ] ウィンドウで、サブシステム名の横にある矢印アイコンをクリックします。
. 承認するアラートを選択し、 [* Acknowledge * （確認） ] をクリックします。
. 名前を入力し、 * Acknowledge * （確認）をクリックします。




== システムヘルスアラートを抑制

System Manager を使用して、手動の操作を必要としないシステムヘルスアラートを抑制できます。

.手順
. [* Events & Jobs*>* System Alerts*] をクリックします。
. [ * システム・アラート * ] ウィンドウで、サブシステム名の横にある矢印アイコンをクリックします。
. 抑制するアラートを選択し、 * 抑制 * をクリックします。
. 名前を入力し、 * 抑制 * をクリックします。




== システムヘルスアラートを削除します

System Manager を使用して、対応済みのシステムヘルスアラートを削除できます。

.手順
. [* Events & Jobs*>* System Alerts*] をクリックします。
. [ * システム・アラート * ] ウィンドウで、サブシステム名の横にある矢印アイコンをクリックします。
. 削除するアラートを選択し、 * 削除 * をクリックします。
. [OK] をクリックします。




== 使用可能なクラスタヘルスモニタ

ヘルスモニタは複数あり、それぞれがクラスタの異なる部分を監視します。ヘルスモニタは、イベント検出、アラート送信、およびクリアされたイベントの削除を行い、 ONTAP システム内で発生したエラーからのリカバリに役立ちます。

[cols="1a,1a,1a"]
|===
| ヘルスモニタ名（識別子） | サブシステム名（識別子） | 目的 


 a| 
クラスタスイッチ（ cluster -switch ）
 a| 
スイッチ（ Switch-Health ）
 a| 
温度、利用率、インターフェイスの設定、冗長性（クラスタネットワークスイッチのみ）、ファンおよび電源の動作に関して、クラスタネットワークスイッチと管理ネットワークスイッチを監視します。クラスタスイッチヘルスモニタは SNMP でスイッチと通信します。デフォルトの設定は SNMPv2c です。

[NOTE]
====
ONTAP 9.2 以降では、最後のポーリング期間以降のクラスタスイッチのリブートをこのモニタで検出して報告できるようになりました。

====


 a| 
MetroCluster ファブリック
 a| 
スイッチ
 a| 
MetroCluster 構成のバックエンドファブリックトポロジを監視して、間違ったケーブル接続およびゾーニングなどの設定ミスや、 ISL の障害を検出します。



 a| 
MetroCluster の健常性
 a| 
インターコネクト、 RAID 、ストレージ
 a| 
FC-VI アダプタ、 FC イニシエータアダプタ、取り残されたアグリゲートやディスク、およびクラスタ間ポートを監視します



 a| 
ノード接続（ node-connect ）
 a| 
CIFS のノンストップオペレーション（ CIFS-NDO ）
 a| 
SMB 接続を監視して、 Hyper-V アプリケーションへのノンストップオペレーションを実現します。



 a| 
ストレージ（ SAS-connect ）
 a| 
ノードレベルでシェルフ、ディスク、およびアダプタを監視して、適切なパスと接続を維持します。



 a| 
システム
 a| 
該当なし
 a| 
他のヘルスモニタからの情報を集約します。



 a| 
システム接続（ system-connect ）
 a| 
ストレージ（ SAS-connect ）
 a| 
クラスタレベルでシェルフを監視して、 2 つの HA クラスタノードへの適切なパスを維持します。

|===


== システムヘルスアラートへの対応方法

システムヘルスアラートが発生した場合は、確認して詳細を確認し、原因となった状態を修復して、再発を防止できます。

ヘルスモニタからアラートが発せられた場合、次のいずれかの方法で対応できます。

* 影響を受けるリソース、アラートの重大度、原因の可能性、考えられる影響、対処方法など、アラートに関する情報を入手する
* アラートが発せられた時間、すでに誰かが承認しているかどうかなど、アラートに関する詳細情報を入手する
* 特定のシェルフやディスクなど、影響を受けるリソースまたはサブシステムの状態に関するヘルス関連の情報を取得する
* アラートを承認して、問題に対応中のユーザがいることを示し、自分自身を「承認者」と指定します。
* ケーブル接続を修正して接続の問題を解決するなど、アラートで指定された対処方法を実施することで、問題を解決する
* アラートが自動的に解除されない場合は、そのアラートを削除します。
* サブシステムのヘルスの状態に影響しないようにアラートを抑制する
+
問題を把握した場合は、抑制が役に立ちます。アラートを抑制すると、そのアラートは引き続き発生する可能性がありますが、抑制されたアラートが発生すると、サブシステムのヘルスは「 ok-with-suppressed 」と表示されます。





== System Alerts （システムアラート）ウィンドウ

システムヘルスアラートの詳細については、 System Alerts （システムアラート）ウィンドウを参照してください。また、アラートの承認、削除、および抑制もこのウィンドウから実行できます。



=== コマンドボタン

* * 確認 *
+
選択したアラートを承認し、問題に対処中であることを示すことができます。このボタンをクリックしたユーザが「承認者」に設定されます。

* * 抑制 *
+
選択したアラートを抑制して、同じアラートが再び通知されないようにすることができます。ユーザは「抑制者」と特定されます。

* * 削除 *
+
選択したアラートを削除します。

* * 更新 *
+
ウィンドウ内の情報を更新します。





=== アラートのリスト

* * サブシステム（番号警告数） *
+
SAS 接続、スイッチヘルス、 CIFS NDO 、 MetroCluster など、アラートが生成されるサブシステムの名前が表示されます。

* * アラート ID*
+
アラート ID が表示されます。

* * ノード *
+
アラートが生成されるノードの名前が表示されます。

* * 重大度 *
+
アラートの重大度を「 Unknown 」、「 Other 」、「 Information 」、「 Degraded 」、「 Minor 」、 メジャー ' クリティカル ' 致命的

* * リソース *
+
特定のシェルフやディスクなど、アラートを生成したリソースが表示されます。

* * 時間 *
+
アラートが生成された時刻が表示されます。





=== 詳細領域

詳細領域には、アラートが生成された時刻や、そのアラートが承認されているかどうかなど、アラートに関する詳細情報が表示されます。また、考えられる原因、アラートによって発生する状態が与えるかもしれない影響、およびアラートによって報告された問題を修正するための推奨される対処方法なども示されます。

* 関連情報 *

https://docs.netapp.com/us-en/ontap/system-admin/index.html["システム管理"]
