---
permalink: online-help-96-97/concept_managing_network.html 
sidebar: sidebar 
keywords: system, manager, storage, create, manage, ipspace, broadcast, domain, subnet, network, interface, ethernet, port, fc, fcoe, adapter, online, help 
summary: System Manager を使用して、 IPspace 、ブロードキャストドメイン、サブネット、ネットワークインターフェイス、イーサネットポートを作成および管理することで、ストレージシステムのネットワークを管理できます。 および FC / FCoE アダプタ 
---
= System Manager - ONTAP 9.7 以前を使用してネットワークを管理します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
IPspace 、ブロードキャストドメイン、サブネット、ネットワークインターフェイス、イーサネットポートを作成および管理することで、 ONTAP System Manager クラシック（ ONTAP 9.7 以前で使用可能）を使用してストレージシステムのネットワークを管理できます。 および FC / FCoE アダプタ



== [ ネットワーク ] ウィンドウ

[role="lead"]
ネットワークウィンドウを使用して、サブネット、ネットワークインターフェイス、イーサネットポート、ブロードキャストドメインなどのネットワークコンポーネントのリストを表示できます。 FC / FCoE アダプタと NVMe アダプタ、および IPspace 、ストレージシステム内のコンポーネントの作成、編集、削除に使用できます。



=== タブ

* * サブネット *
+
サブネットのリストを確認し、ストレージシステムのサブネットを作成、編集、削除できます。

* * ネットワーク・インターフェイス *
+
ネットワークインターフェイスのリストを確認し、ストレージシステムのネットワークインターフェイスを作成、編集、削除できます。また、 LIF を移行したり、インターフェイスのステータスを変更したり、インターフェイスをホームポートに戻したりできます。

* * イーサネットポート *
+
クラスタのポートを確認して編集できます。また、インターフェイスグループや VLAN ポートを作成、編集、削除できます。

* * ブロードキャストドメイン *
+
ブロードキャストドメインのリストを確認し、ストレージシステムのドメインを作成、編集、削除できます。

* * FC / FCoE および NVMe アダプター *
+
クラスタのポートを確認し、 FC / FCoE および NVMe アダプタの設定を編集できます。

* * IPspace *
+
IPspace とブロードキャストドメインのリストを確認し、ストレージシステムの IPspace を作成、編集、削除できます。





=== サブネットタブ



=== コマンドボタン

* * 作成 * 。
+
サブネットの作成ダイアログボックスを開きます。このダイアログボックスで、ネットワークインターフェイスを作成するための設定情報を含む新しいサブネットを作成できます。

* * 編集 * 。
+
Edit Subnet ダイアログボックスを開きます。このダイアログボックスでは、名前、サブネットアドレス、 IP アドレスの範囲、ゲートウェイの詳細など、サブネットの特定の属性を変更できます。

* * 削除 *
+
選択したサブネットを削除します。

* * 更新 *
+
ウィンドウ内の情報を更新します。





=== サブネットリスト

* * 名前 *
+
サブネットの名前を示します。

* * サブネット IP / サブネットマスク *
+
サブネットアドレスの詳細を示します。

* * ゲートウェイ *
+
ゲートウェイの IP アドレスを指定します。

* * 利用可能 *
+
サブネット内の使用可能な IP アドレスの数を示します。

* * 使用済み *
+
サブネット内の使用済みの IP アドレスの数を示します。

* * 総数 *
+
サブネット内の IP アドレスの総数（使用可能および使用済みの合計）を示します。

* * ブロードキャストドメイン *
+
サブネットが属しているブロードキャストドメインを示します。

* * IPspace *
+
サブネットが属している IPspace を示します。





=== 詳細領域

サブネットリストの下の領域には、選択したサブネットに関する詳細情報が表示されます。これには、サブネットの範囲や、 IP アドレスの使用可能数、使用済み数、総数を示すグラフなどが含まれます。



=== Network Interfaces タブの制限

* クラスタ LIF 、ノード管理 LIF 、 VIP LIF 、および BGP LIF については、 System Manager を使用して次の操作を実行することはできません。
+
** LIF を作成、編集、削除、有効化、無効化する
** LIF を移行するか、 LIF をホームポートに戻します


* クラスタ管理 LIF の場合は、 System Manager を使用して LIF を移行したり、 LIF をホームポートに戻したりできます。
+
ただし、を作成、編集、削除、有効化することはできません。 または LIF を無効にします。

* クラスタ間 LIF の場合は、 System Manager を使用して、 LIF を作成、編集、削除、有効化、無効化できます。
+
ただし、 LIF を移行したり、 LIF をホームポートに戻したりすることはできません。

* 次の構成では、ネットワークインターフェイスを作成、編集、削除できません。
+
** MetroCluster 構成
** ディザスタリカバリ（ DR ）用に構成された SVM






=== コマンドボタン

* * 作成 * 。
+
ネットワークインターフェイスの作成ダイアログボックスを開きます。このダイアログボックスで、ネットワークインターフェイスとクラスタ間 LIF を作成して、データの提供と SVM の管理を行うことができます。

* * 編集 * 。
+
ネットワークインターフェイスの編集ダイアログボックスを開きます。このダイアログボックスを使用して、データ LIF の管理アクセスを有効にすることができます。

* * 削除 *
+
選択したネットワークインターフェイスを削除します。

+
このボタンは、データ LIF が無効になっている場合にのみ有効になります。

* * ステータス *
+
ドロップダウンメニューを開きます。このメニューで、選択したネットワークインターフェイスを有効または無効にすることができます。

* * 移行 *
+
データ LIF またはクラスタ管理 LIF を同じノードの別のポートやクラスタ内の別のノードに移行できます。

* * 自宅へ送信 *
+
LIF のホストをホームポートに戻すことができます。

+
このコマンドボタンは、選択したインターフェイスがホーム以外のポートでホストされていて、かつホームポートが使用可能である場合にのみ有効になります。

+
クラスタ内のいずれかのノードが停止している場合は使用できません。

* * 更新 *
+
ウィンドウ内の情報を更新します。





=== インターフェイスのリスト

色分けされたアイコンの上にポインタを移動すると、インターフェイスの動作ステータスが表示されます。

* 緑 - インターフェイスが有効になっていることを示します。
* 赤 - インターフェイスが無効になっていることを示します。
* * インターフェイス名 *
+
ネットワークインターフェイスの名前を示します。

* * Storage Virtual Machine *
+
インターフェイスが属している SVM を示します。

* * IP アドレス / WWPN *
+
インターフェイスの IP アドレスまたは World Wide Port Name （ WWPN ）を示します。

* * 現在のポート *
+
インターフェイスがホストされているノードおよびポートの名前を示します。

* * データ・プロトコル・アクセス *
+
データへのアクセスに使用するプロトコルを指定します。

* * 管理アクセス *
+
インターフェイスで管理アクセスが有効になっているかどうかを示します。

* * サブネット *
+
インターフェイスが属しているサブネットを示します。

* * mx役割*
+
インターフェイスのロールを示します。データ、クラスタ間、クラスタ、クラスタ管理、ノード管理のいずれかになります。





=== 詳細領域

インターフェイスリストの下の領域には、選択したインターフェイスに関する詳細情報が表示されます。これには、ホームポート、現在のポート、ポートの速度、フェイルオーバーポリシー、フェイルオーバーグループ、フェイルオーバー状態、管理ステータス、ロール、 IPspace 、ブロードキャストドメイン、ネットワークマスクなどの一般的なプロパティが含まれます。 ゲートウェイおよび DDNS のステータス。



=== Ethernet Ports （ Ethernet ポート）タブ



=== コマンドボタン

* * インターフェイスグループを作成 *
+
Create Interface Group ダイアログボックスを開きます。このダイアログボックスで、ポートを選択し、ポートおよびネットワークトラフィック分散の使用方法を決定して、インターフェイスグループを作成できます。

* * VLAN を作成します。 *
+
Create VLAN ダイアログボックスを開きます。このダイアログボックスで、イーサネットポートまたはインターフェイスグループを選択し、 VLAN タグを追加して、 VLAN を作成できます。

* * 編集 * 。
+
次のいずれかのダイアログボックスを開きます。

+
** Edit Ethernet Port ダイアログボックス：イーサネットポートの設定を変更できます。
** Edit VLAN ダイアログボックス： VLAN の設定を変更できます。
** Edit Interface Group ダイアログボックス：インターフェイスグループを変更できます。


+
VLAN は、ブロードキャストドメインと関連付けられていない VLAN のみが編集できます。

* * 削除 *
+
次のいずれかのダイアログボックスを開きます。

+
** VLAN の削除ダイアログボックス： VLAN を削除できます。
** インターフェイスグループの削除ダイアログボックス：インターフェイスグループを削除できます。


* * 更新 *
+
ウィンドウ内の情報を更新します。





=== ポートのリスト

色分けされたアイコンの上にポインタを移動すると、ポートの動作ステータスが表示されます。

* 緑 - ポートが有効になっていることを示します。
* 赤 - ポートが無効になっていることを示します。
* * ポート *
+
物理ポート、 VLAN ポート、またはインターフェイスグループのポート名が表示されます。

* * ノード *
+
物理インターフェイスが配置されているノードが表示されます。

* * ブロードキャストドメイン *
+
ポートのブロードキャストドメインが表示されます。

* * IPspace *
+
ポートが属している IPspace が表示されます。

* * タイプ *
+
インターフェイスグループ、物理インターフェイス、仮想 IP 、 VLAN など、インターフェイスのタイプが表示されます。





=== 詳細領域

ポートリストの下の領域には、ポートのプロパティに関する詳細情報が表示されます。

* * 詳細タブ *
+
管理や動作の詳細が表示されます。

+
動作の詳細の一部として、ポートのヘルスステータスが表示されます。「正常」または「デグレード」のいずれかになります。ポートがデグレード状態になるのは、ネットワークの変動が継続的に発生している場合、または同じブロードキャストドメインの他のポートに接続されていない場合です。

+
また、選択したポートでホストされているネットワークインターフェイスのインターフェイス名、 SVM の詳細、 IP アドレスの詳細も表示されます。また、インターフェイスがホームポートにあるかどうかも示します。

* * パフォーマンスタブ *
+
エラー率やスループットなど、イーサネットポートのパフォーマンス指標のグラフが表示されます。

+
クライアントのタイムゾーンやクラスタのタイムゾーンを変更すると、パフォーマンス指標のグラフも変わります。最新のグラフを表示するには、ブラウザの表示を更新してください。





=== ブロードキャストドメインタブ



=== コマンドボタン

* * 作成 * 。
+
[ ブロードキャストドメインの作成 ] ダイアログボックスが開きます。このダイアログボックスで、ポートを含む新しいブロードキャストドメインを作成できます。

* * 編集 * 。
+
Edit Broadcast Domain ダイアログボックスが開きます。このダイアログボックスで、名前、 MTU サイズ、関連付けられているポートなど、ブロードキャストドメインの属性を変更できます。

* * 削除 *
+
選択したブロードキャストドメインを削除します。

* * 更新 *
+
ウィンドウ内の情報を更新します。





=== ブロードキャストドメインのリスト

* * ブロードキャストドメイン *
+
ブロードキャストドメインの名前を示します。

* * MTU *
+
MTU サイズを示します。

* * IPspace *
+
IPspace を示します。

* * 複合ポート更新ステータス *
+
ブロードキャストドメインの作成または編集時に、ポートの更新ステータスを示します。ポートの更新エラーがある場合は、該当するリンクをクリックすると別ウィンドウに表示されます。





=== 詳細領域

ブロードキャストドメインリストの下の領域には、ブロードキャストドメインに含まれるすべてのポートが表示されます。デフォルト以外の IPspace 内のブロードキャストドメインの場合、更新エラーが発生しているポートは詳細領域に表示されません。色分けされたアイコンの上にポインタを移動すると、ポートの動作ステータスが表示されます。

* 緑 - ポートが有効になっていることを示します。
* 赤 - ポートが無効になっていることを示します。




=== FC / FCoE and NVMe Adapters （ FC / FCoE および NVMe アダプタ）タブ



=== コマンドボタン

* * 編集 * 。
+
FC / FCoE および NVMe 設定の編集ダイアログボックスが開きます。このダイアログボックスで、アダプタの速度を変更できます。

* * ステータス *
+
アダプタをオンラインまたはオフラインにすることができます。

* * 更新 *
+
ウィンドウ内の情報を更新します。





=== FC / FCoE および NVMe アダプタのリスト

* * WWNN *
+
FC / FCoE および NVMe アダプタの一意の識別子を示します。

* * ノード名 *
+
アダプタを使用しているノードの名前を示します。

* * スロット *
+
アダプタを使用しているスロットを指定します。

* * WWPN *
+
アダプタの FC World Wide Port Name （ WWPN ）を示します。

* * ステータス *
+
アダプタのステータスがオンラインとオフラインのどちらであるかを示します。

* * 速度 *
+
速度設定が自動と手動のどちらであるかを示します。





=== 詳細領域

FC / FCoE および NVMe アダプタのリストの下の領域には、選択したアダプタに関する詳細情報が表示されます。

* * 詳細タブ *
+
メディアタイプ、ポートアドレス、データリンク速度、接続ステータス、動作ステータス、 ファブリックのステータスとアダプタの速度。

* * パフォーマンスタブ *
+
IOPS や応答時間など、 FC / FCoE および NVMe アダプタのパフォーマンス指標のグラフが表示されます。

+
クライアントのタイムゾーンやクラスタのタイムゾーンを変更すると、パフォーマンス指標のグラフも変わります。最新のグラフを表示するには、ブラウザの表示を更新してください。





=== IPspaces タブ



=== コマンドボタン

* * 作成 * 。
+
IPspace の作成ダイアログボックスを開きます。このダイアログボックスで、新しい IPspace を作成できます。

* * 編集 * 。
+
IPspace の編集ダイアログボックスを開きます。このダイアログボックスで、既存の IPspace の名前を変更できます。

* * 削除 *
+
選択した IPspace を削除します。

* * 更新 *
+
ウィンドウ内の情報を更新します。





=== IPspace のリスト

* * 名前 *
+
IPspace の名前を示します。

* * ブロードキャストドメイン *
+
ブロードキャストドメインを示します。





=== 詳細領域

IPspace リストの下の領域には、選択した IPspace 内の Storage Virtual Machine （ SVM ）のリストが表示されます。
