---
permalink: online-help-96-97/concept_unix.html 
sidebar: sidebar 
keywords: system, manager, unix, svm, online, help, command, button, group, tab, storage, virtual, machine 
summary: System Manager を使用して、各 Storage Virtual Machine （ SVM ）のローカル UNIX ユーザおよびグループのリストを管理できます。 
---
= System Manager ONTAP 9.7 以前を使用したローカル UNIX ユーザおよびグループ
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP System Manager クラシック（ ONTAP 9.7 以前で使用可能）を使用すると、各 Storage Virtual Machine （ SVM ）のローカル UNIX ユーザとグループのリストを管理できます。



== [UNIX]ウィンドウ

UNIX ウィンドウを使用して、各 Storage Virtual Machine （ SVM ）のローカル UNIX ユーザおよびグループのリストを管理できます。ローカル UNIX ユーザおよびグループは、認証やネームマッピングに使用できます。



=== [ グループ ] タブ

SVM に対してローカルな UNIX グループを追加、編集、削除するには、グループタブを使用します。



== コマンドボタン

* * グループを追加 *
+
Add Group ダイアログボックスを開きます。このダイアログボックスで、 SVM に対してローカルな UNIX グループを作成できます。ローカル UNIX グループはローカル UNIX ユーザとともに使用されます。

* * 編集 * 。
+
グループの編集ダイアログボックスを開きます。このダイアログボックスで、グループ ID を編集できます。

* * 削除 *
+
選択したグループを削除します。

* * 更新 *
+
ウィンドウ内の情報を更新します。





=== グループリスト（ Groups List ）

* * グループ名 *
+
グループの名前が表示されます。

* * グループ ID *
+
グループの ID が表示されます。





=== [ ユーザー ] タブ

SVMs に対してローカルな UNIX ユーザを追加、編集、削除するには、 * users * タブを使用します。



=== コマンドボタン

* * ユーザーを追加 *
+
ユーザの追加ダイアログボックスを開きます。このダイアログボックスで、 SVM のローカルの UNIX ユーザを作成できます。

* * 編集 * 。
+
ユーザの編集ダイアログボックスを開きます。このダイアログボックスで、ユーザ ID 、ユーザが属している UNIX グループ、およびユーザのフルネームを編集できます。

* * 削除 *
+
選択したユーザを削除します。

* * 更新 *
+
ウィンドウ内の情報を更新します。





=== ユーザリスト

* * ユーザー名 *
+
ユーザの名前が表示されます。

* * ユーザー ID *
+
ユーザの ID が表示されます。

* * 氏名 *
+
ユーザのフルネームが表示されます。

* * プライマリグループ ID *
+
ユーザが属するグループの ID が表示されます。

* * プライマリグループ名 *
+
ユーザが属するグループの名前が表示されます。


