---
permalink: online-help-96-97/concept_ethernet_ports.html 
sidebar: sidebar 
keywords: system, manager, manager, ethernet, port, create, online, help, create, interface, group, lacp, vlan, settings, duplex, mode, speed, mtu, size,  port, nodes, fcp, 
summary: System Manager を使用して、イーサネットポートを作成および管理できます。 
---
= System Manager - ONTAP 9.7 以前を使用してイーサネットポートを管理します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP システムマネージャクラシック（ONTAP 9.7以前で使用可能）を使用して、イーサネットポートを作成および管理できます。



== インターフェイスグループを作成する

System Manager を使用してインターフェイスグループ（シングルモード、スタティックマルチモード、またはダイナミックマルチモード（ LACP ））を作成し、集約されたネットワークポートの機能を組み合わせてクライアントに単一のインターフェイスを提供できます。

.作業を開始する前に
ブロードキャストドメインまたはインターフェイスグループに属さない空きポート、あるいは VLAN をホストする空きポートを用意しておく必要があります。

.手順
. [ * ネットワーク *>* イーサネットポート * ] をクリックします。
. Create Interface Group をクリックします。
. Create Interface Group * ダイアログボックスで、次の設定を指定します。
+
** インターフェイスグループの名前
** ノード
** インターフェイスグループに含めるポートを指定します
** ポートの使用モード：シングルモード、スタティックマルチモード、またはダイナミックマルチモード（ LACP ）
** ネットワークの負荷分散： IP ベース、 MAC アドレスベース、シーケンシャル、またはポート
** 必要に応じて、インターフェイスグループのブロードキャストドメインを指定します


. [ 作成（ Create ） ] をクリックします。




== VLAN インターフェイスを作成する

同じネットワークドメイン内の分離されたブロードキャストドメインを管理するための VLAN を作成するには、 System Manager を使用します。

.手順
. [ * ネットワーク *>* イーサネットポート * ] をクリックします。
. [Create VLAN] をクリックします。
. Create VLAN * ダイアログボックスで、ノード、物理インターフェイス、およびブロードキャストドメインを選択します（必要な場合）。
+
物理インターフェイスのリストには、イーサネットポートとインターフェイスグループのみが表示されます。このリストには、別のインターフェイスグループまたは既存の VLAN にあるインターフェイスは表示されません。

. VLAN タグを入力し、 * Add * をクリックします。
+
一意の VLAN タグを追加する必要があります。

. [ 作成（ Create ） ] をクリックします。




== イーサネットポートの設定を編集します

System Manager を使用して、二重モードや速度の設定など、イーサネットポートの設定を編集することができます。

.手順
. [ * ネットワーク *>* イーサネットポート * ] をクリックします。
. 物理ポートを選択し、 * Edit * をクリックします。
. [イーサネットポートの編集]ダイアログボックスで、二重モードと速度の設定を次のいずれかに変更します。 `manual` または `automatic`。
. [ 編集（ Edit ） ] をクリックします。




== インターフェイスグループの設定を編集します

System Manager を使用して、インターフェイスグループに対するポートの追加や削除、インターフェイスグループ内のポートの使用モードや負荷分散パターンの変更を行うことができます。

.このタスクについて
ブロードキャストドメインに割り当てられているインターフェイスグループの MTU の設定は変更できません。

.手順
. [ * ネットワーク *>* イーサネットポート * ] をクリックします。
. インターフェイスグループを選択し、 * Edit * をクリックします。
. 必要に応じてインターフェイスグループの設定を変更し、 * Save and Close * をクリックします。




== VLAN の MTU サイズを変更します

ブロードキャストドメインの一部ではない VLAN インターフェイスの MTU サイズを変更するには、 System Manager を使用します。

.このタスクについて
管理ポート e0M の MTU サイズは変更しないでください。

.手順
. [ * ネットワーク *>* イーサネットポート * ] をクリックします。
. 変更する VLAN を選択し、 * Edit * をクリックします。
. Edit VLAN * ダイアログボックスで、必要に応じて MTU サイズを変更し、 * Save * をクリックします。




== VLAN を削除します

System Manager を使用して、ネットワークポートに設定されている VLAN を削除することができます。NIC をスロットから取り外す前に、 VLAN の削除が必要になることがあります。VLAN を削除すると、その VLAN を使用しているすべてのフェイルオーバールールとフェイルオーバーグループから自動的に削除されます。

.作業を開始する前に
その VLAN に関連付けられている LIF がないようにします。

.手順
. [ * ネットワーク *>* イーサネットポート * ] をクリックします。
. 削除する VLAN を選択し、 * Delete * をクリックします。
. 確認のチェックボックスをオンにし、 * 削除 * をクリックします。




== ポートとアダプタ

ポートはノードにグループ化され、選択したプロトコルカテゴリに基づいてノードが表示されます。たとえば、データが FC プロトコルを使用して提供される場合、 FCP アダプタを持つノードのみが表示されます。負荷が少ないポートを選択する際には、ホストされているインターフェイス数が参考になります。

* 関連情報 *

https://docs.netapp.com/us-en/ontap/networking/index.html["Network Management の略"]

https://docs.netapp.com/us-en/ontap/concepts/index.html["ONTAP の概念"]

xref:reference_network_window.adoc[[ ネットワーク ] ウィンドウ]
