---
permalink: online-help-96-97/concept_options_for_resizing_volumes.html 
sidebar: sidebar 
keywords: option, resize, volume, wizard, snapshot, reserve, snapshot, copy, results, view, online, help 
summary: ボリュームのサイズ変更ウィザードを使用して、ボリュームのサイズ変更、 Snapshot リザーブの調整、 Snapshot コピーの削除、変更の結果の動的な表示を行うことができます。 
---
= System Manager を使用してボリュームのサイズを変更するためのオプション - ONTAP 9.7 以前
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP System Manager クラシック（ ONTAP 9.7 以前で利用可能）のボリュームのサイズ変更ウィザードを使用して、ボリュームのサイズ変更、 Snapshot リザーブの調整、 Snapshot コピーの削除、変更の結果の動的な表示を行うことができます。

ボリュームのサイズ変更ウィザードには、ボリューム内の現在のスペース割り当てを示す棒グラフが表示されます。このグラフには、使用スペースと空きスペースの量も表示されます。ボリュームの Snapshot リザーブのサイズを変更すると、このグラフは変更を反映して動的に更新されます。

また、「スペースの計算」ボタンを使用して、選択した Snapshot コピーを削除することにより解放されるスペースの量を確認することもできます。

ボリュームのサイズ変更ウィザードを使用して、次の変更をボリュームに加えることができます。

* * ボリュームサイズを変更します。 *
+
ボリュームの合計サイズを変更して、ストレージスペースを増加または減少させることができます。

* * スナップショット予約の調整 *
+
Snapshot コピー用にリザーブされるスペースの量を調整して、ストレージスペースを増加または減少させることができます。

* * Snapshot コピーを削除 *
+
Snapshot コピーを削除してボリュームスペースを再生できます。

+
[NOTE]
====
使用中の Snapshot コピーは削除できません。

====
* * 自動拡張 *
+
必要に応じて、ボリュームの自動拡張の上限を指定できます。


