---
permalink: online-help-96-97/concept_why_you_use_svms.html 
sidebar: sidebar 
keywords: svm, data, access, nondisruptive, operation, scalability, security, online, help 
summary: SVM は、ストレージシステムと同様に、物理ストレージまたはコントローラに関係なく、クライアントにデータアクセスを提供します。SVM には、ノンストップオペレーション、優れた拡張性、セキュリティ、ユニファイドストレージなどの利点があります。 
---
= System Manager を備えた SVM について - ONTAP 9.7 以前
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP System Managerクラシック（ONTAP 9.7以前で利用可能）とともにSVMSを使用すると、ストレージシステムと同様に、物理ストレージまたはコントローラに関係なくクライアントにデータアクセスを提供できます。SVM には、ノンストップオペレーション、優れた拡張性、セキュリティ、ユニファイドストレージなどの利点があります。

SVM には次の利点があります。

* マルチテナンシー
+
SVM は、セキュアマルチテナンシーの基本ユニットであり、ストレージインフラをパーティショニングすることで、複数の独立したストレージシステムが存在するように見せることができます。これらのパーティションでは、データと管理が分離されます。

* ノンストップオペレーション
+
SVM は、必要なかぎり継続的に無停止で稼働できます。SVM を使用すると、ソフトウェアとハードウェアのアップグレード、ノードの追加と削除、およびすべての管理操作中もクラスタを継続的に稼働できるようになります。

* 拡張性
+
SVM は、オンデマンドデータスループットなどのストレージ要件を満たします。

* セキュリティ
+
SVM はそれぞれ単一の独立したサーバとみなされるため、複数の SVM を相互にデータフローがない状態でクラスタ内に共存させることができます。

* ユニファイドストレージ
+
SVM は、複数のデータアクセスプロトコルを使用して同時にデータをやり取りできます。SVM は、 CIFS や NFS などの NAS プロトコルでファイルレベルのデータアクセスを提供し、 iSCSI 、 FC / FCoE 、 NVMe などの SAN プロトコルでブロックレベルのデータアクセスを提供します。SVM は、 SAN クライアントと NAS クライアントそれぞれに同時にデータを提供できます。

* 管理の委譲
+
SVM 管理者には、クラスタ管理者によって割り当てられた権限があります。


