---
permalink: online-help-96-97/concept_protection_policies.html 
sidebar: sidebar 
keywords: online, help, protection, policy, system, manager, create, edit, delete 
summary: System Manager を使用して、保護ポリシーを作成、編集、削除できます。 
---
= System Manager - ONTAP 9.7以前を使用して保護ポリシーを管理します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP System Managerクラシック（ONTAP 9.7以前で使用可能）を使用して、保護ポリシーを作成、編集、削除できます。



== 保護ポリシーを作成する

System Manager を使用して、クラスタレベルの非同期ミラーポリシー、バックアップポリシー、またはミラーとバックアップのポリシーを作成し、作成したポリシーをクラスタレベルのデータ保護関係に適用することができます。

.手順
. [* 保護 *>] 、 [* 保護ポリシー *] の順にクリックします。
. [ 作成（ Create ） ] をクリックします。
. [ ポリシーの作成 *] ダイアログボックスで、作成するポリシーのタイプを選択します。
. ポリシー名と転送の優先順位を指定します。
+
転送の優先順位を「低」にすると優先順位が最も低くなり、優先順位が「中」の転送よりもあとに実行されます。デフォルトでは、転送の優先順位は「中」に設定されます。

. *オプション：* Enable Network Compression *チェックボックスを選択して、データ転送中に転送されるデータを圧縮します。
. *オプション：*非同期ミラー・ポリシーの場合、*すべてのソースSnapshotコピーを転送*チェック・ボックスを選択して、「all_source_snapshots」ルールをミラー・ポリシーに含めます。これにより、ソース・ボリュームのすべてのSnapshotコピーがバックアップされます。
. *オプション：*[Add Comments*（コメントの追加）]をクリックして、ポリシーのコメントを追加します。
. バックアップポリシーまたはミラーバックアップポリシーの場合は、 SnapMirror ラベルとデスティネーションの保持数を指定します。
. [ 作成（ Create ） ] をクリックします。




== [ 保護ポリシー ] ウィンドウ

Protection Policies ウィンドウを使用して、ミラー、バックアップ、およびミラーバックアップポリシーに関する情報を作成、管理、および表示できます。



=== コマンドボタン

* * 作成 * 。
+
ポリシーの作成ダイアログボックスを開きます。このダイアログボックスで、ミラー、バックアップ、またはミラーバックアップポリシーを作成できます。

* * 編集 * 。
+
ポリシーの編集ダイアログボックスを開きます。このダイアログボックスで、ポリシーを編集できます。

* * 削除 *
+
[ ポリシーの削除 ] ダイアログボックスが開き、ポリシーを削除できます。

* * 更新 *
+
ウィンドウ内の情報を更新します。





=== 保護ポリシーのリスト

* * 名前 *
+
保護ポリシーの名前が表示されます。

* * タイプ *
+
ポリシーのタイプが表示されます。タイプはバックアップ、ミラーバックアップ、非同期ミラーのいずれかです。

* * コメント *
+
ポリシーに指定されている概要を表示します。

* * 転送優先順位 *
+
「 Normal 」や「 Low 」などのデータ転送の優先順位が表示されます。





=== 詳細領域

* * ［ 保険契約の詳細 ］ タブ *
+
保護ポリシーの詳細が表示されます。これには、ポリシーを作成したユーザ、ルールの数、保持数、ネットワーク圧縮のステータスなどの情報が含まれます。

* * ［ ポリシールール ］ タブ *
+
ポリシーに適用されるルールの詳細が表示されます。[ ポリシールール ] タブは、選択したポリシーにルールが含まれている場合にのみ表示されます。


