---
permalink: online-help-96-97/concept_shares.html 
sidebar: sidebar 
keywords: online, help, share, system, manager, qtress, cifs, create, edit, manage, share, access, stop, home, directory, configure, smb 
summary: System Manager を使用して、共有を作成、編集、管理できます。 
---
= System Manager - ONTAP 9.7 以前を使用して共有を管理します
:allow-uri-read: 


ONTAP System Manager クラシック（ ONTAP 9.7 以前で使用可能）を使用して、共有を作成、編集、管理できます。



== CIFS 共有を作成する

System Manager を使用して CIFS 共有を作成し、 CIFS ユーザがアクセス可能なフォルダ、 qtree 、またはボリュームを指定できます。

.作業を開始する前に
CIFS をセットアップして開始するには、 CIFS ライセンスがインストールされている必要があります。

.手順
. [* ストレージ *>* 共有 ] をクリックします。
. SVM * フィールドのドロップダウンメニューから、 CIFS 共有を作成する SVM を選択します。
. [ 共有の作成 *] をクリックします。
. [ 共有の作成 * ] ウィンドウで、 [ * 参照 ] をクリックし、共有するフォルダ、 qtree 、またはボリュームを選択します。
. 新しい CIFS 共有の名前を指定します。
. *オプション：* Hyper-VおよびSQL *で継続的可用性を有効にするチェックボックスをオンにすると、SMB 3.0以降をサポートするクライアントがノンストップオペレーション時にファイルを継続して開いておけるようになります。
+
このオプションを使用して開いたファイルは、フェイルオーバー、ギブバック、 LIF の移行など、システムを停止させるイベントから保護されます。

+
System Manager 9.6 以降では、 FlexGroup ボリュームの継続的可用性がサポートされます。

. SMB 3.0 暗号化を有効にするには、 * この共有へのアクセス時にデータを暗号化 * チェックボックスをオンにします。
. 共有の概要またはコメントを入力し、 * Create * をクリックします。


.結果
CIFS 共有が作成され、グループ内の「 Everyone の完全な制御」にアクセス権限が設定されます。



== 共有アクセスを停止します

フォルダ、 qtree 、またはボリュームへの共有ネットワークアクセスを削除するときは、 System Manager を使用して共有を停止できます。

.作業を開始する前に
CIFS ライセンスをインストールしておく必要があります。

.手順
. [* ストレージ *>* 共有 ] をクリックします。
. SVM * フィールドのドロップダウンメニューから、停止する CIFS 共有が配置されている SVM を選択します。
. 共有のリストから、共有を停止する共有を選択し、 * 共有の停止 * をクリックします。
. 確認のチェックボックスをオンにし、 * 停止 * をクリックします。
. 共有が [ * 共有 ] ウィンドウに表示されなくなったことを確認します。




== ホームディレクトリ共有を作成する

System Manager を使用して、ホームディレクトリ共有を作成し、ホームディレクトリ検索パスを管理できます。

.作業を開始する前に
CIFS がセットアップされて開始されている必要があります。

.手順
. [* ストレージ *>* 共有 ] をクリックします。
. [ ホームディレクトリの作成 *] をクリックし、ユーザーをディレクトリにマップする方法を決定するパターン情報を入力します。
. [ 作成（ Create ） ] をクリックします。
. 作成したホームディレクトリが * Shares * ウィンドウに表示されていることを確認します。




== 共有設定を編集します

System Manager を使用して、シンボリックリンクの設定、共有に対するユーザやグループのアクセス権、共有へのアクセスの種類など、共有設定を変更することができます。また、 Hyper-V による共有の継続的可用性や Access-Based Enumeration （ ABE ；アクセスベースの列挙）を有効または無効にすることもできます。System Manager 9.6 以降では、 FlexGroup ボリュームの継続的可用性がサポートされます。

.手順
. [* ストレージ *>* 共有 ] をクリックします。
. 共有のリストから変更する共有を選択し、 * 編集 * をクリックします。
. 共有設定の編集 * ダイアログボックスで、必要に応じて共有設定を変更します。
+
.. General * タブで、 Hyper-V による共有の継続的可用性を有効にします
+
継続的可用性を有効にすると、 SMB 3.0 をサポートする SMB 3.0 クライアントで、無停止運用時にファイルを継続して開いておくことができます。継続して開いておくように指定したファイルは、フェイルオーバー、ギブバック、 LIF の移行など、システムを停止させるイベントから保護されます。

.. [ * アクセス許可 * ] タブで、ユーザーまたはグループを追加し、アクセスの種類を指定するアクセス許可を割り当てます。
.. [ * オプション * （ * Options * ） ] タブで、必要なオプションを選択します。


. [ 保存して閉じる ] をクリックします。
. [* 共有 ] ウィンドウで選択した共有に加えた変更を確認します。




== ONTAP で動的ホームディレクトリを有効にする方法

ONTAP ホームディレクトリを使用すると、 SMB 共有を設定し、ユーザと一連の変数に基づいてさまざまなディレクトリにマッピングすることができます。ユーザごとに別個の共有を作成するのではなく、 1 つの共有を設定し、いくつかのホームディレクトリパラメータを指定して、エントリポイント（共有）とホームディレクトリ（ SVM 上のディレクトリ）間の関係をユーザ単位で定義します。

ゲストユーザとしてログインしたユーザは、ホームディレクトリを持ちません。また、他のユーザのホームディレクトリにアクセスすることはできません。ユーザとディレクトリのマッピング方法を決定する 4 つの変数があります。

* * 共有名 *
+
ユーザの接続先として作成する共有の名前です。この共有にはホームディレクトリのプロパティを設定する必要があります。

+
共有名には、次の動的な名前を使用できます。

+
** `%w` （ユーザのWindowsユーザ名）
** `%d` （ユーザのWindowsドメイン名）
** `%u` （ユーザのマッピングされたUNIXユーザ名）


+
すべてのホームディレクトリ間で共有名を一意にするには、共有名に/`%w` または `%u` 変数（Variable）：共有名には両方を使用できます `%d` および/`%w` 変数（例： `%d`/`%w`または、共有名に静的な部分と変数の部分（home_など）を含めることができます/`%w`）。

* * 共有パス *
+
共有によって定義される、つまり、共有名の 1 つに関連付けられる相対パスです。各検索パスに付加されて、 SVM のルートからのユーザのホームディレクトリの完全パスを生成します。静的（例： `home`）、動的（例： `%w`）、または2つの組み合わせ（例： `eng/%w`）。

* * 検索パス *
+
SVM のルートからの絶対パスのセットで、 ONTAP ではこのパスに基づいてホームディレクトリが検索されます。を使用して、1つ以上の検索パスを指定できます `vserver cifs home-directory search-path add` コマンドを実行します複数 ONTAP の検索パスを指定すると、有効なパスが見つかるまで、指定された順に各検索パスが試行されます。

* * ディレクトリ *
+
ユーザに対して作成する、そのユーザのホームディレクトリです。通常、ディレクトリ名はユーザの名前です。ホームディレクトリは、検索パスで定義されるいずれかのディレクトリに作成する必要があります。



たとえば、次のように設定します。

* ユーザ： John Smith
* ユーザのドメイン： acme
* ユーザ名： jsmith
* SVM 名： vs1
* ホームディレクトリ共有名#1：home_ `%w` -共有パス： `%w`
* ホームディレクトリ共有名#2： `%w` -共有パス： `%d/%w`
* 検索パス#1： `/vol0home/home`
* 検索パス#2： `/vol1home/home`
* 検索パス#3： `/vol2home/home`
* ホームディレクトリ： `/vol1home/home/jsmith`


シナリオ1：ユーザーがに接続します `\\vs1\home_jsmith`。これは最初のホームディレクトリ共有名に一致し、相対パスが生成されます `jsmith`。ONTAP がというディレクトリを検索するようになりました `jsmith` 各検索パスを順にチェックするには、次の手順に従います。

* `/vol0home/home/jsmith` は存在しません。検索パス#2に進みます。
* `/vol1home/home/jsmith` は存在します。したがって、検索パス#3はチェックされません。これで、ユーザは自分のホームディレクトリに接続されました。


シナリオ2：ユーザーがに接続する `\\vs1\jsmith`。これは2番目のホームディレクトリ共有名に一致し、相対パスが生成されます `acme/jsmith`。ONTAP がというディレクトリを検索するようになりました `acme/jsmith` 各検索パスを順にチェックするには、次の手順に従います。

* `/vol0home/home/acme/jsmith` は存在しません。検索パス#2に進みます。
* `/vol1home/home/acme/jsmith` は存在しません。検索パス#3に進みます。
* `/vol2home/home/acme/jsmith` は存在しません。ホームディレクトリが存在しないため、接続は失敗します。




== 共有ウィンドウ

共有の管理や共有に関する情報の表示には、共有ウィンドウを使用できます。



=== コマンドボタン

* * 共有の作成 *
+
共有を作成できる [ 共有の作成 ] ダイアログボックスを開きます。

* * ホームディレクトリを作成 *
+
Create Home Directory Share ダイアログボックスを開きます。このダイアログボックスで、新しいホームディレクトリ共有を作成できます。

* * 編集 * 。
+
設定の編集ダイアログボックスを開きます。このダイアログボックスで、選択した共有のプロパティを変更できます。

* * 共有を停止 *
+
選択したオブジェクトが共有されないようにします。

* * 更新 *
+
ウィンドウ内の情報を更新します。





=== 共有リスト

共有リストには、各共有の名前とパスが表示されます。

* * 共有名 *
+
共有の名前が表示されます。

* * パス *
+
共有されている既存のフォルダ、 qtree 、またはボリュームの完全なパス名が表示されます。パスの区切り文字には、スラッシュまたはバックスラッシュを使用できますが、 ONTAP では、いずれの区切り文字もスラッシュとして表示されます。

* * ホームディレクトリ *
+
ホームディレクトリ共有の名前が表示されます。

* * コメント *
+
共有の追加の説明がある場合に表示されます。

* * 共有の継続的な可用性 *
+
共有が継続的可用性に対して有効になっているかどうかが表示されます。System Manager 9.6 以降では、 FlexGroup ボリュームの継続的可用性がサポートされます。





=== 詳細領域

共有リストの下の領域には、共有プロパティと各共有のアクセス権が表示されます。

* * プロパティ *
+
** 名前
+
共有の名前が表示されます。

** oplock ステータス
+
共有で便宜的ロック（ oplock ）を使用するかどうかを示します。

** 参照可能
+
Windows クライアントから共有を参照できるかどうかを示します。

** Snapshot を表示します
+
クライアントで Snapshot コピーを表示できるかどうかを示します。

** 共有の継続的な可用性
+
共有が継続的に利用できるように有効になっているか無効になっているかを示します。System Manager 9.6 以降では、 FlexGroup ボリュームの継続的可用性がサポートされます。

** ABE ：アクセスベースの列挙
+
共有で Access-Based Enumeration が有効になっているかどうかを示します。

** BranchCache
+
共有で BranchCache が有効になっているかどうかを示します。

** SMB 暗号化
+
SMB 3.0 を使用したデータ暗号化が Storage Virtual Machine （ SVM ）レベルまたは共有レベルで有効になっているかどうかを示します。SMB 暗号化が SVM レベルで有効になっている場合は、すべての共有に SMB 暗号化が適用され、（ SVM レベルで）「有効」という値が表示されます。

** 以前のバージョン
+
クライアントで以前のバージョンを表示してリストアできるかどうかを指定します。



* * 共有アクセス制御 *
+
共有のドメインユーザ、ドメイングループ、ローカルユーザ、およびローカルグループのアクセス権が表示されます。



* 関連情報 *

xref:task_setting_up_cifs.adoc[CIFSノセツトアツフ]
