---
permalink: online-help-96-97/concept_jobs.html 
sidebar: sidebar 
keywords: jobs, system, manager, job, task, display, information, progress, asynchronous, volume, operation, copy, move, mirror, data, queue, cluster, administrator, online, help 
summary: System Manager を使用して、ジョブ情報の表示やジョブの進捗状況の監視などのジョブタスクを管理できます。 
---
= System Manager - ONTAP 9.7 以前を使用してジョブを管理します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP System Manager クラシック（ ONTAP 9.7 以前で使用可能）を使用して、ジョブ情報の表示やジョブの進捗状況の監視などのジョブタスクを管理できます。



== ジョブ

_ Jobs _ は非同期タスクであり、データのコピー、移動、ミラーリングなど、通常は長時間実行されるボリューム処理です。ジョブはジョブキューに配置され、リソースが利用可能になると実行されます。クラスタ管理者は、ジョブ管理に関連するすべてのタスクを実行できます。

ジョブは、次のいずれかのカテゴリに分類されます。

* サーバ関連ジョブは、特定のノードで実行される管理フレームワークによってキューに入れられます。
* a_cluster-affilied_job は、クラスタ内の任意のノードで実行される管理フレームワークによってキューに入れられます。
* a_private_job はノードに固有で、レプリケートされたデータベース（ RDB ）またはその他のクラスタメカニズムを使用しません。
+
プライベートジョブの管理用コマンドを実行するには、 advanced 権限レベル以上が必要です。



ジョブは、次の方法で管理できます。

* 次のようなジョブ情報を表示する
+
** ジョブはノード単位で実行されます
** クラスタ関連ジョブ
** 完了したジョブ
** ジョブ履歴


* ジョブの進捗状況を監視しています
* ジョブマネージャの初期化状態に関する情報を表示する


完了したジョブの結果は、イベントログで確認できます。



== ジョブウィンドウ

ジョブウィンドウを使用して、ジョブ情報の表示やジョブの進捗状況の監視などのジョブタスクを管理できます。



=== コマンドボタン

* * 更新 *
+
ウィンドウ内の情報を更新します。





=== タブ

* * 現在のジョブ *
+
このタブには、進行中のジョブタスクに関する情報が表示されます。

* * ジョブ履歴 *
+
このタブには、すべてのジョブに関する情報が表示されます。





=== ジョブリスト

* * ジョブ ID *
+
ジョブの ID を表示します。

* * 開始時間 *
+
ジョブの開始時間を表示します。

* * ジョブ名 *
+
ジョブの名前を表示します。

* * ノード *
+
ノードの名前が表示されます。

* * 状態 *
+
ジョブの状態を表示します。

* * ジョブ概要 *
+
ジョブの概要を表示します。

* * 進捗状況 *
+
ジョブの状態を表示します。

* * スケジュール名 *
+
スケジュールの名前が表示されます。


