---
permalink: online-help-96-97/reference_disks_window.html 
sidebar: sidebar 
keywords: command, button, disk, window, inventory, detail, online, help 
summary: ディスクウィンドウを使用すると、ストレージシステム内のすべてのディスクを表示できます。 
---
= System Manager のディスクウィンドウ - ONTAP 9.7 以前
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP システムマネージャクラシック（ONTAP 9.7以前で使用可能）のディスクウィンドウを使用して、ストレージシステム内のすべてのディスクを表示できます。



== コマンドボタン

* * 割り当て *
+
ディスクの所有権をノードに割り当てまたは再割り当てします。

+
このボタンは、選択したディスクのコンテナのタイプが「未割り当て」、「スペア」、または「共有」の場合にのみ有効になります。

* * ゼロスペア *
+
スペアディスクおよびスペアアレイ LUN のすべてのデータを消去してフォーマットします。

* * 更新 *
+
ウィンドウ内の情報を更新します。





== タブ



== まとめ

スペアディスクや割り当てられているディスクのサイズなど、クラスタ内のディスクに関する詳細な情報が表示されます。このタブには、 HDD のスペアディスク、アグリゲート、およびルートアグリゲートに関する情報と、キャッシュディスク（ SSD ）のスペアディスク、ストレージプールのディスク、アグリゲート、 Flash Pool アグリゲート、およびルートアグリゲートに関する情報も表示されます。

オールフラッシュで最適化されたシステムの場合は、 HDD パネルは表示されません。

詳細パネルには追加情報、パーティショニングされたスペアディスクとパーティショニングされていないスペアディスク（ディスクタイプ、ノード、ディスクサイズ、 rpm 、チェックサム、 使用可能なディスク数とスペア容量）が表形式で表示されます。



== 在庫

* * 名前 *
+
ディスクの名前が表示されます。

* * コンテナタイプ *
+
ディスクの用途が表示されます。「アグリゲート」、「切断」、「外部」、「ラベルのメンテナンス」、「メンテナンス」、 共有、スペア、未割り当て、ボリューム、不明、 サポート対象外です。

* * パーティションタイプ *
+
ディスクのパーティションタイプが表示されます。

* * ノード名 *
+
アグリゲートが含まれるノードの名前が表示されます。

+
このフィールドは、クラスタレベルでのみ使用できます。

* * 家の所有者 *
+
このディスクが割り当てられているホームノードの名前が表示されます。

* * 現在の所有者 *
+
このディスクを現在所有しているノードの名前が表示されます。

* * ルート所有者 *
+
このディスクのルートパーティションを現在所有しているノードの名前が表示されます。

* * データ所有者 *
+
このディスクのデータパーティションを現在所有しているノードの名前が表示されます。

* * Data1 所有者 *
+
ディスクの data1 パーティションを現在所有しているノードの名前が表示されます。

* * Data2所有者*
+
ディスクのdata2パーティションを現在所有しているノードの名前が表示されます。

* * ストレージプール *
+
ディスクが関連付けられているストレージプールの名前が表示されます。

* * タイプ *
+
ディスクのタイプが表示されます。

* * ファームウェアバージョン *
+
ディスクのファームウェアバージョンが表示されます。

* * モデル *
+
ディスクのモデルが表示されます。

* * RPM *
+
オプションを使用すると、ディスクドライブの実効速度が表示されます。 `raid.mix.hdd.rpm.capacity` が有効になっており、オプションを指定するとディスクドライブの実際の速度が表示されます。 `raid.mix.hdd.rpm.capacity` は無効です。

+
このフィールドは SSD には適用されません。

* * 有効なサイズ *
+
ディスク上で使用可能なスペースが表示されます。

* * 物理スペース *
+
ディスクの合計物理スペースが表示されます。

* * 棚 *
+
物理ディスクが配置されているシェルフが表示されます。

+
このフィールドはデフォルトでは非表示になっています。

* * 湾 *
+
物理ディスクのシェルフ内のベイが表示されます。

+
このフィールドはデフォルトでは非表示になっています。

* * プール *
+
選択したディスクが割り当てられているプールの名前が表示されます。

+
このフィールドはデフォルトでは非表示になっています。

* * チェックサム *
+
チェックサムのタイプが表示されます。

+
このフィールドはデフォルトでは非表示になっています。

* * キャリア ID *
+
指定したマルチディスクキャリア内のディスクに関する情報を示します。ID の値は 64 ビットです。

+
このフィールドはデフォルトでは非表示になっています。





== インベントリの詳細領域

インベントリタブの下の領域には、アグリゲートまたはボリュームに関する情報（該当する場合）、ベンダー ID 、初期化の状態（割合）、ディスクのシリアル番号、障害が発生したディスクのエラーの詳細など、選択したディスクに関する詳細情報が表示されます。共有ディスクの場合、インベントリの詳細領域には、ルートアグリゲートとルート以外のアグリゲートを含むすべてのアグリゲートの名前が表示されます。

* 関連情報 *

xref:task_viewing_disk_information.adoc[ディスク情報を表示しています]
