---
permalink: online-help-96-97/reference_trace_file_access_window.html 
sidebar: sidebar 
keywords: system, manager, commnd, button, trace, file, access, window, online, help, cif, entry, list 
summary: System Manager 9.6 以降では、 CIFS または NFS プロトコルを使用して SVM のファイルと共有へのアクセスに問題がある場合に、ファイルアクセスのトレースウィンドウを使用して問題を診断できます。 
---
= System Manager の Trace File Access ウィンドウ
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP System Manager 9.6 以降では、 CIFS または NFS プロトコルを使用して SVM のファイルと共有へのアクセスで問題が発生した場合に、ファイルアクセスのトレースウィンドウを使用して問題を診断できます。



== コマンドボタン

* * 続行 *
+
選択した SVM のファイルアクセスのトレースを設定して開始します。

* * プロトコル *
+
選択した SVM のファイルと共有へのアクセスに使用しているプロトコルとして、 CIFS または NFS を選択できます。

* * 詳細オプションアイコン *
+
追加の詳細を指定してトレースの範囲を絞り込むことができます。

* * トレース結果に表示 *
+
拒否されたファイルアクセス要求のみをトレース結果に表示するか、すべてのファイルアクセス要求（成功した要求と拒否された要求）を表示するかを、 [ 詳細オプション ] ダイアログボックスで指定できます。

* * トレースを開始 *
+
トレースを開始できます。結果には、トレースを開始してから 60 分以内に送信されたファイルアクセス要求で発生した問題が表示されます。

* * トレースを停止 *
+
トレースを停止できます。

* * 権限の表示 *
+
権限を表示できます。CIFS プロトコルを使用している場合は、有効なファイル権限と共有権限を表示できます。NFS プロトコルを使用している場合は、有効なファイル権限を表示できます。

* * クリップボードにコピー *
+
結果テーブルをクリップボードにコピーできます。

* * トレース結果のエクスポート *
+
トレース結果をカンマ区切り値（ .csv ）形式でファイルにエクスポートできます。





== 入力フィールド

* * ユーザー名 *
+
トレースするファイルアクセス要求エラーが返されたユーザの名前を入力します。

* * トレース結果の検索 *
+
検索結果に特定の情報を入力し、 * Enter * をクリックします。

* * クライアント IP アドレス *
+
[ 詳細オプション ] ダイアログボックスでは、クライアントの IP アドレスを追加の詳細として指定して、トレースの範囲を絞り込むことができます。

* * ファイル *
+
[ 詳細オプション ] ダイアログボックスでは、追加の詳細としてアクセスするファイルまたはファイルパスを指定して、トレースの範囲を絞り込むことができます。



.CIFSプロトコルのトレース結果リスト
CIFS プロトコルを指定した場合、指定したパラメータに基づいて次のデータがトレース結果リストに表示されます。このデータは新しいものから順番に表示されます。トレースを停止しても、別のトレースを開始するまで結果はリストに残ります。

* share ：成功したかどうかに関係なく、システムがアクセスを試みた共有の名前。
* Path ：成功したかどうかに関係なく、システムがアクセスを試みたファイルのファイルパス。
* クライアント IP アドレス：アクセス要求が開始されたクライアントの IP アドレス。
* 理由：ファイルまたは共有へのアクセスの試行が成功または失敗した理由。
+
[NOTE]
====
「 Synchronize 」、「 Read Control 」、「 Read Attributes 」、「 Execute 」、「 Read EA 」に対してアクセスが許可されていないというメッセージがトレース結果に表示される場合、 「 Write 」または「 Read 」は、表示されている一連の権限に必要なアクセスが付与されていないことを示します。権限の実際のステータスを表示するには、表示されたリンクから権限を表示する必要があります。

====


.NFSプロトコルのトレース結果リスト
NFSプロトコルを指定すると、指定したパラメータに基づいて次のデータがトレース結果リストに表示されます。このデータは新しいものから順番に表示されます。トレースを停止しても、別のトレースを開始するまで結果はリストに残ります。

* Path ：成功したかどうかに関係なく、システムがアクセスを試みたファイルのファイルパス。
* クライアント IP アドレス：アクセス要求が開始されたクライアントの IP アドレス。
* 理由：ファイルまたは共有へのアクセスの試行が成功または失敗した理由。
+
[NOTE]
====
「 Synchronize 」、「 Read Control 」、「 Read Attributes 」、「 Execute 」、「 Read EA 」に対してアクセスが許可されていないというメッセージがトレース結果に表示される場合、 「 Write 」または「 Read 」は、表示されている一連の権限に必要なアクセスが付与されていないことを示します。権限の実際のステータスを表示するには、表示されたリンクから権限を表示する必要があります。

====


* 関連情報 *

https://docs.netapp.com/us-en/ontap/smb-admin/index.html["SMB / CIFS の管理"]

xref:../nas-multiprotocol-config/index.html[SMB / CIFS および NFS のマルチプロトコル構成]
