---
permalink: online-help-96-97/reference_storage_tiers_window.html 
sidebar: sidebar 
keywords: online, help, storage, tier, window, command, button 
summary: ストレージ階層ウィンドウを使用すると、クラスタ全体のスペースの詳細を表示したり、アグリゲートの詳細を追加および表示したりできます。 
---
= System Manager のストレージ階層ウィンドウ - ONTAP 9.7 以前
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP System Manager クラシック（ ONTAP 9.7 およびイヤエで使用可能）のストレージ階層ウィンドウを使用して、クラスタ全体のスペースの詳細を表示したり、アグリゲートの詳細を追加および表示したりできます。

内部階層パネル、またはパフォーマンス階層パネル：クラスタにオールフラッシュ（オール SSD ）アグリゲートがある場合は、すべてのアグリゲートの合計サイズ、クラスタ内のアグリゲートで使用されているスペース、 およびクラスタ内の使用可能なスペースが表示されます。

クラウド階層パネルには、クラスタ内のライセンスで許可されているクラウド階層の総数、クラスタで使用されているライセンススペース、およびクラスタで使用可能なライセンススペースが表示されます。クラウド階層パネルには、ライセンスのない、使用中のクラウド容量も表示されます。

アグリゲートパネルには、アグリゲートの合計スペース、使用済みスペース、および使用可能なスペースの詳細がアグリゲートのタイプ別に表示されます。アクセス頻度の低いコールドデータがソリッドステートドライブ（ SSD ）またはオールフラッシュ FAS アグリゲートにある場合は、その使用スペースも表示されます。アグリゲートを選択してアグリゲート関連の操作を実行できます。



== コマンドボタン

* * アグリゲートの追加 *
+
アグリゲートを作成できます。

* * アクション *
+
次のオプションが用意されています。

+
** * ステータスを * に変更します
+
選択したアグリゲートのステータスを次のいずれかに変更します。

+
*** * オンライン *
+
このアグリゲートに含まれるボリュームへの読み取りおよび書き込みアクセスが許可されます。

*** * オフライン *
+
読み取りおよび書き込みアクセスが許可されていません。

*** * 制限 *
+
パリティの再構築などの一部の処理は許可されますが、データアクセスは許可されません。



** * 容量を追加 *
+
既存のアグリゲートに容量（ HDD または SSD ）を追加できます。

** * キャッシュを追加 *
+
既存の HDD アグリゲートまたは Flash Pool アグリゲートにキャッシュディスク（ SSD ）を追加できます。

+
FabricPool 対応アグリゲートにはキャッシュディスクを追加できません。

+
このオプションは、オールフラッシュで最適化されたノードを含むクラスタでは使用できません。

** * ミラー *
+
アグリゲートをミラーリングできます。

** * ボリューム移動 *
+
FlexVol ボリュームを移動できます。







== 詳細領域

アグリゲート名をクリックすると、そのアグリゲートに関する詳細情報を確認できます。

* * 概要タブ *
+
選択したアグリゲートに関する詳細な情報が表示されます。これには、アグリゲートのスペース割り当て、アグリゲートのスペース削減、アグリゲートのパフォーマンスなどの情報が含まれます。

* * ディスク情報タブ *
+
選択したアグリゲートのディスクレイアウト情報が表示されます。

* * Volumes （ボリューム）タブ *
+
アグリゲート上の合計ボリューム数、合計アグリゲートスペース、およびアグリゲートにコミット済みのスペースについての詳細が表示されます。

* * パフォーマンスタブ *
+
スループットや IOPS など、アグリゲートのパフォーマンス指標のグラフが表示されます。スループットや IOPS についての読み取り、書き込み、および合計転送回数のパフォーマンス指標データが、 SSD と HDD で別々に表示されます。

+
クライアントのタイムゾーンやクラスタのタイムゾーンを変更すると、パフォーマンス指標のグラフも変わります。クライアントまたはクラスタのタイムゾーンを変更した場合、最新のグラフを表示するにはブラウザの表示を更新してください。



* 関連情報 *

xref:task_adding_cloud_tier.adoc[クラウド階層を追加しています]

xref:task_attaching_aggregate_to_cloud_tier.adoc[クラウド階層にアグリゲートを接続しています]

xref:task_deleting_cloud_tier.adoc[クラウド階層を削除しています]

xref:task_editing_cloud_tier.adoc[クラウド階層を編集しています]

xref:task_provisioning_storage_through_aggregates.adoc[アグリゲートを使用したストレージのプロビジョニング]

xref:task_deleting_aggregates.adoc[アグリゲートを削除中]

xref:task_editing_aggregates.adoc[アグリゲートの編集]
