---
permalink: online-help-96-97/reference_dashboard_window.html 
sidebar: sidebar 
keywords: system, manager, dashboard, window, multiple, panel, online, help 
summary: ダッシュボードウィンドウには、システムとそのパフォーマンスについての累積情報をわかりやすく表示した複数のパネルがあります。 
---
= System Manager - ONTAP 9.7 以前のダッシュボードウィンドウ
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP System Manager クラシックのダッシュボードウィンドウ（ ONTAP 9.7 以前で使用可能）には、複数のパネルがあり、システムとそのパフォーマンスについての累積情報をわかりやすく表示できます。

Dashboard window では、重要なアラートと通知、アグリゲートおよびボリュームの効率性と容量、クラスタで使用可能なノード、 high-availability （ HA ）ペアを構成するノードのステータス、最もアクティブなアプリケーションとオブジェクトに関する情報を確認できます。 およびクラスタまたはノードのパフォーマンス指標。

* * アラートと通知 *
+
すべてのアラートは赤色で表示されます。これには、緊急 EMS イベント、オフラインのノードの詳細、破損ディスクの詳細、リスクが「高」のライセンス使用権、オフラインのネットワークポートの詳細などの情報が含まれます。すべての通知が黄色で表示されます。これには、クラスタレベルでの過去 24 時間のヘルスモニタ通知、中レベルのライセンス使用権、未割り当てのディスクの詳細、移行された LIF の数、失敗したボリューム移動処理などの情報が含まれます。 過去 24 時間に管理操作を必要としたボリューム移動処理

+
[Alerts and Notifications] パネルには、最大 3 つのアラートと通知が表示されます。これを超えると、 [View-All] リンクが表示されます。アラートおよび通知に関する詳細情報を表示するには、「すべて表示」リンクをクリックします。

+
[Alerts and Notifications] パネルの更新間隔は 1 分です。

* * クラスタの概要 *
+
容量の上限に近づいているアグリゲートやボリューム、クラスタやノードのストレージ効率、および上位のボリュームの保護の詳細が表示されます。

+
容量タブには、容量の上限に近づいている上位のオンラインアグリゲートが使用済みスペースの降順で表示されます。

+
容量タブには、使用容量が最も多いボリュームの数へのリンクが表示されます。この値は、ボリュームが使用容量を超えている場合に入力します。また、クラスタ内で使用可能なアクセス頻度の低いコールドデータの量も表示されます。

+
効率化タブには、クラスタまたはノードについての Storage Efficiency による削減効果が表示されます。使用済み論理スペースの合計、使用済み物理スペースの合計、および削減量の合計を確認できます。クラスタまたは特定のノードを選択して、その Storage Efficiency による削減効果を表示できます。System Manager 9.5 では、使用済み論理スペースの合計、使用済み物理スペースの合計、および削減量の合計の値に Snapshot コピーに使用されているスペースは _not_included です。ただし、 System Manager 9.6 以降では、使用済み論理スペースの合計、使用済み物理スペースの合計、および削減量の合計の値に Snapshot コピーに使用されているスペースが含まれます。

+
クラスタ概要パネルの更新間隔は 15 分です。

+
Protection タブには、保護関係が定義されていないクラスタ全体のボリュームに関する情報が表示されます。次の条件に該当する FlexVol ボリュームと FlexGroup ボリュームのみが表示されます。

+
** ボリュームが RW ボリュームでオンラインになっている。
** ボリュームを含むアグリゲートがオンラインになっている。
** ボリュームで保護関係が設定されているがまだ初期化されていない。
ボリュームウィンドウに移動すると、保護関係が定義されていないボリュームを確認できます。


+
Protection タブには、保護関係が定義されていないボリュームの数が最も多い上位 5 つの SVM も表示されます。

* * ノード * ：
+
クラスタで使用可能なノードの数と名前、および HA ペアを構成するノードのステータスが表示されます。HA ペアのノードのステータスは、表示されたノードにカーソルを合わせると表示されます。

+
Nodes リンクを使用すると、すべてのノードに関する詳細を確認できます。さらに、表示されたノードをクリックすると、そのノードのモデルに関する情報が表示され、ノードで使用可能なアグリゲート、ストレージプール、シェルフ、およびディスクの数を確認できます。ノードを管理するには、 Manage Nodes リンクを使用します。HA ペアのノードは、 Manage HA リンクを使用して管理できます。

+
Nodes パネルの更新間隔は 15 分です。

* * アプリケーションとオブジェクト *
+
アプリケーションとオブジェクトパネルを使用して、クラスタ内のアプリケーション、クライアント、およびファイルに関する情報を表示できます。

+
Applications タブには、クラスタの上位 5 つのアプリケーションに関する情報が表示されます。IOPS とレイテンシまたは容量の低い順または高い順に上位 5 つのアプリケーションを表示できます。

+
アプリケーションに関する詳細情報を表示するには、特定の棒グラフをクリックする必要があります。容量については、合計スペース、使用済みスペース、および使用可能なスペースが表示され、 IOPS については IOPS の詳細が表示され、レイテンシについてはレイテンシの詳細が表示されます。

+
[ * 詳細の表示 * ] をクリックすると、特定のアプリケーションの [ アプリケーション ] ウィンドウを開くことができます。

+
Objects タブには、クラスタ内の上位 5 つのアクティブなクライアントとファイルに関する情報が表示されます。IOPS またはスループットを基準に、上位 5 つのアクティブなクライアントとファイルを表示できます。

+
[NOTE]
====
この情報は、 CIFS プロトコルと NFS プロトコルについてのみ表示されます。

====
+
アプリケーションとオブジェクトパネルの更新間隔は 1 分です。

* * パフォーマンス *
+
レイテンシ、 IOPS 、およびスループットを基準に、クラスタの平均パフォーマンス指標、読み取りパフォーマンス指標、書き込みパフォーマンス指標が表示されます。平均パフォーマンス指標はデフォルトで表示されます。読み取りまたは書き込みをクリックすると、読み取りパフォーマンス指標または書き込みパフォーマンス指標をそれぞれ表示できます。クラスタまたはノードのパフォーマンス指標を表示できます。

+
ONTAP からクラスタのパフォーマンス情報を取得できない場合は、対応するグラフは参照できません。その場合、 System Manager で特定のエラーメッセージが表示されます。

+
パフォーマンスパネルのグラフの更新間隔は 15 秒です。





== ダッシュボードを使用したクラスタの監視

System Manager のダッシュボードを使用すると、クラスタの健常性とパフォーマンスを監視できます。また、ハードウェアやストレージ構成の問題を特定することもできます。

.手順
. ダッシュボード * タブをクリックすると、ヘルス / パフォーマンスダッシュボードパネルが表示されます。

