---
permalink: online-help-96-97/reference_svm_dashboard_window.html 
sidebar: sidebar 
keywords: svm, dashboard, detail, online, help 
summary: ダッシュボードは、 Storage Virtual Machine （ SVM ）とそのパフォーマンスについて、履歴を含めた情報をわかりやすく表示します。ダッシュボードウィンドウでは、設定されているプロトコル、容量の上限に近づいているボリューム、パフォーマンスなど、 SVM に関連する重要な情報を確認できます。 
---
= System Manager の ONTAP ダッシュボードウィンドウ - 9.7 以前
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP System Manager クラシック（ ONTAP 9.7 以前で使用可能）のダッシュボードウィンドウでは、 Storage Virtual Machine （ SVM ）とそのパフォーマンスについての累積情報がわかりやすく表示されます。ダッシュボードウィンドウでは、設定されているプロトコル、容量の上限に近づいているボリューム、パフォーマンスなど、 SVM に関連する重要な情報を確認できます。



== SVM の詳細

このウィンドウでは、 SVM の詳細が各パネルに表示されます。これには、プロトコルステータスパネル、容量の上限に近づいているボリュームパネル、アプリケーションパネル、パフォーマンスパネルなどがあります。

* * プロトコルステータス *
+
SVM 用に設定されているプロトコルの概要が表示されます。プロトコル名をクリックすると設定を確認できます。

+
プロトコルが設定されていない場合や SVM 用のプロトコルのライセンスがない場合は、プロトコル名をクリックして、プロトコルを設定したりプロトコルのライセンスを追加したりできます。

* * 容量の上限に近いボリューム *
+
容量の使用率が 80% 以上になっていてすぐに対処が必要なボリュームの詳細情報が表示されます。

* * アプリケーション *
+
SVM の上位 5 つのアプリケーションに関する情報が表示されます。IOPS または容量の低い順または高い順に上位 5 つのアプリケーションを表示できます。アプリケーションに関する詳細情報を表示するには、特定の棒グラフをクリックする必要があります。容量の場合は、合計スペース、使用済みスペース、および使用可能なスペースが表示され、 IOPS の場合は IOPS の詳細が表示されます。L2/L3 アプリケーションについては、レイテンシも表示されます。

+
[NOTE]
====
アプリケーションウィンドウに表示される使用サイズが、 CLI で使用されているサイズと一致しません。

====
+
[ * 詳細の表示 * ] をクリックすると、特定のアプリケーションの [ アプリケーション ] ウィンドウを開くことができます。すべてのアプリケーションの表示 * をクリックすると、 SVM のすべてのアプリケーションを表示できます。

+
アプリケーションパネルの更新間隔は 1 分です。

* * SVM パフォーマンス *
+
レイテンシや IOPS など、 SVM のプロトコルのパフォーマンス指標が表示されます。

+
ONTAP から SVM のパフォーマンス情報を取得できない場合は、対応するグラフは参照できません。その場合、 System Manager で特定のエラーメッセージが表示されます。

+
SVM の Performance パネルの更新間隔は 15 秒です。


