---
permalink: online-help-96-97/reference_luns_window.html 
sidebar: sidebar 
keywords: online, help, lun, management, window, command, button, initiator, portset, group, online, help 
summary: LUN ウィンドウを使用して、 LUN の作成と管理、および LUN に関する情報の表示を行うことができます。イニシエータグループやイニシエータ ID を追加、編集、削除することもできます。 
---
= System Manager の LUNs ウィンドウ - ONTAP 9.7 以前
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP System Manager クラシック（ ONTAP 9.7 以前で使用可能）の LUNs ウィンドウを使用して、 LUN の作成と管理、および LUN に関する情報の表示を行うことができます。イニシエータグループやイニシエータ ID を追加、編集、削除することもできます。



== [LUN Management] タブをクリックします

このタブでは、 LUN の作成、クローニング、削除、移動、およびそれらの設定の編集を行うことができます。また、 LUN をストレージ QoS ポリシーグループに割り当てることもできます。



== コマンドボタン

* * 作成 * 。
+
LUN 作成ウィザードを開きます。このウィザードで、 LUN を作成できます。

+
既存の LUN が格納されていない AFF プラットフォーム上のクラスタでは、 FC SAN 向けに最適化された LUN の作成ダイアログボックスが開き、 FC SAN 向けに最適化された LUN を設定できます。

* * クローン *
+
Clone LUN ダイアログ・ボックスを開きますこのダイアログ・ボックスで ' 選択した LUN のクローンを作成できます

* * 編集 * 。
+
LUN の編集ダイアログボックスを開きます。このダイアログボックスで、選択した LUN の設定を編集できます。

* * 削除 *
+
選択した LUN を削除します。

* * ステータス *
+
選択した LUN のステータスをオンラインまたはオフラインに変更できます。

* * 移動 *
+
LUN の移動ダイアログボックスを開きます。このダイアログボックスで、選択した LUN を、同じ Storage Virtual Machine （ SVM ）内の新しいボリュームまたは既存のボリュームまたは qtree に移動できます。

* * ストレージ QoS *
+
Quality of Service の詳細ダイアログボックスを開きます。このダイアログボックスで、新規または既存のポリシーグループに 1 つ以上の LUN を割り当てることができます。

* * 更新 *
+
ウィンドウ内の情報を更新します。





== LUN リスト

* * 名前 *
+
LUN の名前が表示されます。

* * SVM *
+
LUN が作成された Storage Virtual Machine （ SVM ）の名前が表示されます。

* * コンテナパス *
+
LUN が含まれているファイルシステム（ボリュームまたは qtree ）の名前が表示されます。

* * スペース予約 *
+
スペースリザベーションが有効になっているかどうかを示します。

* * 利用可能なサイズ *
+
LUN で使用可能なスペースが表示されます。

* * 合計サイズ *
+
LUN の合計スペースが表示されます。

* * % 使用済み *
+
使用中の合計スペース（割合）が表示されます。

* * タイプ *
+
LUN タイプを示します。

* * ステータス *
+
LUN のステータスを示します。

* * ポリシーグループ *
+
LUN が割り当てられているストレージ QoS ポリシーグループの名前が表示されます。デフォルトでは、この列は表示されません。

* * アプリケーション *
+
LUN に割り当てられているアプリケーションの名前が表示されます。

* * 概要 *
+
LUN の概要が表示されます。





== 詳細領域

LUN リストの下の領域には、選択した LUN に関する詳細が表示されます。

* * 詳細タブ *
+
LUN に関する詳細が表示されます。これには、シリアル番号、クローンかどうか、概要、割り当てられているポリシーグループ、ポリシーグループの最小スループット、ポリシーグループの最大スループット、 LUN の移動処理の詳細などの情報が含まれます。 LUN に割り当てられているアプリケーションを特定します。選択した LUN に関連付けられているイニシエータグループとイニシエータに関する詳細も確認できます。

* * パフォーマンスタブ *
+
データ速度、 IOPS 、応答時間など、 LUN のパフォーマンス指標のグラフが表示されます。

+
クライアントのタイムゾーンやクラスタのタイムゾーンを変更すると、パフォーマンス指標のグラフも変わります。最新のグラフを表示するには、ブラウザの表示を更新します。





== イニシエータグループタブ

イニシエータグループやイニシエータ ID の作成、削除、およびそれらの設定の編集を行うことができます。



== コマンドボタン

* * 作成 * 。
+
イニシエータグループの作成ダイアログボックスを開きます。このダイアログボックスで、イニシエータグループを作成して、特定の LUN へのホストアクセスを制御できます。

* * 編集 * 。
+
イニシエータグループの編集ダイアログボックスを開きます。このダイアログボックスで、選択したイニシエータグループの設定を編集できます。

* * 削除 *
+
選択したイニシエータグループを削除します。

* * 更新 *
+
ウィンドウ内の情報を更新します。





== イニシエータグループのリスト

* * 名前 *
+
イニシエータグループの名前が表示されます。

* * タイプ *
+
イニシエータグループでサポートされるプロトコルのタイプを示します。サポートされるプロトコルは、 iSCSI 、 FC / FCoE 、 Mixed （ iSCSI および FC / FCoE ）です。

* * オペレーティング・システム * ：
+
イニシエータグループのオペレーティングシステムを示します。

* * ポートセット *
+
イニシエータグループに関連付けられているポートセットが表示されます。

* * イニシエータ数 *
+
イニシエータグループに追加されているイニシエータの数が表示されます。





== 詳細領域

イニシエータグループリストの下の領域には、選択したイニシエータグループに追加されているイニシエータと、イニシエータグループにマッピングされている LUN に関する詳細が表示されます。



== [ ポートセット ] タブ

ポートセットの作成、削除、およびそれらの設定の編集を行うことができます。



== コマンドボタン

* * 作成 * 。
+
ポートセットの作成ダイアログボックスを開きます。このダイアログボックスで、ポートセットを作成して LUN へのアクセスを制限できます。

* * 編集 * 。
+
ポートセットの編集ダイアログボックスを開きます。このダイアログボックスで、ポートセットに関連付けるネットワークインターフェイスを選択できます。

* * 削除 *
+
選択したポートセットを削除します。

* * 更新 *
+
ウィンドウ内の情報を更新します。





== ポートセットのリスト

* * ポートセット名 *
+
ポートセットの名前が表示されます。

* * タイプ *
+
ポートセットでサポートされるプロトコルのタイプを示します。サポートされるプロトコルは、 iSCSI 、 FC / FCoE 、 Mixed （ iSCSI および FC / FCoE ）です。

* * インターフェイス数 *
+
ポートセットに関連付けられているネットワークインターフェイスの数が表示されます。

* * イニシエータグループ数 *
+
ポートセットに関連付けられているイニシエータグループの数が表示されます。





== 詳細領域

ポートセットリストの下の領域には、選択したポートセットに関連付けられているネットワークインターフェイスとイニシエータグループに関する詳細が表示されます。

* 関連情報 *

xref:task_creating_luns.adoc[LUN を作成しています]

xref:task_deleting_luns.adoc[LUN を削除しています]

xref:task_creating_initiator_groups.adoc[igroup を作成しています]

xref:task_editing_luns.adoc[LUN を編集しています]

xref:task_editing_initiator_groups.adoc[igroup を編集しています]

xref:task_editing_initiators.adoc[イニシエータを編集中]

xref:task_bringing_luns_online.adoc[LUN をオンラインにしています]

xref:task_taking_luns_offline.adoc[LUN をオフラインにしています]

xref:task_cloning_luns.adoc[LUN のクローニング]
