---
permalink: online-help-96-97/reference_svm_window.html 
sidebar: sidebar 
keywords: storage, virtual, machine, window, svm, online, help, command, button, peer 
summary: Storage Virtual Machines （ SVM ）ウィンドウを使用して、 Storage Virtual Machine （ SVM ）を管理したりその情報を表示したりできます。 
---
= ONTAP 9.7 以前の場合は、 System Manager の Storage Virtual Machine ウィンドウが開きます
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Storage Virtual Machine （ SVM ）を管理して、 Storage Virtual Machine に関する情報を表示するには、 ONTAP System Manger クラシック（ ONTAP 9.7 以前で使用可能）の Storage Virtual Machines ウィンドウを使用します。

ディザスタリカバリ（ DR ）用に設定された SVM は、 System Manager で管理（作成、削除、開始、または停止）できません。また、ディザスタリカバリ用に設定された SVM に関連付けられたストレージオブジェクトも、アプリケーションインターフェイスで表示できません。



== コマンドボタン

* * 作成 * 。
+
Storage Virtual Machine （ SVM ）セットアップウィザードを開きます。このウィザードで、新しい SVM を作成できます。

* * 編集 * 。
+
Storage Virtual Machine の編集ダイアログボックスを開きます。このダイアログボックスで、選択した SVM のプロパティを変更できます。選択した SVM のネームサービススイッチ、ネームマッピングスイッチ、アグリゲートリストなどを変更できます。

* * 削除 *
+
選択した SVM を削除します。

* * 開始 *
+
選択した SVM を起動します。

* * 停止 *
+
選択した SVM を停止します。

* * SVM 設定 *
+
選択した SVM のストレージ、ポリシー、および設定を管理します。

* * 保護オペレーション *
+
次のオプションが用意されています。

+
** * 初期化 *
+
SVM 関係を初期化して、ソース SVM からデスティネーション SVM へのベースライン転送を実行できます。

** * アップデート *
+
ソース SVM からデスティネーション SVM にデータを更新できます。

** * デスティネーション SVM をアクティブ化 *
+
デスティネーション SVM をアクティブ化できます。

** * ソース SVM から再同期 *
+
解除した関係の再同期を開始できます。

** * デスティネーション SVM から再同期（逆再同期） *
+
デスティネーション SVM からソース SVM に関係を再同期できます。

** * ソース SVM を再アクティブ化 *
+
ソース SVM を再アクティブ化できます。



* * 更新 *
+
ウィンドウ内の情報を更新します。

* * ファイルアクセスのトレース *
+
選択した SVM にあるファイルや共有について、指定したユーザ名でアクセスできるかどうかをトレースできます。





== SVM リスト

SVM リストには、各 SVM の名前と、その SVM で使用可能なプロトコルが表示されます。

System Manager で表示できるのはデータ SVM だけです。

* * 名前 *
+
SVMの名前が表示されます。

* * 状態 *
+
SVM の状態が表示されます。これには、実行中、開始中、停止中、停止中などの情報が含まれます。

* * サブタイプ *
+
SVM のサブタイプが表示されます。サブタイプは次のいずれかになります。

+
** デフォルト
+
SVM がデータ提供用 SVM であることを示します。

** DP デスティネーション
+
SVM がディザスタリカバリ用に設定されていることを示します。

** sync-source （同期元）
+
SVM が MetroCluster 設定のプライマリサイト内にあることを示します。

** 同期先
+
SVM が MetroCluster 構成のセカンダリサイト内にあることを示します。



* * 許可されたプロトコル *
+
各 SVM で許可されているプロトコル（ CIFS 、 NFS など）が表示されます。

* * IPspace *
+
関連付けられている SVM の IPspace が表示されます。

* * ボリュームタイプ *
+
各 SVM で許可されているボリュームのタイプ（ FlexVol など）が表示されます。

* * 保護されている *
+
SVM が保護されているかどうかが表示されます。

* * 構成状態 *
+
SVM の設定状態がロックされているかどうかが表示されます。





== 詳細領域

SVM のリストの下の領域には、選択した SVM に関する詳細情報が表示されます。これには、許可されているボリュームのタイプ、言語、 Snapshot ポリシーなどの情報が含まれます。

この SVM で許可されるプロトコルを設定することもできます。SVM の作成時にプロトコルを設定していない場合は、プロトコルのリンクをクリックしてプロトコルを設定できます。

System Manager を使用して、ディザスタリカバリ用に設定された SVM のプロトコルを設定することはできません。

[NOTE]
====
SVM に対してすでに FCP サービスが開始されている場合は、 FC および FCoE のリンクをクリックするとネットワークインターフェイスウィンドウが開きます。

====
プロトコル設定のステータスは色で示されます。

|===
| ステータス | 説明 


 a| 
緑
 a| 
LIF が存在し、プロトコルが設定されています。リンクをクリックすると、設定の詳細を確認できます。

[NOTE]
====
設定は一部完了している可能性がありますただし、サービスは実行されています。LIF を作成して設定を完了するには、ネットワークインターフェイスウィンドウを使用します。

====


 a| 
黄色
 a| 
次のいずれかを示します。

* LIF が存在します。サービスは作成されていますが実行されていません。
* LIF が存在します。サービスが作成されていません。
* サービスが作成されました。LIF は存在しません。




 a| 
グレー
 a| 
プロトコルが設定されていません。プロトコルのリンクをクリックしてプロトコルを設定できます。



 a| 
グレーの枠線
 a| 
プロトコルのライセンスがないか期限が切れています。プロトコルのリンクをクリックすると、 Licenses ページにライセンスを追加できます。

|===
管理インターフェイスを追加し、保護関係、保護ポリシー、 NIS ドメインなどの詳細を表示することもできます。

詳細 * 領域には、 SVM のパブリック SSL 証明書へのリンクもあります。このリンクをクリックすると、次のタスクを実行できます。

* 証明書の詳細、シリアル番号、開始日、および有効期限を表示します。
* 証明書をクリップボードにコピーします。
* 証明書の詳細を E メールで送信する。




== ピア Storage Virtual Machines （ピア Storage Virtual Machines ）領域で

選択した SVM とピア関係にある SVM のリストと、それらのピア関係を使用しているアプリケーションの詳細が表示されます。
