---
permalink: online-help-96-97/reference_application_provisioning_settings.html 
sidebar: sidebar 
keywords: application, provisioning, setting, microsoft, sql, database, applications, san, mongodb, oracle, host, access, initiator, sap, hana, smb 
summary: データベース、サーバ、または仮想デスクトップの基本テンプレートまたは拡張テンプレートを設定する場合は、 System Manager で詳細を指定する必要があります。アプリケーションのプロビジョニングが完了したら、詳細を編集し、サイズ変更（拡張のみ）を指定できます。このセクションでは、各テンプレートのフィールドについて説明します。特定のアプリケーションのプロビジョニングまたは設定の編集に必要なフィールドのみが表示されます。 
---
= System Manager のアプリケーションプロビジョニング設定 - ONTAP 9.7 以前
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP System Manager classic （ ONTAP 9.7 以前で使用可能）のデータベース、サーバ、または仮想デスクトップの基本テンプレートまたは拡張テンプレートを設定する場合は、詳細を指定する必要があります。アプリケーションのプロビジョニングが完了したら、詳細を編集し、サイズ変更（拡張のみ）を指定できます。このセクションでは、各テンプレートのフィールドについて説明します。特定のアプリケーションのプロビジョニングまたは設定の編集に必要なフィールドのみが表示されます。



== SAN 経由の Microsoft SQL データベースアプリケーションの詳細

SAN 経由の Microsoft SQL データベースアプリケーションをプロビジョニングしたり、設定を編集したりするには、次の情報を入力します。

* * データベース名 *
+
必須：設定するデータベースの名前。指定した名前は、各データベース用のストレージをプロビジョニングする際にプレフィックスとして使用されます。

* * データベースサイズ *
+
必須：データベースのサイズ（ MB 、 GB 、 TB 、 PB 単位）。

* * データベースの ONTAP サービス・レベル *
+
必須：データベースのサービスレベル。

* * ログサイズ *
+
必須：データベースログのサイズ。単位は MB 、 GB 、 TB 、 PB です。

* * ログの ONTAP サービスレベル *
+
必須：ログのサービスレベル。

* * tempdb *
+
必須： tempdb データベースのサイズ（ MB 、 GB 、 TB 、 PB 単位）。

* * エクスポートプロトコル *
+
必須：エクスポートプロトコルは SAN です

* * サーバコアの数（ SQL Server 上） *
+
データベースサーバの CPU コアの数を 2 単位で示します。

* * HA コントローラノードのスパニング *
+
ストレージオブジェクトをハイアベイラビリティペアの両方のノードにまたいで作成するかどうかを指定します。





== SAP HANA データベースをプロビジョニングするための詳細

* * アクティブな SAP HANA ノード *
+
アクティブな SAP HANA ノードの数。ノードの最大数は 16 です。

* * HANA ノードあたりのメモリサイズ *
+
単一の SAP HANA ノードのメモリサイズ。

* * HANA ノードあたりのデータディスクサイズ *
+
各ノードのデータディスクのサイズ。

+
[NOTE]
====
0 に設定すると、上記のメモリサイズフィールドを使用してデータ領域のサイズが計算されます。

====




== SMB経由のMicrosoft SQLデータベースアプリケーションの詳細

SMB経由のMicrosoft SQLデータベースアプリケーションをプロビジョニングしたり、設定を編集したりするには、次の情報を入力します。

* * データベース名 *
+
必須：設定するデータベースの名前。指定した名前は、各データベース用のストレージをプロビジョニングする際にプレフィックスとして使用されます。

* * データベースサイズ *
+
必須：データベースのサイズ（ MB 、 GB 、 TB 、 PB 単位）。

* * データベースサービスレベル *
+
必須：データベースのサービスレベル。

* * サーバコアの数（ SQL Server 上） *
+
データベースサーバの CPU コアの数を 2 単位で示します。

* * ログサイズ *
+
必須：データベースログのサイズ。単位は MB 、 GB 、 TB 、 PB です。

* * ログサービスレベル *
+
必須：ログのサービスレベル。

* * Tempdb * 用にプロビジョニングします
+
必須： tempdb をプロビジョニングするかどうかを指定します。

* * エクスポートプロトコル *
+
必須：エクスポートプロトコルは SMB または SAN です。

+
SMB を選択できるのは、 CIFS 用のライセンスがクラスタに設定されている場合のみです。この設定は SVM で行います。

* * ユーザにアクセス権を付与 *
+
必須：アプリケーションのアクセスレベル。

* * 許可 *
+
必須：アプリケーションの権限レベル。





== SQL Server アカウントの詳細

SQL Server アカウントにフルコントロールアクセスを付与するには、次の情報を入力します。

[NOTE]
====
インストールアカウントが許可されている `SeSecurityPrivilege`。

====
* * SQL Server サービスアカウント *
+
必須：既存のドメインアカウントです。次のように指定します。 `domain\user`。

* * SQL Server Agent サービスアカウント *
+
オプション：このドメインアカウントは、 SQL Server Agent サービスが設定されている場合、 domain\user の形式で指定します。





== Oracle データベースアプリケーションの詳細

Oracle データベースアプリケーションをプロビジョニングしたり、設定を編集したりするには、次の情報を入力します。

* * データベース名 *
+
必須：設定するデータベースの名前。指定した名前は、各データベース用のストレージをプロビジョニングする際にプレフィックスとして使用されます。

* * データファイルサイズ *
+
必須：データファイルのサイズ（ MB 、 GB 、 TB 、 PB 単位）。

* * データファイルの ONTAP サービスレベル *
+
必須：データファイルのサービスレベル。

* * Redo ロググループサイズ *
+
必須： Redo ロググループのサイズ。単位は MB 、 GB 、 TB 、 PB です。

* * Redo ロググループの ONTAP サービスレベル *
+
必須： Redo ロググループのサービスレベル。

* * アーカイブログサイズ *
+
必須：アーカイブログのサイズ（ MB 、 GB 、 TB 、 PB 単位）。

* * アーカイブログの ONTAP サービスレベル *
+
必須：アーカイブグループのサービスレベル。

* * エクスポートプロトコル *
+
エクスポートプロトコル： SAN または NFS

* * イニシエータ *
+
イニシエータグループに含めるイニシエータ（ WWPN または IQN ）をカンマで区切ったリスト。

* * ホストにアクセスを許可 *
+
アプリケーションにアクセスを許可するホストの名前。





== MongoDB アプリケーションの詳細

MongoDB アプリケーションをプロビジョニングしたり、設定を編集したりするには、次の情報を入力します。

* * データベース名 *
+
必須：設定するデータベースの名前。指定した名前は、各データベース用のストレージをプロビジョニングする際にプレフィックスとして使用されます。

* * データセットサイズ *
+
必須：データファイルのサイズ（ MB 、 GB 、 TB 、 PB 単位）。

* * データセットの ONTAP サービスレベル *
+
必須：データファイルのサービスレベル。

* * レプリケーションファクタ *
+
必須：レプリケーションの数。

* * プライマリホストのマッピング *
+
必須：プライマリホストの名前。

* * レプリカホスト 1 のマッピング *
+
必須：最初のホストレプリカの名前。

* *レプリカホスト2のマッピング*
+
必須： 2 番目のホストレプリカの名前。





== 仮想デスクトップアプリケーションの詳細

仮想デスクトップインフラの（ VDI ）をプロビジョニングしたり、設定を編集したりするには、次の情報を入力します。

* * 平均デスクトップサイズ（ SAN 仮想デスクトップに使用） *
+
シンプロビジョニングされた各ボリュームのサイズを MB 、 GB 、 TB 、または PB 単位で確認できます。

* * デスクトップサイズ *
+
これは、プロビジョニングするボリュームのサイズを MB 、 GB 、 TB 、または PB 単位で決定するために使用されます。

* * デスクトップの ONTAP サービスレベル *
+
必須：データファイルのサービスレベル。

* * デスクトップの数 *
+
指定した数に基づいて、作成されるボリュームの数が決まります。

+
[NOTE]
====
この値は仮想マシンのプロビジョニングには使用されません。

====
* * ハイパーバイザー * を選択します
+
これらのボリュームに使用するハイパーバイザー。これにより、正しいデータストアプロトコルが決まります。VMware 、 Hyper-V 、 XenServer / KVM のいずれかを選択できます。

* * デスクトップの持続性 *
+
デスクトップを永続的にするか非永続的にするかを指定します。デスクトップの永続性を選択すると、 Snapshot スケジュールやポストプロセスの重複排除ポリシーなど、ボリュームのデフォルト値が設定されます。インライン効率化は、すべてのボリュームに対してデフォルトで有効になります。

+
[NOTE]
====
これらのポリシーはプロビジョニング後に手動で変更できます。

====
* * データストアプレフィックス *
+
入力した値を使用してデータストアの名前が生成されます。該当する場合は、エクスポートポリシーまたは共有の名前にもこの値が使用されます。

* * エクスポートプロトコル *
+
エクスポートプロトコル： SAN または NFS

* * イニシエータ *
+
イニシエータグループに含めるイニシエータ（ WWPN または IQN ）をカンマで区切ったリスト。

* * ホストにアクセスを許可 *
+
アプリケーションにアクセスを許可するホストの名前。





== イニシエータの詳細

イニシエータを設定するには、次の情報を入力します。

* * イニシエータグループ *
+
既存のグループを選択するか、新しいグループを作成できます。

* * イニシエータグループ名 *
+
新しいイニシエータグループの名前。

* * イニシエータ *
+
イニシエータグループに含めるイニシエータ（ WWPN または IQN ）をカンマで区切ったリスト。



次のフィールドは、 _SAP HANA のプロビジョニングにのみ適用されます。

* * イニシエータの OS タイプ *
+
新しいイニシエータグループのオペレーティングシステムのタイプ。

* * FCP ポートセット *
+
イニシエータグループをバインドする FCP ポートセット。





== ホストアクセス設定

ボリュームへのホストアクセスを設定するには、次の情報を入力します。

* * ボリュームエクスポート設定 *
+
作成時にボリュームに適用するエクスポートポリシーを選択します。オプションは次のとおりです。

+
** すべて許可（ Allow All ）
+
すべてのクライアントに読み取り / 書き込みアクセスを許可するエクスポートルールが作成されます。

** カスタムポリシーを作成する
+
読み取り / 書き込みアクセスを許可するホストの IP アドレスを指定できます。



+
[NOTE]
====
ボリュームエクスポートポリシーは、 System Manager のワークフローを使用してあとから変更できます。

====
* * ホスト IP アドレス *
+
IP アドレスをカンマで区切ったリスト。

+
[NOTE]
====
NFS ベースのシステムに対し、データストアプレフィックスを使用して新しいエクスポートポリシーが作成され、 IP のリストへのアクセスを許可するルールが作成されます。

====




== アプリケーションの詳細

アプリケーションが追加されると、 [ アプリケーションの詳細 ] ウィンドウの [ 概要 *] タブで構成設定を表示できます。設定されているアプリケーションのタイプに応じて、 NFS アクセスや CIFS アクセス、権限などのその他の詳細が表示されます。

* * タイプ *
+
作成されたアプリケーション、データベース、または仮想インフラのタイプ。

* * SVM *
+
アプリケーションが作成されたサーバ仮想マシンの名前。

* * サイズ *
+
ボリュームの合計サイズ。

* * 利用可能 *
+
ボリュームで現在使用可能なスペースの量。

* * 保護 *
+
設定されているデータ保護のタイプ。



使用済みスペース、 IOPS 、レイテンシに関するパフォーマンスの詳細については、「 * コンポーネント * 」ペインと「ボリューム * 」ペインを展開できます。

[NOTE]
====
Components ペインに表示される使用済みサイズは、 CLI に表示される使用済みサイズとは異なります。

====