---
permalink: online-help-96-97/reference_protection_window.html 
sidebar: sidebar 
keywords: command, buttons, protection, window, relationship, vault, mirror, online, help, ls 
summary: 保護ウィンドウを使用して、ミラー関係、バックアップ関係、ミラーとバックアップ関係を作成および管理したり、それらの関係の詳細を表示したりできます。Protection ウィンドウには、負荷共有（ LS ）関係と移行データ保護（ TDP ）関係は表示されません。 
---
= System Manager - ONTAP 9.7 以前のバージョンの保護ウィンドウ
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
保護ウィンドウと ONTAP System Manager クラシック（ ONTAP 9.7 以前で使用可能）を使用して、ミラー関係、バックアップ関係、ミラーとバックアップ関係を作成および管理したり、それらの関係の詳細を表示したりできます。Protection ウィンドウには、負荷共有（ LS ）関係と移行データ保護（ TDP ）関係は表示されません。



== コマンドボタン

* * 作成 * 。
+
保護関係の作成ダイアログボックスを開きます。このダイアログボックスで、デスティネーションボリュームからミラー関係、バックアップ関係、ミラーとバックアップ関係を作成できます。

+
System Manager の Create Protection Relationship ダイアログボックスに、ディザスタリカバリ（ DR ）用に設定されている Storage Virtual Machine （ SVM ）が表示されません。

* * 編集 * 。
+
保護関係の編集ダイアログボックスを開きます。このダイアログボックスを使用して、関係のスケジュールとポリシーを編集できます。

+
バックアップ関係、ミラーとバックアップ関係、またはバージョンに依存しないミラー関係については、ポリシーのタイプを変更することで関係のタイプを変更することができます。

* * 削除 *
+
[ 保護関係の削除 ] ダイアログボックスが開きます。このダイアログボックスを使用して、関係を削除できます。

* * 操作 *
+
保護関係で実行できる操作が表示されます。

* * 更新 *
+
ウィンドウ内の情報を更新します。





== 保護関係のリスト

* * ソース Storage Virtual Machine *
+
関係におけるデータのミラー元またはバックアップ元のボリュームを含む SVM が表示されます。

* * ソースボリューム *
+
関係におけるデータのミラー元またはバックアップ元のボリュームが表示されます。

* * デスティネーションボリューム *
+
関係におけるデータのミラー先またはバックアップ先のボリュームが表示されます。

* * は正常です *
+
関係が正常であるかどうかが表示されます。

* * オブジェクトタイプ *
+
関係のオブジェクトのタイプが表示されます。ボリューム、 FlexGroup 、 SVM などです。

* * 関係の状態 *
+
Snapmirrored 、 Uninitialized 、 Broken Off など、関係の状態が表示されます。

* * 転送ステータス *
+
関係のステータスが表示されます。

* * 関係タイプ *
+
ミラー、バックアップ、ミラーとバックアップなど、関係のタイプが表示されます。

* * 遅延時間 *
+
遅延時間は、現在の時刻と、デスティネーションシステムに正常に転送された最後の Snapshot コピーのタイムスタンプとの差です。ソースシステムとデスティネーションシステムのクロックが同期されていないかぎり、遅延時間は常に、最後に成功した転送の時間以上になります。遅延時間の計算ではタイムゾーンの時差が自動的に含められます。

* * ポリシー名 *
+
関係に割り当てられているポリシーの名前が表示されます。

* * ポリシータイプ *
+
関係に割り当てられているポリシーのタイプが表示されます。ポリシーのタイプは、 StrictSync 、 Sync 、非同期ミラー、非同期バックアップ、非同期ミラーバックアップのいずれかです。





== 詳細領域

* * 詳細タブ *
+
選択した関係に関する、ソースクラスタとデスティネーションクラスタ、データ転送率、関係の状態、ネットワーク圧縮率、データ転送の状態、現在のデータ転送の種類、前回のデータ転送の種類、最新の Snapshot コピーなどの一般的な情報が表示されます。 および最新の Snapshot コピーのタイムスタンプ。

* * ［ 保険契約の詳細 ］ タブ *
+
選択した保護関係に割り当てられているポリシーに関する詳細が表示されます。このタブには、指定したラベルに一致するソースボリュームの SnapMirror ラベルと Snapshot コピーのスケジュールも表示されます。

* * 「 Snapshot Copies 」タブ *
+
選択した保護関係の Snapshot コピー数と SnapMirror ラベル、および最新の Snapshot コピーのタイムスタンプが表示されます。


