---
permalink: online-help-96-97/reference_cluster_update_window.html 
sidebar: sidebar 
keywords: online, help, cluster, update, window, tab, update, command, button, history, tab 
summary: クラスタの更新ウィンドウを使用すると、クラスタの自動更新を無停止で実行したり、シングルノードクラスタの停止を伴う更新を実行したりできます。 
---
= System Manager - ONTAP 9.7 以前のバージョンでのクラスタの更新ウィンドウ
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
クラスタの更新ウィンドウを使用すると、クラスタの自動更新を無停止で実行できます。また、 ONTAP System Manager クラシック（ ONTAP 9.7 以前で利用可能）を使用して、シングルノードクラスタを停止させながら更新することもできます。



== タブ

* * クラスタの更新 *
+
クラスタの自動更新を無停止で実行できるほか、シングルノードクラスタの停止を伴う更新を実行できます。

* * 更新履歴 *
+
クラスタの以前の更新の詳細を表示します。





== クラスタの更新タブ

クラスタの更新タブでは、クラスタの自動更新を無停止で実行できるほか、シングルノードクラスタの停止を伴う更新も可能です。



== コマンドボタン

* * 更新 *
+
ウィンドウ内の情報を更新します。

* * 「 * 」を選択します
+
更新に使用するソフトウェアイメージのバージョンを選択できます。

+
** クラスタのバージョンの詳細：現在使用中のクラスタのバージョンと、ノードまたはハイアベイラビリティ（ HA ）ペアのバージョンの詳細が表示されます。
** 利用可能なソフトウェアイメージ：更新する既存のソフトウェアイメージを選択できます。
+
または、NetApp Support Siteからソフトウェアイメージをダウンロードして、更新用に追加することもできます。



* * 検証 *
+
クラスタを表示し、更新に使用するソフトウェアイメージのバージョンに対して検証します。クラスタが更新できる状態になっているかどうかを確認するための、更新前検証です。検証の結果エラーが出た場合、各コンポーネントのステータスと、エラーへの対処方法が表に表示されます。

+
更新は、検証が正常に完了した場合にのみ実行できます。

* * アップデート *
+
クラスタ内のすべてのノード、または HA ペアを、ソフトウェアイメージで選択したバージョンに更新できます。更新の実行中に、更新を一時停止してキャンセルまたは再開することができます。

+
エラーが発生した場合、更新は一時停止され、修復手順を含むエラーメッセージが表示されます。修復手順の実行後に更新を再開するか、または更新をキャンセルすることができます。更新が正常に完了すると、ノード名、アップタイム、状態、および ONTAP のバージョンを確認できます。





== [ 更新履歴 ] タブ

クラスタの更新履歴に関する詳細が表示されます。



== [ 更新履歴 ] リスト

* * イメージバージョン *
+
ノードを更新する ONTAP イメージのバージョンです。

* * ソフトウェア・アップデートは * にインストールされています
+
更新をインストールするディスクのタイプを指定します。

* * ステータス *
+
ソフトウェアイメージの更新ステータス（成功またはキャンセル）を示します。

* * 開始時間 *
+
更新が開始された時間です。

* * 完了時間 *
+
更新が完了した時刻です。

+
このフィールドはデフォルトでは非表示になっています。

* * 更新にかかった時間 *
+
更新が完了するまでにかかった時間です。

* * 以前のバージョン *
+
更新前のノードの ONTAP バージョンです。

* * 更新バージョン *
+
更新後のノードの ONTAP バージョンです。


