---
permalink: online-help-96-97/reference_metrocluster_switchover_switchback_window.html 
sidebar: sidebar 
keywords: metrocluster, switchover, switchback, operations, window, command, button, other, action, online, help, status 
summary: System Manager 9.6 以降では、 MetroCluster のスイッチオーバーとスイッチバックの処理のウィンドウを使用して、ネゴシエート（計画的）スイッチオーバーまたはサイト / クラスタ（サイト B ）から別のサイト / クラスタ（サイト A ）への計画外スイッチオーバーを開始できます。サイト B でメンテナンスや修復を実行したら、サイト A からサイト B へのスイッチバックを開始し、このウィンドウで処理のステータスを確認できます。 
---
= MetroCluster のスイッチオーバーとスイッチバックの処理のウィンドウ
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
System Manager 9.6 以降では、 MetroCluster のスイッチオーバーとスイッチバックの処理のウィンドウを使用して、ネゴシエート（計画的）スイッチオーバーまたはサイト / クラスタ（サイト B ）から別のサイト / クラスタ（サイト A ）への計画外スイッチオーバーを開始できます。サイト B でメンテナンスや修復を実行したら、サイト A からサイト B へのスイッチバックを開始し、このウィンドウで処理のステータスを確認できます。



== コマンドボタン

* * サイト B からサイト A へのスイッチオーバー *
+
サイト B からサイト A にスイッチオーバーするプロセスを開始します

* * スイッチバックサイト A をサイト B に接続 *
+
サイト A からサイト B にスイッチバックするプロセスを開始します





== その他の操作

* * サイト B クラスタ * に移動します
+
サイト B のクラスタ管理 IP アドレスを入力します

* * 計画外スイッチオーバー * のチェックボックス
+
計画外スイッチオーバーを開始する場合は、「 Continue with Unplanned Switchover * 」（計画外スイッチオーバーを続行します * ）チェックボックスをオンにします。





== ステータス領域

スイッチオーバーまたはスイッチバックのプロセスが進むにつれて、 System Manager には次の方法でステータスが表示されます。

* * 進捗状況のグラフ *
+
処理の各フェーズと、それらが完了したフェーズが表示されます。フェーズは「スイッチオーバー」、「サイト B の処理」、および「スイッチバック」です。

* *** 詳細を表示 ***
+
MetroCluster の処理が進むにつれて、システムイベントとそのタイムスタンプがリストに表示されます。

* * ローカル : サイト A *
+
サイト A にあるクラスタの構成図と、処理の進捗に応じたサイトのステータスが表示されます。

* * リモート：サイト B *
+
サイト B にあるクラスタの構成図と、処理の進捗に応じたサイトのステータスが表示されます。



サイト B にログインし、 MetroCluster スイッチオーバーおよびスイッチバック操作ウィンドウを表示すると、サイト A のステータスは「非アクティブ」と表示され、サイト B のステータスは「 `S WITCHOVER mode` 」と表示されます。
