---
permalink: online-help-96-97/task_assigning_luns_to_storage_qos.html 
sidebar: sidebar 
keywords: qos, quality, service, assign, lun, storage, system, manager, lun, online, help, policy, group 
summary: System Manager を使用して LUN をストレージ QoS ポリシーグループに割り当てることで、 LUN のスループットを制限できます。新しい LUN にストレージ QoS を割り当てたり、すでにポリシーグループに割り当てられている LUN に対するストレージ QoS の詳細を変更したりできます。 
---
= System Manager - ONTAP 9.7 以前を使用して、ストレージ QoS に LUN を割り当てます
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP System Manager クラシック（ ONTAP 9.7 以前で使用可能）を使用して LUN をストレージ QoS ポリシーグループに割り当てることで、 LUN のスループットを制限できます。新しい LUN にストレージ QoS を割り当てたり、すでにポリシーグループに割り当てられている LUN に対するストレージ QoS の詳細を変更したりできます。

.このタスクについて
* ポリシーグループに次のストレージオブジェクトが割り当てられている場合、 LUN にストレージ QoS を割り当てることはできません。
+
** LUN の親ボリューム
** LUN の親 Storage Virtual Machine （ SVM ）


* ストレージ QoS の割り当てや QoS の詳細の変更は、最大 10 個の LUN について同時に実行できます。


.手順
. [ * ストレージ * > * LUNs * ] をクリックします。
. LUN 管理 * タブで、ストレージ QoS を割り当てる LUN を 1 つ以上選択します。
. [* ストレージ QoS * ] をクリックします。
. LUN のワークロードパフォーマンスを管理する場合は、 * サービス品質の詳細 * ダイアログボックスで * ストレージ QoS の管理 * チェックボックスを選択します。
+
選択した LUN の一部がすでにポリシーグループに割り当てられている場合、変更内容によってはそれらの LUN のパフォーマンスに影響する可能性があります。

. 新しいストレージ QoS ポリシーグループを作成するか、または既存のポリシーグループを選択して、 LUN の入出力（ I/O ）のパフォーマンスを制御します。
+
|===
| 状況 | 手順 


 a| 
新しいポリシーグループを作成します
 a| 
.. [ 新しいポリシーグループ *] を選択します。
.. ポリシーグループの名前を指定します。
.. 最小スループット制限を指定します。
+
*** System Manager 9.5 では、パフォーマンスがオールフラッシュで最適化されている場合にのみ最小スループット制限を設定できます。System Manager 9.6 では、 ONTAP Select Premium システムにも最小スループット制限を設定できます。
*** FabricPool 対応アグリゲートでは、ボリュームの最小スループット制限を設定することはできません。
*** 最小スループット値を指定しない場合、または最小スループット値が 0 に設定されている場合は、自動的に「なし」という値が表示されます。
+
この値では大文字と小文字が区別されます。



.. 最大スループット制限を指定します。ポリシーグループに含まれるオブジェクトのワークロードがこのスループット制限を超えないように制限されます。
+
*** 最小スループット制限と最大スループット制限の単位は同じにする必要があります。
*** 最小スループット制限を指定しない場合は、 IOPS 、 B/ 秒、 KB/ 秒、 MB/ 秒などの単位で最大スループット制限を設定できます。
*** 最大スループット値を指定しない場合は、値として自動的に「無制限」と表示され、大文字と小文字が区別されます。
+
指定した単位は無視されます。







 a| 
既存のポリシーグループを選択してください
 a| 
.. [ ポリシーグループの選択 ] ダイアログボックスで、 [ 既存のポリシーグループ *] を選択し、 [*Choose*] をクリックして既存のポリシーグループを選択します。
.. 最小スループット制限を指定します。
+
*** System Manager 9.5 では、パフォーマンスがオールフラッシュで最適化されている場合にのみ最小スループット制限を設定できます。System Manager 9.6 では、 ONTAP Select Premium システムにも最小スループット制限を設定できます。
*** FabricPool 対応アグリゲートでは、ボリュームの最小スループット制限を設定することはできません。
*** 最小スループット値を指定しない場合、または最小スループット値が 0 に設定されている場合は、自動的に「なし」という値が表示されます。
+
この値では大文字と小文字が区別されます。



.. 最大スループット制限を指定します。ポリシーグループに含まれるオブジェクトのワークロードがこのスループット制限を超えないように制限されます。
+
*** 最小スループット制限と最大スループット制限の単位は同じにする必要があります。
*** 最小スループット制限を指定しない場合は、 IOPS 、 B/ 秒、 KB/ 秒、 MB/ 秒などの単位で最大スループット制限を設定できます。
*** 最大スループット値を指定しない場合は、値として自動的に「無制限」と表示され、大文字と小文字が区別されます。
 [+]
指定した単位は無視されます。


+
ポリシーグループが複数のオブジェクトに割り当てられている場合、指定した最大スループットはそれらのオブジェクトの合計スループットです。



|===
. *オプション：*選択したLUNのリストを確認するLUNの数を指定するリンクをクリックし、リストからLUNを削除する場合は「*破棄」をクリックします。
+
このリンクは、複数の LUN を選択した場合にのみ表示されます。

. [OK] をクリックします。

