---
permalink: online-help-96-97/task_delegating_administration_to_svm_administrators.html 
sidebar: sidebar 
keywords: online, help, delegate, administration, svm, administrator 
summary: Storage Virtual Machine （ SVM ）を最終的な運用状態に、または基本的なネットワーク設定までセットアップしたら、必要に応じてその管理を SVM 管理者に委譲できます。 
---
= System Manager - ONTAP 9.7 以前を使用して、 SVM 管理者に管理を委譲します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Storage Virtual Machine（SVM）が機能するように設定したあと、または基本的なネットワーク設定があるSVMを使用して、ONTAP System Managerクラシック（ONTAP 9.7以前で使用可能）を使用してSVMの管理をSVM管理者に委譲することもできます。

.このタスクについて
SVM 管理者は、 System Manager を使用して委譲された SVM を管理することはできませ委譲された SVM を管理するには CLI を使用する必要があります。

.手順
. [管理者の詳細]セクションで、 `vsadmin` ユーザアカウント
. SVM 管理用に専用の LIF を作成する場合は、 * SVM 管理用の LIF を作成する * を選択して、ネットワークの詳細を指定します。
+
データプロトコルと管理プロトコルでは同じ LIF を共有できないため、 SAN プロトコルでは専用の SVM 管理 LIF が必要になります。SVM 管理 LIF は、データポート上にのみ作成できます。

. サブネットの詳細も含めて、 iSCSI LIF を作成するためのネットワークの詳細を指定します。
+
|===
| 状況 | 作業 


 a| 
サブネットを使用して IP アドレスを指定します
 a| 
.. サブネットを使用する * を選択します。
.. Add Details ダイアログボックスで、 IP アドレスを割り当てるサブネットを選択します。
+
クラスタ間 LIF の場合、選択した IPspace に関連付けられているサブネットだけが表示されます。

.. インターフェイスに特定の IP アドレスを割り当てる場合は、 * 特定の IP アドレスを使用する * を選択して、 IP アドレスを入力します。
+
指定した IP アドレスがサブネット内にない場合、追加されます。

.. [OK] をクリックします。




 a| 
サブネットを使用せずに手動で IP アドレスを指定します
 a| 
.. サブネットなし * を選択します。
.. [ 詳細の追加 ] ダイアログボックスで、次の手順を実行します。
+
... IP アドレスとネットワークマスクまたはプレフィックスを指定します。
... オプション：ゲートウェイを指定します。
... Destination フィールドにデフォルト値を使用しない場合は、新しい宛先値を指定します。
+
カスタム値を指定しない場合は、 IP アドレスファミリーに基づいてデフォルト値が Destination フィールドに入力されます。

+
ルートが存在しない場合は、ゲートウェイとデスティネーションに基づいて新しいルートが自動的に作成されます。



.. [OK] をクリックします。


|===
. データ LIF を作成するポートを指定します。
+
.. [* 参照 ] をクリックします。
.. Select Network Port or Adapter ダイアログボックスからポートを選択します。
.. [OK] をクリックします。




.結果
。 `vsadmin` アカウントのロックが解除され、パスワードが設定されています。

のデフォルトのアクセス方法 `vsadmin` アカウントはONTAP APIです。 `(ontapi)` SSH `(ssh)`。SVM 管理者は、管理 IP アドレスを使用してストレージシステムにログインできます。



== 次に何をするか

Storage Virtual Machine の編集ダイアログボックスを使用して、 SVM にアグリゲートを割り当てる必要があります。

[NOTE]
====
SVM にアグリゲートが割り当てられていないと、 SVM 管理者はボリュームを作成できません。

====