---
permalink: online-help-96-97/task_creating_luns.html 
sidebar: sidebar 
keywords: create, lun, system, manager, qtree, online, help 
summary: 空きスペースがある場合、 System Manager を使用して、既存のアグリゲート、ボリューム、または qtree の LUN を作成できます。既存のボリュームに LUN を作成したり、その LUN に対する新しい FlexVol を作成したりできます。また、ワークロードのパフォーマンスを管理するためにストレージ QoS を有効にすることもできます。 
---
= System Manager を使用して ONTAP 9.7 以前を作成します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
空きスペースがある場合、ONTAP System Managerクラシック（ONTAP 9.7以前で使用可能）を使用して、既存のアグリゲート、ボリューム、またはqtreeのLUNを作成できます。既存のボリュームに LUN を作成したり、その LUN に対する新しい FlexVol を作成したりできます。また、ワークロードのパフォーマンスを管理するためにストレージ QoS を有効にすることもできます。

.このタスクについて
LUN ID を指定した場合、 System Manager は LUN を追加する前に ID の有効性をチェックします。LUN ID の指定を省略すると、 ONTAP ソフトウェアにより自動的に LUN ID が割り当てられます。

LUN マルチプロトコルタイプを選択する際は、各タイプの使用に関するガイドラインを考慮する必要があります。LUN マルチプロトコルタイプ、すなわちオペレーティングシステムのタイプにより、 LUN 上のデータのレイアウト、および LUN の最小サイズと最大サイズが決まります。LUN の作成後に、 LUN のホストオペレーティングシステムのタイプを変更することはできません。

MetroCluster 構成の場合、 LUN の FlexVol 作成時に System Manager に表示されるのは以下のアグリゲートのみです。

* 通常モードの場合：プライマリサイトの同期元 SVM またはデータ提供用 SVM にボリュームを作成する場合、プライマリサイトのクラスタに属しているアグリゲートのみが表示される。
* 切り替えモードの場合：フェイルオーバー先のサイトの同期先 SVM またはデータ提供用 SVM にボリュームを作成する場合、切り替えられたアグリゲートのみが表示される。


.手順
. [ * ストレージ * > * LUNs * ] をクリックします。
. [* LUN 管理 * ] タブで、 [* 作成 ] をクリックします。
. LUN を作成する SVM を参照して選択します。
. LUN 作成ウィザード * で、 LUN の名前、サイズ、タイプ、概要を指定し、 * スペース・リザーブ * を選択して、 * 次へ * をクリックします。
. LUN 用の新しい FlexVol ボリュームを作成するか、既存のボリュームまたは qtree を選択し、 * Next * をクリックします。
. LUN へのホストアクセスを制御する場合はイニシエータグループを追加し、 * Next * をクリックします。
. LUN のワークロードパフォーマンスを管理する場合は、 [ サービス品質の管理 ] チェックボックスをオンにします。
. 新しいストレージ QoS ポリシーグループを作成するか、または既存のポリシーグループを選択して、 LUN の入出力（ I/O ）のパフォーマンスを制御します。
+
|===
| 状況 | 手順 


 a| 
新しいポリシーグループを作成します
 a| 
.. [ 新しいポリシーグループ *] を選択します
.. ポリシーグループの名前を指定します。
.. 最小スループット制限を指定します。
+
*** System Manager 9.5 では、パフォーマンスがオールフラッシュで最適化されている場合にのみ最小スループット制限を設定できます。System Manager 9.6 では、 ONTAP Select Premium システムにも最小スループット制限を設定できます。
*** FabricPool 対応アグリゲートでは、ボリュームの最小スループット制限を設定することはできません。
*** 最小スループット値を指定しない場合、または最小スループット値が 0 に設定されている場合は、自動的に「なし」という値が表示されます。
+
この値では大文字と小文字が区別されます。



.. 最大スループット制限を指定します。ポリシーグループに含まれるオブジェクトのワークロードがこのスループット制限を超えないように制限されます。
+
*** 最小スループット制限と最大スループット制限の単位は同じにする必要があります。
*** 最小スループット制限を指定しない場合は、 IOPS 、 B/ 秒、 KB/ 秒、 MB/ 秒などの単位で最大スループット制限を設定できます。
*** 最大スループット値を指定しない場合は、値として自動的に「無制限」と表示され、大文字と小文字が区別されます。
+
指定した単位は無視されます。







 a| 
既存のポリシーグループを選択してください
 a| 
.. [ ポリシーグループの選択 ] ダイアログボックスで、 [ 既存のポリシーグループ *] を選択し、 [*Choose*] をクリックして既存のポリシーグループを選択します。
.. 最小スループット制限を指定します。
+
*** System Manager 9.5 では、パフォーマンスがオールフラッシュで最適化されている場合にのみ最小スループット制限を設定できます。System Manager 9.6 では、 ONTAP Select Premium システムにも最小スループット制限を設定できます。
*** FabricPool 対応アグリゲートでは、ボリュームの最小スループット制限を設定することはできません。
*** 最小スループット値を指定しない場合、または最小スループット値が 0 に設定されている場合は、自動的に「なし」という値が表示されます。
+
この値では大文字と小文字が区別されます。



.. 最大スループット制限を指定します。ポリシーグループに含まれるオブジェクトのワークロードがこのスループット制限を超えないように制限されます。
+
*** 最小スループット制限と最大スループット制限の単位は同じにする必要があります。
*** 最小スループット制限を指定しない場合は、 IOPS 、 B/ 秒、 KB/ 秒、 MB/ 秒などの単位で最大スループット制限を設定できます。
*** 最大スループット値を指定しない場合は、値として自動的に「無制限」と表示され、大文字と小文字が区別されます。
+
指定した単位は無視されます。



+
ポリシーグループが複数のオブジェクトに割り当てられている場合、指定した最大スループットはそれらのオブジェクトの合計スループットです。



|===
. 指定された詳細情報を [* LUN summary] ウィンドウで確認し、 [Next] をクリックします。
. 詳細を確認し、 [* 終了 ] をクリックしてウィザードを完了します。


* 関連情報 *

xref:reference_luns_window.adoc[LUN ウィンドウ]

xref:concept_lun_multiprotocol_type_guidelines.adoc[LUN マルチプロトコルタイプの使用に関するガイドライン]
