---
permalink: online-help-96-97/task_adding_preferred_domain_controllers.html 
sidebar: sidebar 
keywords: system, manager, add, preferred, domain, controller, online, help, dns, edit, modify, delete 
summary: System Manager では、 DNS を介してドメインコントローラが自動的に検出されます。必要に応じて、特定のドメインに対する優先ドメインコントローラのリストにドメインコントローラを追加することができます。 
---
= System Manager - ONTAP 9.7 以前を使用して、優先ドメインコントローラを管理します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP System Managerクラシック（ONTAP 9.7以前で使用可能）を使用して、優先ドメインコントローラを管理できます。



== 優先ドメインコントローラを追加する

System Manager では、 DNS を介してドメインコントローラが自動的に検出されます。必要に応じて、特定のドメインに対する優先ドメインコントローラのリストにドメインコントローラを追加することができます。

.手順
. [ * ストレージ * > * SVMs * ] をクリックします。
. SVM を選択し、 * SVM 設定 * をクリックします。
. [* ドメイン *] タブで、 [* 優先ドメインコントローラー * ] 領域の [* 追加 ] をクリックします。
. 追加するドメインコントローラの完全修飾ドメイン名（ FQDN ）および IP アドレスを入力します。
+
ドメインコントローラの IP アドレスをカンマで区切って入力することで複数のドメインコントローラを追加できます。

. [ 保存（ Save ） ] をクリックします。
. 追加したドメインコントローラが優先ドメインコントローラのリストに表示されていることを確認します。




== 優先ドメインコントローラを編集する

System Manager を使用して、特定のドメインに対して設定されている優先ドメインコントローラの IP アドレスを変更することができます。

.手順
. [ * ストレージ * > * SVMs * ] をクリックします。
. SVM を選択し、 * SVM 設定 * をクリックします。
. [*Domain*] タブの [* Preferred Domain Controllers] 領域で、編集するドメインコントローラをダブルクリックします。
. ドメインコントローラの IP アドレスを変更し、 * 保存 * をクリックします。




== 優先ドメインコントローラを削除する

System Manager を使用して、 Storage Virtual Machine （ SVM ）が関連付けられている優先ドメインコントローラを削除することができます。これは、特定のドメインコントローラが不要になった場合に実行できます。

.手順
. [ * ストレージ * > * SVMs * ] をクリックします。
. SVM を選択し、 * SVM 設定 * をクリックします。
. [ * ドメイン * ] タブで、 [ * 優先ドメインコントローラー * ] 領域から削除するドメインを選択し、 [ * 削除 * ] をクリックします。
. 確認のチェックボックスをオンにし、 * 削除 * をクリックします。

