---
permalink: online-help-96-97/task_performing_switchback.html 
sidebar: sidebar 
keywords: metrocluster, perform, switchback, system, manager, online, help 
summary: System Manager 9.6 以降では、スイッチオーバー処理の完了後にスイッチバック処理を実行して、元の MetroCluster サイト（サイト B ）に制御を戻すことができます。 
---
= スイッチバックを実行しています
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
System Manager 9.6 以降では、スイッチオーバー処理の完了後にスイッチバック処理を実行して、元の MetroCluster サイト（サイト B ）に制御を戻すことができます。

.作業を開始する前に
スイッチバック処理を実行する前に、次の作業を完了しておく必要があります。

* で MetroCluster サイトを準備する必要があります xref:task_performing_negotiated_planned_switchover.adoc[ネゴシエート（計画的）スイッチオーバーの実行] または xref:task_performing_unplanned_switchover.adoc[計画外スイッチオーバーの実行]。
* 修復処理でエラーが発生した場合は、表示される手順に従って修正する必要があります。
* リモートサイトの状態が「 Getting ready for switchback 」と表示されている場合、アグリゲートはまだ再同期中です。スイッチバックの準備が完了したことを示すステータスがリモートサイトに表示されるまで待ちます。


.このタスクについて
スイッチオーバー処理が成功すると、 MetroCluster のスイッチオーバーとスイッチバックの処理のウィンドウが表示されます。このウィンドウには、両方のサイトのステータスと、処理が成功したことを示すメッセージが表示されます。

.手順
. サイト A からサイト B へのスイッチバックを * クリックして、スイッチバック処理を開始します。
+
スイッチバック処理によって MetroCluster の制御がサイト B に戻ること、およびプロセスに時間がかかる可能性があることを示す警告メッセージが表示されます。

. 続行する場合は、 * はい * をクリックします。
. スイッチバックプロセスが完了したら、次のいずれかの手順を実行します。
+
** スイッチバック処理が成功した場合は、「 * Done * 」をクリックして、 MetroCluster 処理の完了を確認します。
+
[NOTE]
====
スイッチバック処理が完了したことを示す System Manager のメッセージは、処理の完了を確認するまで表示されたままです。スイッチバック処理の完了を確認するまで、別の処理を開始したり、以降のスイッチオーバー / スイッチバック処理を監視したりすることはできません。

====
** スイッチバック処理が失敗した場合は、ステータス領域の上部にエラーメッセージが表示されます。必要に応じて修正を加え、 [ サイト A からサイト B へのスイッチバック ] をクリックしてプロセスを再試行します。



