---
permalink: online-help-96-97/task_adding_licenses.html 
sidebar: sidebar 
keywords: system, manager, add, license, storage, software, online, help 
summary: ストレージシステムソフトウェアが工場出荷時にインストールされている場合は、 System Manager によってそのソフトウェアがライセンスのリストに自動的に追加されます。ソフトウェアが工場出荷時にインストールされていない場合や追加のソフトウェアライセンスを追加する場合は、 System Manager を使用してソフトウェアライセンスを追加できます。 
---
= System Manager - ONTAP 9.7 以前を使用してライセンスを追加します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
工場出荷時にソフトウェアがインストールされていない場合やソフトウェアライセンスを追加する場合は、 ONTAP System Manager classic （ ONTAP 9.7 以前で利用可能）を使用してソフトウェアライセンスを追加できます。

ストレージシステムソフトウェアが工場出荷時にインストールされている場合は、 System Manager によってそのソフトウェアがライセンスのリストに自動的に追加されます。

.作業を開始する前に
特定の ONTAP サービスのソフトウェアライセンスコードを用意しておく必要があります。

.このタスクについて
* ONTAP 9.10.1以降では、System Managerを使用してネットアップライセンスファイル（NLF）をインストールし、複数のライセンス機能を一度に有効にすることができます。NetApp License File を使用すると、個別の機能ライセンスキーを追加する必要がなくなるため、ライセンスのインストールが簡単になります。NetApp Support Siteからネットアップライセンスファイルをダウンロードします。
+
詳細については、を参照してください link:https://docs.netapp.com/us-en/ontap/task_admin_enable_new_features.html["ライセンスキーを追加して新しい機能を有効にします"]

+
ライセンスの管理については、を参照してください link:https://docs.netapp.com/us-en/ontap/system-admin/manage-licenses-concept.html["ライセンスの管理の概要（クラスタ管理者のみ）"^]

* MetroCluster 構成で新しいライセンスを追加するときは、セカンダリサイトのクラスタにもライセンスを追加することを推奨します。
* System Manager を使用して Cloud Volumes ONTAP ライセンスを追加することはできません。
+
Cloud Volumes ONTAP ライセンスは、ライセンスページに表示されません。System Manager では、 Cloud Volumes ONTAP ライセンスのライセンス使用権リスクに関するアラートは通知されません。

* アップロードできるのは、容量ベースのライセンスだけです。
+
容量ベースのライセンスのタイプは「 JSON 」です。



.手順
. [* Configuration * （設定 * ） ] > [* Cluster * （クラスタ * ） ] > [* Licenses * （ライセンス *
. [ 追加（ Add ） ] をクリックします。
. [ ライセンスの追加 *] ダイアログボックスで、次の手順を実行します。
+
|===
| 状況 | 手順 


 a| 
特定の ONTAP サービスのライセンスを追加します
 a| 
.. ソフトウェアライセンスキーを入力します。
+
ソフトウェアライセンスキーをカンマで区切って入力することで複数のライセンスを追加できます。

.. [ 追加（ Add ） ] をクリックします。




 a| 
容量ベースのライセンスを追加します
 a| 
.. 参照をクリックし、容量ベースのライセンスファイルを選択します。
.. [ 追加（ Add ） ] をクリックします。




 a| 
特定の ONTAP サービスのライセンスと容量ベースのライセンスを追加する
 a| 
.. ソフトウェアライセンスキーを入力します。
+
ソフトウェアライセンスキーをカンマで区切って入力することで複数のライセンスを追加できます。

.. 参照をクリックし、容量ベースのライセンスファイルを選択します。
.. [ 追加（ Add ） ] をクリックします。


|===
+
新しいライセンスが追加されます。

+
[Add License Status] ダイアログボックスに、正常に追加されたライセンスのリストが表示されます。このダイアログボックスには、追加されなかったライセンスのライセンスキーもその理由とともに表示されます。

. [* 閉じる * ] をクリックします。


.結果
ソフトウェアライセンスがストレージシステムに追加され、 Licenses window のライセンスのリストに表示されます。

* 関連情報 *

xref:reference_licenses_window.adoc[ライセンスウィンドウ]
