---
permalink: online-help-96-97/task_setting_up_cluster_using_template_file.html 
sidebar: sidebar 
keywords: set, up, cluster, template, file, system, manager, online, help, autosupport 
summary: System Manager に組み込みのテンプレートファイルを使用してクラスタをセットアップできます。クラスタを作成し、ノード管理ネットワークとクラスタ管理ネットワークのセットアップ、およびイベント通知のセットアップを行います。（ ONTAP System Manager 9.6 以降では、 AutoSupport はサポートされません）。 テンプレートファイルは、 .xlsx または .csv のいずれかの形式でダウンロードできます。 
---
= System Manager - ONTAP 9.7 以前のバージョンでテンプレートファイルを使用してクラスタをセットアップします
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP System Manager クラシック（ ONTAP 9.7 以前で使用可能）に付属のテンプレートファイルを使用して、クラスタの作成、ノード管理ネットワークとクラスタ管理ネットワークのセットアップ、およびイベント通知のセットアップを行うことでクラスタをセットアップできます。（ONTAP System Manager 9.6以降では、AutoSupportはサポートされません）。 テンプレートファイルは、 `.xlsx` 形式または `.csv` の形式で入力し

.このタスクについて
* ONTAP 9.1 以降をサポートするクラスタの場合、 ONTAP 9.1 以降を実行しているストレージシステムのみを追加できます。
* ファイルのアップロード時にすべてのフィールドが自動的に入力されるわけではありません。
+
パスワードやクラスタ管理ポートなど、一部のフィールドの値は手動で入力する必要があります。



.手順
. Webブラウザを開き、設定したノード管理IPアドレスを入力します。 `+https://node-management-IP+`
+
** クラスタのクレデンシャルを設定している場合は、ログインページが表示されます。
+
ログインするにはクレデンシャルを入力する必要があります。

** クラスタのクレデンシャルを設定していない場合は、セットアップガイドウィンドウが表示されます。


. をダウンロードします `.xlsx` テンプレートファイルまたは `.csv` テンプレートファイル。
. テンプレートファイルに必要な値をすべて指定し、ファイルを保存します。
+
[NOTE]
====
** テンプレート内の値以外の列は編集しないでください。
** テンプレートファイルのバージョンは変更しないでください。


====
. * 参照 * をクリックし、更新されたテンプレートファイルを選択します。
+
** テンプレートファイルは、 `.csv` の形式で入力しテンプレートファイルを `.xlsx` を使用して、ファイルを `.csv` をクリックし、ファイルをアップロードします。
** このファイルに使用されるエンコードは次のとおりであることを確認する必要があります。 `UTF8`。そうでない場合、値は読み取られません。


. [ アップロード ] をクリックします。
+
テンプレートファイルで指定した詳細を使用して、クラスタセットアップのプロセスが実行されます。

. クラスタの詳細を表示するには、 * Guided Setup * アイコンをクリックします。
. [*Cluster*] ウィンドウで詳細を確認し、 [*Submit and Continue] をクリックします。
+
必要に応じてクラスタの詳細を編集できます。

+
[ クラスタ ] ウィンドウに 2 回目ログインすると、 [ * 機能ライセンス * ] フィールドがデフォルトで有効になります。新しい機能ライセンスキーを追加することも、事前に入力されたライセンスキーをそのまま使用することもできます。

. [*Network*]( ネットワーク *) ウィンドウで詳細を確認し、 [*Submit and Continue]( 送信して続行 ) をクリックします。
+
必要に応じてネットワークの詳細を編集できます。

. [*Support*]( サポート *) ウィンドウで詳細を確認し '[*Submit and Continue]( 送信して続行 )* をクリックします
+
必要に応じてサポートの詳細を編集できます。

. Storage * ウィンドウで詳細を確認し、アグリゲートを作成するか、クラスタのセットアップを終了します。
+
|===
| 状況 | 作業 


 a| 
ストレージのプロビジョニングと SVM の作成を行わずにクラスタセットアップを終了します
 a| 
[ この手順をスキップする *] をクリックします。



 a| 
アグリゲートを使用してストレージをプロビジョニングし、 SVM を作成します
 a| 
[Submit and Continue] をクリックします。

|===
+
必要に応じてサポートの詳細を編集できます。

. Create Storage Virtual Machine （ SVM ） * ウィンドウで詳細を確認し、 * Submit and Continue * をクリックします。
+
必要に応じて、 SVM 名を編集したり、別のデータプロトコルを選択したり、ネットワークインターフェイスとアダプタの詳細を変更したりできます。

. [* ストレージ * ] ウィンドウで [ この手順 * を省略 ] をクリックした場合は、 [ * 概要 * ] ウィンドウで詳細を表示し、 [ * クラスタの管理 * ] をクリックして System Manager を起動します。
. [* ストレージ * ] ウィンドウで [ 送信して続行 ] をクリックした場合は、 SVM ウィンドウで詳細を確認し、 [ * 送信して続行 ] をクリックします。
+
必要に応じて SVM の詳細を編集できます。

. すべての詳細を * Summary * ウィンドウで確認し、 * Provision an Application * （アプリケーションのプロビジョニング）をクリックしてアプリケーション用のストレージをプロビジョニングするか、 * Manage Your Cluster * （クラスタの管理）をクリックしてクラスタセットアッププロセスを完了し、 System Manager を起動するか、 * Export Configuration * （設定のエクスポート）をクリックして構成ファイルをダウンロードします。


* 関連情報 *

https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/System_Manager_Cluster_Guided_Setup_Templates["System Manager クラスタセットアップガイド用テンプレート"]
