---
permalink: online-help-96-97/task_configuring_iscsi_protocol_on_svms.html 
sidebar: sidebar 
keywords: system, manager, iscsi, protocol, svm, online, help, lif, portset 
summary: System Manager を使用して、 Storage Virtual Machine （ SVM ）に iSCSI プロトコルを設定して、ブロックレベルのデータアクセスを提供できます。iSCSI LIF とポートセットを作成し、 LIF をポートセットに追加できます。最適なアダプタで LIF が作成され、データパスの冗長性を確保するためにポートセットに割り当てられます。 
---
= System Manager - ONTAP 9.7 以前を使用して、 SVM に iSCSI プロトコルを設定します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP System Managerクラシック（ONTAP 9.7以前で使用可能）を使用して、Storage Virtual Machine（SVM）でiSCSIプロトコルを設定してブロックレベルのデータアクセスを提供できます。iSCSI LIF とポートセットを作成し、 LIF をポートセットに追加できます。最適なアダプタで LIF が作成され、データパスの冗長性を確保するためにポートセットに割り当てられます。

.作業を開始する前に
* クラスタで iSCSI ライセンスが有効になっている必要があります。
+
SVM で iSCSI プロトコルが有効になっていない場合は、 Storage Virtual Machine の編集ウィンドウを使用して SVM のプロトコルを有効にできます。

* クラスタのすべてのノードが正常である必要があります。
* 各ノードには少なくとも2つのデータポートが必要で、ポートの状態は `up`。


.このタスクについて
* iSCSI プロトコルは、 SVM の作成時に設定することも、あとで設定することもできます。
* SnapLock アグリゲートは、ボリュームの自動作成の対象としては考慮されません。


.手順
. SVM の作成時に iSCSI プロトコルを設定していない場合は、 * Storage * > * SVMs * をクリックします。
. SVM を選択し、 * SVM 設定 * をクリックします。
. [*Protocols* ] ペインで、 [*iSCSI*] をクリックします。
. *オプション：* Network Access *セクションで、iSCSIターゲットのエイリアスを指定します。
+
エイリアス名の最大文字数は 128 文字です。ターゲットのエイリアスを指定しない場合は、 SVM 名がエイリアスとして使用されます。

. 単一のノードに割り当てることができる iSCSI LIF の数を指定します。
+
ノードあたりの LIF の最小数は 1 です。最大数は、のすべてのポートの最小数です。 `up` ノード全体の状態。最大値が奇数の場合は、 1 つ前の偶数が最大値とみなされます。最小値と最大値の範囲に任意の偶数を選択できます。

+
4ノードクラスタで、node1、node2、およびnode3にはそれぞれ6つのポートがあるとします。 `up` 状態、およびに7つのポートがあるノード4 `up` 状態。この場合、クラスタに実際に設定可能な最大値は 6 です。

+
ノードに LIF を 3 個以上割り当てる場合、各 LIF に少なくともポートセットを 1 つ割り当てる必要があります。

. サブネットの詳細も含めて、 iSCSI LIF を作成するためのネットワークの詳細を指定します。
+
|===
| 状況 | 作業 


 a| 
サブネットを使用して IP アドレスを指定します
 a| 
.. サブネットを使用する * を選択します。
.. Add Details ダイアログボックスで、 IP アドレスを割り当てるサブネットを選択します。
+
クラスタ間 LIF の場合、選択した IPspace に関連付けられているサブネットだけが表示されます。

.. インターフェイスに特定の IP アドレスを割り当てる場合は、 * 特定の IP アドレスを使用する * を選択して、 IP アドレスを入力します。
+
指定した IP アドレスがサブネット内にない場合、追加されます。

.. [OK] をクリックします。




 a| 
サブネットを使用せずに手動で IP アドレスを指定します
 a| 
.. サブネットなし * を選択します。
.. [ 詳細の追加 ] ダイアログボックスで、次の手順を実行します。
+
... IP アドレスとネットワークマスクまたはプレフィックスを指定します。
... オプション：ゲートウェイを指定します。
... Destination フィールドにデフォルト値を使用しない場合は、新しい宛先値を指定します。
+
送信先の値を指定しない場合は、 IP アドレスのファミリーに基づいて、 Destination フィールドにデフォルト値が設定されます。



+
ルートが存在しない場合は、ゲートウェイとデスティネーションに基づいて新しいルートが自動的に作成されます。

.. [OK] をクリックします。


|===
. ブロードキャストドメインを選択してください。
. アダプタタイプを選択します。
+
クラスタに NIC カードが設定されている場合は、 * nic * を選択してください。

+
クラスタに CNS カードが設定されている場合は、 [*CNA*] を選択する必要があります。

+
クラスタに ifgrp が設定されている場合は、「 * インターフェイスグループ * 」を選択する必要があります。

+
[NOTE]
====
ifgrp ポートはブロードキャストドメインに追加する必要があります。

====
. *オプション：LUNサイズ、LUNのOSタイプ、およびホストイニシエータの詳細を指定してiSCSIプロトコルを設定する際に、iSCSIストレージ用のLUNをプロビジョニングします。
. 自動生成された iSCSI LIF の設定を確認または変更する場合は、「 * LIF 設定の確認または変更（詳細設定） * 」を選択します。
+
変更できるのは、 LIF 名とホームポートだけです。ポートセットは、デフォルトでは最小値に設定されます。一意のエントリを指定する必要があります。重複した LIF 名を指定すると、 System Manager によって末尾に番号が付加されます。

+
選択したポートセットに基づいて、 LIF がラウンドロビン方式でポートセットに割り当てられます。これにより、ノードまたはポートで障害が発生した場合の冗長性が確保されます。

. [Submit & Continue] をクリックします。


.結果
指定した設定で iSCSI LIF とポートセットが作成され、選択したポートセットに基づいて、 LIF がポートセットに割り当てられます。すべての LIF が正常に作成されると、 iSCSI サービスが開始されます。

LIF の作成に失敗した場合は、ネットワークインターフェイスウィンドウを使用して LIF を作成し、 LUN ウィンドウでポートセットに割り当ててから、 iSCSI ウィンドウを使用して iSCSI サービスを開始できます。
