---
permalink: online-help-96-97/task_creating_flexvol_volumes.html 
sidebar: sidebar 
keywords: flexvol, create, volume, online, help 
summary: データ用の FlexVol ボリュームは、 System Manager のボリュームの作成ダイアログボックスを使用して作成できます。ルートボリュームにデータを格納するのではなく、データ用のボリュームを必ず別に作成してください。 
---
= System Manager ONTAP 9.7 以前を使用して FlexVol ボリュームを作成します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP System Managerクラシック（ONTAP 9.7以前で使用可能）のボリュームの作成ダイアログボックスを使用して、データ用のFlexVol ボリュームを作成できます。ルートボリュームにデータを格納するのではなく、データ用のボリュームを必ず別に作成してください。

.作業を開始する前に
* クラスタにルート以外のアグリゲートと Storage Virtual Machine （ SVM ）が含まれている必要があります。
* 読み書き可能ボリュームを作成する場合は、 SVM 用のプロトコルを設定し、 SnapMirror ライセンスまたは SnapVault ライセンスをインストールしておく必要があります。
+
プロトコルが未設定で、いずれかのライセンスをインストールしている場合は、データ保護（ DP ）ボリュームだけを作成できます。

* 暗号化されたボリュームを作成するには、 System Manager を使用してボリューム暗号化ライセンスをインストールし、コマンドラインインターフェイス（ CLI ）を使用して「 key-manager setup 」を有効にしておく必要があります。
+
「 key-manager setup 」を有効にした後、 Web ブラウザを更新する必要があります。



.このタスクについて
* ストレージ QoS を有効にできるのは、読み書き可能（ rw ）ボリュームだけです。
* MetroCluster 構成の同期元の SVM で DP ボリュームを作成した場合、そのボリュームは同期先の SVM にレプリケートされません。
* MetroCluster 構成で DP ボリュームを作成した場合、そのソースボリュームは同期先の SVM にレプリケート（ミラーまたはバックアップ）されません。
* MetroCluster 構成では、 System Manager にはボリューム作成用に次のアグリゲートが表示されます。
+
** 通常モードの場合：プライマリサイトの同期元 SVM またはデータ提供用 SVM にボリュームを作成する場合、プライマリサイトのクラスタに属しているアグリゲートのみが表示される。
** 切り替えモードの場合：フェイルオーバー先のサイトの同期先 SVM またはデータ提供用 SVM にボリュームを作成する場合、切り替えられたアグリゲートのみが表示される。


* Cloud Volumes ONTAP のボリュームは暗号化できません。
* デスティネーションクラスタで ONTAP 9.3 より前のバージョンの ONTAP ソフトウェアが実行されている場合、ソースボリュームで暗号化が有効になっていても、デスティネーションボリュームではデフォルトで暗号化が無効になります。


.手順
. [* ストレージ *>* ボリューム *] をクリックします。
. [* 作成 *>* FlexVol の作成 *] をクリックします。
. ボリュームを作成する SVM を参照して選択します。
+
Create Volume （ボリュームの作成）ダイアログボックスが表示されます。このダイアログボックスには次のタブがあります。

+
** 全般
** ストレージ効率
** SnapLock
** Quality of Service の略
** 保護


. [*General] タブで、次の手順を実行します。
+
.. FlexVol ボリュームの名前を指定します。
.. FabricPool * ボタンをクリックして、ボリュームが FabricPool ボリュームであることを指定します。
.. アグリゲートを選択するには、 * Choose * をクリックします。
+
ボリュームが FlexVol ボリュームの場合は FabricPool 対応アグリゲートのみ、 FabricPool 以外の FabricPool FlexVol ボリュームの場合は FabricPool 対応アグリゲートでないアグリゲートのみを選択できます。暗号化されたアグリゲート（ NAE ）を選択すると、作成するボリュームにアグリゲートの暗号化が継承されます。

.. ストレージタイプを選択します。
.. ボリュームのサイズと単位を指定します。
.. Snapshot コピー用にリザーブするスペースの量を指定します。
.. スペースリザベーション * ドロップダウンメニューからスペースリザーブオプションを選択します。
.. ボリュームの暗号化を有効にするには、 * Volume Encryption * チェックボックスを選択します。このオプションを使用できるのは、ボリューム暗号化ライセンスを有効にした場合のみです。また、対応するプラットフォームで暗号化がサポートされている必要があります。


. Storage Efficiency * タブで、次の手順を実行します。
+
.. このボリュームを作成するストレージのタイプを選択します。
+
SnapMirror デスティネーションボリュームを作成する場合は、「 * データ保護 * 」を選択する必要があります。このボリュームへの読み取り専用アクセスが許可されます。

.. ボリュームの階層化ポリシーを指定します。
.. ボリュームのサイズと、 Snapshot コピー用にリザーブする合計ボリュームサイズの割合を指定します。
+
Snapshot コピー用にデフォルトで予約されているスペースは、 SAN ボリュームと VMware ボリュームについては 0% です。NAS ボリュームについては、デフォルトでは 5% です。

.. ボリュームに対して「 * Default 」、「 * Thin Provisioned 」、または「 * Thick Provisioned 」を選択します。
+
シンプロビジョニングが有効になっている場合は、ボリュームにデータが書き込まれたときにのみ、アグリゲートからボリュームにスペースが割り当てられます。

+
[NOTE]
====
*** AFF ストレージシステムの場合、シンプロビジョニングの値は「デフォルト」です。その他のストレージシステムの場合、シックプロビジョニングの値は「デフォルト」です。
*** FabricPool 対応アグリゲートの場合、シンプロビジョニングの値は「 default 」です。


====
.. ボリュームで重複排除を有効にするかどうかを指定します。
+
System Manager では、デフォルトの重複排除スケジュールが使用されます。指定したボリュームサイズが重複排除の実行が可能な最大サイズよりも大きい場合、ボリュームは作成されますが、重複排除は有効になりません。

+
オールフラッシュで最適化されたシステムの場合は、インライン圧縮と `auto` 重複排除スケジュールはデフォルトで有効になっています。



. [*Quality of Service*]( サービス品質 *) タブで、次の手順に従います。
+
.. FlexVol ボリュームのストレージ QoS を有効にしてワークロードのパフォーマンスを管理する場合は、「 Manage Storage Quality of Service 」チェックボックスを選択します。
.. 新しいストレージ QoS ポリシーグループを作成するか、既存のポリシーグループを選択して、 FlexVol の入出力（ I/O ）のパフォーマンスを制御します。
+
|===
| 状況 | 手順 


 a| 
新しいポリシーグループを作成します
 a| 
... [ 新しいポリシーグループ *] を選択します。
... ポリシーグループの名前を指定します。
... 最小スループット制限を指定します。
+
**** System Manager 9.5 では、パフォーマンスがオールフラッシュで最適化されている場合にのみ最小スループット制限を設定できます。System Manager 9.6 では、ポリシーグループに最小スループット制限を設定できます。
**** FabricPool 対応アグリゲートでは、ボリュームの最小スループット制限を設定することはできません。
**** 最小スループット値を指定しない場合、または最小スループット値が 0 に設定されている場合は、自動的に「なし」という値が表示されます。
+
この値では大文字と小文字が区別されます。



... 最大スループット制限を指定します。ポリシーグループに含まれるオブジェクトのワークロードがこのスループット制限を超えないように制限されます。
+
**** 最小スループット制限と最大スループット制限の単位は同じにする必要があります。
**** 最小スループット制限を指定しない場合は、 IOPS 、 B/ 秒、 KB/ 秒、 MB/ 秒などの単位で最大スループット制限を設定できます。
**** 最大スループット値を指定しない場合は ' 自動的に値として無制限が表示されます
+
この値では大文字と小文字が区別されます。指定した単位は無視されます。







 a| 
既存のポリシーグループを選択してください
 a| 
... [ ポリシーグループの選択 ] ダイアログボックスで、 [ 既存のポリシーグループ *] を選択し、 [*Choose*] をクリックして既存のポリシーグループを選択します。
... 最小スループット制限を指定します。
+
**** System Manager 9.5 では、パフォーマンスがオールフラッシュで最適化されている場合にのみ最小スループット制限を設定できます。System Manager 9.6 では、ポリシーグループに最小スループット制限を設定できます。
**** FabricPool 対応アグリゲートでは、ボリュームの最小スループット制限を設定することはできません。
**** 最小スループット値を指定しない場合、または最小スループット値が 0 に設定されている場合は、自動的に「なし」という値が表示されます。
+
この値では大文字と小文字が区別されます。



... 最大スループット制限を指定します。ポリシーグループに含まれるオブジェクトのワークロードがこのスループット制限を超えないように制限されます。
+
**** 最小スループット制限と最大スループット制限の単位は同じにする必要があります。
**** 最小スループット制限を指定しない場合は、 IOPS 、 B/ 秒、 KB/ 秒、 MB/ 秒などの単位で最大スループット制限を設定できます。
**** 最大スループット値を指定しない場合は ' 自動的に値として無制限が表示されます
+
この値では大文字と小文字が区別されます。指定した単位は無視されます。



+
ポリシーグループが複数のオブジェクトに割り当てられている場合、指定した最大スループットはそれらのオブジェクトの合計スループットです。



|===


. [* 保護 *] タブで、次の手順を実行します。
+
.. ボリューム保護を有効にするかどうかを指定します。
+
FabricPool 以外の FlexGroup ボリュームは FabricPool FlexGroup ボリュームで保護できます。

+
FabricPool FlexGroup ボリュームは FabricPool 以外の FlexGroup ボリュームで保護できます。

.. * Replication * タイプを選択します。


+
|===
| 選択したレプリケーションタイプ | 手順 


 a| 
非同期
 a| 
.. * オプション： * レプリケーションタイプと関係タイプがわからない場合は、 * ヘルプ ME 選択 * をクリックし、値を指定して、 * 適用 * をクリックします。
.. 関係タイプを選択します。
+
関係タイプは、ミラー、バックアップ、ミラーとバックアップのいずれかです。

.. デスティネーションボリュームのクラスタと SVM を選択します。
+
選択したクラスタで ONTAP 9.3 より前のバージョンの ONTAP ソフトウェアが実行されている場合、ピア関係が設定された SVM だけが表示されます。選択したクラスタで ONTAP 9.3 以降が実行されている場合は、ピア関係が設定された SVM と許可された SVM が表示されます。

.. ボリューム名サフィックスを必要に応じて変更します。




 a| 
同期
 a| 
.. * オプション： * レプリケーションタイプと関係タイプがわからない場合は、 * ヘルプ ME 選択 * をクリックし、値を指定して、 * 適用 * をクリックします。
.. 同期ポリシーを選択します。
+
同期ポリシーは、 StrictSync または Sync のいずれかです。

.. デスティネーションボリュームのクラスタと SVM を選択します。
+
選択したクラスタで ONTAP 9.3 より前のバージョンの ONTAP ソフトウェアが実行されている場合、ピア関係が設定された SVM だけが表示されます。選択したクラスタで ONTAP 9.3 以降が実行されている場合は、ピア関係が設定された SVM と許可された SVM が表示されます。

.. ボリューム名サフィックスを必要に応じて変更します。


|===
. [ 作成（ Create ） ] をクリックします。
. 作成したボリュームが * Volume * ウィンドウのボリュームリストに含まれていることを確認します。
+
このボリュームは、 UNIX 形式のセキュリティと、所有者に対する UNIX 700 の「 read write execute 」権限で作成されます。



* 関連情報 *

xref:reference_volumes_window.adoc[Volumes （ボリューム）ウィンドウ]
