---
permalink: online-help-96-97/task_creating_protection_policies.html 
sidebar: sidebar 
keywords: create, protection, policies, online, help, system, manager 
summary: System Manager を使用して、非同期ミラーポリシー、バックアップポリシー、またはミラーとバックアップのポリシーを作成し、作成したポリシーをデータ保護関係に適用することができます。 
---
= 保護ポリシーを作成する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
System Manager を使用して、非同期ミラーポリシー、バックアップポリシー、またはミラーとバックアップのポリシーを作成し、作成したポリシーをデータ保護関係に適用することができます。

.手順
. [ * ストレージ * > * SVMs * ] をクリックします。
. 保護ポリシーを作成する Storage Virtual Machine （ SVM ）を選択し、 * SVM 設定 * をクリックします。
. [* Policies * （ポリシー * ） ] ペインで、 [* Protection Policies （保護ポリシー * ） ] をクリックします。
. [ 作成（ Create ） ] をクリックします。
. [ ポリシーの作成 *] ダイアログボックスで、作成するポリシータイプを選択します。
. ポリシー名と転送の優先順位を指定します。
+
転送の優先順位を「低」にすると優先順位が最も低くなり、優先順位が「通常」の転送よりもあとにスケジュールされます。デフォルトでは、優先度は Normal に設定されます。

. 非同期ミラー・タイプのポリシーの場合は '[* すべてのソース Snapshot コピーを転送 *] チェック・ボックスを選択して 'all_source_snapshots' ルールをミラー・ポリシーに含めますこれにより ' ソース・ボリュームのすべての Snapshot コピーがバックアップされます
. [ ネットワーク圧縮を有効にする *] チェックボックスをオンにして、データ転送中に転送されるデータを圧縮します。
. [ コメントの追加 ] をクリックして、ポリシーのコメントを追加します。
. バックアップまたはミラーバックアップタイプのポリシーの場合は、 SnapMirror ラベルとデスティネーションの保持数を指定します。
. [ 作成（ Create ） ] をクリックします。

