---
permalink: online-help-96-97/task_resizing_volumes.html 
sidebar: sidebar 
keywords: resize, volume, capacity, snapshot, copy, online, help 
summary: ボリュームがいっぱいになってきたら、ボリュームのサイズを増やすか、いくつかの Snapshot コピーを削除するか、または Snapshot リザーブを調整します。System Manager のボリュームのサイズ変更ウィザードを使用して、空きスペースを増やすことができます。 
---
= System Manager - ONTAP 9.7 以前を使用してボリュームのサイズを変更します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ボリュームがいっぱいになってきたら、ONTAP System Managerクラシック（ONTAP 9.7以前で使用可能）を使用して、ボリュームのサイズを拡張したり、いくつかのSnapshotコピーを削除したり、Snapshotリザーブを調整したりできます。System Manager のボリュームのサイズ変更ウィザードを使用して、空きスペースを増やすことができます。

.このタスクについて
* 自動拡張が設定されたボリュームの場合、ボリュームの増大分に基づいて、ボリュームの自動拡張の上限を変更できます。
* データ保護ボリュームのサイズは、ミラー関係が解除されている場合やボリュームに対して逆再同期が実行された場合は変更できません。
+
代わりに、コマンドラインインターフェイス（ CLI ）を使用してください。



.手順
. [* ストレージ *>* ボリューム *] をクリックします。
. SVM * フィールドのドロップダウンメニューで、 * すべての SVM * を選択します。
. サイズを変更するボリュームを選択します。
. [ * その他のアクション * > * サイズ変更 * ] をクリックします。
. ウィザードの指示に従って、情報を入力または選択します。
. 詳細を確認し、 [* 終了 ] をクリックしてウィザードを完了します。
. [*Volumes] ウィンドウで、使用可能な容量とボリュームの合計容量に加えた変更を確認します。


* 関連情報 *

xref:reference_volumes_window.adoc[Volumes （ボリューム）ウィンドウ]
