---
permalink: online-help-96-97/task_creating_initiator_groups.html 
sidebar: sidebar 
keywords: create, initiator, group, system, manager, lun, online, help, manage, delete, edit, add 
summary: System Manager を使用して、イニシエータグループを作成できます。イニシエータグループを使用すると、特定の LUN へのホストアクセスを制御できます。イニシエータがアクセスできる LIF を制限するには、ポートセットを使用します。 
---
= System Manager - ONTAP 9.7 以前を使用してイニシエータグループを管理します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP System Manager クラシック（ ONTAP 9.7 以前で使用可能）を使用して、イニシエータグループを管理できます。イニシエータグループを使用すると、特定の LUN へのホストアクセスを制御できます。イニシエータがアクセスできる LIF を制限するには、ポートセットを使用します。



== igroup を作成します

.手順
. [ * ストレージ * > * LUNs * ] をクリックします。
. [* イニシエータ・グループ * ] タブで、 [* 作成 ] をクリックします。
. イニシエータグループの作成 * ダイアログボックスの * 全般 * タブで、 igroup 名、オペレーティング・システム、ホスト・エイリアス名、ポートセット、およびグループでサポートされるプロトコルを指定します。
. [ 作成（ Create ） ] をクリックします。




== igroup を削除します

System Manager のイニシエータグループタブを使用して、イニシエータグループを削除できます。

.作業を開始する前に
イニシエータグループにマッピングされている LUN は、すべて手動でマッピング解除する必要があります。

.手順
. [ * ストレージ * > * LUNs * ] をクリックします。
. イニシエータグループ * タブで、削除するイニシエータグループを 1 つ以上選択し、 * Delete * をクリックします。
. [ 削除（ Delete ） ] をクリックします。
. 削除したイニシエータグループが「 * イニシエータグループ * 」タブに表示されていないことを確認します。




== イニシエータを追加する

System Manager を使用して、イニシエータグループにイニシエータを追加できます。所属先のイニシエータグループが LUN にマッピングされると、イニシエータはその LUN にアクセスできるようになります。

.手順
. [ * ストレージ * > * LUNs * ] をクリックします。
. [* LUN 管理 * ] タブで、イニシエータを追加するイニシエータ・グループを選択し、 [* 編集 ] をクリックします。
. イニシエータグループの編集 * ダイアログボックスで、 * イニシエータ * をクリックします。
. [ 追加（ Add ） ] をクリックします。
. イニシエータ名を指定し、「 * OK 」をクリックします。
. [ 保存して閉じる ] をクリックします。




== イニシエータグループからイニシエータを削除します

System Manager のイニシエータグループタブを使用して、イニシエータを削除できます。イニシエータグループからイニシエータを削除するには、イニシエータのイニシエータグループとの関連付けを解除する必要があります。

.作業を開始する前に
削除するイニシエータを含むイニシエータグループにマッピングされているすべての LUN は、手動でマッピング解除する必要があります。

.手順
. [ * ストレージ * > * LUNs * ] をクリックします。
. イニシエータグループ * タブで、イニシエータを削除するイニシエータグループを選択し、 * Edit * をクリックします。
. イニシエータグループの編集 * ダイアログボックスで、 * Initiators * タブをクリックします。
. テキストボックスからイニシエータを選択して削除し、 * 保存 * をクリックします。
+
イニシエータのイニシエータグループとの関連付けが解除されます。



* 関連情報 *

xref:reference_luns_window.adoc[LUN ウィンドウ]
