---
permalink: online-help-96-97/task_performing_unplanned_switchover.html 
sidebar: sidebar 
keywords: perform, unplanned, switchover, system, manager, metrocluster, site, online, help 
summary: System Manager 9.6 以降では、 MetroCluster サイトの計画外スイッチオーバーを開始できます。この処理は、システム停止や災害が発生した場合に役立ちます。 
---
= 計画外スイッチオーバーの実行
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
System Manager 9.6 以降では、 MetroCluster サイトの計画外スイッチオーバーを開始できます。この処理は、システム停止や災害が発生した場合に役立ちます。

.作業を開始する前に
MetroCluster は正常に動作しているが、ローカルクラスタ（サイト A ）のノードは稼働しており、リモートクラスタ（サイト B ）のノードは停止している必要があります。

.手順
. [[step1]]サイトBが実際に停止していることを確認します。
+
接続エラーが原因でサイト B が停止しているように見える可能性があります。

+
[NOTE]
====
サイト B が稼働している状態でスイッチオーバープロセスを開始すると原因災害が発生する可能性があります。

====
. System Manager で、ローカルの MetroCluster サイト（サイト A ）にクラスタ管理者のクレデンシャルを使用してログオンします。
. [* Configuration * （設定 * ） ] > [* MetroCluster * （ * 設定 *
+
MetroCluster のスイッチオーバー / スイッチバックの処理のウィンドウが表示されます。

. 「 * 次へ * 」をクリックします。
+
MetroCluster のスイッチオーバー / スイッチバックの処理のステータスが表示され、ネゴシエートスイッチオーバーが可能かどうかが System Manager で検証されます。

. 検証プロセスが完了したら、 [* サイト B からサイト A* へのスイッチオーバー ] をクリックしてスイッチオーバープロセスを開始します。
+
スイッチオーバー処理によってサイト B からサイト A に制御が切り替わることを示す警告メッセージが表示されますサイト B のステータスは「到達不能」であり、サイト B のすべてのノードは赤で表示されます。

+
[NOTE]
====
手順に記載されているとおり link:#step1["1."]、サイト B は単に接続されていないだけでなく、実際に停止している必要がありますまた、スイッチオーバー処理によって原因のデータが失われる可能性がある点にも注意してください。

====
. 続行する場合は、チェックボックスがオンになっていることを確認してから、 * はい * をクリックします。
+
スイッチオーバープロセスが開始されます。サイト A とサイト B の状態が、それぞれの構成図の上に表示されます。スイッチオーバー処理が失敗した場合は、エラーメッセージが表示されます。[* 閉じる * ] をクリックします。エラーを修正し、手順からやり直してください link:task_performing_negotiated_planned_switchover.html#step1["1."]

. サイト B で必要なすべてのメンテナンス作業を実行します
. サイト B が稼働していることを確認します。
+
修復プロセスが開始されます。修復の完了を示すメッセージが System Manager に表示されると、サイト B が稼働し、スイッチバックプロセスの準備が行われます。ウィンドウの下部に、サイト A からサイト B へのスイッチバック * ボタンが表示されます。

. に進みます xref:task_performing_switchback.adoc[スイッチバックを実行しています] スイッチバック処理を開始します。

