---
permalink: online-help-96-97/task_editing_vault_relationships.html 
sidebar: sidebar 
keywords: edit, vault, relationships, system, manager, online, help, cluster, schedule 
summary: System Manager を使用して、クラスタの既存のポリシーまたはスケジュールを選択するか、新しいポリシーまたはスケジュールを作成して、バックアップ関係を編集することができます。ただし、既存のポリシーやスケジュールのパラメータを編集することはできません。 
---
= System Manager - ONTAP 9.7 以前を使用してバックアップ関係を管理します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP System Manager クラシック（ ONTAP 9.7 以前で使用可能）を使用して、デスティネーション SVM からバックアップ関係を作成するだけでなく、バックアップ関係を更新、再開、休止、初期化、および削除できます。



== 関係を編集します

System Manager を使用して、クラスタの既存のポリシーまたはスケジュールを選択するか、新しいポリシーまたはスケジュールを作成して、バックアップ関係を編集することができます。ただし、既存のポリシーやスケジュールのパラメータを編集することはできません。

.作業を開始する前に
ソースクラスタとデスティネーションクラスタで正常なピア関係が確立されている必要があります。

.手順
. [* 保護 *>] 、 [* ボリューム関係 *] の順にクリックします。
. ポリシーまたはスケジュールを変更するバックアップ関係を選択し、 * 編集 * をクリックします。
. [ 関係の編集 * （ Edit Relationship * ） ] ダイアログボックスで、適切なアクションを選択する。
+
|===
| 状況 | 実行する処理 


 a| 
既存のポリシーを選択してください。
 a| 
[* 参照 ] をクリックし、既存のポリシーを選択します。    ソースボリュームに関連付けられた Snapshot ポリシーと最も多くのラベルが一致するポリシーを選択できます。



 a| 
新しいポリシーを作成します。
 a| 
.. [ ポリシーの作成 *] をクリックします。
.. ポリシーの名前を指定します。
.. スケジュールされた転送の優先順位を設定します。
+
転送の優先順位を「低」にすると優先順位が最も低くなり、優先順位が「通常」の転送よりもあとにスケジュールされます。デフォルトでは、優先度は Normal に設定されます。

.. 転送中のデータを圧縮するには、 [ ネットワーク圧縮を有効にする *] チェックボックスをオンにします。
.. バックアップポリシーの SnapMirror ラベルとデスティネーションの保持数を指定します。
+
新しい SnapMirror ラベルを有効にするには、同じラベルの Snapshot コピーをソースボリュームに作成する必要があります。

.. [ 作成（ Create ） ] をクリックします。


|===
. 関係のスケジュールを指定します。
+
|===
| 状況 | 実行する処理 


 a| 
既存のスケジュールを割り当てる
 a| 
リストから既存のスケジュールを選択します。



 a| 
新しいスケジュールを作成する
 a| 
.. [ スケジュールの作成 *] をクリックします。
.. スケジュールの名前を指定します。
.. 次のいずれかのオプションを選択します。
+
*** * 基本 *
+
曜日、時刻、および転送間隔だけを指定する場合に選択します。

*** * 詳細 *
+
cron 形式のスケジュールを指定する場合に選択します。



.. [ 作成（ Create ） ] をクリックします。




 a| 
スケジュールを割り当てない
 a| 
「 * なし * 」を選択します。

|===
. [OK] をクリックします。


* 関連情報 *

xref:reference_protection_window.adoc[保護ウィンドウ]



== 関係を初期化

System Manager を使用して、作成時に初期化していないバックアップ関係を初期化することができます。ソース FlexVol ボリュームからデスティネーション FlexVol ボリュームへのベースライン転送が開始されます。

.作業を開始する前に
ソースクラスタとデスティネーションクラスタで正常なピア関係が確立されている必要があります。

.手順
. [* 保護 *>] 、 [* ボリューム関係 *] の順にクリックします。
. 初期化する関係を選択し、 * Operations * > * Initialize * をクリックします。
. [* Initialize （初期化） ] ウィンドウで、 [* Initialize （初期化） ] をクリックします。


.結果
Snapshot コピーが作成されてデスティネーションに転送されます。

この Snapshot コピーは、以降の差分 Snapshot コピーのベースラインとして使用されます。

* 関連情報 *

xref:reference_protection_window.adoc[保護ウィンドウ]



== デスティネーション SVM から関係を作成

System Manager を使用して、バックアップ関係をデスティネーション Storage Virtual Machine （ SVM ）から作成し、バックアップポリシーを割り当てて SnapVault を作成することができます。システムでデータの消失や破損が発生した場合、 SnapVault デスティネーションからバックアップデータをリストアできます。

.作業を開始する前に
* ソースクラスタで ONTAP 8.2.2 以降が実行されている必要があります。
* ソースクラスタとデスティネーションクラスタの両方で SnapVault ライセンスまたは SnapMirror ライセンスが有効になっている必要があります。
+
[NOTE]
====
一部のプラットフォームでは、デスティネーションクラスタで SnapVault ライセンスまたは SnapMirror ライセンスに加えて DPO ライセンスが有効になっていれば、ソースクラスタで SnapVault ライセンスまたは SnapMirror ライセンスが有効になっていなくてもかまいません。

====
* ソースクラスタとデスティネーションクラスタで正常なピア関係が確立されている必要があります。
* デスティネーション SVM の使用可能なスペースを確保する必要があります。
* ソースアグリゲートとデスティネーションアグリゲートはどちらも 64 ビットである必要があります。
* 読み書き可能（ rw ）タイプのソースボリュームを用意しておく必要があります。
* バックアップ（ XDP ）ポリシーが存在する必要があります。
+
バックアップポリシーが存在しない場合は、新規に作成するか、自動的に割り当てられるデフォルトのバックアップポリシー（ XDPDefault ）を使用する必要があります。

* FlexVol ボリュームがオンラインであり、読み取り / 書き込み可能である必要があります。
* SnapLock アグリゲートのタイプが同じである必要があります。
* ONTAP 9.2 以前のバージョンを実行しているクラスタから SAML 認証が有効になっているリモートクラスタに接続する場合は、リモートクラスタでパスワードベースの認証を有効にする必要があります。


.このタスクについて
* System Manager ではカスケード関係はサポートされません。
+
たとえば、関係のデスティネーションボリュームを別の関係のソースボリュームにすることはできません。

* MetroCluster 構成の同期元の SVM と同期先の SVM の間にバックアップ関係を作成することはできません。
* MetroCluster 構成の同期元の SVM 間にバックアップ関係を作成できます。
* 同期元の SVM のボリュームからデータ提供用の SVM のボリュームへのバックアップ関係を作成できます。
* データ提供用の SVM のボリュームから同期元の SVM のデータ保護（ DP ）ボリュームへのバックアップ関係を作成できます。
* バックアップ関係は、 SnapLock 以外のボリューム（プライマリ）と SnapLock のデスティネーションボリューム（セカンダリ）の間でのみ作成できます。
* 一度に保護できるボリュームは最大 25 個です。


.手順
. [* 保護 *>] 、 [* ボリューム関係 *] の順にクリックします。
. [ リレーションシップ *] ウィンドウで、 [ 作成 *] をクリックします。
. [* SVM を参照 * ] ダイアログボックスで、デスティネーションボリュームの SVM を選択します。
. [ 保護関係の作成 * （ Create Protection Relationship Relationship * ） ] ダイアログボックスで、 [ 関係タイプ * （ Relationship Type * ） ] ドロップダウンリストから [ * ボールト * （ * Vault * ） ] を選択する。
. クラスタ、 SVM 、およびソースボリュームを指定します。
+
指定したクラスタで ONTAP 9.3 より前のバージョンの ONTAP ソフトウェアが実行されている場合、ピア関係が設定された SVM だけが表示されます。指定したクラスタで ONTAP 9.3 以降が実行されている場合は、ピア関係が設定された SVM と許可された SVM が表示されます。

. ボリューム名サフィックスを入力します。
+
ボリューム名サフィックスをソースボリュームの名前に追加したものがデスティネーションボリュームの名前として使用されます。

. SnapLock ボリュームを作成する場合は、デフォルトの保持期間を指定します。
+
デフォルトの保持期間は、 1~70 年、または Infinite Volume の任意の値に設定できます。

. *オプション：*参照*をクリックして、ボルトポリシーを変更します。
. 既存のスケジュールのリストから関係のスケジュールを選択します。
. *オプション：*関係の初期化*を選択して、バックアップ関係を初期化します。
. SnapLock アグリゲートを有効にし、 SnapLock Compliance アグリゲートまたは SnapLock Enterprise アグリゲートを選択します。
. FabricPool 対応アグリゲートを有効にし、適切な階層化ポリシーを選択します。
. 選択したボリュームでラベルが一致するかどうかを確認するには、 * Validate * をクリックします。
. [ 作成（ Create ） ] をクリックします。


.結果
デスティネーションボリュームを作成するように選択した場合は、タイプが _dp_is のボリュームが次のデフォルト設定で作成されます。

* 自動拡張は有効になります。
* 重複排除はユーザの設定に応じて有効または無効になります。設定しない場合は、ソースボリュームの設定と同じになります。
* 圧縮は無効になります。
* 言語属性はソースボリュームと同じになります。


デスティネーションボリュームとソースボリュームの間のバックアップ関係が作成されます。関係を初期化するように選択した場合は、ベース Snapshot コピーがデスティネーションボリュームに転送されます。



== 関係を更新します

System Manager を使用して、スケジュールされていない差分更新を手動で開始できます。予定された停電、スケジュールされた保守、またはデータ移行によるデータ損失を防ぐために、手動更新が必要になる場合があります。

.作業を開始する前に
バックアップ関係を初期化しておく必要があります。

.手順
. [* 保護 *>] 、 [* ボリューム関係 *] の順にクリックします。
. データを更新する関係を選択し、 * Operations * > * Update * をクリックします。
. 次のいずれかのオプションを選択します。
+
** 「ポリシーに従う」を選択し、ソースボリュームとデスティネーションボリュームの間の最新の共通の Snapshot コピーから差分転送を実行します。
** Select Snapshot copy * を選択し、転送する Snapshot コピーを指定します。


. *オプション：*転送に使用されるネットワーク帯域幅を制限し、最大転送速度を指定するには、転送帯域幅を*に制限するを選択します。
. [ 更新（ Update ） ] をクリックします。
. [ * 詳細 * ] タブで転送ステータスを確認します。




== 関係を削除します

System Manager を使用して、ソースボリュームとデスティネーションボリュームの間のバックアップ関係を終了し、ソースから Snapshot コピーを解放できます。

.このタスクについて
関係を解放すると、バックアップ関係で使用されているベース Snapshot コピーがソースボリュームから完全に削除されます。バックアップ関係を再作成するには、コマンドラインインターフェイス（ CLI ）を使用して、ソースボリュームから再同期操作を実行する必要があります。

.手順
. [* 保護 *>] 、 [* ボリューム関係 *] の順にクリックします。
. バックアップ関係を削除するボリュームを選択し、 * 削除 * をクリックします。
. 確認のチェックボックスをオンにし、 * 削除 * をクリックします。
+
ベース Snapshot コピーを解放するチェックボックスを選択すると、バックアップ関係に使用されているベース Snapshot コピーもソースボリュームから削除できます。

+
関係を解放せずに、バックアップ関係に対して作成されたベース Snapshot コピーをソースボリュームから削除するには、 CLI を使用してソースクラスタに対して解放処理を実行する必要があります。





== 関係を再開

System Manager を使用して、休止中のバックアップ関係を再開できます。関係を再開すると、デスティネーション FlexVol ボリュームへの通常のデータ転送が再開され、バックアップアクティビティもすべて再開されます。

.手順
. [* 保護 *>] 、 [* ボリューム関係 *] の順にクリックします。
. データ転送を再開する関係を選択し、 * Operations * > * Resume * をクリックします。
. [* Resume （続行） ] ウィンドウで、 [* Resume （続行） ] をクリックします。


.結果
通常のデータ転送が再開されます。関係に対して転送がスケジュールされている場合、その転送は次回のスケジュールから開始されます。



== 関係を休止します

System Manager を使用して、バックアップ関係を休止することでデスティネーション FlexVol へのデータ転送を無効にすることができます。

.手順
. [* 保護 *>] 、 [* ボリューム関係 *] の順にクリックします。
. スケジュールされたデータ転送を停止する関係を選択し、 * Operations * > * Quiesce * をクリックします。
. [ * 休止 ] ウィンドウで、 [ * 休止 ] をクリックします。


.結果
実行中の転送がない場合、転送ステータスは Quiesced と表示されます。転送が進行中の場合、転送は影響を受けず、転送が完了するまで転送ステータスは Quiescing と表示されます。

* 関連情報 *

xref:reference_protection_window.adoc[保護ウィンドウ]
