---
permalink: online-help-96-97/task_enabling_storage_efficiency_on_volume.html 
sidebar: sidebar 
keywords: system, manager, enable, storage, efficiency, volume, deduplication, online, help 
summary: System Manager を使用して Storage Efficiency を有効にして、ボリュームで重複排除とデータ圧縮の両方を設定したり重複排除のみを設定したりして、ストレージスペースを節約できます。ボリュームの作成時に有効にしなかった場合は、あとからボリュームを編集して Storage Efficiency を有効にすることができます。 
---
= System Manager - ONTAP 9.7 以前を使用して、ボリュームで Storage Efficiency を有効にします
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP System Manager クラシック（ ONTAP 9.7 以前で使用可能）を使用して Storage Efficiency を有効にし、ボリュームで重複排除とデータ圧縮の両方を設定したり重複排除のみを設定したりして、ストレージスペースを節約できます。ボリュームの作成時に有効にしなかった場合は、あとからボリュームを編集して Storage Efficiency を有効にすることができます。

.作業を開始する前に
* ボリュームはオンラインである必要があります。
* ポリシーベースの重複排除スケジュールを使用する場合は、効率化ポリシーを作成しておく必要があります。


.このタスクについて
* バックグラウンド圧縮を有効にできるのは、バックグラウンド重複排除が有効になっている場合だけです。
* インライン圧縮は、バックグラウンド重複排除の有効、無効に関係なく有効にすることができます。同様に、インライン重複排除機能も、バックグラウンド重複排除機能の有効、無効に関係
* インライン重複排除を有効にできるのは、オールフラッシュで最適化されたアグリゲートに含まれるボリュームと Flash Pool アグリゲートに含まれるボリュームだけです。
* System Manager 9.6 以降では、 FlexGroup DP ボリュームについての Storage Efficiency の編集がサポートされます。


.手順
. [* ストレージ *>* ボリューム *] をクリックします。
. SVM * フィールドのドロップダウンメニューで、 * すべての SVM * を選択します。
. Storage Efficiency を有効にするボリュームを選択し、 * Edit * をクリックします。
. ボリュームの編集 * ダイアログボックスで、 * Storage Efficiency * をクリックします。
. バックグラウンド重複排除 * チェックボックスを選択します。
. 次のいずれかの方法を選択して重複排除を実行します。
+
|===
| 重複排除の実行対象 | 作業 


 a| 
Storage Efficiency ポリシーに基づきます
 a| 
.. [ * ポリシーベース * ] オプションが選択されていることを確認します。
.. 「 * Choose * 」をクリックし、ストレージ効率化ポリシーを選択します。
.. [OK] をクリックします。




 a| 
必要に応じて
 a| 
オンデマンド * オプションを選択します。

|===
. バックグラウンド圧縮を有効にするには、 * バックグラウンド圧縮 * チェックボックスを選択します。
+
オールフラッシュで最適化されたアグリゲートに含まれるボリュームでバックグラウンド圧縮を有効にすることはできません。

. ボリュームへの書き込み中にデータを圧縮するには、「 * インライン圧縮 * 」チェックボックスを選択します。
+
デフォルトで、インライン圧縮は、オールフラッシュで最適化されたアグリゲートに含まれるボリュームで有効になります。

. データがディスクに書き込まれる前に重複排除を実行するには、「インライン重複排除」チェックボックスをオンにします。
+
デフォルトで、インライン重複排除は、オールフラッシュで最適化されたアグリゲートに含まれるボリュームで有効になります。

. [ 保存して閉じる ] をクリックします。


* 関連情報 *

xref:reference_volumes_window.adoc[Volumes （ボリューム）ウィンドウ]
