---
permalink: online-help-96-97/task_creating_snaplock_volumes.html 
sidebar: sidebar 
keywords: create, snaplock, volume, online, help, system, manager 
summary: System Manager を使用して、 SnapLock Compliance ボリュームまたは SnapLock Enterprise ボリュームを作成できます。ボリュームの作成時に、保持期間を設定したり、ボリュームのデータを自動的に WORM 状態に設定するかどうかを選択したりすることもできます。 
---
= System Manager ONTAP 9.7 以前を使用して SnapLock ボリュームを作成します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP システムマネージャクラシック（ONTAP 9.7以前で使用可能）を使用して、SnapLock ComplianceボリュームまたはSnapLock Enterpriseボリュームを作成できます。ボリュームの作成時に、保持期間を設定したり、ボリュームのデータを自動的に WORM 状態に設定するかどうかを選択したりすることもできます。

.作業を開始する前に
* SnapLock ライセンスがインストールされている必要があります。
* SnapLock アグリゲートがオンラインになっている必要があります。
* 暗号化されたボリュームを作成するには、 System Manager を使用してボリューム暗号化ライセンスをインストールし、コマンドラインインターフェイス（ CLI ）を使用して「 key-manager setup 」を有効にしておく必要があります。
+
「 key-manager setup 」を有効にした後、 Web ブラウザを更新する必要があります。



.このタスクについて
* SnapLock Enterprise ボリューム全体または SnapLock Enterprise ボリュームのファイルは削除できますが、 SnapLock Enterprise ボリュームのファイル内のデータだけを削除することはできません。
* データがボリュームにコミットされている場合、 SnapLock Compliance ボリュームは削除できません。
* Cloud Volumes ONTAP のボリュームは暗号化できません。
* デスティネーションクラスタで ONTAP 9.3 より前のバージョンの ONTAP ソフトウェアが実行されている場合、ソースボリュームで暗号化が有効になっていても、デスティネーションボリュームではデフォルトで暗号化が無効になります。


.手順
. [* ストレージ *>* ボリューム *] をクリックします。
. [* 作成 *>* FlexVol の作成 *] をクリックします。
. ボリュームを作成する Storage Virtual Machine （ SVM ）を参照して選択します。
. ボリュームのデフォルト名を変更する場合は、 * Create Volume * （ボリュームの作成）ダイアログボックスで新しい名前を指定します。
+
SnapLock Compliance ボリュームの名前は、作成後に変更することはできません。

. ボリュームのコンテナアグリゲートを選択します。
+
SnapLock ボリュームを作成するには、 SnapLock Compliance アグリゲートまたは SnapLock Enterprise アグリゲートを選択する必要があります。ボリュームの SnapLock タイプ SnapLock はアグリゲートから継承され、ボリュームの作成後は変更できないため、適切なアグリゲートを選択する必要があります。

. ボリュームの暗号化を有効にするには、 * Volume Encryption * チェックボックスを選択します。
+
このオプションを使用できるのは、ボリューム暗号化ライセンスを有効にした場合のみです。また、対応するプラットフォームで暗号化がサポートされている必要があります。

. このボリュームを作成するストレージのタイプを選択します。
+
SnapMirror デスティネーションボリュームを作成する場合は、「 * データ保護 * 」を選択する必要があります。このボリュームへの読み取り専用アクセスが許可されます。

. ボリュームのサイズと、 Snapshot コピー用にリザーブする合計ボリュームサイズの割合を指定します。
+
Snapshot コピー用にデフォルトで予約されているスペースは、 SAN ボリュームと VMware ボリュームについては 0% です。NAS ボリュームについては、デフォルトでは 5% です。

. *オプション：*シンプロビジョニング*を選択して、ボリュームのシンプロビジョニングを有効にします。
+
シンプロビジョニングが有効になっている場合は、ボリュームにデータが書き込まれたときにのみ、アグリゲートからボリュームにスペースが割り当てられます。

. *オプション：* Storage Efficiency *タブで必要な変更を行い、ボリュームで重複排除を有効にします。
+
System Manager では、デフォルトの重複排除スケジュールが使用されます。指定したボリュームサイズが重複排除の実行が可能な最大サイズよりも大きい場合、ボリュームは作成されますが、重複排除は有効になりません。

. [*SnapLock *] タブを選択し、次の手順を実行します。
+
.. *オプション：*自動コミット期間を指定します。
+
ボリューム内のファイルに変更がなかった場合に WORM 状態にコミットされるまでの期間です。ファイルを手動で WORM 状態に設定するには、自動コミット設定として「 * not specified * 」を選択する必要があります。

+
値は 5 分から 10 年の範囲で指定する必要があります。

.. 最小保持期間と最大保持期間を指定します。
+
値は 1~70 年、または Infinite Volume の範囲で指定する必要があります。

.. デフォルトの保持期間を選択します。
+
デフォルトの保持期間は、最小保持期間と最大保持期間の間の値に設定します。



. *オプション：* Quality of Service *タブで* Manage Storage Quality of Service *チェックボックスを選択して、FlexVol ボリュームのストレージQoSを有効にし、ワークロードのパフォーマンスを管理します。
. ストレージ QoS ポリシーグループを作成するか、または既存のポリシーグループを選択して、 FlexVol の入出力（ I/O ）のパフォーマンスを制御します。
+
|===
| 状況 | 手順 


 a| 
ストレージ QoS ポリシーグループを作成する
 a| 
.. [ 新しいポリシーグループ *] を選択します。
.. ポリシーグループの名前を指定します。
.. 最小スループット制限を指定します。
+
*** System Manager 9.5 では、パフォーマンスがオールフラッシュで最適化されている場合にのみ最小スループット制限を設定できます。System Manager 9.6 では、 ONTAP Select Premium システムにも最小スループット制限を設定できます。
*** FabricPool 対応アグリゲートでは、ボリュームの最小スループット制限を設定することはできません。
*** 最小スループット値を指定しない場合、または最小スループット値が 0 に設定されている場合は、自動的に「なし」という値が表示されます。
+
この値では大文字と小文字が区別されます。



.. 最大スループット制限を指定します。ポリシーグループに含まれるオブジェクトのワークロードがこのスループット制限を超えないように制限されます。
+
*** 最小スループット制限と最大スループット制限の単位は同じにする必要があります。
*** 最小スループット制限を指定しない場合は、 IOPS 、 B/ 秒、 KB/ 秒、 MB/ 秒などの単位で最大スループット制限を設定できます。
*** 最大スループット値を指定しない場合は ' 自動的に値として無制限が表示されます
+
この値では大文字と小文字が区別されます。指定した単位は無視されます。







 a| 
既存のポリシーグループを選択してください
 a| 
.. [ ポリシーグループの選択 ] ダイアログボックスで、 [ 既存のポリシーグループ *] を選択し、 [*Choose*] をクリックして既存のポリシーグループを選択します。
.. 最小スループット制限を指定します。
+
*** System Manager 9.5 では、パフォーマンスがオールフラッシュで最適化されている場合にのみ最小スループット制限を設定できます。System Manager 9.6 では、 ONTAP Select Premium システムにも最小スループット制限を設定できます。
*** FabricPool 対応アグリゲートでは、ボリュームの最小スループット制限を設定することはできません。
*** 最小スループット値を指定しない場合、または最小スループット値が 0 に設定されている場合は、自動的に「なし」という値が表示されます。
+
この値では大文字と小文字が区別されます。



.. 最大スループット制限を指定します。ポリシーグループに含まれるオブジェクトのワークロードがこのスループット制限を超えないように制限されます。
+
*** 最小スループット制限と最大スループット制限の単位は同じにする必要があります。
*** 最小スループット制限を指定しない場合は、 IOPS 、 B/ 秒、 KB/ 秒、 MB/ 秒などの単位で最大スループット制限を設定できます。
*** 最大スループット値を指定しない場合は ' 自動的に値として無制限が表示されます
+
この値では大文字と小文字が区別されます。指定した単位は無視されます。



+
ポリシーグループが複数のオブジェクトに割り当てられている場合、指定した最大スループットはそれらのオブジェクトの合計スループットです。



|===
. ボリュームを保護するには、 * 保護 * タブで * ボリューム保護 * を有効にします。
. [* 保護 *] タブで、 [* レプリケーション *] タイプを選択します。
+
|===
| 選択したレプリケーションタイプ | 手順 


 a| 
非同期
 a| 
.. * オプション： * レプリケーションタイプと関係タイプがわからない場合は、 * ヘルプ ME 選択 * をクリックし、値を指定して、 * 適用 * をクリックします。
.. 関係タイプを選択します。
+
関係タイプは、ミラー、バックアップ、ミラーとバックアップのいずれかです。

.. デスティネーションボリュームのクラスタと SVM を選択します。
+
選択したクラスタで ONTAP 9.3 より前のバージョンの ONTAP ソフトウェアが実行されている場合、ピア関係が設定された SVM だけが表示されます。選択したクラスタで ONTAP 9.3 以降が実行されている場合は、ピア関係が設定された SVM と許可された SVM が表示されます。

.. ボリューム名サフィックスを必要に応じて変更します。




 a| 
同期
 a| 
.. * オプション： * レプリケーションタイプと関係タイプがわからない場合は、 * ヘルプ ME 選択 * をクリックし、値を指定して、 * 適用 * をクリックします。
.. 同期ポリシーを選択します。
+
同期ポリシーは、 StrictSync または Sync のいずれかです。

.. デスティネーションボリュームのクラスタと SVM を選択します。
+
選択したクラスタで ONTAP 9.3 より前のバージョンの ONTAP ソフトウェアが実行されている場合、ピア関係が設定された SVM だけが表示されます。選択したクラスタで ONTAP 9.3 以降が実行されている場合は、ピア関係が設定された SVM と許可された SVM が表示されます。

.. ボリューム名サフィックスを必要に応じて変更します。


|===
. [ 作成（ Create ） ] をクリックします。
. 作成したボリュームが * Volume * ウィンドウのボリュームリストに含まれていることを確認します。


.結果
このボリュームは、 UNIX 形式のセキュリティと、所有者に対する UNIX 700 の「 read write execute 」権限で作成されます。
