---
permalink: online-help-96-97/task_creating_svm.html 
sidebar: sidebar 
keywords: svm, create, storage, virtual, machine, online, help 
summary: Storage Virtual Machine （ SVM ）ウィンドウを使用すると、設定が完了した SVM を作成できます。作成した SVM にストレージオブジェクトを作成すると、 SVM からデータが提供されるようになります。 
---
= System Manager - ONTAP 9.7以前のバージョンでSVMを作成します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP System Manager クラシック（ ONTAP 9.7 以前で使用可能）では、 Storage Virtual Machine （ SVM ）ウィンドウを使用して完全に設定された SVM を作成できます。作成した SVM にストレージオブジェクトを作成すると、 SVM からデータが提供されるようになります。

.作業を開始する前に
* アグリゲートを作成してオンラインにしておく必要があります。
* アグリゲートに SVM のルートボリューム用の十分なスペースがあることを確認しておく必要があります。


.手順
. SVM の名前を入力します。
. SVM のデータプロトコルを選択します。
+
|===
| 状況 | 作業 


 a| 
Active Directory を使用して CIFS サーバを設定し、 CIFS プロトコルを有効にします
 a| 
.. [* Active Directory* （ Active Directory * ） ] ボックスを選択します。
.. Active Directory の管理者名を入力します。
.. Active Directory の管理者パスワードを入力します。
.. CIFS サーバの名前を入力します。
.. Active Directory ドメインの名前を入力します。
.. 要件に応じて、この SVM にある * 1 つのデータ LIF を選択するか、この SVM * にあるノードに 1 つのデータ LIF を選択します。
.. データ LIF の IP アドレス、ネットマスク、ゲートウェイ、ポートなどの詳細を指定します。
.. DNS の詳細を指定します。




 a| 
ワークグループを使用して CIFS サーバを設定し、 CIFS プロトコルを有効にします
 a| 
.. [ ワークグループ *] ボックスを選択します。
.. ワークグループの名前を入力します。
.. CIFS サーバの名前を入力します。
.. 要件に応じて、この SVM に * 1 つのデータ LIF * を選択するか、この SVM にあるノードに 1 つのデータ LIF * チェックボックスを選択します。
.. データ LIF の IP アドレス、ネットマスク、ゲートウェイ、ポートなどの詳細を指定します。




 a| 
NFS プロトコルを有効にします
 a| 
.. [* NFS* ] ボックスを選択します。
.. 要件に応じて、この SVM に * 1 つのデータ LIF * を選択するか、この SVM にあるノードに 1 つのデータ LIF * チェックボックスを選択します。
.. データ LIF の IP アドレス、ネットマスク、ゲートウェイ、ポートなどの詳細を指定します。




 a| 
iSCSI プロトコルを有効にします
 a| 
.. [* iSCSI * ] ボックスを選択します。
.. データ LIF の IP アドレス、ネットマスク、ゲートウェイ、ポートなどの詳細を指定します。




 a| 
FC / FCoE プロトコルを有効にする
 a| 
.. FC / FCoE * ボックスを選択します。
.. FC または FCoE プロトコル用の FC / FCoE ポートを選択します。
+
[NOTE]
====
各ノードで少なくとも 1 つのポート（ FC プロトコル用と FCoE プロトコル用）が正しく設定されている必要があります。

====




 a| 
NVMe プロトコルを有効にします
 a| 
.. [* NVMe* ] ボックスを選択します。
.. NVMe プロトコル用の NVMe ポートを選択します。
+
[NOTE]
====
NVMe を設定するには、いずれかのノードに NVMe 対応アダプタが少なくとも 1 つ必要です。        また、 ONTAP 9.5 以降では、 SVM に関連付けられた HA ペアの各ノードに対して、少なくとも 1 つの NVMe LIF が設定されている必要があります。ペアの各ノードに対して作成できる NVMe LIF の数は 2 つまでです。

====


|===
. *オプション：*詳細オプション*アイコンをクリックし、デフォルト言語、セキュリティ形式、CIFSサーバの詳細、NFSの詳細などの詳細オプションを設定します。
. Submit and Continue * をクリックして SVM を作成します。




== 次に何をするか

Submit and Continue （送信して続行）をクリックした場合、 Summary （サマリ）ウィンドウで指定した詳細を確認し、 * Manage Your Cluster （クラスタの管理） * をクリックして System Manager を起動するか、 * Provision an Application （アプリケーションのプロビジョニング） * をクリックしてストレージアプリケーションをプロビジョニングするか、 * Export Configuration * をクリックして構成ファイルをダウンロードする必要があります。
