---
permalink: online-help-96-97/task_performing_negotiated_planned_switchover.html 
sidebar: sidebar 
keywords: online, help, perform, negotiated, switchover, system, help 
summary: System Manager 9.6 以降では、 MetroCluster サイトのネゴシエート（計画的）スイッチオーバーを開始できます。この処理は、サイトでディザスタリカバリのテストや計画的なメンテナンスを実行する場合に役立ちます。 
---
= ネゴシエートスイッチオーバーの実行
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
System Manager 9.6 以降では、 MetroCluster サイトのネゴシエート（計画的）スイッチオーバーを開始できます。この処理は、サイトでディザスタリカバリのテストや計画的なメンテナンスを実行する場合に役立ちます。

.手順
. [[step1]] System Managerで、ローカルのMetroClusterサイト（サイトA）にクラスタ管理者のクレデンシャルを使用してログオンします。
. [* Configuration * （設定 * ） ] > [* MetroCluster * （ * 設定 *
+
MetroCluster のスイッチオーバー / スイッチバックの処理のウィンドウが表示されます。

. 「 * 次へ * 」をクリックします。
+
MetroCluster のスイッチオーバーとスイッチバックの処理のステータスが表示され、ネゴシエートスイッチオーバーが可能かどうかが System Manager で検証されます。

. 検証プロセスが完了したら、次のいずれかの手順を実行します。
+
** 検証が成功した場合は、手順に進みます link:#step5["5."]。
** 検証が失敗し、サイト B が稼働している場合は、サブシステムの問題や NVRAM のミラーリングが同期されていないなどのエラーが発生しています。次のいずれかのプロセスを実行できます。
+
*** エラーの原因となっている問題を修正し、 [* 閉じる *] をクリックして、ステップからやり直してください link:#step1["1."]。
*** サイト B のノードを停止し、 * 閉じる * をクリックして、の手順を実行します xref:task_performing_unplanned_switchover.adoc[計画外スイッチオーバーの実行]。


** 検証が失敗し、サイト B が停止している場合は、接続に問題がある可能性が高くなります。サイト B が本当に停止していることを確認し、の手順を実行します xref:task_performing_unplanned_switchover.adoc[計画外スイッチオーバーの実行]。


. [[step5]]*[サイトBからサイトAへのスイッチオーバー]*をクリックしてスイッチオーバープロセスを開始します。
+
スイッチオーバー処理によってサイト B のすべてのデータ SVM が停止し、サイト A で再起動されることを示す警告メッセージが表示されます

. 続行する場合は、 * はい * をクリックします。
+
スイッチオーバープロセスが開始されます。サイト A とサイト B の状態が、それぞれの構成図の上に表示されます。スイッチオーバー処理が失敗した場合は、エラーメッセージが表示されます。[* 閉じる * ] をクリックします。エラーを修正し、手順からやり直してください link:#step1["1."]

. 修復の完了を示すメッセージが System Manager に表示されるまで待ちます。
+
修復が完了すると、サイト B が稼働し、スイッチバックプロセスの準備が行われます。

+
スイッチバックプロセスの準備が完了すると、ウィンドウの下部にあるスイッチバックの * サイト A からサイト B へのスイッチバック * ボタンがアクティブになります。

. スイッチバック処理を続行するには、の手順を実行します xref:task_performing_switchback.adoc[スイッチバックを実行しています]。

