---
permalink: online-help-96-97/task_configuring_cifs_nfs_protocols_on_svms.html 
sidebar: sidebar 
keywords: system, manager, configuring, cifs, nfs, protocols, svm, online, help 
summary: System Manager で Storage Virtual Machine （ SVM ）の CIFS プロトコルおよび NFS プロトコルを設定して、 NAS クライアントにファイルレベルのデータアクセスを提供できます。CIFS プロトコルを有効にする場合は、データ LIF と CIFS サーバを作成する必要があります。NFS プロトコルを有効にする場合は、データ LIF と NIS の詳細を指定できます。 
---
= System Manager - ONTAP 9.7 以前を使用して、 SVM に CIFS プロトコルと NFS プロトコルを設定します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP System Managerクラシック（ONTAP 9.7以前で使用可能）を使用して、Storage Virtual Machine（SVM）でCIFSプロトコルおよびNFSプロトコルを設定し、NASクライアントにファイルレベルのデータアクセスを提供できます。CIFS プロトコルを有効にする場合は、データ LIF と CIFS サーバを作成する必要があります。NFS プロトコルを有効にする場合は、データ LIF と NIS の詳細を指定できます。

.作業を開始する前に
* SVM で設定または有効にするプロトコルは、ライセンス取得済みである必要があります。
+
設定するプロトコルが SVM で有効になっていない場合は、 Storage Virtual Machine の編集ウィンドウを使用して SVM のプロトコルを有効にできます。

* CIFS プロトコルを設定するには、 Active Directory 、組織単位、および管理用アカウントのクレデンシャルが必要です。


.このタスクについて
SnapLock アグリゲートは、ボリュームの自動作成の対象としては考慮されません。

.手順
. SVM の作成時にプロトコルを設定していない場合は、 * Storage * > * SVMs * をクリックします。
. SVM を選択し、 * SVM 設定 * をクリックします。
. [* Protocols] ペインで、設定するプロトコルをクリックします。
. 「 * データ LIF の設定 * 」セクションで、 CIFS と NFS の両方に対して同じデータ LIF の設定を保持する場合は、「 * CIFS データ LIF の NFS クライアント用の設定を保持する * 」チェックボックスを選択します。
+
CIFS と NFS の両方に対して同じデータ LIF の設定を使用しない場合は、 CIFS と NFS のそれぞれについて、 IP アドレスとポートを個別に指定する必要があります。

. 次のいずれかのオプションを選択して、 IP アドレスを指定します。
+
|===
| 状況 | 作業 


 a| 
サブネットを使用して IP アドレスを指定します
 a| 
.. サブネットを使用する * を選択します。
.. Add Details ダイアログボックスで、 IP アドレスを割り当てるサブネットを選択します。
+
クラスタ間 LIF の場合、選択した IPspace に関連付けられているサブネットだけが表示されます。

.. インターフェイスに特定の IP アドレスを割り当てる場合は、 * 特定の IP アドレスを使用する * を選択して、 IP アドレスを入力します。
+
指定した IP アドレスがサブネット内にない場合、追加されます。

.. [OK] をクリックします。




 a| 
サブネットを使用せずに手動で IP アドレスを指定します
 a| 
.. サブネットなし * を選択します。
.. [ 詳細の追加 ] ダイアログボックスで、次の手順を実行します。
+
... IP アドレスとネットワークマスクまたはプレフィックスを指定します。
... オプション：ゲートウェイを指定します。
... Destination フィールドにデフォルト値を使用しない場合は、新しい宛先値を指定します。
+
送信先の値を指定しない場合は、 IP アドレスのファミリーに基づいて、 Destination フィールドにデフォルト値が設定されます。



+
ルートが存在しない場合は、ゲートウェイとデスティネーションに基づいて新しいルートが自動的に作成されます。

.. [OK] をクリックします。


|===
. データ LIF を作成するポートを指定します。
+
.. [* 参照 ] をクリックします。
.. [ ネットワークポートまたはアダプタの選択 *] ダイアログボックスで、ポートを選択します。
.. [OK] をクリックします。


. 次の手順を実行して CIFS サーバを設定します。
+
.. CIFS サーバを作成するには、次の情報を指定します。
+
*** CIFS サーバ名
*** CIFS サーバに関連付ける Active Directory
*** CIFS サーバに関連付ける Active Directory ドメイン内の組織単位（ OU ）を指定します
+
デフォルトでは、このパラメータは CN=Computers に設定されます。

*** OU に CIFS サーバを追加するための十分な権限がある管理用アカウントのクレデンシャル


.. *オプション：*このSVMのすべての共有へのアクセス時にデータを暗号化*を選択すると、SVMのすべての共有でSMB 3.0暗号化が有効になります。
.. プロトコルを設定する際に、共有名とそのサイズ、およびアクセス権を指定して CIFS ストレージ用のボリュームをプロビジョニングします。
.. 特定の共有で SMB 3.0 暗号化を有効にするには、この共有にアクセスしているときに * データを暗号化 * を選択します。


. *オプション：* NISサービスを設定します。
+
.. SVM の NIS サービスを設定する場合は、 NIS サーバの IP アドレスと NIS ドメイン名を指定します。
.. 「 nis 」ネームサービスソースを追加するデータベースタイプを選択します。
.. エクスポート名、サイズ、およびアクセス権を指定して NFS ストレージ用のボリュームをプロビジョニングします。


. [Submit & Continue] をクリックします。


.結果
指定した設定で CIFS サーバと NIS ドメインが設定され、データ LIF が作成されます。データ LIF には、デフォルトで管理アクセスが付与されます。設定の詳細は概要ページで確認できます。
