---
permalink: online-help-96-97/task_provisioning_storage_through_aggregates.html 
sidebar: sidebar 
keywords: provision, storage, aggregates, snaplock, fabricpool, online, help, flash, pool 
summary: ストレージの推奨事項に基づいてアグリゲートを作成できます。また、要件に応じてストレージを手動で作成することもできます。System Manager を使用して、 1 つ以上のボリュームにストレージを提供するための Flash Pool アグリゲート、 SnapLock アグリゲート、および FabricPool 対応アグリゲートを作成できます。 
---
= System Manager - ONTAP 9.7 以前を使用して、アグリゲートを使用してストレージをプロビジョニングします
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP System Manager クラシック（ ONTAP 9.7 以前で使用可能）を使用して、ストレージの推奨事項に基づいてアグリゲートを作成したり、要件に応じて手動でアグリゲートを作成したりできます。System Manager を使用して、 1 つ以上のボリュームにストレージを提供するための Flash Pool アグリゲート、 SnapLock アグリゲート、および FabricPool 対応アグリゲートを作成できます。

.作業を開始する前に
アグリゲートを作成するための十分なスペアディスクが必要です。

.このタスクについて
System Manager を使用して次の操作を実行することはできません。

* サイズが異なるディスクを組み合わせる。これは、サイズが異なるスペアディスクが十分にある場合でも同様です。
+
最初は同じサイズのディスクでアグリゲートを作成しておき、あとでサイズが異なるディスクを追加します。

* チェックサムタイプが異なるディスクを組み合わせる。
+
最初は単一のチェックサムタイプのアグリゲートを作成しておき、あとで別のチェックサムタイプのストレージを追加します。





== ストレージの推奨事項に基づいてアグリゲートを作成

ONTAP System Manager クラシック（ ONTAP 9.7 以前で使用可能）を使用して、ストレージの推奨事項に基づいてアグリゲートを作成できます。ストレージシステムの構成が System Manager で分析され、作成するアグリゲートの数、利用可能なノード、利用可能なスペアディスクなど、ストレージの推奨事項が提示されます。

.このタスクについて
* Cloud Volumes ONTAP 、 ONTAP Select 、 MetroCluster の各構成では、ストレージに関する推奨事項に基づいてアグリゲートを作成することはできません。
* エラーがある場合は画面に表示されます。
+
エラーを修正してストレージの推奨事項に基づいてアグリゲートを作成するか、アグリゲートを手動で作成することができます。



.手順
. 次のいずれかの方法を使用してアグリゲートを作成します。
+
** [ * アプリケーションと階層 * > * ストレージ階層 * > * アグリゲートの追加 * ] をクリックします。
** [ * ストレージ * > * アグリゲートとディスク * > * アグリゲート * > * 作成 * ] をクリックします。


. ストレージの推奨事項を確認し、 * Submit * をクリックします。
+
情報ダイアログボックスにアグリゲートのステータスが表示されます。

. Run in Background * （バックグラウンドで実行）をクリックして、 * Aggregates * ウィンドウに移動します。
. 更新 * をクリックすると、作成されたアグリゲートが表示されます。




== アグリゲートを手動で作成する

HDD のみまたは SSD のみで構成されるアグリゲートは、 ONTAP System Manager クラシック（ ONTAP 9.7 以前で使用可能）を使用して手動で作成できます。

.作業を開始する前に
ディスクはすべて同じサイズである必要があります。

.このタスクについて
* ONTAP Select で 4 ノードクラスタのアグリゲートを作成する場合、デフォルトではミラーアグリゲートのオプションが選択されます。
* ONTAP 9.0 以降では、ディスクサイズが 10TB 以上のアグリゲートを作成できます。
* アグリゲートディスクのディスクタイプが FSAS または MSATA で、ディスクサイズが 10TB 以上の場合、選択できる RAID タイプは RAID-TEC のみです。


.手順
. 次のいずれかの方法を使用してアグリゲートを作成します。
+
** [ * アプリケーションと階層 * > * ストレージ階層 * > * アグリゲートの追加 * ] をクリックします。
** [ * ストレージ * > * アグリゲートとディスク * > * アグリゲート * > * 作成 * ] をクリックします。


. アグリゲートを作成するには、 * アグリゲートを手動で作成 * オプションを有効にしてください。
. アグリゲートを作成するには、次の手順
+
.. アグリゲート名、ディスクタイプ、およびアグリゲートに含めるディスクまたはパーティションの数を指定します。
+
ディスクサイズが最大のディスクグループに対して、最小限のホットスペアのルールが適用されます。

.. *オプション：*アグリゲートのRAID構成を変更します。
+
... [ 変更（ Change ） ] をクリックします。
... RAID構成の変更*ダイアログボックスで、RAIDタイプとRAIDグループサイズを指定します。
+
共有ディスクでは、 RAID DP と RAID-TEC の 2 つの RAID タイプがサポートされます。

... [ 保存（ Save ） ] をクリックします。


.. アグリゲートをミラーする場合は、 [ このアグリゲートをミラーリングする * ] チェックボックスをオンにします。
+
MetroCluster 構成の場合、ミラーされていないアグリゲートは作成できません。したがって、 MetroCluster 構成では、ミラーリングオプションがデフォルトで有効になります。



. [ 作成（ Create ） ] をクリックします。


.結果
指定した構成でアグリゲートが作成され、アグリゲートウィンドウのアグリゲートのリストに追加されます。



== Flash Poolアグリゲートを手動で作成する

ONTAP System Manager クラシック（ ONTAP 9.7 以前で使用可能）を使用して、 Flash Pool アグリゲートを手動で作成したり、 SSD を追加して既存の HDD アグリゲートを Flash Pool アグリゲートに変換したりできます。新しい HDD アグリゲートを作成する場合、 SSD キャッシュをプロビジョニングして、 Flash Pool アグリゲートを作成できます。

.作業を開始する前に
* Flash Pool アグリゲートの SSD 層のサイズと構成について、プラットフォームとワークロードそれぞれに固有なベストプラクティスに注意する必要があります。
* すべての HDD を初期化する必要があります。
* アグリゲートに SSD を追加する場合は、既存の SSD と専用の SSD がすべて同じサイズである必要があります。


.このタスクについて
* Flash Pool アグリゲートの作成にはパーティショニングされた SSD は使用できません。
* キャッシュソースがストレージプールの場合、アグリゲートをミラーすることはできません。
* ONTAP 9.0 以降では、ディスクサイズが 10TB 以上のアグリゲートを作成できます。
* アグリゲートディスクのディスクタイプが FSAS または MSATA で、ディスクサイズが 10TB 以上の場合、 RAID-TEC のみを使用できます。


.手順
. 次のいずれかの方法を使用してアグリゲートを作成します。
+
** [ * アプリケーションと階層 * > * ストレージ階層 * > * アグリゲートの追加 * ] をクリックします。
** [ * ストレージ * > * アグリゲートとディスク * > * アグリゲート * > * 作成 * ] をクリックします。


. アグリゲートを作成するには、 * アグリゲートを手動で作成 * オプションを有効にしてください。
. アグリゲートの作成 * ウィンドウで、アグリゲート名、ディスクタイプ、およびアグリゲートに HDD を含めるディスクまたはパーティションの数を指定します。
. アグリゲートをミラーする場合は、 [ このアグリゲートをミラーリングする * ] チェックボックスをオンにします。
+
MetroCluster 構成の場合、ミラーされていないアグリゲートは作成できません。したがって、 MetroCluster 構成では、ミラーリングオプションがデフォルトで有効になります。

. [ * このアグリゲートで Flash Pool キャッシュを使用する * ] をクリックします。
. キャッシュソースを指定します。
+
|===
| キャッシュソース | 作業 


 a| 
ストレージプール
 a| 
.. キャッシュソースとして * ストレージプール * を選択します。
.. キャッシュを提供するストレージプールを選択し、キャッシュサイズを指定します。
.. 必要に応じて RAID タイプを変更します。




 a| 
専用 SSD
 a| 
.. キャッシュソースとして専用 SSD * を選択します。
.. アグリゲートに含める SSD のサイズと数を選択します。
.. 必要に応じて RAID 構成を変更します。
+
... [ 変更（ Change ） ] をクリックします。
... RAID 構成の変更ダイアログボックスで、 RAID タイプと RAID グループサイズを指定します。
... [ 保存（ Save ） ] をクリックします。




|===
. [ 作成（ Create ） ] をクリックします。


.結果
指定した構成で Flash Pool アグリゲートが作成され、アグリゲートウィンドウのアグリゲートのリストに追加されます。



== SnapLock アグリゲートを手動で作成する

System Manager クラシック（ ONTAP 9.7 以前で使用可能）を使用して、 SnapLock Compliance アグリゲートまたは SnapLock Enterprise アグリゲートを手動で作成できます。これらのアグリゲート上に SnapLock ボリュームを作成すると、「 Write Once Read Many 」（ WORM ）機能を利用できます。

.作業を開始する前に
SnapLock ライセンスが追加されている必要があります。

.このタスクについて
* MetroCluster 構成では、 SnapLock エンタープライズアグリゲートのみを作成できます。
* アレイ LUN については、 SnapLock Enterprise アグリゲートのみがサポートされます。
* ONTAP 9.0 以降では、ディスクサイズが 10TB 以上のアグリゲートを作成できます。
* アグリゲートディスクのディスクタイプが FSAS または MSATA で、ディスクサイズが 10TB 以上の場合、 RAID-TEC のみを使用できます。
* ONTAP 9.1 以降では、 AFF プラットフォーム上に SnapLock アグリゲートを作成できます。


.手順
. 次のいずれかの方法を使用して SnapLock アグリゲートを作成します。
+
** [ * アプリケーションと階層 * > * ストレージ階層 * > * アグリゲートの追加 * ] をクリックします。
** [ * ストレージ * > * アグリゲートとディスク * > * アグリゲート * > * 作成 * ] をクリックします。


. アグリゲートを作成するには、 * アグリゲートを手動で作成 * オプションを有効にしてください。
. SnapLock アグリゲートを作成するには、次の手順を
+
.. アグリゲート名、ディスクタイプ、およびアグリゲートに含めるディスクまたはパーティションの数を指定します。
+
SnapLock Compliance アグリゲートの名前は、作成後に変更することはできません。

+
ディスクサイズが最大のディスクグループに対して、最小限のホットスペアのルールが適用されます。

.. *オプション：*アグリゲートのRAID構成を変更します。
+
... [ 変更（ Change ） ] をクリックします。
... RAID 構成の変更ダイアログボックスで、 RAID タイプと RAID グループサイズを指定します。
+
共有ディスクでは RAID タイプとして RAID-DP と RAID-TEC の 2 つがサポートされます。

... [ 保存（ Save ） ] をクリックします。


.. SnapLock タイプを指定します。
.. システム ComplianceClock を初期化していない場合は、 [Initialize ComplianceClock *] チェックボックスをオンにします。
+
このオプションは、 ComplianceClock がすでにノードで初期化されている場合は表示されません。

+
[NOTE]
====
現在のシステム時間が正しいことを確認してください。ComplianceClock はシステム時間に基づいて設定され、設定後に変更または停止することはできません。

====
.. *オプション：*アグリゲートをミラーリングする場合は、*このアグリゲートをミラーリング*チェックボックスを選択します。
+
MetroCluster 構成の場合、ミラーされていないアグリゲートは作成できません。したがって、 MetroCluster 構成では、ミラーリングオプションがデフォルトで有効になります。

+
デフォルトでは、 SnapLock Compliance アグリゲートに対しては無効になります。



. [ 作成（ Create ） ] をクリックします。




== FabricPool対応アグリゲートを手動で作成する

ONTAP System Manager クラシック（ ONTAP 9.7 以前で利用可能）を使用して、 FabricPool 対応アグリゲートを手動で作成したり、既存の SSD アグリゲートにクラウド階層を接続して FabricPool 対応アグリゲートに変換したりできます。

.作業を開始する前に
* クラウド階層を作成し、 SSD アグリゲートが配置されたクラスタに接続しておく必要があります。
* オンプレミスのクラウド階層を作成しておく必要があります。
* クラウド階層とアグリゲートの間に専用のネットワーク接続が確立されている必要があります。


.このタスクについて
次のオブジェクトストアをクラウド階層として使用できます。

* StorageGRID
* Alibaba Cloud （ System Manager 9.6 以降）
* Amazon Web Services （ AWS ） Simple Storage Service （ S3 ）
* Amazon Web Services （ AWS ） Commercial Cloud Service （ C2S ）
* Microsoft Azure Blob Storage
* IBM クラウド
* Google Cloud


[NOTE]
====
* オンプレミスの Azure サービスである Azure Stack はサポートされていません。
* StorageGRID 以外のオブジェクトストアをクラウド階層として使用する場合は、 FabricPool 容量ライセンスが必要です。


====
.手順
. 次のいずれかの方法を使用して FabricPool 対応アグリゲートを作成します。
+
** [ * アプリケーションと階層 * > * ストレージ階層 * > * アグリゲートの追加 * ] をクリックします。
** [ * ストレージ * > * アグリゲートとディスク * > * アグリゲート * > * 作成 * ] をクリックします。


. アグリゲートを作成するには、 * アグリゲートを手動で作成 * オプションを有効にしてください。
. FabricPool 対応アグリゲートを作成します。
+
.. アグリゲート名、ディスクタイプ、およびアグリゲートに含めるディスクまたはパーティションの数を指定します。
+
[NOTE]
====
FabricPool 対応アグリゲートは、オールフラッシュ（オール SSD ）アグリゲートでのみサポートされます。

====
+
ディスクサイズが最大のディスクグループに対して、最小限のホットスペアのルールが適用されます。

.. *オプション：*アグリゲートのRAID構成を変更します。
+
... [ 変更（ Change ） ] をクリックします。
... RAID 構成の変更ダイアログボックスで、 RAID タイプと RAID グループサイズを指定します。
+
共有ディスクでは RAID タイプとして RAID-DP と RAID-TEC の 2 つがサポートされます。

... [ 保存（ Save ） ] をクリックします。




. 「 * FabricPool * 」チェックボックスを選択し、リストからクラウド階層を選択します。
. [ 作成（ Create ） ] をクリックします。


* 関連情報 *

http://www.netapp.com/us/media/tr-4070.pdf["ネットアップテクニカルレポート 4070 ：『 Flash Pool Design and Implementation 』"^]
