---
permalink: online-help-96-97/task_restoring_volume_mirror_relationship.html 
sidebar: sidebar 
keywords: restore, volume, mirror, relationship, snapmirror, online, help, system, manager 
summary: バージョンに依存しないミラー関係の場合、ソースデータが破損して使用できなくなった場合は、 System Manager を使用して、ソースまたはその他のボリュームに Snapshot コピーをリストアできます。元のデータをデスティネーションボリュームの Snapshot コピーで置き換えることができます。 
---
= System Manager - ONTAP 9.7 以前のバージョンを使用して、ミラー関係のボリュームをリストアします
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
バージョンに依存しないミラー関係の場合、 ONTAP System Manager の従来の機能（ ONTAP 9.7 以前で使用可能）を使用して、ソースデータが破損して使用できなくなった場合に、ソースボリュームまたはその他のボリュームに Snapshot コピーをリストアできます。元のデータをデスティネーションボリュームの Snapshot コピーで置き換えることができます。

.作業を開始する前に
* ソースクラスタとデスティネーションクラスタの両方、またはソースボリュームを含むノードとデスティネーションボリュームを含むノードの両方で、 SnapMirror ライセンスが有効になっている必要があります。
* ソースクラスタとデスティネーションクラスタで正常なピア関係が確立されている必要があります。
* ソースアグリゲートやリストア処理の対象となるその他のアグリゲートは 64 ビットである必要があります。
* ONTAP 9.2 以前のバージョンを実行しているクラスタから Security Assertion Markup Language （ SAML ）認証が有効になっているリモートクラスタに接続する場合は、リモートクラスタでパスワードベースの認証も有効にする必要があります。


.このタスクについて
* MetroCluster 構成のソースの Storage Virtual Machine （ SVM ）とデスティネーションの SVM の間でミラー関係が確立されたボリュームはリストアできません。
* SnapLock ボリュームに対してリストア処理を実行することはできません。
* MetroCluster 構成の同期元の SVM 間のミラー関係はリストアできます。
* 同期元の SVM のボリュームからデフォルトの SVM へのミラー関係はリストアできます。
* デフォルトの SVM のボリュームから同期元の SVM の DP ボリュームへのミラー関係はリストアできます。


.手順
. [* 保護 *>] 、 [* ボリューム関係 *] の順にクリックします。
. ミラー関係を選択し、 * Operations * > * Restore * をクリックします。
. リストア * ダイアログボックスで、ミラー関係のソースボリュームにデータをリストアするか、他のボリュームを選択します。
+
|===
| データのリストア先 | 手順 


 a| 
ソースボリューム
 a| 
.. 「 * ソースボリューム * 」を選択します。
.. 手順 7 に進みます。




 a| 
その他のボリューム
 a| 
その他のボリューム * を選択し、リストからクラスタと SVM を選択します。

|===
. データを新しいボリュームまたは既存のボリュームにリストアします。
+
|===
| データのリストア先 | 手順 


 a| 
新しいボリューム
 a| 
デフォルトの名前を変更する場合は、次の形式で表示されます。 `destination_SVM_name_destination_volume_name_` リストアし、新しい名前を指定し、ボリュームの包含アグリゲートを選択します。



 a| 
既存のボリューム
 a| 
Select Volume （ボリュームの選択） * オプションを選択します。

ソースボリューム以外のボリュームの中から、一部のデータだけを含み、残りは共通の Snapshot コピーを使用する読み書き可能ボリュームを選択する必要があります。

言語属性がソースボリュームと同じボリュームだけが表示されます。

|===
. 最新の Snapshot コピーを選択するか、リストアする特定の Snapshot コピーを選択します。
. 確認のチェックボックスをオンにし、 Snapshot コピーからボリュームをリストアします。
. *オプション：* Enable Network Compression *チェックボックスを選択して、リストア処理中に転送されるデータを圧縮します。
. [* リストア ] をクリックします。

