---
permalink: online-help-96-97/task_moving_flexvol_volumes_between_aggregates_or_nodes.html 
sidebar: sidebar 
keywords: move, flexcol, volume, aggregate, node, online, help, system, manager 
summary: System Manager を使用して、容量利用率やパフォーマンスを向上させるために、 FlexVol を別のアグリゲートまたは別のノードに無停止で移動できます。 
---
= System Manager - ONTAP 9.7 以前を使用して、アグリゲート間またはノード間で FlexVol ボリュームを移動します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP System Manager 従来型（ ONTAP 9.7 以前で利用可能）を使用すると、 FlexVol ボリュームを別のアグリゲートまたは別のノードに無停止で移動し、容量利用率とパフォーマンスを向上させることができます。

.作業を開始する前に
データ保護（ DP ）ボリュームを移動する場合は、ボリュームを移動する前にデータ保護のミラー関係を初期化する必要があります。

.このタスクについて
SnapLock ボリュームは、アグリゲート間およびノード間で移動することはできません。

.手順
. [* ストレージ *>* ボリューム *] をクリックします。
. SVM * フィールドのドロップダウンメニューで、 * すべての SVM * を選択します。
. 移動するボリュームを選択します。
. [ * その他のアクション * > * 移動 * （ * More Actions * > * Move * ） ]
. ボリュームの移動 * ダイアログボックスで、ボリュームの移動先のアグリゲートまたはノードを選択し、階層化ポリシーを変更します。
+
[NOTE]
====
** ルートボリュームの階層化ポリシーは変更できません。
** ルートボリュームを FabricPool に移動することはできません。
** 読み取り / 書き込みボリュームの場合は、ボリュームの移動中に階層化ポリシーを「バックアップ」に設定できます。
+
移動後、階層化ポリシーは「スナップショットのみ」に変わります。

** ソースアグリゲートとデスティネーションアグリゲートの両方の「 Used After Move 」に表示される大容量階層の値は、推定値です。
+
正確な値については、アグリゲートウィンドウに移動して特定のアグリゲートの詳細を確認してください。



====
. [ 移動（ Move ） ] をクリックします。




== ボリューム移動のための手動でのカットオーバーのトリガー

ボリューム移動処理では、ボリュームがカットオーバー保留フェーズになったときに、 System Manager を使用して手動でカットオーバーをトリガーすることができます。カットオーバーの時間を設定し、その時間内にカットオーバーの操作が失敗した場合にシステムで実行する処理を設定できます。

.手順
. [ * ストレージ * > * SVMs * ] をクリックします。
. SVM を選択し、 * SVM 設定 * をクリックします。
. [* Volumes （ボリューム） ] タブをクリックします
. ボリューム移動操作を開始したボリュームを展開します。
. Show More Details * リンクをクリックすると、ボリュームに関する詳細情報が表示されます。
. 概要 * タブで、 * カットオーバー * をクリックします。
. カットオーバー * （ * Cutover * ）ダイアログボックスで、 * 詳細オプション * （ * Advanced Options * ）をクリックします。
. *オプション：カットオーバー操作とカットオーバー期間を指定します。
. [OK] をクリックします。

