---
permalink: online-help-96-97/task_editing_volume_properties.html 
sidebar: sidebar 
keywords: edit, volume, properties, online, help, deduplication, system, manager 
summary: System Manager を使用して、ボリューム名、セキュリティ形式、フラクショナルリザーブ、およびスペースギャランティなどのボリュームプロパティを変更できます。また、 Storage Efficiency の設定（重複排除スケジュール、重複排除ポリシー、圧縮）、およびスペース再生利用の設定も変更できます。 
---
= System Manager - ONTAP 9.7 以前を使用してボリュームのプロパティを編集します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP System Managerクラシック（ONTAP 9.7以前で使用可能）を使用して、ボリューム名、セキュリティ形式、フラクショナルリザーブ、およびスペースギャランティなどのボリュームプロパティを変更できます。また、 Storage Efficiency の設定（重複排除スケジュール、重複排除ポリシー、圧縮）、およびスペース再生利用の設定も変更できます。

.作業を開始する前に
ボリューム暗号化を有効にするには、 System Manager を使用してボリューム暗号化ライセンスをインストールし、コマンドラインインターフェイス（ CLI ）を使用して「 key-manager setup 」を有効にしておく必要があります。「 key-manager setup 」を有効にした後、 Web ブラウザを更新する必要があります。

.このタスクについて
* フラクショナルリザーブは 0% または 100% のどちらかに設定できます。
* データ圧縮は 32 ビットボリュームではサポートされていません。
* Data ONTAP 8.3.1 クラスタの場合は、 Cloud Volumes ONTAP for AWS （ AWS ）に対してインライン圧縮とバックグラウンド圧縮の両方を有効にすることができます。
+
Data ONTAP Edge では圧縮はサポートされません。

* SnapLock Compliance ボリュームの名前は変更できません。


.手順
. [* ストレージ *>* ボリューム *] をクリックします。
. SVM * フィールドのドロップダウンメニューから、編集するボリュームが配置されている Storage Virtual Machine （ SVM ）を選択します。
. 変更するボリュームを選択し、 * 編集 * をクリックします。
+
ボリュームの編集ダイアログボックスが表示されます。

. [ 一般 * （ General * ） ] タブで、必要に応じて次のプロパティを変更します。
+
** ボリューム名を変更します
** ボリューム暗号化を有効にします
+
このオプションを使用できるのは、ボリューム暗号化ライセンスを有効にした場合のみです。また、対応するプラットフォームで暗号化がサポートされている必要があります。key-manager setup は CLI から実行できます。

** ボリュームのセキュリティ形式を変更します
** シンプロビジョニングを有効または無効にします


. Storage Efficiency * タブをクリックし、次のプロパティを設定して Storage Efficiency を有効にします。
+
** 重複排除
** データ圧縮
オールフラッシュで最適化されたアグリゲートに含まれるボリュームでバックグラウンド圧縮を有効にすることはできません。このようなボリュームで有効にできるのは、インライン圧縮のみです。


+
インライン重複排除を有効にできるのは、オールフラッシュで最適化されたアグリゲートに含まれるボリュームと Flash Pool アグリゲートに含まれるボリュームだけです。

. SnapLock ボリュームの場合は、 * SnapLock * タブをクリックして、次の手順を実行します。
+
.. 自動コミット期間を指定します。
+
自動コミット期間は、ボリューム内のファイルに変更がなかった場合に WORM 状態にコミットされるまでの期間です。

.. 最小保持期間と最大保持期間を指定します。
+
値は 1~70 年、または Infinite Volume の範囲で指定する必要があります。

.. デフォルトの保持期間を選択します。
+
デフォルトの保持期間は、最小保持期間と最大保持期間の間の値に設定します。



. [ * 詳細設定 * ] タブをクリックして、次のプロパティを有効にします。
+
** ボリュームの使用済みスペースが拡張しきい値を超えたときにボリュームを自動的に拡張する場合は、「 * grow * 」を選択します。
** 使用済みスペースの量に応じてボリュームのサイズを拡張または縮小する場合は、「 * grow 」または「 Shrink * 」を選択します。
+
... ボリュームを拡張できる最大サイズを指定します。


** 次のいずれかのオプションを選択して、古い Snapshot コピーの自動削除を有効にします。
+
*** 試用してください
+
他のサブシステムによってロックされていない Snapshot コピーを削除します。

*** 破棄
+
データバックアップ機能によってロックされている Snapshot コピーを削除します。

*** 中断します
+
データ転送を中断する可能性のある Snapshot コピーを削除します。



** ボリュームに割り当てるキャッシングポリシーを選択します。
+
このオプションは、 Flash Pool アグリゲートに含まれる FlexVol に対してのみ使用できます。

** ボリュームのキャッシュデータの保持優先度を選択します。
+
このオプションは、 Flash Pool アグリゲートに含まれる FlexVol に対してのみ使用できます。

** ボリュームに設定するフラクショナルリザーブを指定します。
** ファイル読み取りのアクセス時間を更新します。
+
このオプションは、 SnapLock ボリュームに対しては無効になります。



. [ 保存して閉じる ] をクリックします。


* 関連情報 *

xref:reference_volumes_window.adoc[Volumes （ボリューム）ウィンドウ]

xref:task_setting_up_cifs.adoc[CIFSノセツトアツフ]
