---
permalink: online-help-96-97/task_assigning_volumes_to_storage_qos.html 
sidebar: sidebar 
keywords: assign, volumes, storage, qos, online, help, flexgroup, online, help, quality, serice 
summary: FlexVol ボリュームと FlexGroup ボリュームをストレージ QoS ポリシーグループに割り当てることで、それらのボリュームのスループットを制限することができます。System Manager を使用して、新しいボリュームに対するストレージ QoS を割り当てたり、すでにポリシーグループに割り当てられているボリュームに対するストレージ QoS の詳細を変更したりできます。 
---
= System Manager - ONTAP 9.7 以前を使用して、ストレージ QoS にボリュームを割り当てます
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP System Manager クラシック（ ONTAP 9.7 以前で使用可能）を使用して、 FlexVol ボリュームと FlexGroup ボリュームをストレージ QoS ポリシーグループに割り当てることで、それらのボリュームのスループットを制限できます。System Manager を使用して、新しいボリュームに対するストレージ QoS を割り当てたり、すでにポリシーグループに割り当てられているボリュームに対するストレージ QoS の詳細を変更したりできます。

.このタスクについて
* ストレージ QoS を割り当てることができるのは、オンラインの読み書き可能（ rw ）ボリュームだけです。
* ポリシーグループに次のストレージオブジェクトが割り当てられている場合、ボリュームにストレージ QoS を割り当てることはできません。
+
** ボリュームの親 Storage Virtual Machine （ SVM ）
** ボリュームの子 LUN
** ボリュームの子ファイル


* ストレージ QoS の割り当てや QoS の詳細の変更は、最大 10 個のボリュームについて同時に実行できます。


.手順
. [* ストレージ *>* ボリューム *] をクリックします。
. SVM * フィールドのドロップダウンメニューで、 * すべての SVM * を選択します。
. ストレージ QoS を割り当てるボリュームを 1 つ以上選択します。
. その他の操作 * > * ストレージ QoS * をクリックします。
. FlexVol ボリュームのワークロードパフォーマンスを管理する場合は、サービス品質の詳細 * ダイアログボックスで、サービス品質の管理 * チェックボックスを選択します。
+
選択したボリュームの一部がすでにポリシーグループに割り当てられている場合、変更内容によってはそれらのボリュームのパフォーマンスに影響する可能性があります。

. 新しいストレージ QoS ポリシーグループを作成するか、既存のポリシーグループを選択して、 FlexVol の入出力（ I/O ）のパフォーマンスを制御します。
+
|===
| 状況 | 手順 


 a| 
新しいポリシーグループを作成します
 a| 
.. [ 新しいポリシーグループ *] を選択します。
.. ポリシーグループの名前を指定します。
.. 最小スループット制限を指定します。
+
*** System Manager 9.5 では、パフォーマンスがオールフラッシュで最適化されている場合にのみ最小スループット制限を設定できます。System Manager 9.6 では、 ONTAP Select Premium システムにも最小スループット制限を設定できます。
*** FabricPool 対応アグリゲートでは、ボリュームの最小スループット制限を設定することはできません。
*** 最小スループット値を指定しない場合、または最小スループット値が 0 に設定されている場合は、自動的に「なし」という値が表示されます。
+
この値では大文字と小文字が区別されます。



.. 最大スループット制限を指定します。ポリシーグループに含まれるオブジェクトのワークロードがこのスループット制限を超えないように制限されます。
+
*** 最小スループット制限と最大スループット制限の単位は同じにする必要があります。
*** 最小スループット制限を指定しない場合は、 IOPS 、 B/ 秒、 KB/ 秒、 MB/ 秒などの単位で最大スループット制限を設定できます。
*** 最大スループット値を指定しない場合は ' 自動的に値として無制限が表示されます
+
この値では大文字と小文字が区別されます。指定した単位は無視されます。







 a| 
既存のポリシーグループを選択してください
 a| 
.. [ ポリシーグループの選択 ] ダイアログボックスで、 [ 既存のポリシーグループ *] を選択し、 [*Choose*] をクリックして既存のポリシーグループを選択します。
.. 最小スループット制限を指定します。
+
*** System Manager 9.5 では、パフォーマンスがオールフラッシュで最適化されている場合にのみ最小スループット制限を設定できます。System Manager 9.6 では、 ONTAP Select Premium システムにも最小スループット制限を設定できます。
*** FabricPool 対応アグリゲートでは、ボリュームの最小スループット制限を設定することはできません。
*** 最小スループット値を指定しない場合、または最小スループット値が 0 に設定されている場合は、自動的に「なし」という値が表示されます。
+
この値では大文字と小文字が区別されます。



.. 最大スループット制限を指定します。ポリシーグループに含まれるオブジェクトのワークロードがこのスループット制限を超えないように制限されます。
+
*** 最小スループット制限と最大スループット制限の単位は同じにする必要があります。
*** 最小スループット制限を指定しない場合は、 IOPS 、 B/ 秒、 KB/ 秒、 MB/ 秒などの単位で最大スループット制限を設定できます。
*** 最大スループット値を指定しない場合は ' 自動的に値として無制限が表示されます
  [+]
この値では大文字と小文字が区別されます。指定した単位は無視されます。


+
ポリシーグループが複数のオブジェクトに割り当てられている場合、指定した最大スループットはそれらのオブジェクトの合計スループットです。



|===
. *オプション：*選択したボリュームのリストを確認する場合は、ボリューム数を指定するリンクをクリックし、リストからボリュームを削除する場合は* Discard *をクリックします。
+
このリンクは、複数のボリュームを選択した場合にのみ表示されます。

. [OK] をクリックします。

