---
permalink: online-help-96-97/task_accessing_cluster_using_system_manager.html 
sidebar: sidebar 
keywords: access, clister, ontap, system, manager, graphic, interface, lif, node, management, online, help 
summary: コマンドラインインターフェイスではなくグラフィカルインターフェイスを使用してクラスタにアクセスして管理するには、 ONTAP System Manager を使用します。 System Manager は ONTAP に搭載されている Web サービスでデフォルトで有効になっており、ブラウザを使用してアクセスできます。 
---
= System Manager - ONTAP 9.7 以前のブラウザベースのグラフィカルインターフェイスを使用してクラスタにアクセスします
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
コマンドラインインターフェイスの代わりにグラフィカルインターフェイスを使用してクラスタにアクセスして管理するには、 ONTAP System Manager クラシック（ ONTAP 9.7 以前で使用可能）を使用します。ONTAP System Manager は Web サービスとして ONTAP に搭載されており、デフォルトで有効になっていて、ブラウザからアクセスできます。

.作業を開始する前に
* で設定されたクラスタユーザアカウントが必要です。 `admin` ロールと `http`、 `ontapi`および `console` アプリケーションタイプ：
* ブラウザでクッキーとサイトのデータを有効にしておく必要があります。


.このタスクについて
ONTAP System Manager には、クラスタ管理 LIF とノード管理 LIF のどちらかを使用してアクセスできます。ONTAP System Manager に無停止でアクセスするには、クラスタ管理 LIF を使用する必要があります。

.手順
. Web ブラウザで、クラスタ管理 LIF の IP アドレスを指定してアクセスします。
+
** IPv4を使用する場合： `+https://cluster-mgmt-LIF+`
** IPv6を使用する場合： `https://[cluster-mgmt-LIF]`
+
ONTAP System Manager のブラウザアクセスでサポートされるのは HTTPS のみです。



+
自己署名のデジタル証明書がクラスタで使用されている場合、信頼されていない証明書であることを示す警告がブラウザ画面に表示されることがあります。危険を承諾してアクセスを続行するか、認証局（ CA ）の署名のあるデジタル証明書をクラスタにインストールしてサーバを認証します。

. * オプション： * CLI を使用してアクセスバナーを設定している場合は、 * 警告 * ダイアログボックスに表示されるメッセージを読み、必要なオプションを選択して続行します。
+
Security Assertion Markup Language （ SAML ）認証が有効になっているシステムでは、このオプションはサポートされていません。

+
** 続行しない場合は、 * Cancel * をクリックしてブラウザを閉じます。
** 続行する場合は、 * OK * をクリックして ONTAP System Manager のログインページに移動します。


. クラスタ管理者のクレデンシャルを使用して ONTAP System Manager にログインします。

