---
permalink: online-help-96-97/task_provisioning_cache_by_adding_disks.html 
sidebar: sidebar 
keywords: ssd, system, manager, storage, pool, root, aggregate, provision, cache, online, help, ssd, disks, flash, pool 
summary: System Manager を使用して、 SSD をストレージプールまたは専用 SSD として追加してキャッシュをプロビジョニングできます。SSD を追加することで、パーティショニングされたディスクを含まない非ルートアグリゲートまたはルートアグリゲートを Flash Pool アグリゲートに変換したり、既存の Flash Pool アグリゲートのキャッシュサイズを拡張したりできます。 
---
= System Manager - ONTAP 9.7 以前を使用して SSD を追加してキャッシュをプロビジョニングします
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP System Manager クラシック（ ONTAP 9.7 以前で使用可能）を使用して、 SSD をストレージプールまたは専用 SSD として追加してキャッシュをプロビジョニングできます。SSD を追加することで、パーティショニングされたディスクを含まない非ルートアグリゲートまたはルートアグリゲートを Flash Pool アグリゲートに変換したり、既存の Flash Pool アグリゲートのキャッシュサイズを拡張したりできます。

.このタスクについて
* 追加された SSD キャッシュはアグリゲートのサイズには反映されず、アグリゲートが最大サイズのときでも SSD RAID グループを追加できます。
* System Manager を使用してキャッシュを追加する場合、パーティショニングされた SSD は使用できません。




== SSD の追加によるアグリゲートへのキャッシュのプロビジョニング

System Manager でストレージプールまたは専用 SSD を追加してキャッシュをプロビジョニングするには、パーティションに分割されたディスクを含まないルート以外の既存の HDD アグリゲートまたはルートアグリゲートを Flash Pool アグリゲートに変換します。

.作業を開始する前に
* アグリゲートがオンラインになっている必要があります。
* キャッシュディスクとして割り当てることができる十分な数のスペア SSD または割り当て単位がストレージプールに必要です。
* クラスタ内のすべてのノードで ONTAP 8.3 以降が実行されている必要があります。
+
クラスタに複数のバージョンが混在している場合は、コマンドラインインターフェイスを使用して Flash Pool アグリゲートを作成し、 SSD キャッシュをプロビジョニングしてください。

* Flash Pool アグリゲートに変換できる、 HDD で構成された、ルートではない有効な 64 ビットのアグリゲートを特定しておく必要があります。
* アレイ LUN を含むアグリゲートは使用できません。


.このタスクについて
Flash Pool アグリゲートの SSD 層のサイズと構成について、プラットフォームとワークロードそれぞれに固有なベストプラクティスに注意する必要があります。

.手順
. 次のいずれかの方法を選択します。
+
** [* アプリケーションと階層 *>* ストレージ階層 *] をクリックします。
** Storage * > * Aggregates & Disks * > * Aggregates * の順にクリックします


. [ * ストレージ階層 * ] ウィンドウでアグリゲートを選択し、 [ * その他の操作 * > * キャッシュの追加 * ] をクリックします。
+
[NOTE]
====
キャッシュの追加は FabricPool 対応アグリゲートではサポートされません。

====
. [ キャッシュの追加 *] ダイアログボックスで、適切なアクションを実行します。
+
|===
| 選択したキャッシュソース | 手順 


 a| 
ストレージプール
 a| 
.. キャッシュを提供するストレージプールを選択します。
.. キャッシュサイズを指定します。
.. 必要に応じて RAID タイプを変更します。




 a| 
専用 SSD
 a| 
使用する SSD のサイズと数を選択し、必要に応じて RAID 構成を変更します。

.. [ 変更（ Change ） ] をクリックします。
.. RAID 構成の変更ダイアログボックスで、 RAID タイプと RAID グループサイズを指定し、 * 保存 * をクリックします。


|===
. [ 追加（ Add ） ] をクリックします。
+
ミラーされたアグリゲートの場合、*キャッシュの追加*ダイアログボックスに、選択した数の2倍のディスクが追加されることを示す情報が表示されます。

. [ キャッシュの追加 *] ダイアログボックスで、 [ はい *] をクリックします。


.結果
選択したアグリゲートにキャッシュディスクが追加されます。



== SSD の追加による Flash Pool アグリゲートのキャッシュの拡張

System Manager を使用して、ストレージプールまたは専用 SSD として SSD を追加し、 Flash Pool アグリゲートのサイズを拡張できます。

.作業を開始する前に
* Flash Pool アグリゲートをオンラインにする必要があります。
* キャッシュディスクとして割り当てることができる十分な数のスペア SSD または割り当て単位がストレージプールに必要です。


.手順
. Storage * > * Aggregates & Disks * > * Aggregates * の順にクリックします
. [* Aggregate* ] ウィンドウで、 Flash Pool アグリゲートを選択し、 [Add Cache* ] をクリックします。
. [ キャッシュの追加 *] ダイアログボックスで、適切なアクションを実行します。
+
|===
| 選択したキャッシュソース | 手順 


 a| 
ストレージプール
 a| 
キャッシュを提供するストレージプールを選択し、キャッシュサイズを指定します。



 a| 
専用 SSD
 a| 
追加する SSD のサイズと数を選択します。

|===
. [ 追加（ Add ） ] をクリックします。
+
ミラーされたアグリゲートの場合、 Add Cache （キャッシュの追加）ダイアログボックスに、選択した数の 2 倍のディスクが追加されることを示す情報が表示されます。

. [ キャッシュの追加 *] ダイアログボックスで、 [ はい *] をクリックします。


.結果
選択した Flash Pool アグリゲートにキャッシュディスクが追加されます。

* 関連情報 *

http://www.netapp.com/us/media/tr-4070.pdf["ネットアップテクニカルレポート 4070 ：『 Flash Pool Design and Implementation 』"^]

xref:concept_how_storage_pool_works.adoc[ストレージプールの仕組み]
