---
permalink: online-help-96-97/task_adding_capacity_disks.html 
sidebar: sidebar 
keywords: add, capacity, disk, online, help, aggregate 
summary: データディスクを追加することによって、既存のルート以外のアグリゲートまたはディスクを含むルートアグリゲートのサイズを拡張できます。System Manager を使用して、選択した ONTAP ディスクタイプの HDD または SSD を追加したり、 RAID グループオプションを変更したりできます。 
---
= System Manager - ONTAP 9.7 以前を使用してデータディスクを追加します
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
データディスクを追加することによって、既存のルート以外のアグリゲートまたはディスクを含むルートアグリゲートのサイズを拡張できます。System Manager クラシック（ ONTAP 9.7 以前で使用可能）を使用して、選択した ONTAP ディスクタイプの HDD または SSD を追加したり、 RAID グループオプションを変更したりできます。

.作業を開始する前に
* アグリゲートがオンラインになっている必要があります。
* 十分な数の互換性のあるスペアディスクが必要です。


.このタスクについて
* アグリゲート内の他のディスクとサイズが同じディスクを追加することを推奨します。
+
アグリゲート内の他のディスクよりも小さいディスクを追加すると、アグリゲートが最適な構成にならず、原因のパフォーマンスの問題が生じることがあります。

+
アグリゲート内の既存の RAID グループに含まれるディスクよりも大きいディスクを追加した場合は、データディスクのサイズが縮小されて、その RAID グループ内の他のディスクと同じスペースになります。アグリゲートに新しい RAID グループを作成し、新しい RAID グループに同等のサイズのディスクが残っている場合、ディスクのサイズは縮小されません。

+
アグリゲート内の他のディスクと違うサイズのディスクを追加すると、選択したディスクは追加されずに、使用可能サイズが指定したサイズの 90~105% に該当する他のディスクが自動的に追加されることがあります。たとえば、 744GB のディスクの場合は、 669~781GB のディスクが選択対象となります。サイズがこの範囲内のすべてのスペアディスクのうち、 ONTAP は最初にパーティショニングされたディスクのみを選択し、次にパーティショニングされていないディスクのみを選択して、最後にパーティショニングされたディスクとパーティショニングされていないディスクの両方を選択します。

* System Manager を使用して次の構成に HDD を追加することはできません。
+
** SSD のみで構成されるアグリゲート
** パーティショニングされたディスクを含むルートアグリゲート
これらの構成にHDDを追加するには、コマンドラインインターフェイスを使用する必要があります。


* 共有ディスクでは、 RAID DP と RAID-TEC の 2 つの RAID タイプがサポートされます。
* ストレージプールの SSD は使用できません。
* RAIDグループタイプがRAID DPで、FSASまたはMSATAタイプの10TB以上のディスクは、 `Specific RAID group`ではなく、 `New RAID group` または `All RAID groups`。
+
ディスクは、既存のアグリゲート内の既存の RAID グループに含まれるディスクと同じサイズに縮小されてから追加されます。

* RAIDグループタイプがRAID-TECの場合、FSASまたはMSATAタイプの10TB以上のディスクを `All RAID groups`、 `New RAID group`および `Specific RAID group`。
+
ディスクは、既存のアグリゲート内の既存の RAID グループに含まれるディスクと同じサイズに縮小されてから追加されます。



.手順
. 次のいずれかの方法を選択します。
+
** [* アプリケーションと階層 *>* ストレージ階層 *] をクリックします。
** Storage * > * Aggregates & Disks * > * Aggregates * の順にクリックします


. 「 * ストレージ階層 * 」ウィンドウで、データディスクを追加するアグリゲートを選択し、メニューをクリックします。その他の操作 [ 容量の追加 ] 。
. [ 容量の追加 * ] ダイアログボックスで、次の情報を指定します。
+
.. 「 * Disk Type to Add * 」オプションを使用して、データディスクのディスクタイプを指定します。
.. ディスクまたはパーティションの数 * オプションを使用して、データディスクの数を指定します。


. [ ディスクの追加先 *] オプションを使用して、データディスクを追加する RAID グループを指定します。
+
System Managerでは、デフォルトでデータディスクが `All RAID groups`。

+
.. [ 変更（ Change ） ] をクリックします。
.. [RAIDグループの選択]ダイアログボックスで、RAIDグループを `New RAID group` または `Specific RAID group` [ディスクの追加先]*オプションを使用します。
+
共有ディスクは、 `New RAID group` オプション



. [ 追加（ Add ） ] をクリックします。
+
ミラーされたアグリゲートの場合、*容量の追加*ダイアログボックスに、選択した数の2倍のディスクが追加されることを示す情報が表示されます。

. キャパシティの追加 * （ Add Capacity ）ダイアログボックスで、 * はい * （ * Yes ）をクリックしてデータディスクを追加します。


.結果
選択したアグリゲートにデータディスクが追加され、アグリゲートのサイズが拡張されます。

* 関連情報 *

xref:concept_what_compatible_spare_disks_are.adoc[互換性のあるスペアディスクとは]
