---
permalink: online-help-96-97/task_configuring_fc_fcoe_protocol_on_svms.html 
sidebar: sidebar 
keywords: online, help, configure, fc, protocol, fcoe, svm, online, help, system, manager 
summary: Storage Virtual Machine （ SVM ）で SAN ホスト用に FC プロトコルおよび FCoE プロトコルを設定できます。最適なアダプタで LIF が作成され、データパスの冗長性を確保するためにポートセットに割り当てられます。要件に応じて、 System Manager を使用して FC プロトコル、 FCoE プロトコル、またはその両方を設定できます。 
---
= System Manager - ONTAP 9.7 以前を使用して、 SVM に FC プロトコルと FCoE プロトコルを設定します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP System Managerクラシック（ONTAP 9.7以前で使用可能）を使用して、SANホスト用にStorage Virtual Machine（SVM）でFCプロトコルおよびFCoEプロトコルを設定できます。最適なアダプタで LIF が作成され、データパスの冗長性を確保するためにポートセットに割り当てられます。要件に応じて、 System Manager を使用して FC プロトコル、 FCoE プロトコル、またはその両方を設定できます。

.作業を開始する前に
* クラスタで FCP ライセンスが有効になっている必要があります。
* クラスタのすべてのノードが正常である必要があります。
* 各ノードで少なくとも 2 つのポート（ FC プロトコル用と FCoE プロトコル用）が正しく設定されている必要があります。


.このタスクについて
* FC プロトコルと FCoE プロトコルは、 SVM の作成時に設定することも、あとで設定することもできます。
+
SVM でプロトコルが許可されていない場合は、 Storage Virtual Machine の編集ウィンドウを使用して SVM のプロトコルを有効にできます。

* SnapLock アグリゲートは、ボリュームの自動作成の対象としては考慮されません。


.手順
. SVM の作成時にプロトコルを設定していない場合は、 * Storage * > * SVMs * タブをクリックします。
. SVM を選択し、 * SVM 設定 * をクリックします。
. [* Protocols] ペインで、 [*FC/FCoE*] をクリックします。
. 「 * データインターフェイス構成 * 」セクションで、対応するオプションを選択して FC プロトコルと FCoE プロトコルのデータ LIF を設定します。
. 各プロトコルのノードあたりのデータ LIF の数を指定します。
+
ノードあたりの LIF の最小数は 1 です。最大数は、のすべてのポートの最小数です。 `up` ノード全体の状態。最大値が奇数の場合は、 1 つ前の偶数が最大値とみなされます。最小値と最大値の範囲に任意の偶数を選択できます。

+
4ノードクラスタで、node1、node2、およびnode3にはそれぞれ6つのポートがあるとします。 `up` 状態、およびに7つのポートがあるノード4 `up` 状態。この場合、クラスタに実際に設定可能な最大値は 6 です。

+
ノードに LIF を 3 個以上割り当てる場合、各 LIF に少なくともポートセットを 1 つ割り当てる必要があります。

. 自動生成された LIF の設定を確認または変更するには、「 * Review 」または「 Edit the Interface Association * 」を選択します。
+
変更できるのは、 LIF 名とホームポートだけです。重複するエントリを指定しないようにしてください。

. *オプション：プロトコルを設定する際に、FCストレージまたはFCoEストレージ用のLUNをプロビジョニングします。LUNサイズ、LUNのOSタイプ、およびホストイニシエータの詳細を指定します。
. [Submit & Continue] をクリックします。


.結果
指定した設定でデータ LIF とポートセットが作成され、LIF が適宜ポートセットに割り当てられます。少なくとも 1 つのプロトコルについてすべての LIF が正常に作成されると、 FCP サービスが開始されます。

LIF の作成に失敗した場合は、 FC / FCoE ウィンドウで LIF を作成して FCP サービスを開始できます。

* 関連情報 *

https://docs.netapp.com/ontap-9/index.jsp["ONTAP 9 ドキュメンテーション・センター"]
