---
permalink: online-help-96-97/task_restoring_volume_mirror_vault_relationship.html 
sidebar: sidebar 
keywords: restore, volume, mirror, vault, relationship, online, help, snapshot, copy, system, manager 
summary: ソースデータが破損して使用できなくなった場合は、 System Manager を使用して、ソースボリュームまたはその他のボリュームに Snapshot コピーをリストアします。元のデータをデスティネーションボリュームの Snapshot コピーで置き換えることができます。 
---
= System Manager - ONTAP 9.7 以前のバージョンで、ミラーとバックアップ関係にあるボリュームをリストアします
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ソースデータが破損して使用できなくなった場合は、 ONTAP System Manager クラシック（ ONTAP 9.7 以前のバージョンで使用可能）を使用して、ソースボリュームまたはその他のボリュームに Snapshot コピーをリストアできます。元のデータをデスティネーションボリュームの Snapshot コピーで置き換えることができます。

.作業を開始する前に
* ソースクラスタとデスティネーションクラスタの両方、またはソースボリュームを含むノードとデスティネーションボリュームを含むノードの両方で、 SnapMirror ライセンスと SnapVault ライセンスが有効になっている必要があります。
* ソースクラスタとデスティネーションクラスタで正常なピア関係が確立されている必要があります。
* ソースアグリゲートやリストア処理の対象となるその他のアグリゲートは 64 ビットである必要があります。
* ONTAP 9.2 以前のバージョンを実行しているクラスタから SAML 認証が有効になっているリモートクラスタに接続する場合は、リモートクラスタでパスワードベースの認証も有効にする必要があります。


.このタスクについて
* MetroCluster 構成のソースの Storage Virtual Machine （ SVM ）とデスティネーションの SVM の間でミラーとバックアップ関係が確立されたボリュームはリストアできません。
* リストアできるのは、次の構成のミラーとバックアップ関係です。
+
** MetroCluster 構成の同期元の SVM 間の移動
** 同期元の SVM のボリュームからデフォルトの SVM
** デフォルトの SVM のボリュームから同期元の SVM の DP ボリュームへの移動




.手順
. [* 保護 *>] 、 [* ボリューム関係 *] の順にクリックします。
. リストアするミラーとバックアップ関係を選択し、 * Operations * > * Restore * をクリックします。
. リストア * ダイアログボックスで、関係のソースボリュームにデータをリストアするか、他のボリュームを選択します。
+
|===
| データのリストア先 | 手順 


 a| 
ソースボリューム
 a| 
.. 「 * ソースボリューム * 」を選択します。
.. link:#step6["手順 6. に進みます。"]。




 a| 
その他のボリューム
 a| 
「 * other volume * 」を選択し、クラスタと SVM を選択します。

|===
. データを新しいボリュームまたは既存のボリュームにリストアします。
+
|===
| データのリストア先 | 手順 


 a| 
新しいボリューム
 a| 
デフォルトの名前を変更する場合は、「 ```d estination_svm_name_destination_volume_name_restore` 」の形式で表示されます。新しい名前を指定し、ボリュームの包含アグリゲートを選択します。



 a| 
既存のボリューム
 a| 
Select Volume （ボリュームの選択） * オプションを選択します。

ソースボリューム以外のボリュームの中から、一部のデータだけを含み、残りは共通の Snapshot コピーを使用する読み書き可能ボリュームを選択する必要があります。

言語属性がソースボリュームと同じボリュームだけが表示されます。

|===
. 最新の Snapshot コピーを選択するか、リストアする特定の Snapshot コピーを選択します。
. [[step6]] Snapshotコピーからボリュームをリストアする場合は、確認のチェックボックスを選択します。
. *オプション：* Enable Network Compression *チェック・ボックスを選択して、リストア処理中に転送されるデータを圧縮します。
. [* リストア ] をクリックします。

