---
permalink: online-help-96-97/task_editing_mirror_relationships.html 
sidebar: sidebar 
keywords: system, manager, edit, mirror, relationships, online, help 
summary: System Manager を使用して、クラスタの既存のポリシーまたはスケジュールを選択するか、ポリシーまたはスケジュールを作成して、ミラー関係を編集することができます。 
---
= System Manager - ONTAP 9.7 以前を使用してミラー関係を管理します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP System Manager クラシック（ ONTAP 9.7 以前で使用可能）を使用して、ミラー関係を管理できます。更新、作成、休止、初期化、再確立、 休止していたミラー関係の再開に加え、ミラー関係の削除と編集を行います。



== 関係を削除します

System Manager を使用して、ミラー関係を削除し、ソースボリュームとデスティネーションボリュームの間のミラー関係を完全に終了できます。ミラー関係を削除すると、ソースボリュームのベース Snapshot コピーが削除されます。

.このタスクについて
ミラー関係を削除する前に、その関係を解除することが推奨されます。

.手順
. [* 保護 *>] 、 [* ボリューム関係 *] の順にクリックします。
. 削除するミラー関係を選択し、 * Delete * をクリックします。
. 確認のチェックボックスを選択してミラー関係を削除し、ベース Snapshot コピーを解放して、 * Delete * をクリックします。


.結果
関係が削除され、ソースボリュームのベース Snapshot コピーが削除されます。



== 関係を再同期する

System Manager を使用して、以前に解除したミラー関係を再確立できます。再同期操作を実行して、災害によってソースボリュームが機能しなくなった状態からリカバリできます。

.作業を開始する前に
ソースクラスタとデスティネーションクラスタ、およびソース SVM とデスティネーション SVM でピア関係が確立されている必要があります。

.このタスクについて
* 再同期操作を実行すると、ミラーデスティネーションの内容がソースボリュームの内容で上書きされます。
+
[NOTE]
====
** SnapLock 準拠ボリュームでは、アクティブファイルシステム内で共通の Snapshot コピーに関連するデータ変更は、現在のボリュームに設定されている有効期限まではロックされた Snapshot コピーに保持されます。
+
ボリュームの有効期限がすでに過ぎているか設定されていない場合は、 Snapshot コピーおよび共通の Snapshot コピーが 30 日間ロックされます。共通の Snapshot コピーからロックされた最新の Snapshot コピーまでの間の中間の Snapshot コピーはすべて削除されます。

** SnapLock Compliance ボリューム以外のボリュームでは、ベースの Snapshot コピーが作成されたあとにデスティネーションボリュームに書き込まれた新しいデータが原因によって失われる可能性があります。


====
* Protection ウィンドウの Last Transfer Error フィールドで再同期操作を実行するように推奨された場合は、まず関係を解除してから再同期処理を実行する必要があります。


.手順
. [* 保護 *>] 、 [* ボリューム関係 *] の順にクリックします。
. 再同期するミラー関係を選択します。
. [* Operations] * > [* Resync] をクリックします。
. 確認のチェックボックスをオンにし、 * Resync * をクリックします。




== 休止した関係を再開します

System Manager を使用して、休止中のミラー関係を再開できます。関係を再開すると、ミラーデスティネーションへの通常のデータ転送が再開され、ミラー処理もすべて再開されます。

.このタスクについて
解除されたミラー関係をコマンドラインインターフェイス（ CLI ）で休止した場合は、 System Manager で再開することはできません。CLI を使用して関係を再開してください。

.手順
. [* 保護 *>] 、 [* ボリューム関係 *] の順にクリックします。
. 再開するミラー関係を選択します。
. [* オペレーション * > * 再開 * （ Operations * > * Resume * ） ] をクリック
. 確認のチェックボックスをオンにし、 * Resume * （続行）をクリックします。


.結果
選択したミラー関係のミラーデスティネーションへのデータ転送が再開されます。



== 関係を更新します

System Manager を使用して、スケジュールされていないデスティネーションのミラー更新を開始できます。予定された停電、スケジュールされた保守、またはデータ移行によるデータ損失を防ぐために、手動更新が必要になる場合があります。

.作業を開始する前に
ミラー関係は SnapMirror 済みの状態である必要があります。

.手順
. [* 保護 *>] 、 [* ボリューム関係 *] の順にクリックします。
. データを更新するミラー関係を選択し、 * Operations * > * Update * をクリックします。
. 次のいずれかのオプションを選択します。
+
** ソースボリュームとデスティネーションボリュームの間の最新の共通の Snapshot コピーに基づく差分転送を実行するには、「 * on demand * 」を選択します。
** Select Snapshot copy * を選択し、転送する Snapshot コピーを指定します。


. *オプション：転送に使用するネットワーク帯域幅を制限し、最大転送速度を指定するには、*転送帯域幅を*に制限するを選択します。
. [ 更新（ Update ） ] をクリックします。
. [ * 詳細 * ] タブで転送ステータスを確認します。




== 関係を休止します

System Manager を使用して、 Snapshot コピーを作成する前にミラーデスティネーションを休止して、安定した状態にすることができます。休止処理を実行すると、アクティブなミラー転送が完了したあと、ミラーリング関係の以降の転送が実行されなくなります。

.このタスクについて
休止できるのは、 SnapMirror 済み状態のミラー関係のみです。

.手順
. [* 保護 *>] 、 [* ボリューム関係 *] の順にクリックします。
. 休止するミラー関係を選択します。
. [* 操作 *>] [ * 休止 ] をクリックします。
. 確認のチェックボックスをオンにし、 * 休止 * をクリックします。




== 関係を初期化

ミラー関係を開始する際には、関係を初期化する必要があります。関係を初期化すると、ソースボリュームからデスティネーションへのデータのベースライン転送が実行されます。System Manager を使用して、作成時に初期化していないミラー関係を初期化することができます。

.手順
. [* 保護 *>] 、 [* ボリューム関係 *] の順にクリックします。
. 初期化するミラー関係を選択します。
. [* Operations] * > [* Initialize] をクリックします。
. 確認のチェックボックスをオンにし、 * Initialize * （初期化）をクリックします。
. [ 保護（ Protection ） ] ウィンドウで、ミラー関係のステータスを確認します。


.結果
Snapshot コピーが作成されてデスティネーションに転送されます。この Snapshot コピーは、以降の差分 Snapshot コピーのベースラインとして使用されます。



== 関係を編集します

System Manager を使用して、クラスタの既存のポリシーまたはスケジュールを選択するか、ポリシーまたはスケジュールを作成して、ミラー関係を編集することができます。

.このタスクについて
* Data ONTAP 8.2.1 のボリュームと ONTAP 8.3 以降のボリュームの間に作成されたミラー関係は編集できません。
* 既存のポリシーやスケジュールのパラメータを編集することはできません。
* バージョンに依存しないミラー関係、バックアップ関係、またはミラーとバックアップ関係について、ポリシーのタイプを変更することで関係のタイプを変更することができます。


.手順
. [* 保護 *>] 、 [* ボリューム関係 *] の順にクリックします。
. ポリシーまたはスケジュールを変更するミラー関係を選択し、 * Edit * をクリックします。
. ［ * 関係の編集 * ］ ダイアログボックスで、既存のポリシーを選択するか、ポリシーを作成します。
+
|===
| 状況 | 実行する処理 


 a| 
既存のポリシーを選択してください。
 a| 
[* 参照 ] をクリックし、既存のポリシーを選択します。



 a| 
ポリシーを作成する
 a| 
.. [ ポリシーの作成 *] をクリックします。
.. ポリシーの名前を指定します。
.. スケジュールされた転送の優先順位を設定します。
+
転送の優先順位を「低」にすると優先順位が最も低くなり、優先順位が「通常」の転送よりもあとにスケジュールされます。デフォルトでは、優先度は Normal に設定されます。

.. 「 all_source_snapshots 」ルールをミラーポリシーに含めるには、「 * すべてのソース Snapshot コピーを転送 * 」チェックボックスを選択します。これにより、ソースボリュームのすべての Snapshot コピーをバックアップできます。
.. 転送中のデータを圧縮するには、 [ ネットワーク圧縮を有効にする *] チェックボックスをオンにします。
.. [ 作成（ Create ） ] をクリックします。


|===
. 関係のスケジュールを指定します。
+
|===
| 状況 | 実行する処理 


 a| 
既存のスケジュールを割り当てる
 a| 
スケジュールのリストから既存のスケジュールを選択します。



 a| 
スケジュールを作成する
 a| 
.. [ スケジュールの作成 *] をクリックします。
.. スケジュールの名前を指定します。
.. [*Basic*] または [*Advanced*] を選択します。
+
*** basic は、曜日、時刻、および転送間隔だけを指定します。
*** advanced を指定すると、 cron 形式のスケジュールが作成されます。


.. [ 作成（ Create ） ] をクリックします。




 a| 
スケジュールを割り当てない
 a| 
「 * なし * 」を選択します。

|===
. [OK] をクリックして変更を保存します。




== デスティネーションSVMからミラー関係を作成

System Managerを使用して、ミラー関係をデスティネーションStorage Virtual Machine（SVM）から作成し、ポリシーとスケジュールをそのミラー関係に割り当てることができます。ミラーコピーを作成しておけば、ソースボリュームのデータが破損した場合や失われた場合でも、データをすぐに使用できます。

.作業を開始する前に
* ソースクラスタで ONTAP 8.2.2 以降が実行されている必要があります。
* ソースクラスタとデスティネーションクラスタで SnapMirror ライセンスが有効になっている必要があります。
+
[NOTE]
====
一部のプラットフォームでは、デスティネーションクラスタで SnapMirror ライセンスに加えて Data Protection Optimization （ DPO ）ライセンスが有効になっていれば、ソースクラスタで SnapMirror ライセンスが有効になっていなくてもかまいません。

====
* ボリュームのミラーリングで SnapLock ボリュームをソースとして選択する場合、デスティネーションクラスタに SnapMirror ライセンスと SnapLock ライセンスがインストールされている必要があります。
* ソースクラスタとデスティネーションクラスタで正常なピア関係が確立されている必要があります。
* デスティネーション SVM の使用可能なスペースを確保する必要があります。
* 読み書き可能（ rw ）タイプのソースボリュームを用意しておく必要があります。
* FlexVol がオンラインであり、読み書き可能タイプである必要があります。
* SnapLock アグリゲートのタイプが同じである必要があります。
* ONTAP 9.2 以前のバージョンを実行しているクラスタから Security Assertion Markup Language （ SAML ）認証が有効になっているリモートクラスタに接続する場合は、リモートクラスタでパスワードベースの認証を有効にする必要があります。


.このタスクについて
* System Manager ではカスケード関係はサポートされません。
+
たとえば、関係のデスティネーションボリュームを別の関係のソースボリュームにすることはできません。

* MetroCluster 構成の同期元の SVM と同期先の SVM の間にミラー関係を作成することはできません。
* MetroCluster 構成の同期元の SVM 間にはミラー関係を作成できます。
* 同期元の SVM のボリュームからデータ提供用の SVM のボリュームへのミラー関係を作成できます。
* データ提供用の SVM のボリュームから同期元の SVM のデータ保護（ DP ）ボリュームへのミラー関係を作成できます。
* ミラー関係は、同じタイプの SnapLock 間でのみ作成できます。
+
たとえば、ソースボリュームが SnapLock Enterprise ボリュームの場合は、デスティネーションボリュームも SnapLock Enterprise ボリュームである必要があります。デスティネーション SVM SnapLock で同じタイプのアグリゲートを使用できることを確認する必要があります。

* ミラー関係用に作成されたデスティネーションボリュームはシンプロビジョニングされません。
* 一度に保護できるボリュームは最大 25 個です。
* ソースクラスタよりも古いバージョンの ONTAP をデスティネーションクラスタで実行している場合、 ONTAP ボリューム間にミラー関係 SnapLock を作成することはできません。


.手順
. [* 保護 *>] 、 [* ボリューム関係 *] の順にクリックします。
. [ ボリューム関係 * ] ウィンドウで、 [ * 作成 ] をクリックします。
. [* SVM を参照 * ] ダイアログボックスで、デスティネーションボリュームの SVM を選択します。
. [ 保護関係の作成 *] ダイアログボックスで、 [ 関係タイプ *] ドロップダウンリストから [ ミラー *] を選択します。
. クラスタ、 SVM 、およびソースボリュームを指定します。
+
指定したクラスタで ONTAP 9.3 より前のバージョンの ONTAP ソフトウェアが実行されている場合、ピア関係が設定された SVM だけが表示されます。指定したクラスタで ONTAP 9.3 以降が実行されている場合は、ピア関係が設定された SVM と許可された SVM が表示されます。

. FlexVol ボリュームの場合は、ボリューム名サフィックスを指定します。
+
ボリューム名サフィックスをソースボリュームの名前に追加したものがデスティネーションボリュームの名前として使用されます。

. [* 参照 ] をクリックし、ミラーポリシーを変更します。
. 既存のスケジュールのリストから関係のスケジュールを選択します。
. 関係の初期化を選択してミラー関係を初期化します。
. FabricPool 対応アグリゲートを有効にし、適切な階層化ポリシーを選択します。
. [ 作成（ Create ） ] をクリックします。


.結果
デスティネーションボリュームを作成するように選択した場合は、 type _dp_is のデスティネーションボリュームが作成され、言語属性はソースボリュームと同じになります。

ソースボリュームとデスティネーションボリュームの間にミラー関係が作成されます。関係を初期化するように選択した場合は、ベース Snapshot コピーがデスティネーションボリュームに転送されます。



== ミラー関係を逆再同期しています

System Manager を使用して、以前に解除したミラー関係を再確立できます。逆再同期操作を実行すると、ソースボリュームとデスティネーションボリュームの機能が入れ替わります。

.作業を開始する前に
ソースボリュームはオンラインである必要があります。

.このタスクについて
* デスティネーションボリュームでデータを提供しながら、ソースボリュームを修理または交換したり、ソースボリュームを更新したり、システムの元の構成を再確立したりできます。
* 逆再同期を実行すると、ミラーソースの内容がデスティネーションボリュームの内容で上書きされます。
+
[NOTE]
====
** SnapLock 準拠ボリュームでは、アクティブファイルシステム内で共通の Snapshot コピーに関連するデータ変更は、現在のボリュームに設定されている有効期限まではロックされた Snapshot コピーに保持されます。
+
ボリュームの有効期限がすでに過ぎているか設定されていない場合は、 Snapshot コピーおよび共通の Snapshot コピーが 30 日間ロックされます。共通の Snapshot コピーからロックされた最新の Snapshot コピーまでの間の中間の Snapshot コピーはすべて削除されます。

** SnapLock Compliance ボリューム以外のボリュームでは、ベースの Snapshot コピーが作成されたあとにソースボリュームに書き込まれた新しいデータが原因によって失われる可能性があります。


====
* 逆再同期の実行時は、関係のミラーポリシーが DPDefault に設定され、ミラースケジュールが None に設定されます。


.手順
. [* 保護 *>] 、 [* ボリューム関係 *] の順にクリックします。
. 反転するミラー関係を選択します。
. [* Operations] * > [* Reverse Resync] をクリックします。
. 確認のチェックボックスをオンにし、 * 逆再同期 * をクリックします。


* 関連情報 *

xref:reference_protection_window.adoc[保護ウィンドウ]
