---
permalink: online-help-96-97/task_updating_cluster_nondisruptively.html 
sidebar: sidebar 
keywords: nondisruptive, upgrades, NDU, cluster, system, manager, online, help 
summary: System Manager を使用して、クライアントデータへのアクセスを中断することなく、 ONTAP 8.3.1 以降を実行しているハイアベイラビリティ（ HA ）ペアのクラスタまたは個別のノードを特定のバージョンの ONTAP ソフトウェアに更新できます。 
---
= System Manager - ONTAP 9.7 以前を使用して、クラスタを無停止で更新します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP System Manager クラシック（ ONTAP 9.7 以前で使用可能）を使用して、クライアントデータへのアクセスを中断することなく、 ONTAP 8.3.1 以降を実行しているハイアベイラビリティ（ HA ）ペアのクラスタまたは個別のノードを特定のバージョンの ONTAP ソフトウェアに更新できます。

.作業を開始する前に
* すべてのノードが HA ペア構成になっている必要があります。
* すべてのノードが正常である必要があります。
* NetApp Support Siteからネットワーク上の HTTP サーバまたは FTP サーバにソフトウェアイメージをコピーしておき、ノードからイメージにアクセスできるようにする必要があります。
+
link:task_obtaining_ontap_software_images.html["ONTAP ソフトウェアイメージの取得"]



.このタスクについて
* クラスタ管理 LIF をホストしているノードの更新中に System Manager からその他のタスクを実行しようとすると、エラーメッセージが表示される場合があります。
+
更新が完了してから、他の処理を実行してください。

* 8 ノード未満のクラスタの場合はローリング更新が、 8 ノード以上のクラスタの場合は一括更新が実行されます。
+
ローリング更新では、クラスタ内のノードが一度に 1 つずつ更新されます。一括更新では、複数のノードが同時に更新されます。

* ONTAP ソフトウェアを Long-Term Service （ LTS ；長期サービス）リリースから次回の LTS リリース（ LTS+1 ）に無停止で更新できます。
+
たとえば、 ONTAP 9.1 と ONTAP 9.3 が LTS リリースの場合は、 ONTAP 9.1 から ONTAP 9.3 にクラスタを無停止で更新できます。

* System Manager 9.6 以降では、 System Manager 9.5 で NVMe プロトコルが設定されている場合に System Manager 9.5 を System Manager 9.6 にアップグレードすると、 NVMe プロトコルをライセンスなしで利用できる 90 日の猶予期間はなくなりました。ONTAP 9.5 を 9.6 にアップグレードした時点で猶予期間が残っている場合、 NVMe の機能を引き続き利用するには、猶予期間を有効な NVMeoF ライセンスに置き換える必要があります。
+
この機能は、 MetroCluster 構成では使用できません。

* System Manager 9.5 で NVMe プロトコルが設定されていない場合に System Manager 9.5 を System Manager 9.6 にアップグレードすると、猶予期間は与えられず、 NVMe プロトコルを使用するには NVMe ライセンスをインストールする必要があります。
+
この機能は、 MetroCluster 構成では使用できません。

* ONTAP 9.5 以降では、 NVMe プロトコルを使用する HA ペアの各ノードに対して、少なくとも 1 つの NVMe LIF が設定されている必要があります。作成できる NVMe LIF の数はノードごとに 2 つまでです。ONTAP 9.5 にアップグレードするときは、 NVMe プロトコルを使用する HA ペアの各ノードに対して少なくとも 1 つの NVMe LIF が定義されていることを確認する必要があります。


.手順
. [* Configuration * （設定 * ） ] > [* Cluster * （クラスタ * ） ] > [* Update * （アップデート *
. 「 * アップデート * 」タブで、新しい画像を追加するか、使用可能な画像を選択します。
+
|===
| 状況 | 作業 


 a| 
ローカルクライアントから新しいソフトウェアイメージを追加します
 a| 
.. [ ローカルクライアントから追加 ] をクリックします。
.. ソフトウェアイメージを検索し、 * 開く * をクリックします。




 a| 
NetApp Support Siteから新しいソフトウェアイメージを追加します
 a| 
.. [ サーバーから追加 ] をクリックします。
.. Add a New Software Image ダイアログボックスに、NetApp Support Siteからダウンロードしたイメージを保存した HTTP サーバまたは FTP サーバの URL を入力します。
+
匿名 FTP の URL は、で指定する必要があります `+ftp://anonymous@ftpserver+` の形式で入力し

.. [ 追加（ Add ） ] をクリックします。




 a| 
使用可能なイメージを選択します
 a| 
表示された画像のいずれかを選択します。

|===
. 更新前の検証チェックを実行してクラスタを更新する準備ができているかどうかを確認するには、 * Validate * をクリックします。
+
クラスタコンポーネントがチェックされて更新を無停止で完了できるかどうかが検証され、エラーや警告があれば表示されます。ソフトウェアの更新前に実施する必要がある対処方法があれば、あわせて表示されます。

+
[NOTE]
====
更新を実行する前に、エラーに対して必要な対処方法をすべて実施する必要があります。警告の修復アクションは無視できますが、更新に進む前にそれらの修復アクションもすべて実行することを推奨します。

====
. 「 * 次へ * 」をクリックします。
. [ 更新（ Update ） ] をクリックします。
+
再度検証が実行されます。

+
** 検証が完了すると、エラーや警告があれば、続行する前に実施する必要がある対処方法と一緒にテーブルに表示されます。
** 検証が警告付きで完了した場合は、 [ 警告付き更新を続行する *] チェックボックスをオンにして、 [ 続行 *] をクリックします。
検証が完了し、更新が開始されたあと、エラーが発生して更新が中断される場合があります。その場合、エラーメッセージをクリックして詳細を表示し、修復アクションを実施してから更新を再開できます。


+
更新が完了すると、ノードがリブートし、 System Manager のログインページが表示されます。ノードのリブートに時間がかかる場合は、ブラウザを更新する必要があります。

. System Manager にログインし、 * Configuration * > * Cluster * > * Update * > * Update History * をクリックして、選択したバージョンにクラスタが正しく更新されたことを確認し、詳細を確認します。


* 関連情報 *

xref:concept_how_you_update_cluster_nondisruptively.adoc[クラスタを無停止で更新する方法]
