---
permalink: online-help-96-97/task_creating_fc_san_optimized_luns.html 
sidebar: sidebar 
keywords: create, fc, san, optimized, lun, system, manager, online, help 
summary: AFF プラットフォームでのクラスタの初期セットアップ時に、 System Manager を使用して FC SAN 向けに最適化された LUN を作成できます。 
---
= System Manager - ONTAP 9.7 以前を使用して、 FC SAN 向けに最適化された LUN を作成します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
AFF プラットフォームでのクラスタの初期セットアップ時に、 ONTAP System Manager クラシック（ ONTAP 9.7 以前で使用可能）を使用して FC SAN 向けに最適化された LUN を作成できます。

.作業を開始する前に
* LUN を含まない AFF_SAN_DEFAULT_SVM という名前の Storage Virtual Machine （ SVM ）を 1 つだけ作成しておく必要があります。
* ハードウェアのセットアップが完了していることを確認しておく必要があります。
+
https://docs.netapp.com/ontap-9/index.jsp["ONTAP 9 ドキュメンテーション・センター"]



.このタスクについて
* この方法は、 2 つ以上のノードで構成されるクラスタの初期セットアップでのみ使用できます。
+
System Manager では、最初の 2 つのノードだけを使用して LUN が作成されます。

* 各 LUN は別々のボリュームに作成されます。
* ボリュームはシンプロビジョニングされます。
* 作成される LUN のスペースリザベーションは無効になります。
* クラスタのほとんどの設定は出荷時点で完了しており、ストレージ効率とパフォーマンスが最大になるように最適化されています。
+
これらの設定は変更しないでください。



.手順
. クラスタ管理者のクレデンシャルを使用して System Manager にログインします。
+
この方法で LUN を作成したあとで、再度この方法を使用することはできません。

+
LUN を作成せずにダイアログボックスを閉じた場合は、 LUN タブに移動し、 * 作成 * をクリックして再度ダイアログボックスにアクセスする必要があります。

. LUN の作成 * ダイアログボックスの * LUN の詳細 * 領域で、アプリケーション・タイプを指定します。
+
|===
| アプリケーションの種類 | 作業 


 a| 
Oracle の場合
 a| 
.. データベースの名前とサイズを指定します。
.. Oracle Real Application Clusters （ RAC ）を導入した場合は、 [* Oracle RAC* ] チェックボックスをオンにします。
+
サポートされる RAC ノード数は 2 つだけです。イニシエータグループに少なくとも 2 つのイニシエータが追加されていることを確認してください。





 a| 
SQL>
 a| 
データベースの数と各データベースのサイズを指定します。



 a| 
その他
 a| 
.. 各 LUN の名前とサイズを指定します。
.. LUN を追加で作成する場合は、 * LUN の追加 * をクリックし、各 LUN の名前とサイズを指定します。


|===
+
選択したアプリケーションの種類に基づいて、データ LUN 、ログ LUN 、バイナリ LUN 、および一時的な LUN が作成されます。

. [* Map to these Initiators] * 領域で、次の手順を実行します。
+
.. イニシエータグループの名前とオペレーティングシステムのタイプを指定します。
.. ホストイニシエータの WWPN をドロップダウンリストから選択するかテキストボックスにイニシエータを入力して追加します。
.. イニシエータのエイリアスを追加します。


+
イニシエータグループが 1 つだけ作成されます。

. [ 作成（ Create ） ] をクリックします。
+
作成した LUN の情報が表示されます。

. [* 閉じる * ] をクリックします。


* 関連情報 *

https://docs.netapp.com/ontap-9/index.jsp["ONTAP 9 ドキュメンテーション・センター"]
