---
permalink: online-help-96-97/task_editing_mirror_vault_relationships.html 
sidebar: sidebar 
keywords: edit, mirror, vault, relationship, system, manager, online, help 
summary: System Manager を使用して、選択したポリシーやスケジュールを変更することで、ミラーとバックアップ関係を編集することができます。ただし、既存のポリシーやスケジュールのパラメータを編集することはできません。 
---
= System Manager - ONTAP 9.7 以前を使用して、ミラーとバックアップ関係を管理します
:allow-uri-read: 


[role="lead"]
ONTAP System Manager クラシック（ ONTAP 9.7 以前で使用可能）を使用して、ミラーとバックアップ関係を管理できます。編集、削除、初期化、更新、休止、 ミラーとバックアップ関係を再開して解除デスティネーションSVMからミラーとバックアップ関係を作成するだけでなく、再同期や逆再同期の処理も実行できます。



== 関係を編集します

System Manager を使用して、選択したポリシーやスケジュールを変更することで、ミラーとバックアップ関係を編集することができます。ただし、既存のポリシーやスケジュールのパラメータを編集することはできません。

.作業を開始する前に
ソースクラスタとデスティネーションクラスタで正常なピア関係が確立されている必要があります。

.このタスクについて
バージョンに依存しないミラー関係、バックアップ関係、またはミラーとバックアップ関係について、ポリシーのタイプを変更することで関係のタイプを変更することができます。

.手順
. [* 保護 *>] 、 [* ボリューム関係 *] の順にクリックします。
. 変更するミラーとバックアップ関係を選択し、 * 編集 * をクリックします。
. [ 関係の編集 * （ Edit Relationship * ） ] ダイアログボックスで、適切なアクションを選択する。
+
|===
| 状況 | 実行する処理 


 a| 
既存のポリシーを選択してください。
 a| 
[* 参照 ] をクリックし、既存のポリシーを選択します。    ソースボリュームに関連付けられた Snapshot ポリシーと最も多くのラベルが一致するポリシーを選択できます。



 a| 
新しいポリシーを作成します。
 a| 
.. [ ポリシーの作成 *] をクリックします。
.. ポリシーの名前を指定します。
.. スケジュールされた転送の優先順位を設定します。
+
転送の優先順位を「低」にすると優先順位が最も低くなり、優先順位が「通常」の転送よりもあとにスケジュールされます。デフォルトでは、優先度は Normal に設定されます。

.. 転送中のデータを圧縮するには、 [ ネットワーク圧縮を有効にする *] チェックボックスをオンにします。
.. バックアップポリシーの SnapMirror ラベルとデスティネーションの保持数を指定します。
+
新しい SnapMirror ラベルを有効にするには、同じラベルの Snapshot コピーをソースボリュームに作成する必要があります。

.. [ 作成（ Create ） ] をクリックします。


|===
. 関係のスケジュールを指定します。
+
|===
| 状況 | 実行する処理 


 a| 
既存のスケジュールを割り当てる
 a| 
[* 参照 ] をクリックし、既存のスケジュールを選択します。



 a| 
新しいスケジュールを作成する
 a| 
.. [ スケジュールの作成 *] をクリックします。
.. スケジュールの名前を指定します。
.. 次のいずれかのオプションを選択します。
+
*** * 基本 *
+
曜日、時刻、および転送間隔だけを指定する場合に選択します。

*** * 詳細 *
+
cron 形式のスケジュールを指定する場合に選択します。



.. [ 作成（ Create ） ] をクリックします。




 a| 
スケジュールを割り当てない
 a| 
「 * なし * 」を選択します。

|===
. [OK] をクリックします。




== 関係を手動で更新する

System Manager を使用して、スケジュールされていない差分更新を手動で開始できます。予定された停電、スケジュールされた保守、またはデータ移行によるデータ損失を防ぐために、手動更新が必要になる場合があります。

.作業を開始する前に
ミラーとバックアップ関係が初期化され、 SnapMirror 済みの状態である必要があります。

.手順
. [* 保護 *>] 、 [* ボリューム関係 *] の順にクリックします。
. データを更新するミラー関係を選択し、 * Operations * > * Update * をクリックします。
. 次のいずれかのオプションを選択します。
+
** 「ポリシーに従う」を選択し、ソースボリュームとデスティネーションボリュームの間の最新の共通の Snapshot コピーから差分転送を実行します。
** Select Snapshot copy * を選択し、転送する Snapshot コピーを指定します。


. 転送に使用するネットワーク帯域幅を制限するには、「 * 転送帯域幅を * に制限」を選択し、最大転送速度を指定します。
. [ 更新（ Update ） ] をクリックします。
. [ * 詳細 * ] タブで転送ステータスを確認します。




== 関係を初期化

System Manager を使用して、作成時に初期化していないミラーとバックアップ関係を初期化することができます。関係を初期化すると、ソースボリュームからデスティネーションへ全データのベースライン転送が実行されます。

.作業を開始する前に
ソースクラスタとデスティネーションクラスタで正常なピア関係が確立されている必要があります。

.手順
. [* 保護 *>] 、 [* ボリューム関係 *] の順にクリックします。
. 初期化するミラーとバックアップ関係を選択し、 * Operations * > * Initialize * をクリックします。
. 確認のチェックボックスをオンにし、 [Initialize （初期化） ] をクリックします。
. [ 保護（ Protection ） ] ウィンドウで関係のステータスを確認します。


.結果
Snapshot コピーが作成されてデスティネーションに転送されます。

この Snapshot コピーは、以降の差分 Snapshot コピーのベースラインとして使用されます。



== デスティネーション SVM から関係を作成

System Manager を使用して、ミラーとバックアップ関係をデスティネーション Storage Virtual Machine （ SVM ）から作成することができます。この関係を作成すると、ソースボリュームからデスティネーションボリュームにデータを定期的に転送して、データの保護を強化できます。また、ソースボリュームのバックアップを作成して、データを長期にわたって保持することもできます。

.作業を開始する前に
* デスティネーションクラスタで ONTAP 8.3.2 以降が実行されている必要があります。
* ソースクラスタとデスティネーションクラスタで SnapMirror ライセンスが有効になっている必要があります。
+
[NOTE]
====
一部のプラットフォームでは、デスティネーションクラスタで SnapMirror ライセンスに加えて Data Protection Optimization （ DPO ）ライセンスが有効になっていれば、ソースクラスタで SnapMirror ライセンスが有効になっていなくてもかまいません。

====
* ソースクラスタとデスティネーションクラスタで正常なピア関係が確立されている必要があります。
* デスティネーション SVM の使用可能なスペースを確保する必要があります。
* ソースアグリゲートとデスティネーションアグリゲートはどちらも 64 ビットである必要があります。
* 読み書き可能（ rw ）タイプのソースボリュームを用意しておく必要があります。
* SnapLock アグリゲートのタイプが同じである必要があります。
* ONTAP 9.2 以前のバージョンを実行しているクラスタから SAML 認証が有効になっているリモートクラスタに接続する場合は、リモートクラスタでパスワードベースの認証を有効にする必要があります。


.このタスクについて
* System Manager ではカスケード関係はサポートされません。
+
たとえば、関係のデスティネーションボリュームを別の関係のソースボリュームにすることはできません。

* MetroCluster 構成の同期元の SVM と同期先の SVM の間には、ミラーとバックアップ関係を作成することはできません。
* MetroCluster 構成の同期元の SVM 間には、ミラーとバックアップ関係を作成できます。
* 同期元の SVM のボリュームからデータ提供用の SVM のボリュームへのミラーとバックアップ関係を作成できます。
* データ提供用の SVM から同期元の SVM の DP ボリュームへのミラーとバックアップ関係を作成できます。
* 一度に保護できるボリュームは最大 25 個です。


.手順
. [* 保護 *>] 、 [* ボリューム関係 *] の順にクリックします。
. [ リレーションシップ *] ウィンドウで、 [ 作成 *] をクリックします。
. [* SVM を参照 * ] ダイアログボックスで、デスティネーションボリュームの SVM を選択します。
. [ 保護関係の作成 * （ Create Protection Relationship Relationship * ） ] ダイアログボックスで、 [ 関係タイプ * （ Relationship Type * ） ] ドロップダウンリストから [ * ミラーとバックアップ * （ * Mirror and Vault * ） ] を選択する。
. クラスタ、 SVM 、およびソースボリュームを指定します。
+
指定したクラスタで ONTAP 9.3 より前のバージョンの ONTAP ソフトウェアが実行されている場合、ピア関係が設定された SVM だけが表示されます。指定したクラスタで ONTAP 9.3 以降が実行されている場合は、ピア関係が設定された SVM と許可された SVM が表示されます。

. ボリューム名サフィックスを入力します。
+
ボリューム名サフィックスをソースボリュームの名前に追加したものがデスティネーションボリュームの名前として使用されます。

. *オプション：*参照*をクリックし、ミラーとバックアップポリシーを変更します。
+
ソースボリュームに関連付けられた Snapshot ポリシーと最も多くのラベルが一致するポリシーを選択できます。

. 既存のスケジュールのリストから関係のスケジュールを選択します。
. *オプション：* Initialize Relationship *を選択して、関係を初期化します。
. FabricPool 対応アグリゲートを有効にし、適切な階層化ポリシーを選択します。
. 選択したボリュームでラベルが一致するかどうかを確認するには、 * Validate * をクリックします。
. [ 作成（ Create ） ] をクリックします。




== 関係を再同期する

System Manager を使用して、以前に解除したミラーとバックアップ関係を再確立できます。再同期操作を実行して、災害によってソースボリュームが機能しなくなった状態からリカバリできます。

.作業を開始する前に
ソースクラスタとデスティネーションクラスタ、およびソースとデスティネーションの Storage Virtual Machine （ SVM ）でピア関係が確立されている必要があります。

.このタスクについて
再同期処理を実行する前に、次の点に注意してください。

* 再同期操作を実行すると、デスティネーションボリュームの内容がソースの内容で上書きされます。
+
[NOTE]
====
再同期処理では、ベースの Snapshot コピーが作成されたあとにデスティネーションボリュームに書き込まれた新しいデータが原因によって失われる可能性があります。

====
* Protection ウィンドウの Last Transfer Error フィールドで再同期操作を実行するように推奨された場合は、最初に関係を解除してから再同期処理を実行する必要があります。


.手順
. [* 保護 *>] 、 [* ボリューム関係 *] の順にクリックします。
. 再同期するミラーとバックアップ関係を選択し、 * Operations * > * Resync * をクリックします。
. 確認のチェックボックスをオンにし、 * Resync * をクリックします。




== 関係を逆再同期

System Manager を使用して、以前に解除したミラーとバックアップ関係を再確立できます。逆再同期操作を実行すると、ソースボリュームとデスティネーションボリュームの機能が入れ替わります。デスティネーションボリュームでデータを提供しながら、ソースを修理または交換したり、ソースを更新したり、システムの元の構成を再確立したりできます。

.作業を開始する前に
ソースボリュームはオンラインである必要があります。

.このタスクについて
* 逆再同期を実行すると、ソースボリュームの内容がデスティネーションボリュームの内容で上書きされます。
+
[NOTE]
====
逆再同期処理を実行すると、ソースボリュームで原因のデータが失われる可能性があります。

====
* 逆再同期の実行時は、関係のポリシーが MirrorAndVault に設定され、スケジュールが None に設定されます。


.手順
. [* 保護 *>] 、 [* ボリューム関係 *] の順にクリックします。
. 反転するミラーとバックアップ関係を選択し、 * Operations * > * Reverse Resync * をクリックします。
. 確認のチェックボックスをオンにし、 * 逆再同期 * をクリックします。




== 関係を解除します

ソースボリュームを使用できなくなった場合にクライアントアプリケーションからデスティネーションボリュームのデータにアクセスできるようにするには、 System Manager を使用して、ミラーとバックアップ関係を解除します。デスティネーションボリュームでデータを提供しながら、ソースボリュームを修理または交換したり、ソースボリュームを更新したり、システムの元の構成を再確立したりできます。

.作業を開始する前に
* ミラーとバックアップ関係が休止状態またはアイドル状態である必要があります。
* デスティネーションボリュームを Storage Virtual Machine （ SVM ）ネームスペースにマウントしておく必要があります。


.このタスクについて
ONTAP システムと SolidFire ストレージシステムの間のミラー関係を解除できます。

.手順
. [* 保護 *>] 、 [* ボリューム関係 *] の順にクリックします。
. 解除するミラーとバックアップ関係を選択し、 * Operations * > * Break * をクリックします。
. 確認のチェックボックスをオンにし、 * ブレーク * をクリックします。


.結果
ミラーとバックアップ関係が解除されます。デスティネーションボリュームのタイプがデータ保護（ DP ）の読み取り専用から読み書き可能に変更されます。あとで使用できるように、ミラーとバックアップ関係のベースの Snapshot コピーが保存されます。



== 関係を再開

ミラーとバックアップ関係が休止中の場合、 System Manager を使用して関係を再開できます。関係を再開すると、デスティネーションボリュームへの通常のデータ転送が再開され、保護アクティビティもすべて再開されます。

.このタスクについて
解除されたミラーとバックアップ関係をコマンドラインインターフェイス（ CLI ）で休止した場合は、 System Manager で再開することはできません。CLI を使用して関係を再開してください。

.手順
. [* 保護 *>] 、 [* ボリューム関係 *] の順にクリックします。
. 再開するミラーとバックアップ関係を選択し、 * Operations * > * Resume * をクリックします。
. 確認のチェックボックスをオンにし、 * Resume * （続行）をクリックします。


.結果
通常のデータ転送が再開されます。関係に対して転送がスケジュールされている場合、その転送は次回のスケジュールから開始されます。



== 関係を削除します

System Manager を使用して、ソースボリュームとデスティネーションボリュームの間のミラーとバックアップ関係を終了し、ソースボリュームから Snapshot コピーを解放できます。

.このタスクについて
* ミラーとバックアップ関係を削除する前に、その関係を解除することが推奨されます。
* 関係を再作成するには、コマンドラインインターフェイス（ CLI ）を使用して、ソースボリュームから再同期操作を実行する必要があります。


.手順
. [* 保護 *>] 、 [* ボリューム関係 *] の順にクリックします。
. 削除するミラーとバックアップ関係を選択し、 * 削除 * をクリックします。
. 確認のチェックボックスをオンにし、 * 削除 * をクリックします。
+
ベース Snapshot コピーを解放するチェックボックスを選択すると、ミラーとバックアップ関係に使用されているベース Snapshot コピーもソースボリュームから削除できます。

+
関係を解放せずに、ミラーとバックアップ関係に対して作成されたベース Snapshot コピーをソースボリュームから削除するには、 CLI を使用してソースクラスタに対して解放処理を実行する必要があります。



.結果
関係が削除され、ソースボリュームのベース Snapshot コピーが永続的に削除されます。



== 関係を休止します

System Manager を使用して、 Snapshot コピーを作成する前にデスティネーションボリュームを休止して、安定した状態にすることができます。休止処理を実行すると、アクティブなデータ転送が完了したあと、ミラーとバックアップ関係の以降の転送が実行されなくなります。

.作業を開始する前に
ミラーとバックアップ関係は、 SnapMirror 済みの状態である必要があります。

.手順
. [* 保護 *>] 、 [* ボリューム関係 *] の順にクリックします。
. 休止するミラーとバックアップ関係を選択し、 * Operations * > * Quiesce * をクリックします。
. 確認のチェックボックスをオンにし、 * 休止 * をクリックします。


.結果
実行中の転送がない場合、転送ステータスは次のように表示されます。 `Quiesced`。転送が実行中の場合、転送は影響を受けず、転送ステータスはと表示されます。 `Quiescing` 転送が完了するまで。
