---
permalink: online-help-96-97/task_editing_svm_settings.html 
sidebar: sidebar 
keywords: online, help, system, manager, edit, svm, settings 
summary: System Manager を使用して、 Storage Virtual Machine （ SVM ）のプロパティ（ネームサービススイッチ、ネームマッピングスイッチ、アグリゲートリストなど）を編集できます。 
---
= System Manager - ONTAP 9.7 以前を使用して、 SVM の設定を編集します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP System Manager クラシック（ ONTAP 9.7 以前で使用可能）を使用して、 Storage Virtual Machine （ SVM ）のプロパティ（ネームサービススイッチ、ネームマッピングスイッチ、アグリゲートリストなど）を編集できます。

.このタスクについて
* SVM の次のプロパティの値を編集できます。
+
** ネームサービススイッチ
** データのやり取りに使用できるプロトコル
+
[NOTE]
====
SVM に CIFS プロトコルが設定されている場合、その SVM で CIFS プロトコルを無効にしても引き続きデータ処理に使用されます。

====
** ボリュームの作成に使用できるアグリゲートのリスト
+
[NOTE]
====
FlexVol ボリュームの場合、アグリゲートを割り当てることができるのは、 SVM 管理者に管理を委譲している場合だけです。

====


* System Manager では、 CLI を使用して作成された SVM や、 ONTAP によって設定されておらず、デフォルト値に設定されていない SVM については、ネームサービススイッチおよびネームマッピングスイッチの値は表示されません。
+
サービスタブが無効になっているため、コマンドラインインターフェイスを使用してサービスを表示できます。

+
System Manager でネームサービススイッチおよびネームマッピングスイッチが表示されるのは、 SVM を System Manager で作成した場合と、 SVM のサービスが ONTAP でデフォルト値に設定されている場合だけです。



.手順
. [ * ストレージ * > * SVMs * ] をクリックします。
. SVMを選択し、*[編集]*をクリックします。
. [ * 詳細 * ] タブで、必要なデータプロトコルを変更します。
. リソース割り当て * タブで、ボリューム作成を委任する方法を次の中から 1 つ選択します。
+
|===
| ボリューム作成をプロビジョニングするアグリゲート | 作業 


 a| 
すべてのアグリゲート
 a| 
ボリューム作成を委譲しない * オプションを選択します。



 a| 
特定のアグリゲートの場合
 a| 
.. [*Delegate volume creation *] オプションを選択します。
.. ボリューム作成を委譲するアグリゲートを選択します。


|===
. *Service* タブで、必要なデータベース・タイプのネーム・サービス・スイッチ・ソース、およびネーム・サービス情報取得時の各ソースの参照順序を指定します。
+
各データベースタイプのデフォルト値は次のとおりです。

+
** hosts ：ファイル、 DNS
** namemap ：ファイル
** グループ：ファイル
** netgroup ： files
** passwd ：ファイル


. [ 保存して閉じる ] をクリックします。


* 関連情報 *

xref:concept_how_data_ontap_name_service_switch_configuration_works.adoc[ONTAP のネームサービススイッチ設定の仕組み]
