---
permalink: online-help-96-97/task_obtaining_ontap_software_images.html 
sidebar: sidebar 
keywords: online, help, obtain, ontap, software, image, netapp, support, site, online, help 
summary: ONTAP 9.4 以降では、 ONTAP ソフトウェアイメージをNetApp Support Siteからローカルフォルダにコピーできます。ONTAP 9.3 以前からのアップグレードの場合は、 ONTAP ソフトウェアイメージをネットワーク上の HTTP サーバまたは FTP サーバにコピーする必要があります。 
---
= System Manager - ONTAP 9.7 以前を使用して、 ONTAP ソフトウェアイメージを取得します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP ソフトウェアイメージは、 ONTAP System Manager クラシック（ ONTAP 9.7 以前で使用可能）で取得できます。ONTAP 9.4 以降では、 ONTAP ソフトウェアイメージをNetApp Support Siteからローカルフォルダにコピーできます。ONTAP 9.3 以前からのアップグレードの場合は、 ONTAP ソフトウェアイメージをネットワーク上の HTTP サーバまたは FTP サーバにコピーする必要があります。

.このタスクについて
クラスタを ONTAP の目的のリリースにアップグレードするには、ソフトウェアイメージが必要です。ソフトウェアイメージ、ファームウェアのバージョン情報、プラットフォームモデルの最新のファームウェアは、NetApp Support Siteで入手できます。次の重要な情報に注意してください。

* ソフトウェアイメージはプラットフォームモデルに固有です。
+
ご使用のクラスタに対応するイメージを取得してください。

* ソフトウェアイメージには、 ONTAP の特定のバージョンのリリース時点でのシステムファームウェアの最新バージョンが含まれています。
* NetApp Volume Encryption を搭載したシステムを ONTAP 9.5 以降にアップグレードする場合は、 NetApp Volume Encryption を含む制限のない国の ONTAP ソフトウェアイメージをダウンロードする必要があります。
+
規制対象国用の ONTAP ソフトウェアイメージを使用して NetApp Volume Encryption を搭載したシステムをアップグレードすると、システムがパニック状態になり、ボリュームへのアクセスが失われます。

* ONTAP 9.3 から 9.7 にアップグレードする場合は、 ONTAP 9.5 および 9.7 のソフトウェアイメージをコピーする必要があります。


.手順
. NetApp Support Siteの「 * ソフトウェアのダウンロード」領域で、対象となる ONTAP ソフトウェアを探します。
. ソフトウェアイメージをコピーします。
+
** ONTAP 9.3以前の場合は、ソフトウェアイメージをコピーします（例： `93_q_image.tgz`）を使用して、NetApp Support Siteから、イメージを提供するHTTPサーバまたはFTPサーバ上のディレクトリに移動します。
** ONTAP 9.4以降の場合は、ソフトウェアイメージ（例： `97_q_image.tgz`）をクリックします。NetApp Support Siteから、イメージが提供されるHTTPサーバまたはFTPサーバ上のディレクトリ、またはローカルフォルダに移動します。



