---
permalink: online-help-96-97/task_editing_application.html 
sidebar: sidebar 
keywords: edit, application, online, help, provisioned, snapshot, copy 
summary: プロビジョニングされたアプリケーションを編集して、ストレージサイズを増やしたり、アプリケーションの Snapshot コピーを管理したりすることができます。 
---
= System Manager - ONTAP 9.7 以前を使用してアプリケーションを編集します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP System Manager クラシック（ ONTAP 9.7 以前で使用可能）を使用して、プロビジョニングされたアプリケーションを編集し、ストレージサイズを増やしたり、アプリケーションの Snapshot コピーを管理したりできます。

.このタスクについて
クラスタ管理者は、プロビジョニングしたアプリケーションを編集してストレージサイズを変更できます。また、アプリケーションの Snapshot コピーを作成、リストア、または削除することもできます。次の手順の例では、 * NAS * Container * アプリケーションを編集する方法を説明します。

.手順
. [* アプリケーションと階層 *>*Applications* ] をクリックします
. NAS コンテナアプリケーションの名前をクリックします。
+
[NOTE]
====
アプリケーションのリストを表示しているときに他のユーザが CLI または REST API を使用してアプリケーションを追加した場合、それらの新しいアプリケーションはリストをスクロールしても表示されません。

====
+
[ アプリケーションの詳細： NAS] ウィンドウの [ 概要 *] タブには、アプリケーションの設定が表示されます。

. [ 編集（ Edit ） ] をクリックします。
+
Edit NAS Container-NAS （ NAS コンテナの編集： NAS ）には、現在のストレージサイズ設定と、 *NFS Access-Grant Access to Host* アドレスが表示されます。

. ストレージ合計サイズ * の値を変更します。
. サイズ単位のフィールドで、ドロップダウンメニューから適切な単位を選択します（バイト、 MB 、 GB 、または TB ）。
. [*Service Level*] ONTAP フィールドで、ドロップダウンメニューから値を選択します。
. [ 保存（ Save ） ] をクリックします。
. [*Application Details: NAS*] ウィンドウに戻り、 [** Snapshot Copies**] タブを選択します。
+
このプロビジョニング済みアプリケーションの Snapshot コピーが一覧表示されます。「 * Search * 」フィールドを使用して、 Snapshot コピーを名前で検索できます。

. 次のタスクを必要に応じて実行し、 Snapshot コピーを管理します。
+
|===
| タスク | アクション 


 a| 
作成
 a| 
Create * をクリックして、新しい Snapshot コピーを作成します。



 a| 
リストア
 a| 
リストアする Snapshot コピーの横にあるチェックボックスをクリックし、 * Restore * をクリックします。



 a| 
削除
 a| 
削除する Snapshot コピーの横にあるチェックボックスをクリックし、 * Delete * をクリックします。

|===

