---
permalink: online-help-96-97/task_creating_svms.html 
sidebar: sidebar 
keywords: create, svm, system, manager, cluster, online, help 
summary: System Manager を使用してすべての構成を設定して Storage Virtual Machine （ SVM ）を作成すると、その SVM ですぐにデータを提供することができます。クラスタには 1 つ以上の SVM を配置できます。 
---
= System Manager - ONTAP 9.7 以前を使用して SVM を作成します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP System Managerクラシック（ONTAP 9.7以前で使用可能）を使用して、完全に設定されたStorage Virtual Machine（SVM）を作成し、データをただちに提供することができます。クラスタには 1 つ以上の SVM を配置できます。

.作業を開始する前に
* クラスタには、ルートではないオンライン状態のアグリゲートが少なくとも 1 つ必要です。
* アグリゲートには、 SVM のルートボリューム用の十分なスペースが必要です。
* CIFS の作成および認証エラーが発生しないように NTP を設定して有効にし、クラスタ内で時間を同期させておく必要があります。
* SVM で設定するプロトコルのライセンスが必要です。
* セキュアな DDNS を使用するために CIFS プロトコルを設定しておく必要があります。


.このタスクについて
* SVM を作成する際、次の作業を実行できます。
+
** SVM を作成し、完全に設定する。
** SVM で許可するボリュームタイプを設定する。
** SVM を作成し、最小限のネットワーク設定だけを行う。
** SVM 管理者に管理を委譲する。


* SVMの名前には、英数字と特殊文字「'」を使用できます。.`" (period), "`-`"(ハイフン)、および"`_`"(アンダースコア)。
+
SVM 名の 1 文字目はアルファベットまたは "_" （アンダースコア）にする必要があります。最大文字数は 47 文字です。

+
[NOTE]
====
SVM 名には、 vs0.example.com のような一意の Fully Qualified Domain Name （ FQDN ；完全修飾ドメイン名）を使用します。

====
* SnapMirror 関係は、言語設定が同じボリューム間でのみ確立できます。
+
SVM の言語によって、 SVM 内のすべての NAS ボリュームのファイル名とデータの表示に使用される文字セットが決まります。

* SnapLock アグリゲートを SVM のルートアグリゲートとして使用することはできません。


.手順
. [ * ストレージ * > * SVMs * ] をクリックします。
. [ 作成（ Create ） ] をクリックします。
. Storage Virtual Machine （ SVM ）のセットアップ * ウィンドウで、次の詳細を指定します。
+
** SVM 名
** SVM に割り当てられている IPspace です
** 許可されているボリュームタイプです
** 許可されているプロトコル
** SVM の言語
** ルートボリュームのセキュリティ形式
** ルートアグリゲート
+
SVMのデフォルトの言語設定はC.UTF-8です。

+
デフォルトでは、空きスペースが最も多いアグリゲートが SVM のルートボリュームのコンテナとして選択されます。デフォルトのセキュリティ形式とルートアグリゲートは、選択したプロトコルに基づいて選択されます。

+
CIFSプロトコル、またはCIFSプロトコルと他のプロトコルの組み合わせを選択した場合は、セキュリティ形式はNTFSに設定されます。NFS 、 iSCSI 、 NVMe 、 FC / FCoE の各プロトコル、またはそれらのプロトコルの組み合わせを選択した場合は、セキュリティ形式は UNIX に設定されます。

+
[NOTE]
====
NVMe を使用する場合は、プロトコルを組み合わせることはできません。

====


+
MetroCluster 構成では、クラスタに含まれるアグリゲートのみが表示されます。

. DNS ドメインの名前とネームサーバの IP アドレスを指定して DNS サービスを設定します。
+
デフォルトでは、既存の SVM 設定の値が選択されます。

. *オプション：プロトコルを使用してデータにアクセスするようにデータLIFを設定する場合は、ターゲットエイリアス、サブネット、ノードあたりのLIF数を指定します。
+
LIF のポートセットの数を変更するには、「 * Review or Modify LIFs configuration （ Advanced Settings ） * 」チェックボックスを選択します。

+
特定のノードのポートセットの詳細を編集するには、詳細領域のノードリストからノードを選択します。

. *オプション：SVMのクレデンシャルを指定して、SnapDrive やSnapManager などのホスト側アプリケーションをSVM管理者に対して有効にします。
. *オプション：* NVMe以外のプロトコルを使用する場合、* Create a new LIF for SVM management *をクリックしてSVM管理用の新しいLIFを作成し、ポートセットとIPアドレスに新しい管理LIFのサブネットの有無を指定します。
+
CIFS プロトコルと NFS プロトコルのデータ LIF には、デフォルトで管理アクセスが付与されます。新しい管理 LIF は必要な場合にのみ作成する必要があります。iSCSI および FC の場合、データプロトコルと管理プロトコルで 1 つの LIF を共有できないため、 SVM 管理 LIF が必要になります。

. *オプション：* ONTAP 9.5以降では、SVMセットアップウィザードの2ページ目で各ノードに少なくとも1つのLIFを設定します。* NVMeプロトコルを設定。*
+
HA ペアの各ノードに対して少なくとも 1 つの LIF を設定する必要があります。LIF はノードごとに 2 つ指定することもできます。設定アイコンをクリックすると、 LIF の設定が 1 つまたは 2 つに切り替わります。

. [Submit & Continue] をクリックします。
+
指定した設定で SVM が作成されます。



.結果
作成した SVM は自動的に起動します。ルートボリューム名は次のように自動的に生成されます。 `SVM name_root`。デフォルトでは、が表示されます `vsadmin` ユーザアカウントが作成され、ロック状態になっている。



== 次に何をするか

SVM で少なくとも 1 つのプロトコルを設定してデータアクセスを許可する必要があります。
