---
permalink: online-help-96-97/task_updating_single_node_clusters.html 
sidebar: sidebar 
keywords: update, singe, node, cluster, system, manager, online, help 
summary: System Manager を使用して、シングルノードクラスタを更新できます。 
---
= System Manager - ONTAP 9.7 以前を使用してシングルノードクラスタを更新します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP System Manager クラシック（ ONTAP 9.7 以前で使用可能）を使用して、シングルノードクラスタを更新できます。

.作業を開始する前に
* クラスタでONTAP 9.4以降が実行されている必要があります。
* NetApp Support Siteからネットワーク上の HTTP サーバ、 FTP サーバ、またはローカルシステムにソフトウェアイメージをコピーしておき、ノードからイメージにアクセスできるようにする必要があります。
+
link:task_obtaining_ontap_software_images.html["ONTAP ソフトウェアイメージの取得"]



.このタスクについて
* System Manager 9.5 以降では、 2 パック MetroCluster 構成のシングルノードクラスタを更新できます。
+
この処理は両方のサイトで実行する必要があります。

* MetroCluster 構成のシングルノードクラスタの更新は、システムの停止を伴わない処理です。
+
クラスタのリブート中は、 System Manager のユーザインターフェイスを使用できません。

* System Manager 9.4 以降では、 MetroCluster 以外の構成のシングルノードクラスタを更新できます。
+
MetroCluster 以外の構成のシングルノードクラスタの更新は、システムの停止を伴う処理です。更新の実行中はクライアントデータを使用できません。

* クラスタ管理 LIF をホストしているノードの更新中に他のタスクを実行しようとすると、エラーメッセージが表示される場合があります。
+
更新が完了してから、他の処理を実行してください。

* System Manager 9.4 で NVMe プロトコルが設定されている場合に System Manager 9.4 を System Manager 9.5 にアップグレードすると、 90 日の猶予期間が与えられ、この期間は NVMe プロトコルをライセンスなしで利用できます。
+
この機能は、 MetroCluster 構成では使用できません。

* System Manager 9.5 で NVMe プロトコルが設定されていない場合に System Manager 9.5 を System Manager 9.6 にアップグレードすると、猶予期間は与えられず、 NVMe プロトコルを使用するには NVMe ライセンスをインストールする必要があります。
+
この機能は、 MetroCluster 構成では使用できません。



.手順
. [* Configuration * （設定 * ） ] > [* Cluster * （クラスタ * ） ] > [* Update * （アップデート *
. [* クラスタ・アップデート * ] タブで、新しいソフトウェア・イメージを追加するか、使用可能なソフトウェア・イメージを選択します。
+
|===
| 状況 | 作業 


 a| 
ローカルクライアントから新しいソフトウェアイメージを追加します
 a| 
.. [ ローカルクライアントから追加 ] をクリックします。
.. ソフトウェアイメージを検索し、 * 開く * をクリックします。




 a| 
NetApp Support Siteから新しいソフトウェアイメージを追加します
 a| 
.. [ サーバーから追加 ] をクリックします。
.. Add a New Software Image ダイアログボックスに、NetApp Support Siteからダウンロードしたイメージを保存した HTTP サーバまたは FTP サーバの URL を入力します。
+
匿名 FTP の URL は、で指定する必要があります `+ftp://anonymous@ftpserver+` の形式で入力し

.. [ 追加（ Add ） ] をクリックします。




 a| 
使用可能なイメージを選択します
 a| 
表示された画像のいずれかを選択します。

|===
. 更新前の検証チェックを実行してクラスタを更新する準備ができているかどうかを確認するには、 * Validate * をクリックします。
+
クラスタコンポーネントがチェックされて更新を実行できるかどうかが検証され、エラーや警告があれば表示されます。ソフトウェアの更新前に実施する必要がある対処方法があれば、あわせて表示されます。

+
[NOTE]
====
更新を実行する前に、エラーに対して必要な対処方法をすべて実施する必要があります。警告の修復アクションは無視できますが、更新に進む前にそれらの修復アクションもすべて実行することを推奨します。

====
. 「 * 次へ * 」をクリックします。
. [ 更新（ Update ） ] をクリックします。
+
再度検証が実行されます。

+
** 検証が完了すると、エラーや警告があれば、続行する前に実施する必要がある対処方法と一緒にテーブルに表示されます。
** 検証が警告付きで完了した場合は、 [ 警告付き更新を続行する *] チェックボックスをオンにして、 [ 続行 *] をクリックします。
検証が完了し、更新が開始されたあと、エラーが発生して更新が中断される場合があります。その場合、エラーメッセージをクリックして詳細を表示し、修復アクションを実施してから更新を再開できます。


+
更新が完了すると、ノードがリブートし、 System Manager のログインページが表示されます。ノードのリブートに時間がかかる場合は、ブラウザを更新する必要があります。

. System Manager にログインし、 * Configuration * > * Cluster * > * Update * > * Update History * をクリックして、選択したバージョンにクラスタが正しく更新されたことを確認し、次に詳細を表示します。

