---
permalink: online-help-96-97/task_moving_luns.html 
sidebar: sidebar 
keywords: move, lun, qtree, storage, virtual, machine, svm, online, help 
summary: System Manager を使用して、 Storage Virtual Machine （ SVM ）内で、あるボリュームの LUN を別のボリュームまたは qtree に移動できます。ハイパフォーマンスディスクを含むアグリゲートでホストされているボリュームに LUN を移動すると、 LUN へのアクセス速度が向上します。 
---
= System Manager ONTAP 9.7 以前を使用して LUN を移動します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP System Manager クラシック（ ONTAP 9.7 以前で使用可能）を使用して、 Storage Virtual Machine （ SVM ）内で、格納先ボリュームから別のボリュームまたは qtree に LUN を移動できます。ハイパフォーマンスディスクを含むアグリゲートでホストされているボリュームに LUN を移動すると、 LUN へのアクセス速度が向上します。

.このタスクについて
* 同じボリューム内の qtree に LUN を移動することはできません。
* CLI を使用してファイルから作成した LUN は、 System Manager を使用して移動することはできません。
* LUN の移動処理は無停止で実行でき、移動中も LUN はオンラインでデータを提供することができます。
* デスティネーションボリュームに割り当てられているスペースが LUN の格納に十分でない場合は、 System Manager を使用して LUN を移動することはできません。ボリュームで自動拡張が有効になっていても同様です。
+
代わりに CLI を使用する必要があります。

* SnapLock ボリューム上で LUN を移動することはできません。


.手順
. [ * ストレージ * > * LUNs * ] をクリックします。
. [* LUN 管理 * ] タブで、 LUN のリストから移動する LUN を選択し、 [* 移動 ] をクリックします。
. *オプション：* LUNの移動*ダイアログ・ボックスの*移動オプション*領域で'デフォルトの名前を変更する場合は'新しいLUN名を指定します
. LUN の移動先のストレージオブジェクトを選択し、次のいずれかの操作を実行します。
+
|===
| LUN の移動先 | 作業 


 a| 
新しいボリューム
 a| 
.. 新しいボリュームを作成するアグリゲートを選択します。
.. ボリュームの名前を指定します。




 a| 
既存のボリュームまたは qtree
 a| 
.. LUN を移動するボリュームを選択します。
.. 選択したボリュームに qtree が含まれている場合、 LUN の移動先の qtree を選択します。


|===
. [ 移動（ Move ） ] をクリックします。
. LUN の移動処理を確認し、 * Continue * をクリックします。
+
ごく短時間、移動した LUN が元のボリュームと移動後のボリュームの両方に表示されます。移動処理が完了すると、デスティネーションボリュームに LUN が表示されます。

+
デスティネーションボリュームまたは qtree が、 LUN の新しいコンテナパスとして表示されます。


