---
permalink: fc-config-esxi/task_verifying_host_can_write_to_read_from_lun.html 
sidebar: sidebar 
keywords: lun, verify, write, data, verify that the host can write to and read from the lun 
summary: LUN を使用する前に、ホストが LUN のデータを読み取りおよび書き込みできることを確認する必要があります。 
---
= ホストが LUN に対して読み取りと書き込みを実行できることを確認します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
LUN を使用する前に、ホストが LUN のデータを読み取りおよび書き込みできることを確認する必要があります。

.このタスクについて
LUN の作成先のクラスタノードがパートナーノードにフェイルオーバーできるように設定されている場合、ノードのフェイルオーバー時にデータを読み取れることを確認する必要があります。このテストは本番環境のクラスタでは実行できない場合があります。

.手順
. vSphere Web Client * Home * ページで、 * Hosts and Clusters * をクリックします。
. ナビゲーションペインで、 * ストレージ * タブをクリックします。
. データセンターを展開し、新しいデータストアを選択します。
. 中央のウィンドウ枠で、 * Manage * > * Files * をクリックします。
+
データストアの内容が表示されます。

. データストアに新しいフォルダを作成し、そのフォルダにファイルをアップロードします。
+
クライアント統合プラグインのインストールが必要になる場合があります。

. 書き込んだファイルにアクセスできることを確認します。
. *オプション：LUNを含むクラスタノードをフェイルオーバーし、ファイルに対して引き続き書き込みおよび読み取り可能かどうかを確認します。
+
テストに失敗した場合は、ストレージクラスタで FC サービスが実行されていることを確認し、 LUN および FC スイッチゾーニングへの FC パスをチェックしてください。

. *オプション：クラスタノードをフェイルオーバーした場合は、ノードをギブバックし、すべてのLIFをホームポートに戻します。
. ESXi クラスタの場合は、クラスタの各 ESXi ホストのデータストアを表示し、アップロードしたファイルが表示されることを確認します。


* 関連情報 *

https://docs.netapp.com/us-en/ontap/high-availability/index.html["ONTAP 9 ハイアベイラビリティ構成"]
