---
permalink: fc-config-rhel/index.html 
sidebar: sidebar 
keywords: fc, service, storage, virtual, machine, svm, provision, lun, fc, host, bus, adapter, hba, linux, server, configuration, red hat enterprise linux 
summary: Storage Virtual Machine に FC サービスをセットアップし、 LUN をプロビジョニングし、 Red Hat Enterprise Linux サーバで FC ホストバスアダプタを使用して LUN を使用できるように設定することができます。 
---
= Red Hat Enterprise Linux 向けの FC の設定の概要
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP ONTAP 9.7 以前のインターフェイスを使用して、 Storage Virtual Machine （ SVM ）に FC サービスをセットアップし、 LUN をプロビジョニングし、 Red Hat Enterprise Linux サーバで FC ホストバスアダプタ（ HBA ）を使用して LUN を使用できるように設定することができます。

この手順を使用して SVM に FC サービスをセットアップします。状況：

* ホストで Red Hat Enterprise Linux 6.4 以降のサポート対象バージョンが実行されている。
* 従来の FC HBA およびスイッチを使用している。
+

NOTE: この手順では Fibre Channel over Ethernet （ FCoE ）については説明しません。

* クラスタの各ノードに使用可能な FC ターゲットポートが少なくとも 2 つある。
オンボード FC および UTA2 （別名「 CNA 」）ポート、および一部のアダプタは設定が可能です。これらのポートは ONTAP コマンドラインインターフェイス（ CLI ）で設定しますが、この手順では説明しません。
* FC SAN ブートを設定しない。


上記の想定条件に該当しない場合は、次の資料を参照してください。

* https://docs.netapp.com/us-en/ontap/san-admin/index.html["SAN 管理"^]
* https://docs.netapp.com/us-en/ontap/san-config/index.html["SAN構成"^]
* https://docs.netapp.com/us-en/ontap-sanhost/hu_luhu_71.html["Linux Unified Host Utilities 7.1 のインストール"^]




== ONTAP でこれを行うその他の方法

|===


| 実行するタスク | 参照先 


| 再設計された System Manager （ ONTAP 9.7 以降で使用可能） | link:https://docs.netapp.com/us-en/ontap/task_san_provision_linux.html["Linux サーバ用の SAN ストレージをプロビジョニング"^] 


| ONTAP コマンドラインインターフェイス（ CLI ） | link:https://docs.netapp.com/us-en/ontap/san-admin/lun-setup-workflow-concept.html["CLI での LUN セットアップのワークフロー"^] 
|===