---
permalink: iscsi-config-rhel/task_verifying_that_host_can_write_to_read_fom_lun.html 
sidebar: sidebar 
keywords: multipath, device, verify, host, data, verify that the host can write to and read from a multipath device 
summary: マルチパスデバイスを使用する前に、ホストがマルチパスデバイスのデータを読み取りおよび書き込みできることを確認する必要があります。 
---
= ホストによるマルチパスデバイスに対する読み取りと書き込みを確認
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
マルチパスデバイスを使用する前に、ホストがマルチパスデバイスのデータを読み取りおよび書き込みできることを確認する必要があります。

.作業を開始する前に
アクセスするストレージクラスタノードの Linux ホストで DM-Multipath が設定されている必要があります。

.このタスクについて
マルチパスデバイスの対応するストレージクラスタノードがパートナーノードにフェイルオーバーできるように設定されている場合、ノードのフェイルオーバー時にデータを読み取れることを確認する必要があります。この検証は本番環境のストレージクラスタでは実行できない場合があります。

.手順
. 指定したマルチパスデバイスでいくつかのI/Oを実行します。
+
`dd if=/dev/zero of=<multipath_device_name\>`

. 統計情報を更新する秒数を指定して、マルチパスデバイスでI/Oが実行されていることを確認します（この例では2秒に設定しています）。
+
`iostat 2`

+
マルチパスデバイスで I/O が実行されている場合、さまざまな I/O カウンタの出力が動的に変化し、マルチパスデバイスで I/O が正常に実行されていることがわかります。

+
[listing]
----
avg-cpu:  %user   %nice %system %iowait  %steal   %idle
            0.00    0.00    0.01    0.00    0.00   99.98

Device:            tps   Blk_read/s   Blk_wrtn/s   Blk_read   Blk_wrtn
sda               0.18         1.34         2.29     832606    1428026
dm-0              0.37         1.29         2.29     801530    1427984
dm-1              0.00         0.00         0.00       2576          0
dm-2              0.00         0.00         0.00       1770         24
sdd               0.17         1.18        17.87     734688   11128584
sde               0.17         1.18        18.01     734560   11219016
sdf               0.00         0.00         0.00       1344          0
sdg               0.00         0.00         0.00       1344          0
dm-3              0.68         4.71        71.96    2932496   44816008
sdh               0.17         1.18        18.22     734360   11343920
sdi               0.17         1.18        17.86     734272   11124488
sdj               0.00         0.00         0.00       1344          0
sdk               0.00         0.00         0.00       1344          0
.............
----
. 可能であれば、 `takeover` ストレージクラスタノードで次のコマンドを実行します。
+
`storage failover takeover -ofnode <node_name\>`

. を再実行して、マルチパスデバイスでI/Oが引き続き実行されていることを確認します。 `iostat` コマンドを実行します
. を実行します `giveback` ストレージクラスタノードで次のコマンドを実行します。
+
`storage failover giveback -ofnode <node_name\>`

. チェックしてください `iostat` I/Oが引き続き実行されていることを確認するための出力。




== 次に何をするか

テストに失敗した場合は、 iSCSI サービスが実行されていることを確認し、 DM-Multipath の設定とマルチパスデバイスへの iSCSI パスを再度確認してください。
