---
permalink: iscsi-config-windows/task_verifying_that_host_can_write_to_read_from_lun.html 
sidebar: sidebar 
keywords: lun, verify, host, write, data, verify that the host can write to and read from the lun 
summary: LUN を使用する前に、ホストが LUN のデータを読み取りおよび書き込みできることを確認する必要があります。 
---
= ホストが LUN に対して読み取りと書き込みを実行できることを確認します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
LUN を使用する前に、ホストが LUN のデータを読み取りおよび書き込みできることを確認する必要があります。

.作業を開始する前に
LUN が初期化され、ファイルシステムでフォーマットされている必要があります。

.このタスクについて
LUN の作成先のストレージクラスタノードがパートナーノードにフェイルオーバーできるように設定されている場合、ノードのフェイルオーバー時にデータを読み取れることを確認する必要があります。このテストは本番環境のストレージクラスタでは実行できない場合があります。

テストに失敗した場合は、 iSCSI サービスが実行されていることを確認し、 LUN への iSCSI パスをチェックしてください。

.手順
. ホストから LUN にファイルをコピーします。
. ファイルを元のディスク上の別のフォルダにコピーします。
. コピーしたファイルを元のファイルと比較します。
+
を使用できます `comp` 2つのファイルを比較するには、Windowsのコマンドプロンプトでコマンドを実行します。

. *オプション：LUNを含むストレージクラスタノードをフェイルオーバーし、LUNのファイルに引き続きアクセスできるかどうかを確認します。
. ネイティブ DSM を使用して LUN へのパスを表示し、パスの数が適切であることを確認します。
+
LUN の作成先のストレージクラスタノードへのパスとパートナーノードへのパスが 2 つずつ確立されている必要があります。


