---
permalink: volume-move/index.html 
sidebar: sidebar 
keywords: nondisruptive, data, volume, node, storage, virtual, machine, svm, ontap, cluster, volume move overview, move, overview 
summary: ONTAP 9.7 以前の ONTAP System Manager のクラシックインターフェイスを使用すると、 ONTAP 9 クラスタの同じ Storage Virtual Machine （ SVM ）内のノード間で、データボリュームを無停止で移動できます。 
---
= ボリューム移動の概要
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 9.7 以前の ONTAP System Manager のクラシックインターフェイスを使用すると、 ONTAP 9 クラスタの同じ Storage Virtual Machine （ SVM ）内のノード間で、データボリュームを無停止で移動できます。



== これらの手順を使用するための要件

これらの手順を実行する前に、次の条件を満たしていることを確認してください。

* クラスタで ONTAP 9 を実行している。
* クラスタ管理者の権限が必要です。
* すべての選択肢について検討するのではなく、ベストプラクティスに従う。
* ONTAP 9.7 以降では、 ONTAP システムマネージャ UI ではなく、 ONTAP 9.7 以前のリリースで _Classic_System Manager UI を使用する場合。
+
一部のタスクでは、 ONTAP コマンドラインインターフェイス（ CLI ）を使用する必要があります。

* 移動するボリュームがわかっている。
+
移動するボリュームを決定する際には、 Active IQ Unified Manager （旧 OnCommand Unified Manager ）を使用できます。

* 移動するボリュームはデータボリュームです。
* 新規または転用するハードウェアの設置が完了しており、すでにアグリゲートがある。
* クラスタに LUN がある場合、すべてのノードから LUN ごとにパスが 2 つ確保されている。
* クラスタネットワークポートでフロー制御が有効になっていません。
* ボリュームにネームスペースが含まれている場合、クラスタで ONTAP 9.6 以降が実行されている。
+
ONTAP 9.5 を実行する NVMe 構成では、ボリューム移動はサポートされません。





== ONTAP でこれを行うその他の方法

|===


| 実行するタスク | 参照先 


 a| 
再設計された System Manager （ ONTAP 9.7 以降で使用可能）
 a| 
https://docs.netapp.com/us-en/ontap/volumes/manage-volumes-task.html["ボリュームを管理します"^]



 a| 
ONTAP コマンドラインインターフェイス
 a| 
https://docs.netapp.com/us-en/ontap/volumes/index.html["論理ストレージ管理"^]

|===


== ボリューム移動の代替手段

ボリュームを移動する前に、次の方法の方が適しているかどうかを確認してください。

* コントローラを無停止でインプレースアップグレードする場合は、アグリゲートの再配置（ ARL ）を使用できないかどうかを検討してください。 ARL は物理的なデータ移動を必要としません。
+
https://docs.netapp.com/us-en/ontap/high-availability/index.html["高可用性"^]

* 移動するのが LUN のみで、ボリュームは移動しない場合は、 LUN の移動プロセスを使用できます。
+
https://docs.netapp.com/us-en/ontap/san-admin/index.html["SAN 管理"^]


