---
permalink: volume-move/task_planning_method_timing_volume_move.html 
sidebar: sidebar 
keywords: system, manager, volume, manual, cutover, lun, report, node, advance, procedure, command-line, interface, cli, plan, plan the method and timing of a volume move 
summary: ONTAP 9.7 以前では、 ONTAP System Manager の「クラシック」インターフェイスを使用してボリュームを移動し、手動カットオーバーを実施するかどうかを決定できます。LUN レポートノードを更新する必要がある場合は、コマンドラインインターフェイス（ CLI ）の高度な手順を使用する必要があります。必要に応じて、ボリューム移動のタイミングを計画することもできます。 
---
= ボリューム移動の方法とタイミングを計画します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 9.7 以前では、 ONTAP System Manager の _classic_ インターフェイスを使用してボリュームを移動し、手動カットオーバーを実施するかどうかを決定できます。LUN レポートノードを更新する必要がある場合は、コマンドラインインターフェイス（ CLI ）の高度な手順を使用する必要があります。必要に応じて、ボリューム移動のタイミングを計画することもできます。

.このタスクについて
SnapMirror 関係または SnapVault 関係のソースボリュームは、ボリュームのミラーリング中に移動することができます。SnapMirror サービスは、ボリューム移動ジョブのカットオーバーフェーズ中に一時的に停止します。

デスティネーションボリュームも移動できます。反復フェーズでは、 SnapMirror または SnapVault の更新とボリューム移動の処理が同時に実行されます。カットオーバーフェーズでのカットオーバーの実行については、カットオーバーと SnapMirror または SnapVault の更新のうち、先に実行された方から順番に処理されます。最初の処理が完了するまで、他の処理はブロックされます。

.手順
. 手動カットオーバーが必要かどうかを決定します。
+
_cutover_は 、移動処理が終了 ONTAP したあと、新しいアグリゲートのボリュームからデータの提供を開始する瞬間です。カットオーバーは自動で開始することも、手動で開始することもできます。

+
ストレージシステムで変更が発生するタイミングを制御する必要がある場合は、メンテナンス期間中に手動で移動処理の最終カットオーバーを実行できます。

+
カットオーバーにシステム停止は必要ありませんが、発生するタイミングを制御するためにメンテナンス期間を使用できます。

+
[NOTE]
====
自動カットオーバーと手動カットオーバーのどちらを選択した場合も、ボリューム移動は無停止で実行されます。

====
. ボリュームに LUN が含まれており、クラスタが 4 ノード以上の場合は、ボリュームを別の HA ペアに移動するときに CLI を使用して LUN レポートノードを更新します。
+
ボリュームに LUN が含まれていない場合や 2 ノードクラスタの場合は、この手順を省略できます。

. *オプション：*次の考慮事項を使用して時間を計画します。
+
** ボリューム移動処理は、クライアントアクセスとシステム全体のパフォーマンスを維持しながら、バックグラウンドで無停止で実行するように設計されているため、予想よりも時間がかかることがあります。
+
たとえば、 ONTAP はボリューム移動処理に使用できるリソースを調整します。

** 移動をできるだけ短時間で実行するには、クラスタのアクティビティが少ない時間を選択する必要があります。特に次のアクティビティを選択する必要があります。
+
*** ボリュームに対する I/O 処理
*** コントローラの CPU 使用率が 50% 未満の場合など、バックグラウンドリソースを使用するジョブ
*** クラスタインターコネクトを使用するジョブ


** ボリュームのオフライン化、制限、または削除、 SnapMirror の再同期、解除、 リストア、 Snapshot リストアのいずれかを実行できます。
+
これらの処理が実行されている場合は、完了するまで待ってから移動を開始する必要があります。

** ボリューム移動処理の実行中は、スイッチオーバーは実行できますが MetroCluster スイッチバックは実行できません。
** スイッチオーバーされたサイトに属するボリュームに対してボリューム移動処理を実行中の場合、 MetroCluster のスイッチバックはブロックされます。稼働しているサイトのローカルボリュームに対してボリューム移動処理を実行中の場合、スイッチバックはブロックされません。
** MetroCluster の強制的なスイッチオーバーは、ボリューム移動処理を実行中も実行できます。




.関連情報
link:task_verifying_lun_reporting_nodes_after_moving_volume.html["ボリューム移動後の LUN レポートノードの確認"]
