---
permalink: peering/reference_prerequisites_for_cluster_peering.html 
sidebar: sidebar 
keywords: cluster, peer, connectivity, port, ip, address, subnet, firewall, cluster-naming, requirement, prerequisite, prerequisite for cluster peering 
summary: ONTAP 9.7 以前の ONTAP System Manager の「クラシック」インターフェイスを使用してクラスタピアリングをセットアップする前に、接続、ポート、 IP アドレス、サブネット、ファイアウォール、 とクラスタの命名要件が満たされている。 
---
= クラスタピアリングの前提条件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 9.7 以前で ONTAP の System Manager_CLASSICE_Interface を使用してクラスタピアリングをセットアップする前に、接続、ポート、 IP アドレス、サブネット、ファイアウォール、 とクラスタの命名要件が満たされている。



== 接続要件

ローカルクラスタのすべてのクラスタ間 LIF が、リモートクラスタのすべてのクラスタ間 LIF と通信できる必要があります。

必須ではありませんが、一般に、クラスタ間 LIF には同じサブネットの IP アドレスを使用した方が構成がシンプルになります。IP アドレスは、データ LIF と同じサブネット内や、別のサブネット内に存在できます。各クラスタで使用するサブネットは、次の要件を満たしている必要があります。

* サブネットには、各ノードに 1 つのインタークラスタ LIF が割り当てられる十分な数の IP アドレスが必要です。
+
たとえば、 6 ノードクラスタの場合、クラスタ間通信で使用するサブネットには使用可能な IP アドレスが 6 つ必要です。



クラスタ間ネットワークでは、各ノードにインタークラスタ LIF と IP アドレスが必要です。

クラスタ間 LIF のアドレスには IPv4 または IPv6 のいずれかを使用できます。

[NOTE]
====
ONTAP 9 では、必要に応じて IPv4 プロトコルと IPv6 プロトコルがクラスタ間 LIF に共存することを許可し、 IPv4 から IPv6 にピアリングネットワークを移行できます。以前のリリースでは、クラスタ全体のすべてのクラスタ間関係が IPv4 または IPv6 のどちらかだったため、プロトコルの変更はシステム停止を伴うイベントでした。

====


== ポート要件

クラスタ間通信には専用のポートを使用することも、データネットワークで使用されているポートを共有することもできます。ポートは、次の要件を満たしている必要があります。

* 特定のリモートクラスタとの通信に使用するポートは、すべて同じ IPspace に属している必要があります。
+
複数のクラスタとのピア関係の作成には複数の IPspace を使用できます。ペアワイズのフルメッシュ接続は IPspace 内でのみ必要になります。

* クラスタ間通信で使用されるブロードキャストドメインに、 1 ノードあたり最低 2 つのポートがあり、クラスタ間通信で別のポートへのフェイルオーバーが可能になっている。
+
ブロードキャストドメインに追加できるポートは、物理ネットワークポート、 VLAN 、インターフェイスグループ（ ifgrps ）です。

* すべてのポートが接続されている。
* すべてのポートが正常な状態である必要があります。
* ポートの MTU 設定が一貫している。




== ファイアウォールの要件

ファイアウォールとクラスタ間ファイアウォールポリシーでは、次のプロトコルを許可する必要があります。

* ICMP サービス
* ポート 10000 、 11104 、および 11105 経由でのすべてのインタークラスタ LIF の IP アドレスへの TCP 接続
* クラスタ間 LIF 間の双方向 HTTPS
+
HTTPS は CLI を使用したクラスタピアリングのセットアップ時には必要ありませんが、 ONTAP System Manager を使用してデータ保護を設定する場合にはあとで必要になります。



デフォルト `intercluster` ファイアウォールポリシーでは、HTTPSプロトコル経由のアクセスとすべてのIPアドレス（0.0.0.0/0）からのアクセスが許可されます。ポリシーは必要に応じて変更または置き換えできます。

.関連情報
https://docs.netapp.com/us-en/ontap/data-protection/index.html["データ保護"]
