---
permalink: nas-multiprotocol-config/task_verifying_nfs_access_from_unix_administration_host.html 
sidebar: sidebar 
keywords: configure, nfs, access, storage, virtual, machine, svm, configuration, administration, host, read, data, verify, verify nfs access from a unix administration host 
summary: Storage Virtual Machine （ SVM ）に対する NFS アクセスの設定が完了したら、正しく設定されていることを確認する必要があります。設定を確認するには、 NFS 管理ホストにログインし、 SVM に対するデータの読み取りと書き込みが可能かどうかを確認します。 
---
= UNIX 管理ホストから NFS アクセスを確認
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Storage Virtual Machine （ SVM ）に対する NFS アクセスの設定が完了したら、正しく設定されていることを確認する必要があります。設定を確認するには、 NFS 管理ホストにログインし、 SVM に対するデータの読み取りと書き込みが可能かどうかを確認します。

.作業を開始する前に
* クライアントシステムに、前に指定したエクスポートルールで許可されている IP アドレスが割り当てられている必要があります。
* root ユーザのログイン情報が必要です。


.手順
. クライアントシステムに root ユーザとしてログインします。
. 入力するコマンド `cd /mnt/` ディレクトリをマウントフォルダに変更します。
. 新しいフォルダを作成し、 SVM の IP アドレスを使用してマウントします。
+
.. 入力するコマンド `mkdir /mnt/folder` をクリックして、新しいフォルダを作成します。
.. 入力するコマンド `mount -t nfs -o nfsvers=3,hard IPAddress:/volume_name /mnt/folder` をクリックして、この新しいディレクトリにボリュームをマウントします。
.. 入力するコマンド `cd folder` ディレクトリを新しいフォルダに変更します。
+
次のコマンドでは、 test1 という名前のフォルダを作成し、 IP アドレス 192.0.2.130 のボリューム vol1 をマウントフォルダ test1 にマウントして、ディレクトリを新しい test1 に変更しています。

+
[listing]
----
host# mkdir /mnt/test1
host# mount -t nfs -o nfsvers=3,hard 192.0.2.130:/vol1 /mnt/test1
host# cd /mnt/test1
----


. 新しいファイルを作成し、そのファイルが存在することを確認して、テキストを書き込みます。
+
.. 入力するコマンド `touch filename` をクリックしてテストファイルを作成します。
.. 入力するコマンド `ls -l filename` ファイルが存在することを確認します。
.. 入力するコマンド `cat >filename`をクリックしてテキストを入力し、Ctrl+Dキーを押してテストファイルにテキストを書き込みます。
.. 入力するコマンド `cat filename` をクリックして、テストファイルの内容を表示します。
.. 入力するコマンド `rm filename` をクリックしてテストファイルを削除します。
.. 入力するコマンド `cd ..` をクリックして親ディレクトリに戻ります。


+
[listing]
----
host# touch myfile1
host# ls -l myfile1
-rw-r--r-- 1 root root 0 Sep 18 15:58 myfile1
host# cat >myfile1
This text inside the first file
host# cat myfile1
This text inside the first file
host# rm -r myfile1
host# cd ..
----


.結果
SVM に対する NFS アクセスが有効になっていることを確認できました。
