---
permalink: expansion/task_ensuring_hardware_level_ha_is_enabled.html 
sidebar: sidebar 
keywords: install, controller, module, reuse, maintenance, mode, ha, state, hardware-level, enable, ensure hardware-level ha is enabled 
summary: 新しく取り付けたコントローラモジュールが、新しいものではなく再利用されたものである場合は、メンテナンスモードに切り替えて、モジュールの HA の状態が HA に設定されていることを確認する必要があります。 
---
= ハードウェアレベルの HA が有効になっていることを確認する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
新しく設置したコントローラモジュールが、新しくではなく再利用された場合 - メンテナンスモードに切り替えて、モジュールの HA の状態が HA に設定されていることを確認する必要があります。

.このタスクについて
新しいコントローラモジュールを使用する場合は、 HA がデフォルトで有効になるため、この手順はスキップできます。それ以外の場合は、両方のノードでこの手順を実行する必要があります。

.手順
. 最初のノードでメンテナンスモードに切り替えます。
+
.. 次のコマンドを入力してノードシェルを終了します。 `halt`。
+
LOADER プロンプトが表示されます。

.. メンテナンスモードに切り替えるには、 `boot_ontap maint`。
+
情報が表示されると、メンテナンスモードのプロンプトが表示されます。



. メンテナンスモードで、コントローラモジュールとシャーシが HA 状態であることを確認します。
+
.. 次のコマンドを入力して、コントローラモジュールとシャーシのHA状態を表示します。 `ha-config show`。
.. 表示されたコントローラの状態が `HA`と入力します `ha-config modify controller ha`。
.. 表示されたシャーシの状態が `HA`と入力します `ha-config modify chassis ha`。
.. 次のコマンドを入力して、コントローラモジュールとシャーシの両方でHAが有効になっていることを確認します。 `ha-config show`。


. ONTAP に戻る：
+
.. 入力するコマンド `halt` をクリックしてメンテナンスモードを終了します。
.. 次のコマンドでONTAPを起動します `boot_ontap`
.. ノードがブートし、クラスタセットアップウィザードがコンソール上で自動的に起動するまで待ちます。
.. Enter キーを 4 回押して、ノード管理 LIF の既存の設定をそのまま使用します。
.. ノードに `admin` ユーザ。パスワードは必要ありません。


. クラスタに追加するもう一方のノードで、この手順を繰り返します。

