---
permalink: nfs-config/index.html 
sidebar: sidebar 
keywords: nfs, access, volume, exist, storage, virtual, machine, svm, system manager classic 
summary: ONTAP System Manager クラシックインターフェイス（ ONTAP 9.7 以前）を使用して、新規または既存の Storage Virtual Machine （ SVM ）の新しいボリュームへの NFS アクセスを簡単に設定できます。 
---
= NFS 構成の概要
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP System Manager クラシックインターフェイス（ ONTAP 9.7 以前）を使用して、新規または既存の Storage Virtual Machine （ SVM ）の新しいボリュームへの NFS アクセスを簡単に設定できます。

この手順は、ボリュームへのアクセスを設定する場合に使用します。

* NFSv4 または NFSv4.1 ではなく、 NFSv3 を使用して NFS アクセスを行う。
* すべての選択肢について検討するのではなく、ベストプラクティスに従う。
* データネットワークでデフォルトの IPspace 、デフォルトのブロードキャストドメイン、およびデフォルトのフェイルオーバーグループを使用する。
+
データネットワークがフラット構成であれば、これらのデフォルトのオブジェクトを使用することで、リンク障害の発生時に LIF が確実に正しくフェイルオーバーされます。デフォルトのオブジェクトを使用しない場合は、を参照してください https://docs.netapp.com/us-en/ontap/networking/index.html["ネットワーク管理マニュアル"^] LIF パスのフェイルオーバーを設定する方法については、を参照してください。

* 新しいボリュームを UNIX ファイル権限を使用して保護する。
* LDAP を使用する場合は、 Active Directory から提供されます。


ONTAP NFS プロトコル機能の範囲の詳細については、を参照してください link:https://docs.netapp.com/us-en/ontap/nfs-admin/index.html["NFS のリファレンスの概要"^]。



== ONTAP でこれを行うその他の方法

|===


| 実行するタスク | 参照先 


| 再設計された System Manager （ ONTAP 9.7 以降で使用可能） | link:https://docs.netapp.com/us-en/ontap/task_nas_provision_linux_nfs.html["NFS を使用して Linux サーバ用の NAS ストレージをプロビジョニング"^] 


| ONTAP のコマンドラインインターフェイス | link:https://docs.netapp.com/us-en/ontap/nfs-config/index.html["CLI を使用した NFS の設定の概要"^] 
|===